var POL={

mentex:[

"Instrukcja użytkowania<br><span class='bt1'>Odbiornika Głosów Duchów i Zjaw<br></span>firmy Edison<br><br><br>Kontakt z zaświatami (ostrzeżenie)<br><br>Stan emocjonalny Duchów i Zjaw z którymi się kontaktujesz odpowiada ich potencjałowi elektrycznemu, zwanemu też stanem 'energetycznym'. Duchy mogą objawiać się w wysokim lub w niskim stanie energetycznym, ale możesz z nimi rozmawiać tylko wtedy, gdy są one w niskim stanie energetycznym.<br><br>Prowokacyjne lub agresywne wypytywanie duchów może sprawić, że zmienią one swój stan energetyczny. Gdy duch przejdzie w wysoki stan energetyczny, to urządzenie będzie odbierać tylko głośne trzaski, a dalsza komunikacja nie będzie możliwa.<br><br>Duchy w wysokim stanie energetycznym często objawiają się w postaci fizycznej bez potrzeby stosowanie urządzeń optycznych lub elektronicznych. Dzieje się tak zazwyczaj w innych miejscach. Pamiętaj: istoty nadprzyrodzone to dusze Umarłych. Prosimy o okazanie im stosownego szacunku.",

"wzrost energii<br>na skutek rozmowy<br><br>STAN NISKI<br><br><br><br><br>GŁOS DUCHA SŁYSZALNY",

"<br><br><br>STAN WYSOKI<br><br><br><br><br>MOŻLIWE OBJAWIENIE SIĘ<br>W POSTACI FIZYCZNEJ<br>rozproszenie energii na skutek objawienia się",

"<div class='ht'><span style='font-size:170%'>Wskazówki do gry</span><br><br>W At Dead Of Night najlepiej jest grać w środku nocy lub przynajmniej w ciemnym pokoju. Postaraj się ograniczyć dźwięki płynące z otoczenia lub załóż słuchawki.<br><br>Musisz być w stanie widzieć najmroczniejsze części otoczenia, ponieważ w znacznej części hotelu jest ciemno, a cień Jimmy'ego jest czasami ledwie widoczny. Za pomocą klawiszy 'U' oraz 'I' możesz w razie potrzeby zmienić jasność.  <br><br>Jeżeli Jimmy znajduje się na tym samym piętrze co ty, to będziesz w stanie usłyszeć jego głos. Wsłuchując się w odgłos jego kroków będziesz w stanie określić, jak blisko się on znajduje. Również duchy wydają dźwięki. Jeżeli chcesz się lepiej wsłuchać w takie dźwięki, wciśnij klawisz 'D', żeby na chwilę przyciszyć pozostałe odgłosy płynące z hotelu.<br><br>Jeśli masz problemy ze słuchem, wybierz opcję 'Wzbogacona deskrypcja', znajdującą się pod opcją 'Napisy'. Jeżeli nie masz problemów ze słuchem, zalecamy pozostawienie tej opcji niezaznaczonej.<br><br>Kompas wskazuje, gdzie znajdują się duchy – również przez ściany. Jeżeli nie jesteś w stanie znaleźć ducha we wskazanym kierunku, spróbuj przejść się po korytarzach. Kompas obraca się powoli, gdy brak jest w pobliżu duchów, ale coraz szybciej, gdy jesteś blisko jednego z nich.<br><br>Pamiętaj, że możesz zajrzeć do wnętrza pokoju przez dziurkę od klucza. Możesz również biec szybciej po korytarzu, jeżeli przesuniesz strzałkę ku górze ekranu.</div>",

"<div class='ht'><span style='font-size:170%'>Jimmy a DID</span><br><br>Historia Jimmy'ego to teatralne i symboliczne przedstawienie kogoś, w kim ścierają się dwie sprzeczne postawy moralne. Nie jest zamiarem twórców gry traktowanie takiego przedstawienia tego zjawiska jako wiernego oddania bardzo realnego schorzenia psychologicznego znanego jako DID (Zaburzenie dysocjacyjne tożsamości).<br><br>Prawdziwe DID to poważna i wyniszczająca człowieka choroba, która często (lecz nie zawsze) jest powiązana z byciem ofiarą przemocy w dzieciństwie. Brak jest jakiejkolwiek korelacji pomiędzy DID a nieetycznym/kryminalnym zachowaniem. Cierpiący na DID zasługują na współczucie, ale w praktyce często spotykają się z potępieniem lub brakiem zaufania, zazwyczaj na skutek niezrozumienia przez opinię publiczną ich sytuacji.<br><br>Nie było naszym zamiarem sugerowanie, że Jimmy cierpi na to zaburzenie i w pełni zgadzamy się, że powielanie stereotypów szkodzi osobom cierpiącym na DID, a także uniemożliwia ono postęp wiedzy i zrozumienie tego zjawiska. Szczerze przepraszamy za spowodowane przez nas osobom cierpiącym na DID przykrość i ból.<br><br>Więcej informacji na temat DID można znaleźć pod następującym adresem:<br><br>https://survivorsnetwork.org.uk/resource/dissociative-identity-disorder-d-i-d/</div>",

"Podziękowania dla<br>fantastycznej obsady<br><br><table><tr><td><span class='h5'>Jimmy</span><br><span class='ht'>Huld Martha</span><br><br><span class='h5'>Rose</span><br><span class='ht'>Joanna Bond</span><br><br><span class='h5'>Dr Bose</span><br><span class='ht'>Rohit Gokani</span><br><br></td><td><span class='h5'>Maya</span><br><span class='ht'>Chloe Booyens</span><br><br><span class='h5'>Harvey</span><br><span class='ht'>Karl Haynes</span><br><br><span class='h5'>Amy<span><br><span class='ht'>Daisy Follin</span><br><br></td></tr></table><span class='h5'>Role Drugoplanowe</span><table><tr><td><span class='ht'>Rachel Alfieri<br>Paige Ryan<br>Sam Follin</span></td><td><span class='ht'>Jamie Follin<br>Clare Follin<br>Tom Follin</span></td></tr></table><br><span class='h5'>Specjalne Podziękowania</span><br><table><tr><td><span class='ht'>Mark Wilson</span></td><td><span class='ht'>Fay Wilkins</span></td><td><span class='ht'>Daniel Alfieri<span></td><td><span class='ht'>Sally Alfieri</span></td><td><span class='ht'>Luke Chase</span></td></tr></table><br><span class='h7'>Gra stworzona przez Tima 'co ja teraz zrobię' Follina<br>©2020 Baggy Cat Ltd</span></span>",

"&#160;&#160;&#160;&#160;&#160;&#160;&#160;Wzbogacona deskrypcja<br><br><span class='h2'>Bardziej szczegółowe napisy i audiodeskrypcja dźwięków słyszanych podczas gry wraz ze wskaźnikiem głośności.<br><br>Jeżeli nie masz problemów ze słuchem, radzimy ci nie włączać tej opcji.</span>",

"&#160;&#160;&#160;&#160;&#160;&#160;&#160;Napisy<br><br><span class='h2'>Podstawowe napisy w trakcie gry i podczas trwania prologu.</span>",

"Brak zdarzeń<br>do przejrzenia.",

"ROZPOCZNIJ NOWĄ GRĘ",

"<span class='h9'>Historia Jimmy'ego Halla</span><br><br><span class='h2'>Odkryj sekrety Jimmy'ego, zadając zjawom pytania o przedmioty, które udało ci się znaleźć oraz znajdując związki pomiędzy posiadanymi informacjami, dzięki którym zjawy się objawią. Jimmy dołoży wszelkich starań, by cię powstrzymać przed odkryciem prawdy.</span>",

"<span class='h9'>Finał poprzedniej rozgrywki</span><br><br><span class='h2'>Wczytaj ostatnią ukończoną rozgrywkę od momentu, gdy Jimmy zaprosił cię na spotkanie z Hugonem.</span>",

"<span class='h9'>Ostatni ratunek (nowa gra)</span><br><br><span class='h2'>Uratuj wszystkie swoje przyjaciółki i nie daj się dopaść Jimmy'emu. Jeden cios i po tobie! Ten tryb nie korzysta z funkcji zapisu i możesz wrócić do swojej aktualnej rozgrywki, gdy uciekniesz lub gdy Jimmy cię zaatakuje.</span>",

"Obejrzyj Pełny Samouczek",

"Obejrzyj od sceny 'Pościg'",

"Obejrzyj od sceny 'Strategia'",

"Obejrzyj od sceny 'Umarli'",

"Obejrzyj od sceny 'Talent Mai'",

"Obejrzyj Prolog",

"Obejrzyj od sceny 'Maya przybywa do hotelu'",

"Obejrzyj od sceny 'Teraz rządzi tu Hugo'",

"Obejrzyj od sceny '2.30 w nocy'",

"Obejrzyj od sceny 'Odbiornik Zjaw'",

"Statystyki",

"Rozpocznij nową grę",

"Przejrzyj wizje",

"Instrukcja obsługi odbiornika",

"Obejrzyj Samouczek i Wstęp",

"Napisy i Opisy",

"Napisy końcowe",

"Jak grać",

"Jimmy a DID",

"Opuść hotel<br><span class='h2'>Zapisz i Wyjdź</span>",

"Czy na pewno chcesz<br>teraz opuścić hotel?",

"TAK, WYPUŚĆ MNIE!",

"<br>BRAK<br>PRZEDMIOTÓW<br>DO WYŚWIETLENIA",

"Jimmy uderzył cię po raz ostatni.<br><br>To koniec twojej ucieczki.<br><br>Ale zawsze możesz spróbować ponownie...",

"Wejdź do Hotelu<br><span style='font-size:50%'>Wróć do ostatniego zapisanego stanu gry</span>",

"Wejdź do Hotelu<br><span style='font-size:70%'>Rozpocznij nową rozgrywkę</span>",

"ROZPOCZNIJ ROZGRYWKĘ STANDARDOWĄ",

"ROZPOCZNIJ ROZGRYWKĘ EKSTREMALNĄ",

"Zapisz aktualny stan gry",

],

achtex:[

  "Ukończono",
  "historię",
  "Udało cię się uniknąć Jimmy'ego",
  "Jimmy zaatakował cię raz",
  "Jimmy zaatakował cię dwa razy",
  "Jimmy zaatakował cię",
  "razy",
  "Tajemnica hotelu odkryta",
  "Historia",
  "Ukończone",
  "Musisz",
  "uratować",
  "Uratowano",
  "Wszystkie przyjaciółki uratowane",
  "Musisz znaleźć wyjście z hotelu",
  "Gra ukończona",
  "Brak statystyk do wyświetlenia",
  "Statystyki",
  "Osiągnięcia",
  "Historia Amy ukończona",
  "Historia doktora Bose ukończona",
  "Historia Harvey'ego ukończona",
  "Historia Rose ukończona",
  "Główny wątek fabularny ukończony",
  "Główny wątek fabularny ukończony bez doznania obrażeń",
  "At Dead Of Night ukończone",
  "Uratowano wszystkie osoby w szybkiej rozgrywce.",
  "Ukończono At Dead of Night bez doznania obrażeń!",
  "Powrót do hotelu",
  "Brak osiągnięć w tej chwili",
  "Gra dokonuje autozapisu po ujrzeniu duchów, wywołaniu reakcji u duchów (ale dopiero po wyłączeniu wykrywacza duchów) oraz gdy Jimmy cię znokautuje.",
  "Ukończono główny wątek fabularny w TRYBIE EKSTREMALNYM.",
  "Ukończono główny wątek fabularny w TRYBIE EKSTREMALNYM bez doznania obrażeń.",
  "Ukończono At Dead of Night w TRYBIE EKSTREMALNYM",
  "Ukończono At Dead of Night w TRYBIE EKSTREMALNYM bez doznania obrażeń!",
  "Wszystkim twoim przyjaciółkom udało się bezpiecznie uciec.",

],

selx:[

  "Nie zna odpowiedzi",
  "Jeszcze o to nie zapytano",
  "Skontaktuj się ze zjawą, by o to zapytać",
  "Kliknij na przedmiot, by usłyszeć odpowiedź zjawy",
  "Stań twarzą w stronę zamkniętych drzwi, żeby użyć klucza",
  "Wybierz, żeby o to zapytać",
  "nie zna opowiedzi",
  "Odpowiedź:",
  "BEZPIECZNEJ PODRÓŻY<br>Mamy nadzieję, że wkrótce odwiedzisz nas ponownie",
  "Aktualny Stan Gry Zapisany",
  "Rozpocznij Najpierw Grę",

],

numwo:[

  "Została tylko jedna przyjaciółka do uratowania",
  "Masz jeszcze do uratowania dwie przyjaciółki",
  "Masz jeszcze do uratowania trzy przyjaciółki",
  "Masz jeszcze do uratowania cztery przyjaciółki",
  "Masz do uratowania pięć przyjaciółek",

],

numwa:[

  "Pięć przyjaciółek uratowanych.",
  "Cztery przyjaciółki uratowane.",
  "Trzy przyjaciółki uratowane.",
  "Dwie przyjaciółki uratowane.",
  "Jedna przyjaciółka uratowana.",

],

helx:"<span class='ht'>&#8679;S</span> Zapisz Grę | <span class='ht'>Esc</span> Pokaż menu | <span class='ht'>D</span> Przycisz ścieżkę dźwiękową | <span class='ht'>Q/W</span> Głośność<br><span class='ht'>&#8679;X</span> Szybkie wyjście | <span class='ht'>U/I</span> Dostosuj jasność | <span class='ht'>O/P</span> Dostosuj nasycenie | <span class='ht'>R</span> Zresetuj poziomy ",

resk:[

  "Znaleziono<br><br>pięć Kluczy typu deadlock<br><br><span style='font-size:50%'>Masz do uratowania pięć przyjaciółek</span>",
  "Zaczekaj,<br><br>aż uciekną<br><br>",
  "<span style='font-size:50%'>Wszystkie przyjaciółki uratowane</span>",
  "<span style='font-size:50%'>Masz jeszcze do uratowania jedną przyjaciółkę</span>",
  "<span style='font-size:50%'>Masz jeszcze do uratowania dwie przyjaciółki</span>",
  "<span style='font-size:50%'>Masz jeszcze do uratowania trzy przyjaciółki</span>",
  "<span style='font-size:50%'>Masz jeszcze do uratowania cztery przyjaciółki</span>",

],

ityptex:[

  "Wyświetl: Wszystko",
  "Wyświetl: Znalezione przedmioty",
  "Wyświetl: Wizje",
  "Wyświetl: Powiązania",
  "Wyświetl: Klucze"

],

intros:[

  "Oto znalezione przez ciebie urządzenie. Wybierz tę ikonkę, żeby je włączyć.",
  "Jest ono w stanie wykryć głosy zjaw, o ile jesteś w ich pobliżu.",
  "Przejdź do MENU i obejrzyj filmik z samouczkiem zanim zaczniesz grać!",
  "Znalezione przez ciebie urządzenie jest w stanie wykryć głosy zjaw, o ile jesteś w ich pobliżu.",

  "Przejdź do MENU i obejrzyj filmik z samouczkiem zanim zaczniesz grać!",
  "To jest lista obejrzanych przez ciebie rzeczy i zdarzeń, a także zgromadzonych przez ciebie kluczy.",

  "Maya może pytać zjawy o to, co znajduje się na tej liście.",
  "To jest lista obejrzanych przez ciebie rzeczy i zdarzeń, a także zgromadzonych przez ciebie kluczy.",

  "Maya może pytać zjawy o to, co znajduje się na tej liście.",
  "Z lusterka jasnowidzenia można korzystać tylko wtedy, gdy widoczna jest ta ikonka",

  "przy drzwiach w pokojach albo w kuchni na parterze.",
  "Użyj lusterka, aby uzyskać wskazówki, gdzie musisz teraz iść albo jakiego przedmiotu należy teraz użyć.",
  "Pomoże ci ono również znaleźć zgubione klucze, kompas oraz duchowe pudełeczko.",
  "Z lusterka jasnowidzenia można korzystać tylko wtedy, gdy widoczna jest ta ikonka",

  "przy drzwiach w pokojach albo w kuchni na parterze.",
  "Użyj lusterka, aby uzyskać wskazówki, gdzie musisz teraz iść albo jakiego przedmiotu należy teraz użyć.",
  "Pomoże ci ono również znaleźć zgubione klucze, kompas oraz duchowe pudełeczko.",
  "Kompas wskaże ci, w którą stronę musisz iść, żeby znaleźć zjawę.",

  "Pytaj zjawy o wizje, których doświadczasz.",

  "Odpowiedź zjawy będzie widoczna, gdy wybierzesz konkretny przedmiot.",
  "Połącz dwie odpowiedzi, która twoim zdaniem są ze sobą powiązane, aby odkryć historię zjawy.",

  "Połącz odpowiedzi na pytania o wizje z odpowiedziami na pytania o przedmioty, aby dokonywać szybszych postępów.",
  "Jeżeli zjawa przestanie odpowiadać, być może poszła ona sobie gdzieś dalej.",

  "Korzystaj z kompasu, wypatruj migoczących świateł i dobrze się wsłuchuj w dźwięki z otoczenia.",
  "Rozmowę ze zjawą rozpoczniesz od zadania pytania o jej tożsamość.",

  "Brak odpowiedzi oznacza, że nie ma w pobliżu żadnej zjawy.",
  "Głośny hałas oznacza, że w pobliżu znajduje się zjawa w wysokim stanie energetycznym.",
  "Rozmowę ze zjawą rozpoczniesz od zadania pytania o jej tożsamość.",

  "Brak odpowiedzi oznacza, że nie ma w pobliżu żadnej zjawy ",
  "Głośny hałas oznacza, że w pobliżu znajduje się zjawa w wysokim stanie energetycznym.",
  "Jimmy Hall szuka cię na tym piętrze. Trzymaj się od niego z daleka!",

  "Aby skorzystać z klucza, otwórz ekwipunek, stań twarzą do drzwi i wybierz klucz.",

  "Drzwi można otwierać i zamykać za pomocą odpowiedniego klucza.",
  "Aby skorzystać z klucza, otwórz ekwipunek, stań twarzą do drzwi i wybierz klucz.",

  "Drzwi można otwierać i zamykać za pomocą odpowiedniego klucza.",
  "Stan rozgrywki zostanie tutaj zapisany po raz ostatni.",

  "Musisz teraz uratować swoje przyjaciółki...<br>ale jeżeli Jimmy cię złapie, to koniec gry!",
  "Ostatnia osoba<br>uwolniona.<br>Znajdź wyjście<br>i zwiewaj!",

  "Rusz się do przodu, żeby wypuścić tę osobę z pokoju",

],

substan:[

  "Nie wiem.",
  "Może.",
  "Nie",
  "GŁOS<br>LEDWO<br>SŁYSZALNY/",
  "TRZASKI<br>RADIA/"

],

subrepa:[
[
  "Halo?",
  "Halo",
  "Halo.",
  "Halo",
  "Halo.",
  "Halo"
],[
  "Halo?",
  "Halo?",
  "Halo?",
  "Halo?"
],[
  "Halo?",
  "Słyszę cię",
  "Słyszę cię.",
  "Słyszę cię."
],[
  "Halo?",
  "Słyszę cię.",
  "Halo?",
  "Słyszę cię.",
  "Słyszę cię."
],
],

subrepb:[
[
  "Nazywam się Amy Bell. Mam dziesięć lat.",
  "Tak, mówi Amy.",
  "Tak, mówi Amy.",
  "Tak, to ja.",
  "Tak, mówi Amy.",
  "Tak, mówi Amy.",
  "Tak, mówi Amy.",
  "Tak, to ja."
],[
  "Doktor Bose. Jestem psychiatrą klinicznym.",
  "Tak, mówi doktor Bose.",
  "Mówi doktor Bose.",
  "Tak, mówi doktor Bose.",
  "Tak.",
  "Tak, to ja.",
  "Tak, tu doktor Bose."
],[
  "Nazywam się Harvey. Prowadzę ten hotel.",
  "Tak.",
  "Tak, mówi Harvey.",
  "Tak, tu Harvey.",
  "Tak, tu Harvey.",
  "Tak, tu Harvey."
],[
  "Rose. Rose Hall. To jest mój hotel.",
  "Tak.",
  "Tak, mówi Rose.",
  "Tak.",
  "Tak, mówi Rose.",
  "Tak.",
  "Tak, mówi Rose."
],
],

subcall:[

  "Jimmy?",
  "Hej!",
  "Tu jestem!",
  "Na dole!",
  "Tędy!",

],

subin:[

  "Czy jest tam ktoś?",
  "Czy jest tam ktoś?",
  "Czy jest tam ktoś?",
  "Czy jest tam kto?",
  "Czy jest tam kto?",
  "Czy jest tam kto?",
  "Czy jest tam ktoś?",
  "Halo?",
  "Halo?",
  "Czy jest tam ktoś?",
  "Czy jest tam ktoś?",

],

subnm:[

  "Czy to Amy?",
  "Czy to doktor Bose?",
  "Czy to Harvey?",
  "Czy to Rose?",
  "Jak się nazywasz?",

],

subrepc:[

  ["H","To własność Rose, ale nigdy z nich nie skorzystała","R","Należały do mnie. Chciałam stąd odejść, ale nigdy nie miałam do tego okazji."],
  ["R","Jimmy je kupił; chciał żeby wyglądało na to, że zdobywał nagrody."],
  ["A","Należała do mnie. To był prezent urodzinowy, który mi ukradziono.","H","To torebeczka tamtej biednej dziewczynki.","R","To własnośc pewnej dziewczynki."],
  ["A","Nie wiedziałam, co to było, dopóki Jimmy mi tego nie pokazał.","P","Zapytaj o to Jimmy'ego.","H","To moje rzeczy, ale nie trzymałem ich razem.","R","Nie wiem. Należały do Harvey'ego."],
  ["A","To Jimmy'ego. Mnie się nie podobał.","P","Widziałem, jak Jimmy się nim bawił. Ja uważałem to za niebezpieczne.","H","To była część wystawy poświęconej średniowiecznej broni. Jimmy go ukradł.","R","Kiedyś był razem ze zbroją, którą mieliśmy. Ale potem miecz zniknął."],
  ["A","Nie wiem, ale dzieci nie powinny pić alkoholu.","P","Wzięto je pewnie z baru.","H","Nie pamiętam, ale co komu szkodzi wypić od czasu do czasu?","R","Pewnie Harvey je tam postawił."],
  ["A","Tamten chłopiec często je rysował.","P","Jimmy. On zwykł rysować takie rzeczy.","H","A jak myślisz? Oczywiście, że Jimmy! Ależ on miał gwałtowną wyobraźnię, oj miał.","R","Jimmy często rysował obrazki o wojnie. Był taki, jak większość chłopców."],
  ["P","Jimmy ją znalazł i założył na głowę.","H","Należała do kucharza! Kto inny nosi czapkę kucharską?","R","Nasz kucharz zwykł ją nosić."],
  ["A","Ona mogła należeć do mnie.","P","Należała do mnie. Był to dowód– na wszelki wypadek.","H","Nie wiem, ale mogła mieć coś wspólnego z doktorem."],
  ["P","Niektórym pacjentom podaje się go do leczenia impulsywnych zachowań.","H","To pewnie własność doktora.","R","To należało do doktora Bose."],
  ["P","Nie wiem, ale Jimmy je znalazł.","H","Zawsze leżało pod ladą na recepcji. Nie wiem, skąd to się tam wzięło.","R","To była własność mojego męża."],
  ["A","To dzieło Jimmy'ego. Nie wiem, skąd mu to przyszło do głowy. Dziwny był.","P","Jimmy go prowadził. To było ostrzeżenie. Powinienem był to przewidzieć.","H","Jimmy miał nawyk wycinać z gazet artykuły o znęcających się nad innymi nauczycielach i lekarzach. To nie był normalny chłopiec.","R","Harvey powiedział, że to robota Jimmy'ego. Ja nie pamiętam."],
  ["P","To ja je ze sobą związałem. Był to eksperyment."],
  ["H","Kopał prądem. Zatrzymałem go, żeby mogła mu się przyjrzeć policja.","R","Harvey go zabrał. Powiedział, że był niebezpieczny."],
  ["A","Nie wiem. Tamten chłopiec często się nimi bawił.","P","Harvey je zachował. Nie wiem dlaczego.","H","Zachowałem je. Na wszelki wypadek.","R","Należały do mojego męża. W czasach gdy był jeszcze nauczycielem."],
  ["A","Wzięto ją z hotelowej gablotki. Widziałam ją tam.","P","W hotelu były dawniej wystawione stare sztuki broni.","H","Zabrano ją z naszej starej wystawy rzeczy ze zbrojowni. Jimmy'emu się podobała.","R","Wzięto ją ze starej wystawy Harvey'ego. Ale mnie się nie podobało, że takie rzeczy były w hotelu."],
  ["H","Były do drzwi kotłowni.","R","To były klucze do kotłowni. Ale musieliśmy tam wymienić drzwi."],
  ["P","Pierwsze słyszę.","H","Tak, udało im się nad nim zapanować, ale straciłem wiele rzeczy.","R","Tak. Ale zdążyliśmy opanować pożar, zanim ogień się rozprzestrzenił."],
  ["P","Należał do Harvey'ego. Nie podobało mi się, że coś takiego było w hotelu.","H","Był mój. Należał do mojego ojca. W środku było jeszcze kilka naboi.","R","Należał do Harvey'ego. Ale był trzymany w mojej sypialni."],
  ["A","Jimmy mi go pokazał. Ale to nie było jego.","H","To nie sztylet, a otwieracz do listów. Nie musi być naostrzony.","R","To otwieracz do listów. Był to jakiś prezent od kogoś."],
  ["R","To był numer sceniczny Jimmy'ego."],
  ["P","Nie widziałem ich.","H","Nie przypominam sobie.","R","Jimmy je potłukł."],
  ["A","Jimmy zawsze go miał pod ręką.","P","To własność Jimmy'ego. Zawsze trzymał go w kieszeni. Nie powiedział mi, do czego był on mu potrzebny. ","H","Jimmy zwykł go ze sobą nosić. Nie mam pojęcia dlaczego.","R","Jimmy miał w zwyczaju nosić ze sobą jakiś drut. Lubił się bawić elektroniką."],
  ["R","Jimmy ją napisał."],
  ["H","To pewnie własność Rose.","R","To moja własność. Złożono mi propozycję nie do odrzucenia."],
  ["A","Nie wiem. Nie widziałam żadnych małych dzieci.","R","Była przeznaczona dla dziecka. Trzymałam ją w szafce nocnej."],
  ["R","Jimmy to syn Huga. W każdym sensie tego słowa."],
  ["A","To ja – chłopiec o imieniu Jimmy zamknął mnie w piwnicy. Potem zaczął mnie okradać.","P","To była córka jednego z gości hotelu. Jimmy był wobec niej niemiły.","H","Była w hotelu razem ze swoją rodziną.","R","Była gościem w naszym hotelu."],
  ["A","Bo mu się to wydawało być śmieszne. Potem mi ją oddał, ale i tak ją potem popsuł.","P","Nie mam pojęcia, on po prostu robił takie rzeczy.","H","Kto wie? Pewnie go to rozbawiło.","R","Nieprawda. Tamta kłamczucha! Jimmy nie był złodziejem."],
  ["A","Poparzyłam sobie rękę, bardzo mnie bolała, ale nie mogłam o tym nikomu powiedzieć.","P","Jej ręka była bardzo  poparzona, ale dla Jimmy'ego to był tylko żarcik.","H","Była poparzona, dość mocno poparzona.","R","Była poparzona, ale dalej wycinała takie niebezpieczne numery. Dziwna była."],
  ["A","Szukałam lekarza, ale Jimmy mi groził i kazał mi zostać na miejscu.","H","Pewnie bała się Jimmy'ego.","R","Nie wiem, mogło chodzić o różne rzeczy. To była dziwna dziewczynka."],
  ["A","Chłopiec powiedział, że to lekarstwo. Paskudnie smakowało.","P","Nie było mnie tam wtedy, ale myślę, że wypiła alkohol."],
  ["A","Zrobiło mi się naprawdę lekko. Naprawdę myślałam , że uda mi się zeskoczyć na sam dół.","P","Jimmy dał jej za wiele do wypicia.","H","Wypiła całą butelkę whiskey. Nie wiedziała, co robi.","R","Nie wiem. Za dużo o niej nie wiedziałam."],
  ["A","Skoczyłam, ale potem zrobiło się ciemno i nie mogłam się obudzić. Nie mogę się już obudzić. Nie wiem gdzie jestem.","P","Spadła ze schodów z ostatniego piętra. Była zbyt pijana, żeby wiedzieć co robi. Z tego powodu skontaktowała się ze mną Rose.","H","Zleciała ze schodów z ostatniego piętra, aż na samo dno. Wiedziałem, że to sprawka Jimmy'ego. To musiał być on.","R","Spadła. Harvey obwiniał za to Jimmy'ego. To była jej wina, a nie Jimmy'ego."],
  ["P","To byłem ja – zadzwoniła do mnie Rose, mama Jimmy'ego. Chciała żebym z nim porozmawiał, żebym się dowiedział, co go niepokoi. Ale Harvey martwił się o stan umysłu Jimmy'ego, o rzeczy, które chłopiec sobie wyobrażał.","H","To był doktor Bose. Miał za zadanie pomóc Jimmy'emu. Ale Jimmy'emu nikt nie był już w stanie pomóc.","R","To doktor Bose. Przyszedł pomóc Jimmy'emu."],
  ["P","Jimmy zaczał zabijać małe zwierzątka i ptaszki. Zrozumiałem, że brakowało mu empatii. Więc zapytałem go, czy nie mógłby zrobić dla mnie czegoś miłego. Zaskoczył mnie, bo od razu wpadł na pewien pomysł.","H","Jimmy powiedział, że gdzieś to znalazł. Co z tym robił, to inna historia.","R","Harvey powiedział, że to właśnie Jimmy najprawdopodobniej zabił tamto zwierzątko, ale ja w to nie wierzyłam."],
  ["P","Jimmy zrobił dla mnie kanapkę. Przyniósł mi ją do pokoju, tak jak go o to poprosiłem. Z początku niczego nie podejrzewałem.","H","Doktor próbował nauczyć czegoś Jimmy'ego. Chciał, żeby chłopiec nauczył się pomagać innym. Co za pomyłka...","R","Doktor Bose próbował sprawić, że Jimmy będzie robił coś, czego chłopiec nie chciał robić."],
  ["P","Jimmy włożył mi do kanapki kawałki potłuczonego szkła. O mało się nie udławiłem. Zachowałem szmatkę i szkło dla policji, ale zrozumiałem, że nie doceniłem choroby Jimmy'ego. Musiałem pilnie zintensyfikować terapię.","H","Prawdę o Jimmym poznał dość brutalnie. Wygłupy Jimmy'ego zawsze szły za daleko.","R","Pochlastał się. Ale winę próbował zrzucić na Jimmy'ego. Sam się tak urządził, to nie była sprawka Jimmy'ego."],
  ["P","Jimmy nie pozwolił mi podać sobie leku. Musiałem za nim ganiać po hotelu. Potem powiedział Rose, że chciałem go zmusić do przyjęcia lekarstwa, że użyłem wobec niego przemocy. Bzdury!","H","Nie wiem. Nie było mnie tam.","R","Probówał podać jakiś lek Jimmy'emu bez mojej zgody."],
  ["P","Obawiałem się, że Rose uwierzy Jimmy'emu. To było bezczelne kłamstwo. Ale udało mi się ją przekonać, że Jimmy zmyślał.","H","Martwił się tym, co Jimmy mógł o nim zmyślić. Słusznie.","R","Bo martwił się o swoją reputację. Nie wiedziałam komu wierzyć, ale postanowiłam dać mu drugą szansę."],
  ["P","Pomyślałem, że po tym, jak go przyłapano na kłamstwie zacznie ze mną rozmawiać i robić to, o co go proszę. Zamiast tego wymślił nowe kłamstwo. O wiele gorsze. Najgorsze z możliwych.","R","Rozmawiał z Jimmym i próbował przejąć nad nim kontrolę. Sprawić, że zacznie robić różne rzeczy, złe rzeczy. Nie powinnam mu nigdy była zaufać."],
  ["P","Rose zgłosiła na mnie zażalenie. Wiedziałem, że stracę licencję. Pozbawiony kariery, pozbawiony przyszłości. Postanowiłem przejąć kontrolę, raz na zawsze.","H","Mieli go aresztować. Jimmy zrujnował mu życie. Ale ja wiedziałem, jak było naprawdę.","R","Przyszli go aresztować. Zasłużył sobie na to wszystko."],
  ["P","Miałem tego dosyć. Nie było już odwrotu. Moje życie i tak dobiegło już końca.","H","Ponieważ go doprowadzono do takiego stanu. Wszyscy myśleli, że doktor... dotykał Jimmy'ego. Bo widzisz, Jimmy był taki sprytny. Doktor nie miał szans. Biedna duszyczyka.","R","Bo wiedział, że był winny. Słusznie postąpił."],
  ["P","To był Harvey. On wiedział, że Jimmy kłamał na mój temat. Harvey rozumiał sytuację.","H","To byłem ja. Jimmy oskarżył doktora. Rose mu uwierzyła, ale ja znałem już skądś tamtą historyjkę.","R","To był Harvey. Nie wierzył Jimmy'emu. Ale ja wiedziałam, że Jimmy nie kłamie."],
  ["P","Jimmy nigdy nie przyznał się do kłamstwa.","H","Oczywiście, że nie! Tylko się śmiał. Potem zaczął zastawiać na mnie małe pułapki. Niektóre nie były wcale takie małe.","R","Nie. Dlaczego Jimmy miałby się przyznać do czegoś, czego nie zrobił? Harvey niesłusznie tak go traktował."],
  ["H","Wiedział, że to mój grzejnik. Podłączył go bezpośrednio do instalacji. O mały włos mnie nie zabiło. Umyślnie to zrobił, ale Rose nie chciała mnie słuchać. Wiedziałem, że muszę mu dać nauczkę. Zepsuł moją własność, więc ja postanowiłem popsuć coś należącego do niego.","R","Harvey obwiniał Jimmy'ego, ale tamten grzejnik był wadliwy. Harvey powinien był się go pozbyć dawno temu."],
  ["P","Nie wiem, ale przemoc tylko pogarsza sprawę.","H","Zniszczyłem jego telewizor, konsole do gier i takie tam. Byłem wkurzony, ale to nic nie dało. Tylko mu się pogorszyło. Wkrótce wziął odwet.","R","Zniszczył rzeczy Jimmy'ego. Nie był w stanie zapanować nad swoim gniewem."],
  ["H","Jimmy tak to zaplanował, żeby wystrzeliła, gdy otworzyłem drzwi. Trafiłem na oddział ratunkowy – musieli mnie pozszywać i dać mi zastrzyk przeciw tężcowi. Jak wróciłem, nie mogłem go znaleźć. Rose powiedziała, że schował się w piwnicy. To podsunęło mi pewien pomysł.","R","Harvey powiedział, że Jimmy trafił go strzałą, ale ja wiedziałam, że Jimmy nie użyłby takiej broni."],
  ["H","Chciałem odpłacić Jimmy'emu pięknym za nadobne. Myślałem, że w piwnicy nic nie zbroi. Myliłem się.","R","Nie wiem, co on robił."],
  ["P","Nie pamiętam.","H","Udało nam się opanować sytuację zanim wymknęła nam się spod kontroli. Ale w piwnicy przechowywane były wszystkie nasze stare fotografie i listy. Wszystko poszło z dymem. Jimmy wymknął się spod kontroli; miałem go dość. Chciałem się go pozbyć.","R","Harvey obwiniał Jimmy'ego, ale pożar spowodował wiszący luzem kawał drutu. To był wypadek."],
  ["P","Nie wiem. Ale Harvey nie był w stanie zapanować nad swoim gniewem.","H","Nie wiedziałem, co zamierzałem zrobić. Zagrozić mu, wyrzucić go z hotelu... Problem tkwił w tym, że nie spodziewałem się, że Jimmy również będzie uzbrojony.","R","Nie wiem. Harvey nie powinien był mieć broni palnej w hotelu."],
  ["H","Szukałem Jimmy'ego."],
  ["H","Jimmy podkradł się do mnie od tyłu, w ogóle go nie zauważyłem. Kiedy przyszło co do czego, to Jimmy zawsze wygrywał.","R","Harvey zwariował. Jimmy zrobił to w samoobronie."],
  ["H","Rose... Rose uwierzyła Jimmy’emu. Broniła go do samego końca.","R","To byłam ja. Musiałam wytłumaczyć policji, że sztylet był tylko otwieraczem do listów, a Harvey miał przy sobie załadowaną broń. To była samoobrona. Zrozumieli mnie."],
  ["H","Jimmy... Oni go wypuścili. Powiedzieli, że to samoobrona, że ja próbowałem zastrzelić Jimmy'ego. Ale to wszystko kłamstwa.","R","Jimmy... wracał właśnie do domu. Policjanci zrozumieli. Uwierzyli mu, ale tamta sytuacja go zmieniła. Zaczął mi pomagać w prowadzeniu hotelu. I wpadł na pomysł, jak ściągnąć większą liczbę gości."],
  ["H","Nie wiem, kto to był.","R","Dobrze się bawiłam, znowu zaczęliśmy zarabiać na hotelu. Wyglądało na to, że jest coraz lepiej, ale wtedy... Jimmy zaczął się dziwnie zachowywać. Wykrzykiwał coś, patrząc na siebie w lustrze. Wyglądał na rozzłoszczonego."],
  ["R","Jimmy... Z początku nie rozumiałam, co jest grane. Miałam mętlik w głowie. Ale potem do mnie dotarło. To nie Jimmy to robił. Zaczął pękać – tak jak lustra. Jimmy stracił nad sobą kontrolę."],
  ["H","Tego nie wiem, ale wiem, że koniec końców Jimmy zawsze wszystko rujnował.","R","Na scenie nie występował już Jimmy, ale Hugo Punch, jego postać komediowa. Hugo zaczął ubliżać co noc swej widowni. Wyglądało na to, że sprawiało mu to przyjemność. Pewnej nocy po jego występie ktoś z gości powiedział Jimmy'emu, co o nim sądzi. Jimmy wpadł w szał i zrobił coś głupiego."],
  ["R","To dziennikarze. Chcieli porozmawiać z Jimmym. Ale to nie Jimmy był za to odpowiedzialny – to Hugo Punch związął tamtą kobietę. Jimmy nie był w stanie już nad nim zapanować. Cierpiał na depresję. Chciał wszystko za sobą zostawić i odejść."],
  ["R","To był Jimmy. Próbował się zabić. Dlatego musiałam wyjawić mu prawdę."],
  ["H","Nie wiem. Rose nie o wszystkim mi powiedziała.","R","To Hugo. Pogrzebałam go tam w betonie, w ukrytym pokoju. Powinnam była tak wcześniej uczynić. Za długo pozwalałam mu znęcać się nad Jimmym. To przeze mnie wyrosło z niego, co wyrosło. Myślałam, że uwolnię się od winy poprzez wyjawienie Jimmy'emu prawdy. Byłam w błędzie. To tylko wszystko pogorszyło. Nie byłam w stanie zaakceptować tego, co zrobiłam. Nie byłam w stanie tego znieść."],
  ["R","Gdybym sama tego nie zrobiła, to uczyniłby to Jimmy – albo raczej Hugo. To Hugo sprawuje nad nim władzę. On steruje Jimmym. Poproś Jimmy'ego, żeby ci pokazał, gdzie mieszka Hugo."],
  ["H","Nigdy go nie spotkałem.","R","Był iluzjonistą i artystą scenicznym. Kupił ten hotel, żeby promować swoje występy. Był sławny, pokazywali go w telewizji. Byłam jego asystentką, a potem... kimś więcej."],
  ["R","Nigdy nie wiedziałam, czego chce. Jedyne co mogłam mu dać to dziecko."],
  ["R","Hugo był brutalnym, podłym, chorym na umyśle człowiekiem."],
  ["A","Tak, wziął ją, jak nie patrzyłam i ukradł mi pieniądze. Zbeształam go, ale w ogóle mnie nie słuchał."],
  ["A","Namoczył moją zabawkę tym czymś z butelki. Nienawidzę go!"],
  ["A","Tak, zdjął go ze ściany. Wyglądał na ostry. Kazał mi obiecać, że nikomu nie powiem. Powiedział, że wie, jak sprawić, żeby ręka przestała mnie boleć."],
  ["A","Być może – kazał mi to wypić do dna. Paskudnie smakowało. Potem dziwnie się poczułam..."],
  ["P","Tak. Sugerowało to zaburzenia osobowościowe, ale niezbyt się tym martwiłem do czasu, aż... zdałem sobie sprawę jak wybujała była jego wyobraźnia."],
  ["P","Tak. Jimmy obiecał, że coś dla mnie zrobi, więc poszedłem za nim zobaczyć, co dokładnie planował."],
  ["P","Było to moje pierwsze zetknięcie się z poczuciem humoru Jimmy'ego."],
  ["P","Nie było to idealne lekarstwo, ale tylko to miałem. Jimmy pilnie potrzebował leczenia – był niebezpieczny."],
  ["P","Jimmy powiedział, że uderzyłem go wiosłem do klapsów. Nigdy nie użyłem przemocy wobec pacjenta – to była wierutna bzdura! Ale Rose mu uwierzyła."],
  ["P","Jimmy oskarżył mnie o najgorsze możliwe przestępstwo. Wpadł na to, czytając gazetę. Wszystko zmyślił."],
  ["P","Rozważałem użycie sznurka do wieszania prania, ale okazał się on za cienki. Zamiast tego, znalazłem kawałek zwykłego sznurka. Wciąż miałem moje klucze do hotelu, więc po wyjściu za kaucją wkradłem się pewnej nocy do środka."],
  ["H","Stamtąd to było wzięte! Jak tylko znalazłem tamten album z wycinkami, to wiedziałem, jak Jimmy wpadł na tamten pomysł. To była ta sama historia. Nawet szczegóły były identyczne."],
  ["H","Jimmy zawsze bawił się z prądem. Zabawne, że jego akurat nigdy nie kopnął."],
  ["H","Miałem te kije w celach samoobrony, ale byłem wkurzony. Wziąłem jeden z nich i wybrałem się do pokoju Jimmy'ego."],
  ["H","Jimmy lubił taki rodzaj broni. Nie widziałem go przez cała noc po tym, jak zniszczyłem jego rzeczy. Powinienem był się domyślić, że planował wycięcie swojego następnego numeru."],
  ["H","Cóż, jeżeli Jimmy chciał się tam ukrywać, to pomyślałem, że mu się tam spodobało."],
  ["H","Nikt nie zdawał sobie sprawy, jak daleko Jimmy gotów był się posunąć, żeby zdobyć uwagę innych."],
  ["H","Oszalałem. Byłem wściekły jak diabli. Nienawidziłem go. Straciłem nad sobą panowanie."],
  ["H","To nie był nawet sztylet! Ale nigdy to do mnie nie dotarło – Jimmy był zawsze o krok do przodu."],
  ["R","Tak. To był numer sceniczny Jimmy'ego. Był komikiem. Dobrym, bardzo dobrym. Ludzie zaczęli przychodzić po prostu, żeby go obejrzeć."],
  ["R","Tłuczenie luster to był dopiero początek. Zapytałam go o to, ale on niczego nie pamiętał. Potem zaczęły się dziać inne dziwne rzeczy."],
  ["R","Jimmy zamknął się w pokoju i związał ją. Nie wiedziałam, co zamierzał zrobić. Znazłam ją i uwolniłam. Jimmy powiedział, że to był tylko żarcik! Nie pozwała nas, ale porozmawiała z prasą."],
  ["R","Jimmy nie cierpiał tego, co uczynił. Hugo Punch był jego przeciwnikiem od urodzenia. Tkwił w nim, każąc mu czynić zło. Jimmy nie chciał tak dłużej żyć."],
  ["R","Tak, pobraliśmy się. Z początku byliśmy szczęśliwi, zanim stan rzeczy zaczął się zmieniać."],
  ["R","Myślałam, że urodzenie dziecka wszystko rozwiąże. Myliłam się."],
  ["R","Wyjawiłam Jimmy'emu całą prawdę. Nie pamiętał Huga, zablokował w sobie pamięć o nim. Hugo bił Jimmy'ego od maleńkości, przez dwa lata. Powinnam temu była wcześniej położyć kres."],
  ["R","Nie miałam wyboru. Jimmy wybrał się odwiedzić grób Huga. Zostałam sama. Wiedziałem, co muszę zrobić."],

],

subob:[

  ["Widziałam jakieś walizki w skrzyni. Do kogo one należały?",
  "czy ma to jakiś związek z tamtymi walizkami?"],

  ["Znalazłam jakieś trofea. Kto je zdobył?",
  "czy ma to jakiś związek z tamtymi trofeami?"],

  ["Do kogo należała tamta torebeczka?",
  "czy ma to jakiś związek z tamtą torebeczką?"],

  ["Widziałam butelkę z terpentyną i zapalniczkę. Do czego ich użyto?",
  "czy ma to jakiś związek z terpentyną i zapalniczką?"],

  ["Czyj to miecz?",
  "czy ma to coś wspólnego z tamtym mieczem?"],

  ["Dlaczego w jednym z pokojów była cała masa butelek whiskey?",
  "czy ma to jakiś związek z tamtymi butelkami whiskey?"],

  ["Kto namalował tamte obrazki pełne przemocy?",
  "czy ma to coś wspólnego z tamtymi pełnymi przemocy obrazkami?"],

  ["Do kogo należała tamta czapka kucharska?",
  "czy ma to coś wspólnego z tamtą czapką kucharską?"],

  ["Dlaczego w jednej z szuflad znajdowała poplamiona krwią szmatka?",
  "czy ma to coś wspólnego z tamtą poplamioną krwią szmatką?"],

  ["Skąd ta butelka z diazepamem?",
  "czy ma to coś wspólnego z tamtą butelką z diazepamem?"],

  ["Skąd to drewniane wiosło do klapsów?",
  "czy ma to coś wspólnego z tamtym drewnianym wiosłem do klapsów?"],

  ["Znalazłam album z wycinkami z gazet. Kto go prowadził?",
  "czy ma to coś wspólnego z tamtym albumem z wycinkami z gazet?"],

  ["Skąd się tam wziął wałek do ciasta obwiązany sznurkiem do bielizny?",
  "czy ma to coś wspólnego z tamtym wałkiem do ciasta obwiązanym sznurkiem do bielizny?"],

  ["Dlaczego stary grzejnik jest oznaczony jako 'niebezpieczny'?",
  "czy ma to coś wspólnego z tamtym niebezpiecznym grzejnikiem?"],

  ["O co chodziło z kijami do bejsbola i krykieta?",
  "czy ma to coś wspólnego z tamtymi kijami do bejsbola i krykieta?"],

  ["Skąd ta kusza?",
  "czy ma to coś wspólnego z tamtą kuszą?"],

  ["Do czego służyły tamte zardzewiałe klucze?",
  "czy ma to coś wspólnego z tamtymi zardzewiałymi kluczami?"],

  ["Czy w hotelu wybuchnął pożar?",
  "czy ma to coś wspólnego z tamtym pożarem w hotelu?"],

  ["Czyj to pistolet?",
  "czy ma to coś wspólnego z tamtym pistoletem?"],

  ["Czyj to sztylet?",
  "czy ma to coś wspólnego z tamtym sztyletem?"],

  ["Kim jest Hugo Punch?",
  "czy ma to coś wspólnego z tamtym plakatem o Hugonie Punchu?"],

  ["Dlaczego ktoś stłukł tamte lustra?",
  "czy ma to coś wspólnego z tamtymi potłuczonymi lustrami?"],

  ["Do czego służył tamten zwój drutu?",
  "czy ma to coś wspólnego z tamtym zwojem drutu?"],

  ["Kto napisał tamtą notatkę pożegnalną?",
  "czy ma to coś wspólnego z tamtą notatką pożegnalną?"],

  ["Do kogo należała tamten pierścionek?",
  "czy ma to coś wspólnego z tamtym pierścionkiem?"],

  ["Do kogo należała tamta grzechotka dla dziecka?",
  "czy ma to coś wspólnego z tamtą grzechotką dla dziecka?"],

  ["Znalazłam akt urodzenia Jimmy'ego. Wynika z niego, że Hugo Hall to ojciec Jimmy'ego.",
  "czy ma to coś wspólnego z aktem urodzenia Jimmy'ego?"],

  ["W piwnicy widziałam płaczącą dziewczynkę. Kim ona była?",
  "",
  "Powiedziałaś, że Jimmy cię okradł;",
  "Powiedziałeś, że Jimmy był niemiły wobec tamtej małej dziewczynki;",
  "To, czego się od ciebie dowiedziałam o tamtej małej dziewczynce w hotelu;",
  "To, czego się od ciebie dowiedziałam o tamtej małej dziewczynce, która była tu gościem;"],

  ["Widziałam, jak tamta mała dziewczyna krzyczy, żeby Jimmy oddał jej zabawkę. Dlaczego ją sobie wziął?",
  "Widziałam, jak krzyczysz, żeby Jimmy oddał ci zabawkę. Dlaczego ją wziął?",
  "Powiedziałaś, że Jimmy ukradł ci zabawkę;",
  "Powiedziałeś, że kradzież leżała w naturze Jimmy'ego;",
  "",
  "Powiedziałaś, że Jimmy nie był złodziejem;"],

  ["Widziałam, jak mała dziewczynka o imieniu Amy trzyma płonącą zabawkę. Co się stało?",
  "Widziałam, jak trzymasz płonącą zabawkę. Co się stało?",
  "Powiedziałaś, że nie mogłaś nikomu powiedzieć, że poparzyłaś sobie rękę;",
  "Powiedziałeś, że dla Jimmy'ego podpalenie zabawki Amy to był tylko taki żarcik;",
  "Dziewczynka została poważnie poparzona;",
  "Powiedziałaś, że tamta mała dziewczynka dalej robiła niebezpiecze rzeczy i obwiniała Jimmy'ego;"],

  ["Widziałam Amy na zewnątrz jakiegoś pokoju. Coś ją przeraziło. Co to było?",
  "Widziałam cię na zewnątrz jakiegoś pokoju. Coś cię przeraziło. Co to było?",
  "Powiedziałaś, że potrzebny ci był lekarz, ale Jimmy ci groził i kazał tam zostać;",
  "",
  "Powiedziałeś, że tamta mała dziewczynka prawdopodobnie bała się Jimmy'ego;",
  "Powiedziałaś, że z tamtą małą dziewczynką coś było nie tak;"],

  ["Widziałam, jak Amy coś pije. Nie smakowało jej. Co to było?",
  "Widziałam, jak coś pijesz. Nie smakowało ci. Co to było?",
  "Powiedziałaś, że lekarstwo paskudnie smakowało;",
  "To, czego się od ciebie dowiedziałam o piciu alkoholu przez Amy;",
  "",
  ""],

  ["Widziałam tamtą małą dziewczynką na szczycie schodów, przy balustradzie. Co ona tam robiła?",
  "Widziałam cię na szczycie schodów, przy balustradzie. Co tam robiłaś?",
  "Powiedziałaś, że myślałaś, że jesteś w stanie zeskoczyć na sam dół schodów;",
  "Powiedziałeś, że Jimmy dał jej za dużo do wypicia;",
  "Powiedziałeś, że Amy wypiła całą butelkę whiskey;",
  ""],

  ["Widziałam, że Amy leżała u podnóża schodów. Co się stało?",
  "Widziałam, jak leżysz u podnóża schodów. Co się stało?",
  "Powiedziałaś, że nie możesz się już obudzić;",
  "Powiedziałeś, że śmierć Amy sprawiła, że Rose się z tobą skontaktowała;",
  "Powiedziałeś, że to Jimmy był odpowiedzialny za śmierć Amy;",
  "Powiedziałaś, że Amy sama była sobie winna swojej śmierci;"],

  ["Widziałam, jak jakiś mężczyzna pukał do drzwi i mówił Jimmy'emu, że przyszedł mu pomóc. Kto to był?",
  "",
  "",
  "Powiedziałeś, że Harvey'ego martwił stan umysłu Jimmy'ego;",
  "Powiedziałeś, że Jimmy'emu nikt już nie był w stanie pomóc;",
  "Powiedziałaś, że doktor Bose miał pomóc Jimmy'emu;"],

  ["Widziałam, jak doktor Bose trzymał na drucie martwe zwierzątko. Co się stało?",
  "Widziałam, jak trzymasz na drucie martwe zwierzątko. Co się stało?",
  "",
  "Powiedziałeś, że Jimmy wpadł na pomysł, jak zrobić dla ciebie coś miłego;",
  "Powiedziałeś, że Jimmy twierdził, że tamto małe zwierzątko gdzieś znalazł;",
  "Powiedziałaś, że twoim zdaniem Jimmy nie zabił tamtego zwierzątka;"],

  ["Widziałam, jak doktor Bose rozmawiał z Jimmym na zewnątrz kuchni? Co on robił?",
  "Widziałam, że rozmawiałeś na zewnątrz kuchni z Jimmym. O co chodziło?",
  "",
  "Powiedziałeś, że nie spodziewałeś się, że coś było nie tak;",
  "Powiedziałeś, że doktor Bose nie powinien był próbować pomóc Jimmy'emu;",
  "Powiedziałaś, że doktor Bose chciał zmusić Jimmy'ego do robienia jakichś niechcianych rzeczy;"],

  ["Widziałam, jak doktor Bose pluł krwią. Co się stało?",
  "Widziałam, jak plułeś krwią. Co się stało?",
  "",
  "Powiedziałeś, że Jimmy pilnie potrzebował pomocy;",
  "Powiedziałeś, że Jimmy zawsze za daleko się posuwał ze swoimi żartami;",
  "Powiedziałaś, że doktor Bose sam się zranił, ale obarczył za to winą Jimmy'ego;"],

  ["Widziałam, jak doktor Bose rozmawiał z Jimmym, trzymając igłę w ręku. O co chodziło?",
  "Widziałam, jak rozmawiasz z Jimmym, trzymając igłę w ręku. O co chodziło?",
  "",
  "Powiedziałeś, że Jimmy nie dał sobie podać leku;",
  "",
  "Powiedziałaś, że doktor Bose próbował podać lek Jimmy'emu bez twojej zgody;"],

  ["Widziałam, jak doktor Bose próbował wytłumaczyć, co stało się z Jimmym. Wyglądał na zdesperowanego.",
  "Widziałam, jak próbujesz wytłumaczyć, co się stało z Jimmym. Wyglądałeś na zdesperowanego.",
  "",
  "Powiedziałeś, że Rose dała się przekonać o tym, że Jimmy zmyślał;",
  "Powiedziałeś, że doktor Bose słusznie był zaniepokojony tym, co Jimmy mógłby jeszcze o nim wymyślić;",
  "Powiedziałaś, że postanowiłaś dać doktorowi Bose drugą szansę;"],

  ["Widziałam siedzącego na łóżku doktora Bose, który rozmawiał z Jimmym. O co chodziło?",
  "Siedziałeś na łóżku i rozmawiałeś z Jimmym. O co chodziło?",
  "",
  "Powiedziałeś, że Jimmy powiedział o tobie nowe, o wiele gorsze kłamstwo;",
  "",
  "Powiedziałaś, że nie powinnaś nigdy była zaufać doktorowi Bose;"],

  ["Doktor Bose wyglądał na bardzo strapionego; policjanci dobijali się do jego drzwi. O co chodziło?",
  "Wyglądałeś na bardzo strapionego; policjanci dobijali się do twoich drzwi. O co chodziło?",
  "",
  "Powiedziałeś, że postanowiłeś raz na zawsze przejąć kontrolę;",
  "Powiedziałeś, że nie wierzyłeś w to, co Jimmy powiedział o doktorze Bose;",
  "Powiedziałaś, że doktor Bose zasłużył sobie na to wszystko;"],

  ["Doktor Bose zawiązał sobie sznur wokół szyi. Zabił się. Dlaczego?",
  "Zawiązałeś sobie sznur wokół szyi. Zabiłeś się. Dlaczego?",
  "",
  "Powiedziałeś, że chciałeś położyć temu kres;",
  "Powiedziałeś, że doktor Bose został zmuszony do samobójstwa;",
  "Powiedziałaś, że doktor Bose słusznie postąpił;"],

  ["Jakiś mężczyzna mówił, że Jimmy kłamał na temat napaści. Kto to był?",
  "",
  "",
  "Powiedziałeś, że Harvey wiedział, że Jimmy kłamie;",
  "Powiedziałeś, że znałeś już skądś tamtą historię;",
  "Powiedziałaś, że Harvey niesłusznie nie wierzył wersji zdarzeń Jimmy'ego;"],

  ["Harvey krzyczał i kazał Jimmy'emu przyznać się do kłamstwa. Czy Jimmy przyznał się?",
  "Krzyczałeś, każąc Jimmy'emu przyznać się do kłamstwa. Przyznał się?",
  "",
  "Powiedziałeś, że Jimmy nigdy nie przyznał się do kłamstwa;",
  "Powiedziałeś, że Jimmy zaczął na ciebie zastawiać pułapki;",
  "Powiedziałaś, że Harvey niesłusznie znęcał się nad Jimmym;"],

  ["Harvey'ego poraził prąd. Co się stało?",
  "Poraził cię prąd. Co się stało?",
  "",
  "",
  "Powiedziałeś, że postanowiłeś zniszczyć jego własność;",
  "Powiedziałaś, że Harvey powinien był wcześniej wyrzucić tamten wadliwy grzejnik;"],

  ["Harvey wychodził z pokoju, trzymając w ręku kij. Co zrobił?",
  "Wychodziłeś z pokoju, trzymając w ręku kij. Co zrobiłeś?",
  "",
  "Powiedziałeś, że przemoc tylko szkodzi;",
  "Powiedziałeś, że Jimmy wziął wkrótce odwet;",
  "Powiedziałaś, że Harvey nie był w stanie zapanować nad gniewem;"],

  ["Harvey'ego postrzelono w nogę strzałą. Co się stało?",
  "Postrzelono cię w nogę strzałą. Co się stało?",
  "",
  "",
  "Powiedziałeś, że myślałeś, że Jimmy schował się w piwnicy;",
  "Powiedziałaś, że Jimmy nigdy nie użyłby takiej broni;"],

  ["Harvey zamknął Jimmy'ego w piwnicy. Co się stało?",
  "Zamknąłeś Jimmy'ego w piwnicy. Co się stało?",
  "",
  "",
  "Powiedziałeś, że się myliłeś, mowiąc że Jimmy nie będzie w stanie niczego zepsuć w piwnicy;",
  ""],

  ["W piwnicy wybuchnął pożar. Co się stało z hotelem?",
  "W piwnicy wybuchnął pożar. Co się stało z hotelem?",
  "",
  "",
  "Powiedziałeś, że chciałeś się pozbyć Jimmy'ego;",
  "Powiedziałaś, że pożar był wypadkiem;"],

  ["Harvey ćwiczył z pistoletem. Co zamierzał zrobić?",
  "Ćwiczyłeś z pistoletem. Co zamierzałeś zrobić?",
  "",
  "Powiedziałaś, że Harvey nie był w stanie kontrolować swojego gniewu;",
  "Powiedziałeś, że nie spodziewałeś się, że Jimmy również będzie uzbrojony;",
  "Powiedziałaś, że Harvey nie powinien był mieć pistoletu w hotelu;"],

  ["Harvey szedł w stronę sali balowej z pistoletem w dłoni. Co tam robił?",
  "Szedłeś w stronę sali balowej z pistoletem w dłoni. Co tam robiłeś?",
  "",
  "",
  "Powiedziałeś, że szukałeś Jimmy'ego;",
  ""],

  ["Harvey'ego zadźgano za kulisami. Co się stało?",
  "Zadźgano cię za kulisami. Co się stało?",
  "",
  "",
  "Powiedziałeś, że koniec końców Jimmy zawsze wygrywał;",
  "Powiedziałaś, że była to samoobrona;"],

  ["Pewna kobieta tłumaczyła, że tamten sztylet był w rzeczywistości nożem do listów. Kto to był?",
  "",
  "",
  "",
  "Powiedziałeś, że Rose broniła Jimmy'ego do samego końca;",
  "Powiedziałaś, że policjanci zrozumieli, że Jimmy działał w samoobronie;"],

  ["Kogo witała Rose przy wejściu do recepcji?",
  "Kogo witałaś przy wejściu do recepcji?",
  "",
  "",
  "Powiedziałeś, że myśleli, że próbowałeś zastrzelić Jimmy'ego;",
  "Powiedziałaś, że Jimmy wpadł na pomysł, jak ściągnąć do hotelu więcej gości;"],

  ["Rose zapowiadała występ Huga Puncha.",
  "Zapowiadałaś występ Huga Puncha;",
  "",
  "",
  "",
  "Powiedziałaś, że Jimmy wpatrywał się w siebie w lustrze i stawał się coraz bardziej rozzłoszczony;"],

  ["Rose stała na korytarzu pełnym manekinów. Kto je tam postawił?",
  "Stałaś na korytarzu pełnym manekinów. Kto je tam postawił?",
  "",
  "",
  "",
  "Powiedziałaś, że Jimmy nie panował już nad sobą;"],

  ["Rose była w sali balowej. Widownia krzyczała z dezaprobatą, a Rose składała przeprosiny. Co się tam działo?",
  "Widziałam cię w sali balowej. Widownia krzyczała z dezaprobatą, a ty składałaś przeprosiny. Co się tam działo?",
  "",
  "",
  "Powiedziałeś, że koniec końców Jimmy zawsze wszystko rujnował;",
  "Powiedziałaś, że Jimmy stracił nad sobą panowanie i zrobił coś głupiego;"],

  ["Rose wyglądała na bardzo zmartwioną, a ludzie dobijali się do drzwi zadając jej pytania. Kim oni byli?",
  "Wyglądałaś na bardzo zmartwioną, a ludzie dobijali się do drzwi zadając ci pytania. Kim oni byli?",
  "",
  "",
  "",
  "Powiedziałaś, że Jimmy chciał to wszystko zostawić za sobą i odejść;"],

  ["Rose była w pokoju na górze. Wyglądało na to, że znalazła coś w łazience. Co się stało?",
  "Byłaś w pokoju na górze. Wyglądało na to, że znalazłaś coś w łazience. Co się stało?",
  "",
  "",
  "",
  "Powiedziałaś, że musisz wyjawić prawdę Jimmy'emu;"],

  ["Rose zaatakowała kogoś drewnianym kijem. Kogo?",
  "Zaatakowałaś kogoś drewnianym kijem. Kogo?",
  "",
  "Powiedziałeś, że Rose miała mroczną przeszłość;",
  "Powiedziałeś, że Rose nie o wszystkim ci mówiła;",
  "Powiedziałaś, że nie byłaś w stanie tego znieść;"],

  ["Rose płonęła. Co się stało?",
  "Widziałam, jak płoniesz. Co się stało?",
  "",
  "",
  "",
  "Powiedziałaś, żebym poprosiła Jimmy'ego, aby mi pokazał, gdzie mieszka Hugo;"],

  ["Ktoś był na scenie. Artysta, który przedstawił się jako 'Wielki Hugo'.",
  "",
  "",
  "",
  "Powiedziałeś, że Hugo był pierwszym mężem Rose;",
  "Powiedziałaś, że ty i Hugo byliście czymś więcej;"],

  ["Jakiś mężczyzna krzyczał na kogoś, każąc tej osobie okazywać posłuszeństwo. Kto to był?",
  "",
  "",
  "",
  "",
  "Powiedziałaś, że jedyne, co mogłaś dać Hugowi to dziecko;"],

  ["Słyszałam krzyczącego mężczyznę i płaczące dziecko. Co się stało?",
  "",
  "",
  "",
  "",
  "Powiedziałaś, że Jimmy to syn Huga;"],

],

subs:[

  "INTRO",[
   13.6,5,"Jimmy!",14.6,4,"",
   16.2,4,"Jimmy!",17.4,4,"",
   18.8,2,"Jimmy!",20,4,"",
   20.1,6,"DŹWIĘKI Z GŁOŚNIKA",21.6,6,"",
   24.3,3,"Zostaw mnie w spokoju...",25.9,4,"",
   26.5,6,"SZLOCHANIE",27.9,4,"",
   28.6,6,"CORAZ DONOŚNIEJSZE GŁOSY",30.3,4,"",
   30.7,3,"Przestań!",31.8,4,"",
   32.4,3,"Proszę, zostaw mnie w spokoju!",34.8,4,"",
   35.8,6,"GŁOSY I SZUM",37.3,4,"",
   44.5,6,"DZWONIĄCY TELEFON",45.6,0,"",
   46.6,1,"Halo?",47.6,0,"",
   47.7,3,"Maya? Mówi Hannah.",48.8,0,"",
   49.4,1,"Hannah? Gdzie jesteś?",51.2,0,"",
   51.3,1,"Poszłyście sobie i zostawiłyście mnie samą!",53.6,0,"",
   53.7,1,"Gdzie teraz jesteście? Co to za numer?",55.6,0,"",
   55.7,3,"Zarezerwowałyśmy miejsca w hotelu przy drodze.",57.4,0,"",
   57.5,3,"Daleko to?",58.8,0,"",
   58.9,1,"Nie wiem. Zadzwonię, jak tam dotrę.",61.1,0,"",
   61.2,3,"Nie da się, brak sygnału.",62.9,0,"",
   63,1,"Cóż... ",64.1,1,"",
   65,1,"Nieważne. Idź spać, Hannah.",67,0,"",
   67.1,3,"To słuchaj. Upewnij się, że...",68.3,0,"",
   68.6,6,"URYWANIE SIĘ ROZMOWY",70.1,0,"",
   71,6,"KONIEC ROZMOWY",72.5,0,"",
   84,6,"DŹWIĘKI JAZZU Z LAT 50. PŁYNĄCE Z RADIA",85.5,4,"",
   92.1,3,"Ach, Maya jak sądzę?",94.1,0,"",
   94.5,3,"Och, nie bój się.",96.4,0,"",
   96.6,3,"Twoje przyjaciółki zarezerwowały pokój...",99,0,"",
   99.1,3,"...chwileczkę...",100.8,0,"",
   101.8,3,"Ach, tak.",102.8,0,"",
   102.9,3,"Pokój 101.",104,0,"",
   104.2,3,"Wszystko już opłacone, więc nie musisz się o nic martwić.",107.2,0,"",
   107.3,3,"Fajne te twoje przyjaciółki.",109.1,0,"",
   109.9,3,"Bardzo fajne.",111.2,0,"",
   111.5,3,"I widzę, że sporo was jest.",115.6,0,"",
   116.2,3,"Fajnie tak zobaczyć tyle...",118.2,0,"",
   118.3,3,"...nowych, świeżych twarzyczek dla odmiany.",122.7,0,"",
   123.5,3,"Ach... przyjechałyście do miasteczka na festiwal muzyki, nieprawdaż?",126.8,0,"",
   127.3,1,"Tak, miałyśmy urządzić sobie dzisiaj biwak, ale...",130.5,0,"",
   130.6,3,"Nie w taką pogodę!",133.1,0,"",
   136,3,"Zostaniecie na śniadanie?",137.5,0,"",
   137.6,1,"Raczej nie, pewnie się po prostu zmyjemy.",140.2,0,"",
   140.3,3,"W porządku. Chciałbym cię zapytać, Mayu...",143.7,0,"",
   143.8,3,"Chciałabyś się dzisiaj wieczorem rozerwać?",147.5,0,"",
   147.9,1,"Dzisiaj wieczorem?",148.9,0,"",
   149,3,"Zazwyczaj występ zaczyna się koło północy.",152.1,0,"",
   152.6,3,"Występuję na scenie jako komik.",155.8,0,"",
   155.9,3,"Gram taką postać o imieniu Hugo Punch.",161,0,"",
   161.1,3,"Lekki z niego komik-socjopata.",164.8,0,"",
   164.9,3,"Mówi niestosowne rzeczy i tym podobne.",169.6,0,"",
   169.7,3,"Studentom całkiem się to podoba.",171.7,0,"",
   172.3,1,"Raczej nie skorzystam. Pewnie wszystkie pójdziemy po prostu spać.",175.7,0,"",
   175.8,3,"Na pewno nie dałoby się ciebie do tego przymusić?",179.2,0,"",
   179.5,1,"Nie, raczej pójdę spać. Sorki.",182.8,0,"",
   182.9,3,"W porządku, w porządku...",185.4,0,"",
   185.6,1,"Gdzie są pokoje?",186.7,0,"",
   187.2,3,"Użyj windy, twój pokój jest na pierwszym piętrze.",190.2,0,"",
   190.3,1,"Ok, dzięki.",191.6,0,"",
   193.1,3,"A, i proszę zostaw jutro klucz w skrzynce.",198.1,0,"",
   198.2,1,"Ok!",199.2,0,"",
   199.3,6,"ODGŁOS ZAMYKAJĄCYCH SIĘ DRZWI WINDY",200.8,0,"",
   204.4,3,"Najlepsze widowisko w mieście i żadnych chętnych.",207.2,0,"",
   210.3,3,"Po co komu prawdziwa rozrywka! Mają przecież 'You Tune' i 'My Face', czy jak to się tam nazywa.",216.6,0,"",
   216.7,3,"Głupie, niewykształcone...",218.7,0,"",
   218.8,5,"Hugo nie lubi nieuprzejmych dzieci, są niegrzeczne.",223,0,"",
   225.5,3,"Tylko nie zaczynaj.",227.3,0,"",
   231.1,3,"Nie chcę tego słuchać. Nie dzisiaj.",234.2,0,"",
   237,5,"Niegrzecznym dzieciom potrzebna jest nauczka!",240.9,0,"",
   254.2,3,"Zamknij się! Po prostu się zamknij!",256.5,0,"",
   257.3,3,"Zawsze tak robisz. To są goście hotelu.",260.2,0,"",
   260.5,3,"Niczego ci nie zrobiły.",262.4,0,"",
   263.3,3,"Zostaw je w spokoju.",265.4,0,"",
   266.2,5,"Niegrzeczne dzieci powinny dostać manto. Tak, tak, tak...",269.3,0,"",
   269.5,5,"Prosto do piekiełka!",272.3,0,"",
   272.8,5,"Wiesz, co musisz zrobić, Jimmy.",275,0,"",
   275.6,5,"Pokaż im, kto tu rządzi.",277.7,0,"",
   278.9,5,"Właśnie tak!",281.1,0,"",
   293.3,6,"KRZYK W ODDALI",294.9,0,"",
   308,6,"ŚMIECH MĘŻCZYZNY",309.6,0,"",
   310,3,"Tak jest, pora spać...",313,0,"",
   345.2,6,"TELEFON TRZESZCZY",346.9,0,"",
   358.5,6,"GŁOSY Z GŁOŚNIKA",361.9,0,"",
   362,1,"Uciekaj z hotelu!",363.6,0,"",
   363.7,1,"Uciekaj, póki możesz!",365.7,0,"",
   367.6,1,"Musisz się dowiedzieć, co on zrobił...",369.3,0,"",
   369.4,1,"...i wszystkim to opowiedzieć.",371.3,0,"",
   371.4,1,"Spraw, żeby do niego dotarło, co on zrobił!",373.3,0,"",
   373.5,6,"GŁOSY PRZERADZAJĄ SIĘ W SZUM",376,0,"",
   382.1,1,"Hotel Sea View skrywa mroczną przeszłość.",386.1,0,"",
   389,1,"Zamieszkujące go duchy mają do opowiedzenia pewną historię.",393,0,"",
   395.7,1,"Użyj Wykrywacza zjaw i duchów, aby się z nimi porozumieć.",400.7,0,"",
   402.8,1,"Wyjawią cie one sekrety Jimmy'ego.",406.8,0,"",
   409.5,1,"Ale Jimmy musi ukryć prawdę...",413.5,0,"",
   416.9,1,"...za wszelką cenę.",420.9,0,"X",
],
  "A2",[
   0.8,1,"Jimmy, oddaj to! To moje!",2.9,0,"",
   3,1,"Przestań mi podkradać rzeczy!",4.3,0,"X",
],
  "A3",[
   0.7,6,"KRZYKI",2,0,"X",
],
  "A4",[
   1.1,1,"Mówię ci, Jimmy, tak nie wolno!",3.1,0,"",
   3.2,1,"Wredny jesteś...",4.7,0,"X",
   3.8,6,"GŁOS ZANIKA",4.4,0,"X",
],
  "A5",[
   3.8,6,"KASZEL",4.8,0,"X",
],
  "A6",[
   4.2,6,"CHICHOT",5.2,0,"X",
],
  "P1",[
   3.8,6,"PUKANIE",4.8,0,"",
   5.8,2,"Jimmy?",6.8,0,"",
   7.2,2,"Nazywam sie doktor Bose.",8.9,0,"",
   9,2,"Chciałbym z tobą chwilkę porozmawiać, w porządku?",11.5,0,"",
   14.5,2,"Dziękuję. To nie potrwa długo.",16.6,2,"X",
],
  "P3",[
   1,2,"Znakomity pomysł, Jimmy!",3.4,0,"",
   3.5,2,"Świetny z ciebie kiedyś będzie kucharz.",5.7,0,"",
   5.8,2,"Jak skończysz, to czy mógłbyś mi to przynieść do pokoju?",8,0,"",
   8.1,2,"Będę na ciebie czekać, okej?",9.8,0,"X",
],
  "P4",[
   3,6,"KREW PRYSKA",4,0,"",
   7.6,2,"Jimmy!",8.6,0,"X",
],
  "P5",[
   1.2,2,"To nie będzie boleć, Jimmy.",2.9,0,"",
   3,2,"Przestań się wiercić i stójże w miejscu!",6.6,0,"X",
],
  "P6",[
   0.6,2,"Pani Hall, nigdy nie użyłbym przemocy wobec pacjenta.",4.8,0,"",
   4.8,2,"To sprzeczne z moim system wartości.",7.3,0,"",
   7.4,2,"Niech mnie pani zrozumie – on to wszystko zmyśla!",10,0,"X",
],
  "P7",[
   1.1,2,"Tak łatwo mi się nie wywiniesz, Jimmy.",3.9,0,"",
   4,2,"Powinniśmy zacząć od nowa, nie sądzisz?",6.5,0,"",
   6.6,2,"Spróbuj tym razem się mnie słuchać, dobrze?",8.7,0,"",
   8.8,2,"To byłby dobry początek, nieprawdaż?",11,0,"X",
],
  "P8",[
   0.6,2,"Panie Bose, tu policja.",2.1,0,"",
   2.2,2,"Musimy z panem porozmawiać na posterunku.",4.1,0,"",
   4.4,2,"Proszę otworzyć drzwi.",5.8,0,"X",
],
  "P9",[
   14.1,6,"ODGŁOSY DUSZENIA SIĘ",15.5,0,"",
   15.9,6,"ALARM Z WINDY",16.9,0,"X",
],
  "H1",[
   0.8,3,"Zmyślił to. Mówię ci, on o wszystkim kłamie.",3.4,0,"",
   3.5,3,"O innych sprawach też pewnie kłamał.",5,0,"",
   5.1,4,"Bzdura! O czymś takim by nie skłamał!",7.3,0,"",
   7.4,3,"Na pewno?",8.3,0,"",
   8.4,3,"On łże na każdy temat! Otwórz do cholery oczy, Rose!",11.4,0,"",
   11.5,3,"O, tak! Idź sobie!",12.8,0,"",
   12.9,4,"Nie słucham cię, Harvey. Ty go po prostu nie cierpisz.",14.7,0,"",
   14.9,3,"Ja mówię prawdę!",16.2,0,"X",
],
  "H2",[
   1.5,6,"ODGŁOSY DOBIJANIA SIĘ DO DRZWI",2.4,0,"",
   2.5,3,"Jimmy?",3.5,0,"",
   4.3,3,"Wiem, że mnie słyszycz!",5.8,0,"",
   6.2,3,"Wiem, że twoja historyjka o psychiatrze to bujda.",10,0,"",
   10.1,3,"Wiem, skąd ją wziąłeś!",11.6,0,"",
   12,3,"Wiedziałem, że ją skądś znałem. To było w twoim przeklętym albumie z wycinkami z gazet!",15.3,0,"",
   16.1,3,"Wyłaź!",17.3,0,"",
   18.3,3,"Jimmy!",19.6,0,"X",
],
  "H3",[
   1.2,6,"DŹWIĘK ISKIER",2.2,0,"",
   2.3,6,"OKRZYK BÓLU",3.3,0,"",
   7.2,3,"Jimmy!",8.2,0,"X",
],
  "H4",[
   1,6,"ŁOMOT ROZBIJANYCH RZECZY",2,0,"X",
],
  "H5",[
   0.8,6,"OKRZYK BÓLU",1.9,0,"",
   4.1,3,"Jimmy!",5.1,0,"X",
],
  "H6",[
   1.3,3,"Możesz tam sobie zostać na noc, Jimmy!",3.7,0,"",
   3.8,3,"Ja mam tego dosyć.",5,0,"",
   5.1,6,"ODGŁOSY DOBIJANIA SIĘ DO DRZWI",6.6,0,"X",
],
  "H7",[
   0.3,6,"ALARM PRZECIWPOŻAROWY",1.8,0,"",
   2.7,3,"Jimmy, nie wygłupiaj się! Otwórz drzwi!",4.9,0,"",
   5.2,3,"Bo zginiesz, ty durniu! Otwórzże te drzwi!",8.4,0,"X",
],
  "H8",[
   2.7,3,"Wynocha z mojego hotelu, Jimmy.",4.6,0,"",
   6.6,3,"Wynocha z mojego hotelu...",8,0,"",
   8.6,3,"To jest mój hotel. Wynocha z mojego hotelu, Jimmy.",12,0,"X",
],
  "H9",[
   1.8,3,"Wynocha z mojego hotelu.",3.2,0,"",
   3.3,3,"To jest MÓJ hotel.",5,0,"X",
],
  "R1",[
   0.8,8,"Harvey zamierzał zastrzelić Jimmy'ego.",2.4,0,"",
   2.5,8,"To był tylko nóż do listów. To była samoobrona! Spójrzcie!",5.9,0,"X",
],
  "R2",[
   3.5,4,"Jimmy",4.5,0,"X",
],
  "R3",[
   1.2,4,"Panie i Panowie.",2.4,0,"",
   2.5,4,"Przed Państwem...",3.9,0,"",
   4,4,"...nasza dzisiejsza atrakcja...,",5.9,0,"",
   6,4,"Pan Hugo Punch!",8,0,"",
   8.1,6,"MUZYKA I APLAUZ",9.6,0,"X",
],
  "R4",[
   0,4,"",0,0,"",
],
  "R5",[
   0.7,4,"Na tym polega jego numer sceniczny.",2.6,0,"",
   2.7,4,"Takie ma poczucie humoru!",4.4,0,"",
   4.5,4,"Przykro mi, jeżeli zostało to odczute jako obraźliwe...",6.3,0,"",
   6.4,4,"Przepraszam...",7.6,0,"X",
],
  "R6",[
   0.5,6,"ODGŁOSY DOBIJANIA SIĘ DO DRZWI",1.8,0,"",
   1.9,4,"Pani Hall?",3.4,0,"",
   4.2,4,"Pani Hall, czy moglibyśmy zamienić z panią słówko?",6.5,0,"X",
],
  "R7",[
   1.4,4,"Jimmy?",2.4,0,"",
   4.1,6,"KRZYK",5.1,0,"",
   5.2,4,"Jimmy! Coś ty narobił! Jimmy!",8,0,"X",
],
  "R8",[
   0.5,6,"PŁACZ DZIECKA",1.5,0,"",
   1.6,5,"Rób, co ci każę. Rozumiesz?",4.2,0,"",
   4.3,5,"Głupi bachor!",5.4,0,"",
   5.5,6,"ODGŁOSY BICIA DZIECKA",6.7,0,"",
   6.9,6,"ODGŁOS KIJA UDERZAJĄCEGO MĘŻCZYZNĘ",8.3,0,"X",
],
  "R9",[
   1.4,6,"KRZYK",2.9,0,"X",
],
  "V1",[
   5.5,7,"Patrzcie i podziwiajcie!",6.3,0,"",
   6.4,6,"GONG",7.4,0,"",
   7.5,7,"Oto ja, Wielki Hugo!",10.2,0,"",
   11.9,7,"Stoję ponad całą resztą.",15.9,0,"",
   17.4,7,"Jestem światłem przepędzającym mrok.",21.4,0,"",
   22.7,7,"Tylko ja jestem Panem.",26.5,0,"X",
],
  "V2",[
   5,6,"SZLOCHANIE KOBIETY",6.5,0,"",
   8,5,"Nie kupuj niczego bez mojej zgody!",10.5,0,"",
   10.6,6,"DŹWIĘK TŁUCZONEGO SZKŁA",11.5,0,"",
   11.6,5,"Nie dam ci zrujnować mi życia!",14,0,"",
   14.1,6,"DŹWIĘK TŁUCZONEGO SZKŁA",15.2,0,"",
   15.1,5,"Twoje życie nie jest nic warte!",16.8,0,"",
   16.9,5,"Rozumiesz, co do ciebie mówię?",18.6,0,"",
   18.7,6,"ŁOSKOT I KRZYK KOBIETY",20.9,0,"X",
],
  "V3",[
   3.1,6,"PŁACZ DZIECKA",4.6,0,"",
   9,5,"Siad!",10,0,"",
   10.1,6,"DŹWIĘKI SMAGANIA",11.4,0,"",
   11.5,5,"Głupi bachorze!",12.8,0,"",
   12.9,5,"Rób, co ci każę!",14.9,0,"",
   15,6,"KRZYK KOBIETY<br>Nie!",17,0,"X",
],
  "EPI",[
   17.9,3,"Panie i Panowie.",19,0,"",
   19.1,3,"Przed Państwem...",20.6,0,"",
   20.7,3,"...nasza dzisiejsza atrakcja...,",22.5,0,"",
   22.6,3,"Pan Hugo Punch!",24.7,0,"",
   24.8,6,"APLAUZ",26.4,0,"",
   33.5,5,"Maya!",34.5,0,"",
   36.1,5,"Maya!",37.1,0,"",
   40.5,5,"Maya?",41.5,0,"",
   42,5,"Maya!",43.5,0,"",
   44,6,"SZLOCHANIE",46,0,"",
   47.5,3,"Przestań, przestań, przestań...",49.9,0,"",
   50,3,"Przestań.",51.5,0,"",
   52.6,3,"Dlaczego każesz mi robić takie rzeczy?",55.3,0,"",
   56,3,"Proszę cię, przestań.",57.5,0,"",
   58.4,3,"Proszę przestań, przestań.",60.4,0,"",
   63.2,5,"I tak zawsze to zrobisz, Jimmy.",64.9,0,"",
   66.7,5,"Ja tu rządzę.",68.6,0,"",
   68.7,5,"Nie ty.",69.7,0,"",
   71,5,"Ja tu rządzę.",73.5,0,"",
],
  "BRO",[
   1.5,5,"Witaj w grobowcu Huga!",5.5,5,"",
   5.6,5,"Sekrecik mojej mamusi.",8.9,5,"",
   9,5,"Wiesz, że sama zmieszała beton?",11.8,5,"",
   11.9,5,"Potem wylała go na jego ciało...",15.1,5,"",
   15.2,5,"...i patrzyła, jak zastygnął.",17.8,5,"",
   18.1,5,"Myślała, że się go pozbyła.",21,5,"",
   21.3,5,"Nie dotarła do niej prawda, Mayu.",24.7,5,"",
   24.8,5,"Widzisz, Hugo był po prostu jednym z nas.",29.1,5,"",
   29.2,5,"Kolejną kłodą dodaną do ognia.",33,5,"",
   33.2,5,"Wypalił się.",35.8,5,"",
   36,5,"Ale ogień trawił rodzinę Hallów od stuleci.",41.2,5,"",
   41.3,5,"Oczyszczając drogę....",43.5,5,"",
   43.6,5,"rozświetlając mrok...",45.9,5,"",
   46,5,"niszcząc i starych, i biednych, i bogatych.",52.3,5,"",
   52.4,5,"W tobie też on płonie, Mayu.",56.7,5,"",
   56.8,5,"Ja coś o tym wiem!",58.8,5,"",
   59,5,"Naszym przeznaczeniem jest być razem.",62.9,5,"",
   63,5,"To na ciebie właśnie czekałem.",66.6,5,"",
   66.8,5,"I dlatego nie mogę pozwolić ci stąd odejść.",71,5,"",
   71.1,5,"Zostaniesz tu ze mną, Mayu.",75.2,5,"",
   75.3,5,"Na zawsze.",77.5,5,"X",
],
  "COR",[
   0.2,5,"Gawędzimy sobie ze zmarłymi, co Mayu?",4.3,1,"",
   4.5,1,"Wiem, że Hugo to twój ojciec, Jimmy.",6.6,1,"",
   6.7,1,"Znalazłam twój akt urodzenia. I wiem, że Rose próbowała go zabić.",10.5,1,"",
   10.6,5,"Ale jej się to nie udało, prawda?",13.6,1,"",
   13.7,1,"Więc gdzie on teraz jest?",15.5,1,"",
   15.8,6,"ŚMIECH",17,1,"",
   20.3,5,"Chodź i się z nim przywitaj!",22.8,1,"",
   22.9,5,"Najwyższy czas żebym przedstawił cię mojej rodzince, Mayu.",27.8,1,"",
   27.9,6,"ŚMIECH",29,1,"X",
],
  "AP",[
   2.6,5,"Halo, Mayu!",5,1,"",
   6.5,5,"Mayu!",7.5,5,"",
   9,5,"Mayu!",10.3,5,"",
   10.4,6,"ODGŁOSY DOBIJANIA SIĘ DO DRZWI",11.4,5,"",
   11.9,5,"Nie uciekniesz mi, Mayu!",14.9,5,"",
   15,5,"Otwórz drzwi!",16.2,5,"X",
],
  "TUT",[
   0.83,1,"SYTUACJA",
   4.33,1,"",
   6.4,1,"Oto Jimmy Hall – właściciel,",
   9.3,1,"a także niebezpieczny Psychopata",
   12.37,1,"",
   15.27,1,"Ma podłe zamiary względem przyjaciółek Mai",
   18.3,1,"",
   19.4,1,"Maya uciekła",
   22.4,1,"",
   24.23,1,"Jimmy wie, że musi ją powstrzymać",
   27.33,1,"",
   27.83,1,"POŚCIG",
   31.57,1,"",
   33.3,1,"Jimmy chowa się, gdzie tylko można",
   36.8,1,"",
   39.37,1,"Za rogami",
   41.63,1,"",
   42.33,1,"W ciemnych zakamarkach",
   44.33,1,"",
   45.27,1,"Czeka na ciebie",
   47.6,1,"",
   48.23,1,"Albo próbuje się do ciebie podkraść od tyłu",
   50.57,1,"",
   51.2,1,"Nie jest w stanie ukryć się na schodach,",
   53.53,1,"",
   54.33,1,"na parterze,",
   56.47,1,"",
   57.33,1,"ani w piwnicy",
   60.27,1,"",
   60.7,1,"STRATEGIA",
   64.67,1,"",
   66.17,1,"Jeżeli Jimmy cię zobaczy,",
   67.67,1,"zejdź mu z pola widzenia",
   71.83,1,"",
   75.13,1,"Możesz schować się w dowolnym otwartym pokoju.",
   78.17,1,"",
   79.67,1,"Jeżeli Jimmy wejdzie do środka,",
   81.73,1,"",
   84.13,1,"schowaj się w szafie",
   86.4,1,"",
   90.2,1,"albo w łazience.",
   92.33,1,"",
   94.73,1,"Użyj wizjera, żeby zobaczyć,",
   97.67,1,"",
   98.53,1,"czy Jimmy nie czai się na zewnątrz.",
   101.43,1,"",
   103.63,1,"Zawołaj go, żeby przykuć jego uwagę",
   105.2,1,"",
   106.67,1,"i określić, w którą stronę pójdzie.",
   109.67,1,"",
   110.23,1,"W szufladach pokojów znajdują się klucze.",
   112.67,1,"",
   114.17,1,"Użyj ich, żeby zablokować Jimmy'emu dostęp do środka",
   116.4,1,"",
   117.83,1,"albo zamknij go w pokoju,",
   120.13,1,"jeżeli uda cię się najpierw uciec,",
   123.17,1,"",
   124.67,1,"Szybko sprawdzaj pokoje dzięki dziurkom od klucza.",
   127.7,1,"",
   129.67,1,"UMARLI",
   133.5,1,"",
   135.17,1,"Jimmy jest mordercą.",
   138.2,1,"Jego ofiary wciąż tu są.",
   141.17,1,"Nadal nawiedzają hotel.",
   144.47,1,"",
   145.67,1,"Użyj odbiornika zjaw, żeby z nimi porozmawiać.",
   150.2,1,"",
   153.23,1,"Pytaj ich o wizje, których doświadczasz i odkryj ich historie.",
   159.07,1,"",
   159.13,1,"Pytanie o ważne powiązania, sprawią że zjawy się pojawią.",
   166.63,1,"",
   168.17,1,"Idź śladem migoczących świateł",
   171.1,1,"i wsłuchuj się w dziwne dźwięki.",
   174.07,1,"",
   175.47,1,"Użyj kompasu, który wskazuje ci właściwy kierunek.",
   178.4,1,"",
   180.07,1,"Kiedy jesteś w pobliżu, rozejrzyj się dookoła",
   183.07,1,"albo stań w miejscu i spójrz przed siebie.",
   186.17,1,"",
   186.7,1,"TALENT MAI",
   191.5,1,"",
   192.5,1,"Maya potrafi zajrzeć do innego świata.",
   196.5,1,"",
   197.97,1,"Znajdź słabo oświetlone miejsce",
   200.43,1,"",
   201.43,1,"i użyj tam lusterka.",
   204.67,1,"",
   206.27,1,"Zobaczysz wtedy: położenie ważnych przedmiotów...",
   209.2,1,"położenie zjaw...",
   212.23,1,"powiązania między przedmiotami i zjawami.",
   217.23,1,"",
   218.3,1,"Niekiedy Jimmy może ci ukraść niektóre przedmioty po tym, jak cię złapie.",
   222.77,1,"",
   224.27,1,"Znajdź odbiornik zjaw w magazynie na pierwszym piętrze (obok schodów).",
   229.3,1,"",
   230.27,1,"Znajdź kompas i klucze do pokojów gościnnych.",
   234.77,1,"",
   236.23,1,"Przeczytaj instrukcję użytkowania odbiornika duchów, aby dowiedzieć się więcej o polowaniu na duchy.",
   241.47,1,"",
],
],

itexts:[

  "stare walizki",
  "stare trofea i nagrody",
  "dziecięca torebeczka",
  "butelka z terpentyną i zapalniczka",
  "ozdobny miecz",
  "butelki whiskey i innych wysokoprocentowych alkoholi",
  "pełne przemocy obrazki namalowane przez dziecko",
  "czapka kucharska",
  "stara szmatka poplamiona krwią",
  "strzykawka i butelka z diazepamem",
  "drewniane wiosło do klapsów",
  "album z wycinkami z gazet",
  "sznur do bielizny i wałek do ciasta",
  "stary grzejnik oznaczony jako 'niebezpieczny'",
  "kije do bejsbola i krykieta",
  "kusza",
  "zardzewiałe klucze",
  "zdjęcia dymu unoszącego się z hotelu",
  "stary pistolet",
  "ozdobny sztylet",
  "plakat przedstawiający numer sceniczny Jimmy'ego Halla",
  "potłuczone lustra wiszące na ścianie",
  "zwinięty miedziany drut",
  "ręcznie napisana notatka pożegnalna",
  "pierścionek w pudełeczku",
  "zabawka dla dziecka",
  "aktu urodzenia Jimmy'ego Halla",

],

ketex:[

  "Klucz do pokoju ",
  "Zanotowano ",
  "Zanotowano ",
  "Dodano przedmiot: ",
  "Dodano klucz do pokoju numer ",
  "Kompas",
  "Lusterko jasnowidzenia",

],

patex:[

  ["H","To własność Rose, ale nigdy z nich nie skorzystała.","R","[Walizki] należały do mnie. Chciałam stąd odejść, ale nigdy nie miałam do tego okazji."],
  ["R","Jimmy kupił [trofea]; chciał żeby wyglądało na to, że zdobywa nagrody."],
  ["A","[Torebeczka] należy do mnie. Dostałam ją na urodziny, ale mi ją ukradziono.","H","To torebeczka tamtej biednej dziewczynki.","R","[Torebeczka] to własność tamtej dziewczynki."],
  ["A","Nie wiedziałam, czym były [terpentyna i zapalniczka], dopóki Jimmy mi tego nie pokazał.","P","Zapytaj o to Jimmy'ego.","H","[Terpentyna i zapalniczka] to moje rzeczy, ale nie trzymałem ich razem.","R","[Terpentyna i zapalniczka] należały do Harvey'ego."],
  ["A","To [miecz] Jimmy'ego. Mnie się nie podobał.","P","Dla Jimmy'ego [miecz] był zabawką. Ja uważałem to za niebezpieczne.","H","To była część wystawy poświęconej średniowiecznej broni. Jimmy ukradł [miecz].","R","[Miecz] był razem ze zbroją, którą mieliśmy. Ale potem zniknął."],
  ["A","Nie wiem [skąd te butelki], ale dzieci nie powinny pić alkoholu.","P","[Butelki] wzięto pewnie z baru.","H","Nie pamiętam [skąd te butelki], ale co komu szkodzi wypić od czasu do czasu?","R","Pewnie Harvey postawił tam te [butelki]."],
  ["A","Tamten chłopiec często rysował [obrazki przedstawiające przemoc].","P","Jimmy zwykł rysować [obrazki przedstawiające przemoc].","H","A jak myślisz, kto rysował [obrazki przedstawiające przemoc]? Oczywiście, że Jimmy! Ależ on miał gwałtowną wyobraźnię, oj miał!","R","Jimmy często rysował [brutalne] obrazki przedstawiające wojnę. Był taki, jak większość chłopców."],
  ["P","Jimmy znalazł [czapkę kucharską] i założył ją na głowę.","H","Kucharz ją nosił! Kto inny nosi czapkę kucharską?","R","Nasz kucharz zwykł nosić [czapkę kucharską]."],
  ["A","[Szmatka] mogła być moja.","P","[Szmatka] była moja. Był to dowód rzeczowy – na wszelki wypadek.","H","[Szmatka] mogła mieć coś wspólnego z doktorem."],
  ["P","To [lekarstwo] podaje się niektórym pacjentom w celu leczenia impulsywnych zachowań.","H","Doktor pewnie zapomniał i zostawił [lekarstwo].","R","[Lekarstwo] należało do doktora Bose."],
  ["P","Nie wiem, ale Jimmy znalazł [wiosło do klapsów].","H","[Wiosło do klapsów] zawsze leżało pod ladą na recepcji. Nie wiem skąd się tam wzięło.","R","[Wiosło do klapsów] należało do mojego mężą."],
  ["A","Jimmy prowadził tamten [album z wycinkami]. Nie wiem dlaczego. Dziwny był.","P","Jimmy prowadził [album z wycinkami]. To było ostrzeżenie. Powinienem był to przewidzieć.","H","Jimmy – miał nawyk wycinać z gazet artykuły o znęcających się nad innymi nauczycielach i lekarzach. To nie był normalny chłopiec.","R","Harvey powiedział, że tamten [album z wycinkami] należał do Jimmy'ego, ale ja nie pamiętam."],
  ["P","To ja związałem ze sobą [sznur do bielizny i wałek do ciasta]. To był eksperyment."],
  ["H","[Stary grzejnik] kopał prądem. Zatrzymałem go, aby mogła mu się przyjrzeć policja.","R","Harvey zabrał [stary grzejnik]. Powiedział, że był niebezpieczny."],
  ["A","Tamtemu chłopcu [kije] służyły do zabawy.","P","Harvey zachował [kije]. Nie wiem dlaczego.","H","Zachowałem [kije]. Na wszelki wypadek.","R","[Kije] należały do mojego męża. W czasach gdy był jeszcze nauczycielem."],
  ["A","[Kusza] znajdowała się w hotelowej gablotce. Widziałam ją tam.","P","W hotelu były dawniej wystawione stare sztuki broni.","H","[Kusza] pochodziła ze starej wystawy rzeczy ze zbrojowni. Jimmy'emu się podobała.","R","[Kuszę] wzięto ze starej wystawy Harvey'ego. Ale nie podobało mi się, że takie coś było w hotelu."],
  ["H","[Zardzewiałe kluczy] były do drzwi kotłowni.","R","[Zardzewiałe klucze] były do kotłowni, ale musieliśmy wymienić jej drzwi."],
  ["P","Pierwsze słyszę.","H","Udało im się nad nim zapanować, ale straciłem wiele rzeczy.","R","Zdążyliśmy go opanować, zanim ogień się rozprzestrzenił."],
  ["P","[Pistolet] należał do Harvey'ego. Nie podobało mi się, że coś takiego było w hotelu.","H","[Pistolet] był mój. Należał do mojego ojca. W środku było jeszcze kilka naboi.","R","[Pistolet] należał do Harvey'ego, ale przechowywaliśmy go w mojej sypialni."],
  ["A","Jimmy mi go pokazał, ale to nie była jego własność.","H","To nie sztylet, a otwieracz do listów. Nie musi być naostrzony.","R","[Sztylet] był w rzeczywistości otwieraczem do listów. To był od kogoś prezent."],
  ["R","[Plakat] dotyczył numeru scenicznego Jimmy'ego."],
  ["P","Nie widziałem [potłuczonych luster].","H","Nie przypominam sobie.","R","Jimmy potłukł [lustra]."],
  ["A","Jimmy zawsze go miał pod ręką.","P","[Miedziany drut] był Jimmy'ego. Zawsze miał go w kieszeni. Nigdy mi nie powiedział, do czego był mu potrzebny.","H","Jimmy zwykł ze sobą nosić [miedziany drut]. Nie mam pojęcia dlaczego.","R","Jimmy miał w zwyczaju nosić ze sobą jakiś drut. Lubił się bawić sprzętem elektronicznym."],
  ["R","To Jimmy napisał [notatkę pożegnalną]."],
  ["H","[Pierścionek] prawdopodobnie należy do Rose.","R","[Pierścionek] był mój. Złożono mi propozycję nie do odrzucenia."],
  ["A","Nie wiem. Nie widziałam żadnych dzieci.","R","[Grzechotka] była przeznaczona dla dziecka. Trzymałam ją w szafce nocnej."],
  ["R","Jimmy to syn Huga. W każdym sensie tego słowa."],
  ["A","Chłopiec o imieniu Jimmy zamknął mnie w piwnicy. Potem zaczął mnie okradać.","P","[Tamta dziewczynka] była córką jednego z gości hotelu. Jimmy był wobec niej niemiły.","H","[Dziewczynka] była w hotelu razem ze swoją rodziną.","R","[Dziewczynka] była gościem naszego hotelu."],
  ["A","[Jimmy'ego] bawiło [ukradnięcie mi zabawki]. Potem mi ją oddał, ale i tak ją potem zepsuł.","P","[Jimmy] po prostu robił takie rzeczy.","H","[Jimmy] pewnie uznał to za zabawne.","R","Kłamczucha! Jimmy nie był złodziejem."],
  ["A","Poparzyłam sobie rękę, bardzo mnie bolała, ale nie mogłam o tym nikomu powiedzieć.","P","Ręka [dziewczynki] była bardzo nieprzyjemnie poparzona.","H","[Dziewczynka] była poparzona, dość mocno poparzona.","R","[Tamta dziewczynka] się poparzyła, ale dalej wycinała takie niebezpieczne numery. Dziwna była."],
  ["A","Szukałam lekarza, ale Jimmy mi groził i kazał mi zostać na miejscu.","H","[Dziewczynka] pewnie bała się Jimmy’ego.","R","[Lęk Amy mógł być spowodowany] czymkolwiek. To była dziwna dziewczynka."],
  ["A","Chłopiec powiedział, że to lekarstwo. Paskudnie smakowało.","P","Nie było mnie tam wtedy, ale myślę, że wypiła alkohol."],
  ["A","Zrobiło mi się lekko. Naprawdę myślałam, że uda mi się zeskoczyć na sam dół.","P","Jimmy dał dziewczynce za dużo do wypicia.","H","[Dziewczynka] wypiła całą butelkę whiskey. Nie wiedziała, co robi.","R","Niewiele wiedziałam o [tamtej dziewczynce]."],
  ["A","Skoczyłam, ale potem zrobiło się ciemno i nie mogłam się obudzić. Nie mogę się już obudzić.","P","[Dziewczynka] spadła ze schodów z ostatniego piętra. Była zbyt pijana, żeby wiedzieć, co robi. Z tego powodu skontaktowała się ze mną Rose.","H","[Dziewczynkal] zleciała z ostatniego piętra po schodach. Wiedziałem, że była to sprawka Jimmy'ego.","R","[Dziewczynka] spadła. Harvey obwiniał za to Jimmy'ego. To była wina dziewczynki, a nie Jimmy'ego."],
  ["P","Zadzwoniła do mnie Rose. Chciała, żebym z nim porozmawiał i dowiedział się, co go niepokoi. Ale Harvey'ego martwiły rzeczy, które działy się w wyobraźni Jimmy'ego.","H","Doktor Bose miał za zadanie pomóc Jimmy'emu. Ale Jimmy'emu nikt nie był już w stanie pomóc.","R","Doktor Bose przyszedł pomóc Jimmy'emu."],
  ["P","Jimmy zaczął zabijać małe zwierzątka. Zrozumiałem, że brakowało mu empatii. Więc zapytałem go, czy nie mógłby zrobić dla mnie czegoś miłego. Zaskoczył mnie, bo od razu wpadł na pewien pomysł.","H","Jimmy powiedział, że [martwego królika] gdzieś znalazł. Co z nim robił to inna historia.","R","Harvey powiedział, że to właśnie Jimmy najprawdopodobniej zabił [króliczka], ale ja w to nie wierzyłam."],
  ["P","Jimmy zrobił dla mnie kanapkę. Przyniósł mi ją do pokoju, tak jak go o to poprosiłem. Z początku niczego nie podejrzewałem.","H","Doktor próbował nauczyć czegoś Jimmy'ego. Chciał, żeby chłopiec nauczył się pomagać innym. Co za pomyłka...","R","Doktor Bose próbował sprawić, że Jimmy będzie robił coś, czego chłopiec nie chciał robić."],
  ["P","Jimmy włożył mi do kanapki kawałki potłuczonego szkła. O mało się nie udławiłem. Zrozumiałem, że nie doceniłem choroby Jimmy'ego. Musiałem pilnie zintensyfikować terapię. ","H","[Doktor Bose] poznał prawdę o Jimmym dość brutalnie. Wygłupy Jimmy'ego zawsze szły za daleko.","R","[Doktor Bose] pochlastał się, ale winę próbował zrzucić na Jimmy'ego. Sam się tak urządził – to nie była sprawka Jimmy’ego."],
  ["P","Jimmy nie pozwolił mi podać sobie leku. Potem powiedział Rose, że chciałem go zmusić do przyjęcia lekarstwa, że użyłem wobec niego przemocy. Bzdury!","H","Nie wiem. Nie było mnie tam wtedy.","R","[Doktor Bose] próbował podać jakiś lek Jimmy'emu bez mojej zgody."],
  ["P","Obawiałem się, że Rose uwierzy Jimmy'emu. Ale udało mi się ją przekonać, że Jimmy zmyślał.","H","[Doktor Bose] martwił się tym, co Jimmy może o nim zmyślić. I słusznie.","R","Bo [doktor Bose] obawiał się o swoją reputację. Ale postanowiłam dać mu drugą szansę."],
  ["P","Pomyślałem, że po tym, jak go przyłapano na kłamstwie, Jimmy zacznie ze mną współpracować. Zamiast tego wymyślił nowe kłamstwo. O wiele gorsze. Najgorsze z możliwych.","R","[Doktor Bose] rozmawiał z Jimmym, próbował przejąć nad nim kontrolę. Sprawić, że zacznie robić złe rzeczy. Nie powinnam mu była nigdy zaufać."],
  ["P","Rose zgłosiła na mnie zażalenie. Wiedziałem, że stracę licencję. Pozbawiony kariery, pozbawiony przyszłości. Postanowiłem przejąć kontrolę, raz na zawsze.","H","Mieli aresztować [doktora Bose]. Jimmy zrujnował mu życie. Ja wiedziałem, jak było naprawdę.","R","Przyszli aresztować [doktora Bose]. Zasłużył sobie na to wszystko."],
  ["P","Miałem tego dosyć. Nie było już odwrotu. Moje życie i tak dobiegło już końca.","H","[Doktor Bose] został doprowadzony do takiego stanu. Wszyscy myśleli, że doktor... dotykał Jimmy'ego. Bo widzisz, Jimmy był taki sprytny. Doktor nie miał szans.","R","[Doktor Bose] wiedział, że jest winny. Słusznie postąpił."],
  ["P","Harvey wiedział, że Jimmy kłamał na mój temat. Harvey rozumiał całą sytuację.","H","Jimmy oskarżył doktora. Rose mu uwierzyła, ale ja znałem już skądś tamtą historyjkę.","R","Harvey nie wierzył w słowa Jimmy'ego [na temat doktora], ale ja wiedziałam, że Jimmy nie kłamie."],
  ["P","Jimmy nigdy nie przyznał się do kłamstwa.","H","Jimmy tylko się śmiał. Potem zaczął zastawiać na mnie małe pułapki. Niektóre z nich nie były wcale takie małe.","R","Dlaczego Jimmy miałby się przyznać do czegoś, czego nie zrobił? Harvey niesłusznie się nad nim znęcał."],
  ["H","[Jimmy] Wiedział, że to mój grzejnik. Podłączył go bezpośrednio do instalacji. Wiedziałem, że muszę mu dać nauczkę. Zepsuł moją własność, więc ja postanowiłem popsuć coś należącego do niego.","R","Harvey obwiniał Jimmy'ego, ale tamten grzejnik był wadliwy. Harvey powinien był się go pozbyć dawno temu."],
  ["P","Nie wiem, [po co Harvey’emu był ten kij], ale przemoc pogarsza tylko sprawę.","H","Zniszczyłem telewizor i konsole do gier [Jimmy'ego]. Byłem wkurzony, ale to nic nie dało. Tylko mu się pogorszyło. Wkrótce wziął odwet.","R","[Harvey] zniszczył rzeczy Jimmy'ego. Nie był w stanie zapanować nad swoim gniewem."],
  ["H","Jimmy tak to zaplanował, żeby [kusza] wystrzeliła, gdy otworzyłem drzwi. Trafiłem na oddział ratunkowy. Jak wróciłem, nie mogłem go znaleźć. Rose powiedziała, że schował się w piwnicy. To podsunęło mi pewien pomysł.","R","Harvey powiedział, że Jimmy trafił go strzałą, ale ja wiedziałam, że Jimmy nie użyłby takiej broni."],
  ["H","Chciałem odpłacić Jimmy'emu pięknym za nadobne. Myślałem, że [w piwnicy] nic nie zbroi. Myliłem się.","R","Nie wiem, co [Harvey] robił [w piwnicy]."],
  ["P","Nie pamiętam [pożaru w hotelu].","H","Udało nam się opanować [pożar w hotelu] zanim wymknęł nam się spod kontroli. Ale w piwnicy przechowywane były wszystkie nasze stare fotografie i listy. Poszły z dymem. Nad Jimmym nie dało się już zapanować, miałem go dość. Chciałem się go pozbyć.","R","Harvey obwiniał Jimmy'ego za [pożar w hotelu], ale wywołał go wiszący luzem kawał drutu. To był wypadek."],
  ["P","Nie wiem [skąd ten pistolet]. Ale Harvey nie był w stanie zapanować nad swoim gniewem.","H","Nie wiedziałem, co zamierzałem zrobić [z pistoletem]. Problem tkwił w tym, że nie spodziewałem się, że Jimmy również będzie uzbrojony.","R","Nie wiem, [skąd był tamten pistolet]. Harvey nie powinien był mieć broni palnej w hotelu."],
  ["H","Szukałem Jimmy'ego."],
  ["H","Jimmy podkradł się do mnie od tyłu, w ogóle go nie zauważyłem. Kiedy przyszło co do czego, Jimmy zawsze wygrywał.","R","Harvey zwariował. Jimmy zrobił to w samoobronie."],
  ["H","Rose uwierzyła Jimmy'emu. Broniła go do samego końca.","R","Musiałam wytłumaczyć policji, że sztylet był tylko otwieraczem do listów, a Harvey miał przy sobie załadowaną broń. To była samoobrona."],
  ["H","[Policja] wypuściła Jimmy'ego. Potraktowano to jako samoobronę. Stwierdzono, że próbowałem zastrzelić Jimmy'ego. Ale to wszystko kłamstwa.","R","Jimmy wrócił do domu. Policjanci zrozumieli, że [była to samoobrona]. Ale tamta sytuacja go zmieniła –  zaczął mi pomagać w prowadzeniu hotelu. I wpadł na pomysł, jak ściągnąć większą liczbę gości."],
  ["H","Nie wiem, kim był [Hugo Punch].","R","Dobrze się bawiłam, znowu zaczęliśmy zarabiać na hotelu. Ale Jimmy zaczął się nagle dziwnie zachowywać. Wykrzykiwał coś, patrząc na siebie w lustrze. Wyglądał na rozzłoszczonego."],
  ["R","Z początku nie rozumiałam, co się dzieje. Miałam mętlik w głowie. Ale potem do mnie dotarło. To nie Jimmy to robił. Zaczął pękać – tak jak lustra. Jimmy stracił nad sobą kontrolę."],
  ["H","Tego nie wiem, ale wiem, że koniec końców Jimmy zawsze wszystko rujnował.","R","Na scenie nie występował już Jimmy, ale Hugo Punch. Zaczął ubliżać co noc swojej publiczności. Pewnej nocy po jego występie ktoś z gości powiedział Jimmy’emu, co o nim sądzi. Jimmy wpadł w szał i zrobił coś głupiego."],
  ["R","Dziennikarze [dobijali się do drzwi], bo chcieli porozmawiać z Jimmym. Ale to Hugo Punch związał tamtą kobietę. Jimmy nie był w stanie już nad nim zapanować. Cierpiał na depresję. Chciał wszystko za sobą zostawić i odejść."],
  ["R","[W wannie] był Jimmy. Próbował się zabić. Dlatego musiałam wyjawić mu prawdę."],
  ["H","Nie wiem, [kogo zaatakowała Rose]. Nie o wszystkim mi mówiła.","R","Zabetonowałam Huga [w piwnicy], w ukrytym pokoju. Za długo pozwalałam mu znęcać się nad Jimmym. To przeze mnie wyrosło z niego, to co wyrosło. Myślałam, że przez wyjawienie prawdy Jimmy'emu uwolnię się od winy. Myliłam się. To tylko wszystko pogorszyło. Nie byłam w stanie zaakceptować tego, co zrobiłam. Nie byłam w stanie tego znieść."],
  ["R","Gdybym sama się nie [zabiła], to zabiłby mnie Jimmy – albo raczej Hugo. To Hugo go kontroluje, nawet w tej chwili. On manipuluje Jimmym. Poproś Jimmy'ego, żeby ci pokazał, gdzie mieszka Hugo."],
  ["H","Nigdy nie spotkałem kogoś o pseudonimie [Wielki Hugo].","R","Hugo był iluzjonistą i artystą scenicznym. Kupił ten hotel, żeby promować swoje występy. Stał się sławny. Byłam jego asystentką, a potem... kimś więcej."],
  ["R","Nigdy nie wiedziałam, czego chce. Jedyne co mogłam mu dać to dziecko."],
  ["R","Hugo był brutalnym, podłym, chorym na umyśle człowiekiem."],
  ["A","Tak! [Jimmy] wziął ją, jak nie patrzyłam i ukradł mi pieniądze. Zbeształam go, ale w ogóle mnie nie słuchał."],
  ["A","[Jimmy] namoczył moją zabawkę tym czymś z butelki. Nienawidzę go!"],
  ["A","[Jimmy] zdjął miecz ze ściany. Wyglądał na ostry. Kazał mi obiecać, że nikomu nie powiem. Powiedział, że wie, jak sprawić, żeby ręka przestała mnie boleć."],
  ["A","[Jimmy] kazał mi wypić [lekarstwo] do dna. Paskudnie smakowało. Potem dziwnie się poczułam."],
  ["P","[Obrazki przedstawiające akty przemocy] wskazywały na zaburzenia osobowości, ale niezbyt się tym martwiłem do czasu, aż... zdałem sobie sprawę, jak wybujała była wyobraźnia [Jimmy'ego]."],
  ["P","Jimmy powiedział, że coś dla mnie zrobi, więc poszedłem za nim zobaczyć, co dokładnie planuje."],
  ["P","[Kanapka z kawałkami szkła] była moim pierwszym zetknięciem się z poczuciem humoru Jimmy'ego."],
  ["P","[Diazepam] nie był idealnym lekarstwem, ale jedynym jakie miałem. Jimmy pilnie potrzebował leczenia – był niebezpieczny."],
  ["P","Jimmy powiedział, że uderzyłem go wiosłem do klapsów. Nigdy nie użyłem przemocy wobec pacjenta – to była wierutna bzdura! Ale Rose mu uwierzyła."],
  ["P","Jimmy oskarżył mnie o najgorsze możliwe przestępstwo. Wpadł na to, czytając gazetę. Wszystko zmyślił."],
  ["P","Rozważałem użycie sznurka do wieszania prania, ale okazał się on za cienki. Zamiast tego znalazłem kawałek zwykłego sznurka. Wciąż miałem swoje klucze do hotelu, więc po wyjściu za kaucją wkradłem się pewnej nocy do środka."],
  ["H","Jak tylko znalazłem tamten album z wycinkami, to wiedziałem, jak Jimmy wpadł na [tamten pomysł]. To była ta sama historia. Nawet szczegóły były identyczne."],
  ["H","Jimmy zawsze bawił się z prądem. Zabawne, że jego akurat nigdy nie kopnęło."],
  ["H","Zachowałem tamte kije w celach samoobrony, ale byłem wkurzony. Wziąłem jeden z nich i wybrałem się do pokoju Jimmy'ego."],
  ["H","Jimmy lubił broń taką, jak na przykład tamta [kusza]. Nie widziałem go przez całą noc po tym, jak zniszczyłem jego rzeczy. Powinienem był się domyślić, że planował wycięcie swojego następnego numeru."],
  ["H","Cóż, jeżeli Jimmy chciał się ukrywać [w piwnicy], to pomyślałem, że mu się tam spodobało."],
  ["H","Nikt nie zdawał sobie sprawy, jak daleko Jimmy gotów był się posunąć, żeby zyskać uwagę innych."],
  ["H","Oszalałem. Byłem wściekły jak diabli. Nienawidziłem go. Straciłem nad sobą panowanie."],
  ["H","To był [otwieracz do listów], nawet nie sztylet! Ale nigdy do mnie nie dotarło, że Jimmy był zawsze o krok do przodu."],
  ["R","Jimmy zaczął występować na scenie jako Hugo Punch. Był komikiem. Dobrym, bardzo dobrym. Ludzie zaczęli przychodzić po prostu, żeby go obejrzeć."],
  ["R","Tłuczenie luster to był dopiero początek. Zapytałam go o to, ale on niczego nie pamiętał. Potem zaczęły się dziać inne dziwne rzeczy."],
  ["R","Jimmy zamknął w pokoju i związał tamtą [kobietę, która się na niego poskarżyła]. Znalazłam ją i uwolniłam. Nie pozwała nas, ale porozmawiała z prasą."],
  ["R","Hugo Punch był przeciwnikiem Jimmy'ego od urodzenia. Jimmy nie chciał tak dłużej żyć."],
  ["R","[Hugo i ja] pobraliśmy się. Z początku byliśmy szczęśliwi, ale potem sytuacja zaczęła się zmieniać."],
  ["R","Myślałam, że urodzenie dziecka wszystko rozwiąże. Myliłam się."],
  ["R","Wyjawiłam Jimmy'emu całą prawdę. Hugo bił Jimmy'ego od maleńkości, przez dwa lata. Powinnam temu była wcześniej położyć kres."],
  ["R","Jimmy wybrał się odwiedzić grób Huga. Zostałam sama. Wiedziałem, co muszę zrobić."],
],

finwords:[

  "W każdym z nas jest<br>ktoś, kogo nie znamy.",7,
  "",0.5,
  "Przemawia do nas w snach",6,
  "i tłumaczy, że widzi nas <br>zupełnie inaczej, niż my siebie.<br><span class='h8'>Carl Jung</span>",8,
  "V",5,
  "Tego kogoś można zobaczyć",4,
  "",0.5,
  "w środku nocy.<br>(At Dead of Night)",5,
  "",16,
  "<span class='hf'>Maya</span><br>Chloe Booyens",5,
  "<span class='hf'>Jimmy Hall</span><br>Huld Martha",5,
  "<span class='hf'>Rose Hall</span><br>Joanna Bond",5,
  "<span class='hf'>Harvey</span><br>Karl Haynes",5,
  "<span class='hf'>Dr Bose</span><br>Rohit Gokani",5,
  "<span class='hf'>Amy Bell</span><br>Daisy Follin",5,
  "<span class='hf'>W rolach drugoplanowych</span><br>Rachel Alfieri<br>Paige Ryan<br>Sally Alfieri<br>Daniel Alfieri<br>Luke Chase",8,
  "<span class='hf'>W rolach drugoplanowych</span><br>Sam Follin<br>Jamie Follin<br>Tom Follin<br>Clare Follin",7,
  "<span class='hf'>Specjalne podziękowania</span><br>Mark Wilson<br>Fay Wilkins",7,
  "",1,
  "Dziękujemy ci za granie w<br>At Dead Of Night",8,
  "",

],

words:[

  "WŁĄCZ URZĄDZENIE",
  "WYŁĄCZ URZĄDZENIE",
  "KRZYKNIJ",
  "UŻYJ LUSTERKA JASNOWIDZENIA",
  "ZADAJ PYTANIE",
  "ZAMKNIJ",
  "Zapytaj<br>kto<br>tam",
  "Zapytaj<br>o imię",
  "Czy to<br>",
  "BIEGNIJ PRZED SIEBIE",
  "WCIŚNIJ<br>PODPOZIOM",
  "WCIŚNIJ<br>PARTER",
  "WCIŚNIJ<br>PIERWSZE<br>PIĘTRO",
  "WCIŚNIJ<br>DRUGIE<br>PIĘTRO",
  "WCIŚNIJ<br>TRZECIE<br>PIĘTRO",
  "WRÓĆ",
  "OTWÓRZ<br>MENU",
  "Zawołaj w stronę Jimmy'ego",
  "SPRAWDŹ<br>DRZWI<br>",
  "SPRAWDŹ<br>POKÓJ<br>",
  "WRÓĆ<br>DO POKOJU",
  "WYPUŚĆ<br>PRZYJACIÓŁKĘ<br>NA ZEWNĄTRZ",
  "POŁĄCZONO<br>TO",
  "SPRAWDŹ<br>MAGAZYN NR<br>PIĘĆ",
  "WEZWIJ<br>WINDĘ",
  "ZAPYTAJ O TO",
  "UKRYJ SIĘ<br>W SZAFIE",
  "UKRYJ SIĘ<br>W ŁAZIENCE",
  "ZERKNIJ<br>PRZEZ WIZJER",
  "WEJDŹ<br>DO POKOJU",
  "SZUKAJ<br>TUTAJ",
  "OPUŚĆ<br>POKÓJ",
  "SPRAWDŹ<br>DRZWI",
  "ZAMKNIJ",
  "OTWÓRZ<br>NOTATKI",
  "POŁĄCZ<br>W PARĘ",
  "WRÓĆ<br>DO DRZWI",
  "POŁĄCZ WIZJE<br><span style='font-family:arial'>Z</span> PRZEDMIOTAMI",
  "ZAPYTAJ, CZY ISTNIEJE TUTAJ ZWIĄZEK",
  "ZAPYTAJ",
  "NASTĘPNA STRONA",
  "POPRZEDNIA STRONA",
  "SPRAWDŹ DRZWI DO KLATKI SCHODOWEJ",
  "ZA CIEMNO",
  "WEJDŹ<br>DO POKOJU",
  "WYJDŹ<br>Z SAMOUCZKA",
  "Znajdź urządzenie w przechowalni na pierwszym piętrze (obok schodów)",
  "Musisz znaleźć<br>lusterko<br>jasnowidzenia",
  "Musisz<br>znaleźć<br>kompas",
  "Musisz znaleźć<br>kompas oraz<br>lusterko jasnowidzenia",
  "Gra<br>Zapisana",
  "WYJRZYJ<br>PRZEZ OKNO",
  "Zaczekaj, aż nie będziesz już w niebezpieczeństwie",
  "WYJDŹ",
  "Zły klucz",
  "Otwarto drzwi",
  "Stań twarzą do drzwi,<br>żeby spróbować użyć klucza",
  "Drzwi zamknięte",
  "Sprawdź najpierw drzwi",
  "Użyj klucza,<br>żeby zamknąć drzwi",
  "Otwórz pierwsze drzwi",
  "IDŹ NA GÓRĘ",
  "IDŹ NA DÓŁ",
  "Jest tu za ciemno, żeby można było skorzystać z urządzenia",
  "Odczekaj chwilę, zanim spróbujesz ponownie nawiązać kontakt.",
  "Jimmy zaraz wejdzie do pokoju!",
  "Jimmy'ego słychać gdzieś w pobliżu",
  "Jimmy lekko zachichotał",
  "Rozpocznij najpierw grę",
  "Nie możesz w tej chwili zapisać stanu gry",
  "Aktualny Stan Gry Zapisany",
  "Jest za wcześnie, żeby ponownie móc użyć lusterka",
  "Nie rób tego!<br>Jimmy jest w pokoju!",
  "ZAJRZYJ PRZEZ<br>DZIURKĘ OD KLUCZA",
  "Najrozsądniej będzie nie zamykać przechowalni",
  "WEŹ<br>URZĄDZENIE",
  "Jest tu za ciemno, żeby można było skorzystać z lusterka",
  "Przechowalnia",
  "Nie wiadomo",
  "Jest tu za jasno, żeby można było skorzystać z lusterka",
  "WRÓĆ<br>DO MENU",
  "Zapisz<br>Grę?",
  "ZAPISZ",
  "W pobliżu słychać kroki Jimmy'ego",
  "Słychać, że Jimmy gdzieś się bardzo szybko porusza",
  "Zamknięto drzwi do pokoju",
  "POMIŃ<br>PRZEBUDZENIE",
  "Poszukaj urządzenia w przechowalniach",
  "POMIŃ",
  "ZAMKNIJ WIADOMOŚĆ",

],

ghostex:[

  "A",
  "Nawiązano Kontakt<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;AMY&#160;&#160;</span>&#10023;<br><br>10-letnia dziewczynka",
  "P",
  "Nawiązano Kontakt<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;DR BOSE&#160;&#160;</span>&#10023;<br><br>Psychiatra kliniczny",
  "H",
  "Nawiązano Kontakt<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;HARVEY&#160;&#160;</span>&#10023;<br><br>Właściciel hotelu",
  "R",
  "Nawiązano Kontakt<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;ROSE&#160;&#160;</span>&#10023;<br><br>Właścicielka hotelu",

],

headtex:[

  "<span class='h3'>Znajdź Odbiornik Zjaw.</span>",
  "<span class='h3'>Włącz Odbiornik Zjaw,<br>aby się z nimi skontaktować.</span>",
  "<span class='h3'>Podgłośnij Odbiornik Zjaw, aby usłyszeć ich odpowiedzi.</span>",
  "<span class='h3'>Spróbuj nawiązać kontakt ze zjawą</span><br><span class='h2'>(Użyj ikonki 'Mów' u góry)</span>",
  "<span class='h3'>Zjawa nawiązuje z tobą kontakt.<br>Potwierdź tożsamość zjawy.</span>",
  "<span class='h3'>Nawiązano Kontakt ",
  "<span class='h3'>Zjawa jest zbyt daleko. Spróbuj podejść bliżej.</span>",
  "<span class='h2'>Zjawom które spotkasz możesz zadawać pytania. Połącz ich odpowiedzi, aby odkryć powiązania. Kiedy nie rozmawiasz akurat ze zjawą, możesz przejrzeć odpowiedzi zjaw w tym miejscu.</span>",

],

gametex:[

  "Rozgrywka Standardowa<br><br><span class='h2'>Znajdź zjawy, zadaj im pytania i odkryj powiązania, aby sprawić, że się pojawią. W tym samym czasie Jimmy spróbuje cię powstrzymać przed odkryciem prawdy.</span>",
  "Znajdź i Uratuj<br><br><span class='h2'>Uratuj swoje przyjaciółki, podczas gdy Jimmy spróbuje cię dopaść. Jedno trafienie oznacza koniec gry.</span>",
  "Znajdź i Uratuj<br><br><span class='h2'>Wróć do końca ostatniej rozgrywki.</span>",
  "<span class='h9'>Wybierz tryb gry</span><br><br><span class='h2'>Wybierz pomiędzy Trybem Standardowym a Trybem Ekstremalnym. Jeżeli Jimmy zaatakuje cię w Trybie Ekstremalnym, to za każdym razem zabierze ci prawie wszystkie zebrane przez ciebie przedmioty.<br><br>Twoja aktualna rozgrywka zostanie utracona, a twoje osiągnięcia zostaną zresetowane.</span>",
  "<span class='h9'>Na pewno?</span><br><br><span class='h2'>to zakończy twoją aktualną rozgrywkę i zabierze cię do ostatniego zapisanego stanu gry.</span>",
  "<span class='h9'>Raz łup i już trup!/span><br><br><span class='h2'>Ta gra nie używa funkcji zapisu, więc masz tylko jedną szansę, żeby wszystkich uratować!</span>",

],

getex:[

  "<br>Znaleziono<br><br>Lusterko jasnowidzenia<br><br><span style='font-size:50%'>W ciemnych miejscach<br>ujawnia ono<br>wskazówki i poszlaki</span>",
  "<br>Znaleziono<br><br>Kompas<br><br><span style='font-size:50%'>Wskazuje on, gdzie<br>znajdują się zjawy</span>",
  "<span style='font-size:40%>'>Znaleziono<br>Klucz oznaczony<br>",
  "Znaleziono klucz typu deadlock do pokoju",
  "Znaleziono klucz typu deadlock do pokoju",

],

roomtex:"Pokój",

foundtex:"Znaleziono",

alreadytex:[

  "Masz już lusterko jasnowidzenia",
  "Masz już kompas"

],

adtext:[

  "Płacz<br>dziewczynki",
  "Dźwięki dochodzące z salonu gier",
  "Cichy płacz<br>dziewczynki",
  "Łagodny śpiew<br>dziewczynki",
  "Delikatne<br>pukanie",
  "Dźwięk przesuwanej zastawy stołowej",
  "Dźwięk<br>wody z kranu",
  "Dźwięk<br>wykręcania numeru telefonu",
  "Głośne<br>pukanie",
  "Dobijanie się<br>do drzwi",
  "Dźwięk iskier<br>i syczenie",
  "Łoskot<br>rozwalanych rzeczy",
  "Urywany odgłos<br>uderzania lub łamania czegoś",
  "Dobijanie się<br>do metalowych drzwi",
  "Głośny alarm",
  "Głos Harvey'ego krzyczącego na Jimmy'ego",
  "Łagodny<br>szum tłumu",
  "Muzyka płynąca<br>z radia",
  "Gwizdy i okrzyki z tłumu",
  "Sporadyczne dzwonienie do drzwi",
  "Dźwięk napełniania wanny wodą",
  "Sporadyczne<br>odgłosy bicia",
  "Dźwięki muzyki",

],

itdetext:[

  "Walizki",
  "Trofea",
  "Dziecięca torebeczka",
  "Terpentyna i zapalniczka",
  "Miecz",
  "Butelki whiskey",
  "Obrazki pełne przemocy",
  "Czapka kucharska",
  "Poplamiona szmatka",
  "Diazepam",
  "Drewniane wiosło do klapsów",
  "Album z wycinkami z prasy",
  "Sznur do bielizny",
  "Niebezpieczny grzejnik",
  "Kije sportowe",
  "Kusza",
  "Zardzewiałe klucze",
  "Zdjęcia pożaru",
  "Pistolet",
  "Ozdobny sztylet",
  "Plakat Huga Puncha",
  "Stłuczone lustra",
  "Zwinięty drut",
  "Notatka pożegnalna",
  "Obrączka ślubna",
  "Grzechotka",
  "Akt urodzenia",
  "Dziewczynka w piwnicy",
  "Okradnięcie Amy przez Jimmy'ego",
  "Trzymająca płonącą zabawkę Amy",
  "Przestraszona Amy na zewnątrz pokoju",
  "Amy pijąca coś okropnego",
  "Amy u szczytu schodów",
  "Amy u podnóża schodów",
  "Pukający do drzwi mężczyzna w garniturze",
  "Znalezione przez doktora Bose martwe zwierzątko",
  "Dr Bose na zewnątrz kuchni",
  "Plujący krwią dr Bose",
  "Dr Bose trzymający w ręku igłę do zastrzyków",
  "Dr Bose wyjaśniający, co się stało",
  "Dr Bose siedzący na łóżku w pokoju",
  "Dr Bose w pokoju gier",
  "Samobójstwo doktora Bose",
  "Mężczyzna twierdzący, że Jimmy kłamie",
  "Harvey krzyczący przez drzwi",
  "Harvey porażony prądem",
  "Harvey z kijem",
  "Postrzelenie Harvey'ego w nogę",
  "Zamknięcie Jimmy'ego w piwnicy przez Harvey'ego",
  "Pożar w piwnicy",
  "Harvey z pistoletem",
  "Harvey zmierzający w stronę sali balowej",
  "Zadźganie Harvey'ego",
  "Kobieta wyjaśniająca prawdę o sztylecie",
  "Rose u drzwi wejściowych",
  "Zapowiedź Huga Puncha przez Rose",
  "Znalezienie manekinów przez Rose",
  "Przeprosiny Rose",
  "Chowająca się Rose i dobijający się do drzwi ludzie",
  "Znalezienie Jimmy'ego przez Rose w łazience",
  "Zaatakowanie kogoś przez Rose kijem",
  "Płonąca Rose",
  "Wielki Hugo na scenie",
  "Krzyczący mężczyzna i płaczące dziecko",
  "Krzyki i spadająca winda",
  "Nieposłuszeństwo Jimmy'ego",
  "Namoczenie zabawki Amy przez Jimmy'ego",
  "Jimmy i sposób na powstrzymanie bólu ręki Amy",
  "Wypite przez Amy paskudztwo",
  "Widziane przez doktora obrazki autorstwa Jimmy'ego",
  "Pomysł Jimmy'ego",
  "Doktor Bose i poczucie humoru Jimmy'ego",
  "Decyzja doktora o podaniu leku Jimmy'emu",
  "Oskarżenie doktora Bose przez Jimmy'ego o stosowanie przemocy",
  "Oskarżenie doktora Bose przez Jimmy'ego o molestowanie",
  "Decyzja doktora Bose",
  "Znalezienie przez Harvey'ego albumu z wycinkami",
  "Zabawy z prądem Jimmy'ego",
  "Wizyta uzbrojonego w kij Harvey'ego w pokoju Jimmy'ego",
  "Podejrzenie Harvey'ego o istnienie kolejnej pułapki",
  "Użycie przez Harvey'ego klucza do kotłowni",
  "Zdanie sobie sprawy przez Harvey'ego z szaleństwa Jimmy'ego",
  "Utrata kontroli przez Harvey'ego",
  "Jimmy będący zawsze o krok do przodu",
  "Numer sceniczny Jimmy'ego",
  "Początek dziwnych zdarzeń",
  "Zdobycie informacji przez gazety",
  "Zmęczenie Jimmy'ego całą tą sytuacją",
  "Zmiana dotykająca Huga",
  "Dziecko to żadne rozwiązanie",
  "Ujawnienie prawdy",
  "Poczucie winy u Rose",
  "Klucz do przechowalni",
  "",
  "",
  "Lusterko jasnowidzenia",
  "Kompas",
  "Klucz podpisany 'Schody na Pierwszym Piętrze'",
  "",
  "",
  "Lusterko jasnowidzenia",
  "Kompas",
  "Klucz do przechowalni",
  "",
  "",
  "Lusterko jasnowidzenia",
  "Kompas",
  "Klucz podpisany 'Schody na Drugim Piętrze'",
  "",
  "",
  "Lusterko jasnowidzenia",
  "Kompas",
  "Klucz do przechowalni",
  "",
  "",
  "Lusterko jasnowidzenia",
  "Kompas",
  "Klucz podpisany 'Schody na Trzecim Piętrze'",
  "",
  "",
  "Lusterko jasnowidzenia",
  "Kompas",
  "Klucz do przechowalni",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Klucz do wyjścia z hotelu",
  "Klucz do przechowalni w piwnicy",

],

keyfinds:[

    "PRZECHOWALNIA",
    "SCHODY PIERWSZE PIĘTRO",
    "SCHODY DRUGIE PIĘTRO",
    "SCHODY TRZECIE PIĘTRO",

  ],

gnames:[
  "Amy",
  "Dr Bose",
  "Harvey",
  "Rose",
  "Hugo"
],

extras:[
  "WITAMY W<br>HOTELU SEA VIEW<br><span style='font-size:50%'>PODPISZ SIĘ TUTAJ</span>",
  "Maya:",
  "Gra zapisana",
  "Podłączono kontroler do gier",
  "Odłączono kontroler do gier",
],

};
