var SPA={

mentex:[

"El<br><span class='bt1'>Receptor de voz fantasmal y espiritual de Edison<br></span>Guía de uso<br><br>Aviso sobre la comunicación sobrenatural<br><br>Cuando se contacta con un fantasma o espíritu, su estado emocional se traduce directamente a su potencial eléctrico o estado de 'energía'. Los fantasmas pueden manifestarse en estados de alta o baja energía, pero para la comunicación por voz se requiere un estado de baja energía.<br><br>Los fantasmas pueden verse impulsados ​​a cambiar entre estados de energía mediante preguntas provocativas o agresivas. Si un fantasma entra en un estado de alta energía, este dispositivo solo recibirá un fuerte ruido estático y la comunicación no podrá continuar.<br><br>Los fantasmas en un estado de alta energía a menudo se manifiestan físicamente, sin ayuda electrónica u óptica. Esto suele ocurrir en una ubicación diferente. Tenga en cuenta que las entidades sobrenaturales son las almas de los muertos. Por favor, trátelos con el debido respeto.",

"energía aumentada<br>por conversación<br><br>ESTADO BAJO<br><br><br><br><br>LA VOZ SE PUEDE ESCUCHAR",

"<br><br><br>ESTADO ALTO<br><br><br><br><br>PUEDE MANIFESTARSE FÍSICAMENTE<br><br>energía disipada por manifestación",

"<div class='ht'><span style='font-size:170%'>Consejos de juego</span><br><br>Juega At Dead Of Night en plena noche, o al menos en una habitación oscura, y asegúrate de que haya la menor cantidad posible de sonidos de fondo, o usa auriculares si estás jugando solo.<br><br>Deberías poder ver las áreas más oscuras de la imagen, ya que gran parte del hotel está a oscuras y la sombra de Jimmy a veces apenas se intuye. Ajusta el brillo (teclas U / I) para que aparezcan las sombras si es necesario.<br><br>La voz de Jimmy se puede escuchar si está en el mismo piso que tú. Si escuchas con atención, también puedes escuchar sus pasos, que te ayudarán a saber cómo de cerca está. Los fantasmas también emiten sonidos. Si quieres escuchar mejor, presiona 'D' para bajar el sonido ambiente por unos instantes.<br><br>Si necesitas asistencia auditiva, selecciona la opción 'Descripción mejorada' en 'Subtítulos'. Si no necesitas esta ayuda, es recomendable dejarlo desactivado.<br><br>Las brújulas apuntan hacia los fantasmas incluso a través de las paredes, por lo que si no puedes encontrar un fantasma en la dirección en la que apunta, intenta caminar por los pasillos. La brújula gira lentamente cuando no hay fantasmas alrededor y gira más rápido cuando estás cerca de uno.<br><br>Recuerda que puedes mirar a través de los ojos de las cerraduras para ver el interior de las habitaciones y que puedes correr más rápido por pasillos largos moviendo la flecha hacia la parte superior de la pantalla.</div>",

"<div class='ht'><span style='font-size:170%'>Jimmy y el TID</span><br><br>La historia de Jimmy es una representación teatral y simbólica de alguien que lucha contra dos caminos morales opuestos y no pretende ser una descripción literal del trastorno psicológico real conocido como TID, o trastorno de identidad disociativo.<br><br>El TID real es una enfermedad angustiante y debilitante, a menudo (pero no siempre) asociada con el abuso infantil. El TID no se correlaciona de ninguna manera con un comportamiento inmoral o criminal. Quienes padecen TID necesitan compasión, pero a menudo experimentan condena o desconfianza, generalmente como resultado de un malentendido público.<br><br>No era nuestra intención dar a entender que Jimmy padece este trastorno y aceptamos plenamente que perpetuar los estereotipos es perjudicial y dificulta el progreso y su comprensión. Nos disculpamos sinceramente por cualquier angustia o dolor causado a quienes padecen TID.<br><br>Para obtener más información, consulte:<br><br>https://survivorsnetwork.org.uk/resource/dissociative-identity-disorder-d-i-d/</div>",

"Gracias a los fabulosos talentos<br>de las actrices y actores<br><br><table><tr><td><span class='h5'>Jimmy</span><br><span class='ht'>Huld Martha</span><br><br><span class='h5'>Rose</span><br><span class='ht'>Joanna Bond</span><br><br><span class='h5'>Dr Bose</span><br><span class='ht'>Rohit Gokani</span><br><br></td><td><span class='h5'>Maya</span><br><span class='ht'>Chloe Booyens</span><br><br><span class='h5'>Harvey</span><br><span class='ht'>Karl Haynes</span><br><br><span class='h5'>Amy<span><br><span class='ht'>Daisy Follin</span><br><br></td></tr></table><span class='h5'>Y actores secundarios</span><table><tr><td><span class='ht'>Rachel Alfieri<br>Paige Ryan<br>Sam Follin</span></td><td><span class='ht'>Jamie Follin<br>Clare Follin<br>Tom Follin</span></td></tr></table><br><span class='h5'>Con agradecimiento especial a</span><br><table><tr><td><span class='ht'>Mark Wilson</span></td><td><span class='ht'>Fay Wilkins</span></td><td><span class='ht'>Daniel Alfieri<span></td><td><span class='ht'>Sally Alfieri</span></td><td><span class='ht'>Luke Chase</span></td></tr></table><br><span class='h7'>Creado por Tim 'y entonces que haces ahora' Follin<br>©2020 Baggy Cat Ltd</span></span>",

"&#160;&#160;&#160;&#160;&#160;&#160;&#160;Descripción mejorada<br><br><span class='h2'>Muestra subtítulos mejorados y una descripción de texto de los sonidos que se escuchan durante el juego, junto con un indicador de volumen.<br><br>Si no necesitas ayuda, es mejor dejar esta opción desactivada.</span>",

"&#160;&#160;&#160;&#160;&#160;&#160;&#160;Subtítulos<br><br><span class='h2'>Muestra subtítulos básicos en el juego y en el prólogo.</span>",

"Aún no hay eventos que revisar.",

"EMPEZAR UN NUEVO JUEGO",

"<span class='h9'>La historia de Jimmy Hall</span><br><br><span class='h2'>Descubre los secretos de Jimmy preguntando a los espíritus sobre las cosas que encuentres y haz conexiones entre ellas para que se manifiesten. Jimmy hará todo lo posible para evitar que descubras la verdad.</span>",

"<span class='h9'>Final del último juego</span><br><br><span class='h2'>Juega el último juego completado desde que Jimmy te invitó a conocer a Hugo.</span>",

"<span class='h9'>El rescate final (juego nuevo)</span><br><br><span class='h2'>Rescata a todos tus amigos mientras evitas ser atacado por Jimmy. ¡Un golpe y estás muerto! Este juego no se guarda y puedes volver a tu juego actual cuando escapes o si te atacan.</span>",

"Ver tutorial completo",

"Ver desde 'La persecución'",

"Ver desde 'Estrategia'",

"Ver desde 'Los muertos'",

"Ver desde 'El Talento de Maya'",

"Ver Prólogo",

"Ver desde 'La Llegada de Maya'",

"Ver desde 'Hugo Toma el Control'",

"Ver desde '2:30am'",

"Ver desde 'El Receptor Espiritual'",

"Estadísticas del juego",

"Empieza un juego nuevo",

"Revisar avistamientos",

"Instrucciones del Receptor",

"Ver Tutorial e Introducción",

"Subtítulos y Descripciones",

"Créditos",

"Consejos para jugar",

"Jimmy y el TID",

"Salir del hotel<br><span class='h2'>Guardar y Salir</span>",

"¿Seguro que quieres<br>salir del hotel ahora?",

"¡SÍ, DÉJAME SALIR!",

"<br>NO TIENES<br>OBJETOS QUE<br>VER TODAVÍA",

"Jimmy te ha golpeado por última vez.<br><br>Tu huida termina aquí.<br><br>Pero siempre puedes volver a intentarlo ...",

"Entrar en el Hotel<br><span style='font-size:50%'>Regresa a tu última partida guardada</span>",

"Entrar en el Hotel<br><span style='font-size:70%'>Empieza un juego nuevo</span>",

"COMIENZA EL JUEGO ESTÁNDAR",

"COMIENZA EL JUEGO EXTREMO",

"Guardar juego actual",

],

achtex:[

  "Has completado",
  "de la historia",
  "Has evitado ser atacado",
  "Jimmy te ha atacado una vez",
  "Jimmy te ha atacado dos veces",
  "Jimmy te ha atacado",
  "veces",
  "Descubriste el secreto del hotel",
  "Historia",
  "Completado",
  "Tienes",
  "que rescatar",
  "Has rescatado",
  "Has rescatado a todas tus amigas",
  "Necesitas encontrar la salida del hotel.",
  "¡Completaste el juego!",
  "Aún no hay estadísticas que mostrar",
  "Estadísticas del juego",
  "Logros",
  "Completaste la historia de Amy",
  "Completaste la historia del Dr Bose",
  "Completaste la historia de Harvey",
  "Completaste la historia de Rose",
  "Completaste la historia principal",
  "Completaste la historia principal sin que te golpeen",
  "Completaste At Dead Of Night",
  "Rescataste a todo el mundo en un juego rápido.",
  "¡Completaste At Dead Of Night sin que te golpeen!",
  "Volver a Sea View",
  "No tienes logros en este momento",
  "El juego se guarda después de avistar fantasmas, después de provocar reacciones de fantasmas (tras apagar el receptor) y cuando Jimmy te deja inconsciente.",
  "Completaste la historia principal en MODO EXTREMO.",
  "Completaste la historia principal en MODO EXTREMO sin que te golpeen.",
  "Completaste At Dead Of Night en MODO EXTREMO",
  "¡Completaste At Dead Of Night en MODO EXTREMO sin que te golpeen!",
  "Todas tus amigas escaparon sin peligro.",

],

selx:[

  "No Tenía Respuesta",
  "Aún no has preguntado sobre esto",
  "Ponte en contacto con un espíritu para preguntarle sobre esto.",
  "Haz clic en el elemento para ver la respuesta de cada espíritu",
  "Mira de frente la puerta cerrada para probar la llave",
  "Selecciona para preguntar sobre esto",
  "no tenía respuesta",
  "Dijo:",
  "QUE TENGA UN BUEN VIAJE<br>vuelva pronto",
  "Juego Actual Guardado",
  "Empieza Un Juego Primero",

],

numwo:[

  "Solo te queda un amigo para rescatar",
  "Tienes dos amigas para rescatar",
  "Tienes tres amigas para rescatar",
  "Tienes cuatro amigas para rescatar",
  "Tienes cinco amigas para rescatar",

],

numwa:[

  "Has rescatado a cinco amigas",
  "Has rescatado a cuatro amigas",
  "Has rescatado a tres amigas",
  "Has rescatado a dos amigas",
  "Has rescatado a una amiga",

],

helx:"<span class='ht'>&#8679;S</span> Guardar Partida | <span class='ht'>Esc</span> Alternar menú | <span class='ht'>D</span> Atenuar banda sonora | <span class='ht'>Q/W</span> Volumen<br><span class='ht'>&#8679;X</span> Salida rápida | <span class='ht'>U/I</span> Ajustar brillo | <span class='ht'>O/P</span> Ajustar saturación | <span class='ht'>R</span> Restablecer niveles",

resk:[

  "Encontraste cinco<br><br>llaves de habitaciones<br><br><span style='font-size:50%'>Tienes cinco amigas que rescatar</span>",
  "Espera a<br><br>que escape<br><br>",
  "<span style='font-size:50%'>Has rescatado a todas tus amigas</span>",
  "<span style='font-size:50%'>Tienes una amiga más para rescatar</span>",
  "<span style='font-size:50%'>Tienes dos amigas más para rescatar</span>",
  "<span style='font-size:50%'>Tienes tres amigas más para rescatar</span>",
  "<span style='font-size:50%'>Tienes cuatro amigas más para rescatar</span>",

],

ityptex:[

  "Mostrando Todo",
  "Mostrando Objetos Encontrados",
  "Mostrando Avistamientos",
  "Mostrando Conexiones",
  "Mostrando llaves",

],

intros:[

  "Este es el dispositivo que encontraste. Selecciona esto para encenderlo.",
  "Puede detectar las voces de los espíritus si estás lo suficientemente cerca de ellos.",
  "Si no lo has visto ya, ¡entra en el MENÚ y mira el tutorial antes de continuar!",
  "El dispositivo que encontraste puede detectar las voces de los espíritus si estás lo suficientemente cerca de ellos.",

  "Si no lo has visto ya, ¡entra en el MENÚ y mira el tutorial antes de continuar!",
  "Esta es una lista de las cosas que has visto y las llaves que has cogido.",

  "Maya puede preguntarle a los espíritus sobre cosas de esta lista.",
  "Esta es una lista de las cosas que has visto y las llaves que has cogido.",

  "Maya puede preguntarle a los espíritus sobre cosas de esta lista.",
  "Solo puedes usar el espejo vidente cuando el icono está visible,",

  "ya sea en la puerta de las habitaciones o en la cocina de la planta baja.",
  "Usa el espejo para ver pistas sobre dónde ir o qué elementos usar a continuación,",
  "También te ayudará a localizar llaves perdidas, brújulas y el receptor fantasmal.",
  "Solo puedes usar el espejo vidente cuando el icono está visible,",

  "ya sea en la puerta de las habitaciones o en la cocina de la planta baja.",
  "Usa el espejo para ver pistas sobre dónde ir o qué elementos usar a continuación,",
  "También te ayudará a localizar llaves perdidas, brújulas y el receptor fantasmal.",
  "La brújula apuntará hacia los espíritus cercanos.",

  "Pregunta a los espíritus sobre las cosas que ha visto.",

  "Verás su respuesta al seleccionar el elemento.",
  "Empareja dos respuestas que creas que estén relacionadas para averiguar la historia del espíritu.",

  "Empareja los avistamientos con objetos para un progreso más rápido.",
  "Si el espíritu deja de responder, es posible que se haya alejado.",

  "Utiliza una brújula, busca luces parpadeantes y escucha los sonidos.",
  "Inicia conversaciones con los espíritus haciendo preguntas introductorias.",

  "Si no hay respuesta, no hay espíritus alrededor.",
  "Un ruido fuerte significa que hay un espíritu en estado de alta energía cerca.",
  "Inicia conversaciones con los espíritus haciendo preguntas introductorias.",

  "Si no hay respuesta, no hay espíritus alrededor.",
  "Un ruido fuerte significa que hay un espíritu en estado de alta energía cerca.",
  "Jimmy Hall está buscándote en este piso. ¡Mantente alejado de él!",

  "Para probar las llaves, abre el inventario, mira hacia la puerta y selecciona una llave.",

  "Las puertas se pueden bloquear o desbloquear con la llave correcta.",
  "Para probar las llaves, abre el inventario, mira hacia la puerta y selecciona una llave.",

  "Las puertas se pueden bloquear o desbloquear con la llave correcta.",
  "El juego se guardará aquí por última vez.",

  "Ahora tienes que rescatar a tus amigas<br>pero... ¡si Jimmy te atrapa, se acabó el juego!",
  "Esa era la última persona por rescatar. ¡Ahora encuentra la salida y vete!",

  "Avanza para enviarlas fuera de la habitación.",

],

substan:[

  "No lo sé.",
  "Tal vez.",
  "Cero",
  "SE ESCUCHA<br>DÉBILMENTE<br>UNA VOZ/",
  "RADIO<br>ESTÁTICA/"

],

subrepa:[
[
  "Hola",
  "Hola",
  "Hola.",
  "Hola",
  "Hola.",
  "Hola"
],[
  "Hola",
  "Hola",
  "Hola",
  "Hola"
],[
  "Hola",
  "Puedo oírte.",
  "Puedo oírte.",
  "Puedo oírte."
],[
  "Hola",
  "Puedo oírte.",
  "Hola",
  "Puedo oírte.",
  "Puedo oírte."
],
],

subrepb:[
[
  "Soy Amy Bell. Tengo diez años.",
  "Sí. Soy Amy.",
  "Sí. Soy Amy.",
  "Sí, soy yo.",
  "Sí. Soy Amy.",
  "Sí. Soy Amy.",
  "Sí. Soy Amy.",
  "Sí, soy yo."
],[
  "Doctor Bose. Soy psiquiatra clínico.",
  "Sí, soy el Doctor Bose.",
  "Soy el Doctor Bose.",
  "Sí, soy el Doctor Bose.",
  "Sí.",
  "Sí, soy yo.",
  "Soy el Doctor Bose, sí."
],[
  "Harvey. Dirijo el hotel.",
  "Sí.",
  "Sí, soy Harvey.",
  "Sí, soy Harvey.",
  "Sí, soy Harvey.",
  "Sí, soy Harvey."
],[
  "Rose, Rose Hall. Este es mi hotel.",
  "Sí.",
  "Sí. Soy Rose.",
  "Sí.",
  "Sí, soy Rose.",
  "Sí.",
  "Sí. Soy Rose."
],
],

subcall:[

  "¿JIMMY?",
  "¡HEY!",
  "¡ESTOY AQUÍ!",
  "¡AQUÍ!",
  "¡POR AQUÍ!",

],

subin:[

  "¿Hay alguien ahí?",
  "¿Hay alguien ahí?",
  "¿Hay alguien ahí?",
  "¿Hay alguien ahí?",
  "¿Hay alguien ahí?",
  "¿Hay alguien ahí?",
  "¿Quién está ahí?",
  "Hola",
  "Hola",
  "¿Hay alguien ahí?",
  "¿Hay alguien ahí?",

],

subnm:[

  "¿Eres Amy?",
  "¿Eres el Doctor Bose?",
  "¿Eres Harvey?",
  "¿Eres Rose?",
  "¿Cómo te llamas?",

],

subrepc:[

  ["H","Rose, pero nunca llegó a usarlos","R","Eran míos. Quería marcharme, pero nunca tuve la oportunidad."],
  ["R","Jimmy los compró, para que pareciera que había ganado premios."],
  ["A","Era mío. Era por mi cumpleaños, pero me lo robaron.","H","Era el bolso de esa niña, pobrecita.","R","Era de la niña pequeña."],
  ["A","No sabía lo que eran, hasta que Jimmy me lo mostró.","P","Será mejor que le preguntes a Jimmy.","H","Eran míos, pero no los guardaba juntos.","R","No lo sé. Eran de Harvey."],
  ["A","Jimmy lo tenía. No me gustaba.","P","Vi a Jimmy jugar con él. Pensé que era peligroso.","H","Teníamos una exhibición de armas medievales. Jimmy lo robó.","R","Era parte de una armadura que teníamos. Pero desapareció."],
  ["A","No lo sé, pero los niños no deberían beber alcohol.","P","Probablemente eran del bar.","H","No lo recuerdo, pero tiene nada de malo tomar una copa.","R","Harvey debió ponerlos allí."],
  ["A","El niño solía dibujarlos.","P","Jimmy. Solía ​​dibujarlos.","H","¿Quién crees? ¡Jimmy! Tenía una imaginación muy violenta, el pequeño Jimmy.","R","Jimmy solía hacer dibujos sobre la guerra. Era como la mayoría de los chicos."],
  ["P","Jimmy lo encontró y se lo puso.","H","¡El chef! ¿Quién más llevaría un gorro de cocina?","R","Nuestro chef solía llevarlo."],
  ["A","Podría haber sido mío.","P","Era mío. Lo guardé, por si lo necesitaba como prueba.","H","No lo sé, pero podría haber tenido algo que ver con el doctor. "],
  ["P","Puede ayudar a tratar conductas impulsivas, en algunas personas.","H","Probablemente se lo dejó el doctor.","R","Pertenecía al Doctor Bose."],
  ["P","No lo sé, pero Jimmy lo encontró.","H","Siempre estaba debajo del mostrador de recepción. No sé de dónde salió.","R","Era de mi marido."],
  ["A","Jimmy lo hizo. No sé por qué. Él era raro.","P","Jimmy lo hizo. Fue una advertencia. Debería haberlo visto venir.","H","Jimmy. Solía guardar recortes de noticias sobre médicos y maestros maltratadores. No era un niño normal.","R","Harvey decía que Jimmy lo hizo. No recuerdo."],
  ["P","Yo los uní. Era un experimento."],
  ["H","Daba descargas eléctricas. Lo guardé para que la policía pudiera comprobarlo.","R","Harvey lo guardó. Dijo que era peligroso."],
  ["A","No lo sé. El niño solía jugar con ellos.","P","Harvey los guardaba. No sé por qué.","H","Yo los guardaba, en caso de que los necesitara. ","R","Solían pertenecer a mi marido, de cuando era maestro."],
  ["A","Estaba en el armario, en el hotel. Lo vi.","P","El hotel solía tener una exhibición de armas antiguas.","H","Era de una exhibición de armas que solíamos tener. Jimmy le tenía aprecio.","R","Era de una exhibición que Harvey solía tener. Pero no me gustaba que estuviera en el hotel."],
  ["H","Eran de la puerta del antiguo cuarto de calderas.","R","Eran del cuarto de calderas. Pero tuvimos que cambiar la puerta."],
  ["P","Nunca escuché nada sobre eso.","H","Sí. Lograron contenerlo, pero perdí muchas cosas.","R","Sí. Pero lo contuvimos a tiempo, antes de que se propagara."],
  ["P","Harvey era el dueño. No me gustaba que estuviera en el hotel.","H","Era mío. Pertenecía a mi padre. Todavía tenía algunas balas.","R","Harvey. Pero lo guardábamos en mi habitación."],
  ["A","Jimmy me lo enseñó. Pero no era suyo.","H","No es una daga. Es un abrecartas. No debería estar afilado.","R","Era un abrecartas. Fue un regalo de alguien."],
  ["R","Era la pieza cómica de Jimmy."],
  ["P","No los vi.","H","No recuerdo eso.","R","Jimmy los rompió."],
  ["A","Jimmy solía llevarlo consigo.","P","Era de Jimmy. Siempre lo guardaba en su bolsillo. No me dijo para qué lo usaba.","H ","Jimmy solía llevarlo consigo. No tengo idea de por qué.","R","Jimmy solía llevar cables encima. Le gustaba jugar con la electrónica."],
  ["R","Jimmy lo escribió."],
  ["H","Probablemente pertenezca a Rose.","R","Era mío. Alguien me hizo una oferta que no pude rechazar."],
  ["A","No lo sé. No vi a ningún bebé.","R","Era para el bebé. Lo guardé en el cajón de mi mesita de noche."],
  ["R","Jimmy es hijo de Hugo. En todos los sentidos."],
  ["A","Era yo - un chico llamado Jimmy me encerró en el sótano. Luego empezó a robarme cosas.","P","Era la hija de un huésped del hotel. Jimmy no se portaba bien con ella.","H","Se hospedaba en el hotel con su familia.","R","Ella era una huésped del hotel."],
  ["A","Porque pensó que era gracioso. Lo devolvió, pero luego lo destrozó igualmente.","P","No tengo ni idea. Es el tipo de cosas que hacía.","H","Quién sabe. Probablemente pensó que era gracioso.","R","No lo hizo. La chica estaba mintiendo. Jimmy no robó nada."],
  ["A","Me quemé la mano. Me dolía mucho, pero no podía decírselo a nadie.","P","Su mano sufrió quemaduras graves, pero Jimmy pensó que todo era una broma.","H","Sufrió graves quemaduras.","R","Se quemó, pero siguió haciendo cosas peligrosas como esa. Era rara."],
  ["A","Quería encontrar un médico, pero Jimmy me amenazó e hizo que me quedara.","H","Probablemente ella tenía miedo de Jimmy.","R","No lo sé. Podría haber sido cualquier cosa. Era una chica rara."],
  ["A","El niño me dijo que era medicina. Tenía un sabor horrible.","P","Yo no estaba allí entonces, pero creo que bebió alcohol."],
  ["A","Me sentía muy ligera. Pensé realmente que sería capaz de tirarme sin peligro.","P","Jimmy forzó a la chica a beber demasiado.","H","Ella se había bebido una botella de whisky. No sabía lo que estaba haciendo.","R","No lo sé. No sabía mucho sobre ella."],
  ["A","Me tiré, pero luego todo se oscureció y no podía despertar. Nunca podré despertar. No sé dónde estoy.","P","Se tiró por escaleras desde el último piso. Estaba demasiado borracha para saber lo que hacía. Esa fue la razón por la que Rose se puso en contacto conmigo.","H","Se tiró desde el último piso por las escaleras. No me cabía duda de que Jimmy estaba detrás de ello.","R","Se tiró. Harvey culpó a Jimmy por ello. Pero fue culpa de la niña, no de Jimmy."],
  ["P","Fui yo. Recibí una llamada de Rose, la madre de Jimmy. Quería que hablara con Jimmy, que averiguara qué le pasaba. Pero Harvey estaba preocupado por la mente de Jimmy, por las cosas que estaba imaginando.","H","Era el Doctor Bose. Se suponía que él ayudaría a Jimmy, pero ya era demasiado tarde.","R","Doctor Bose. Él vino a ayudar a Jimmy."],
  ["P","Jimmy estaba matando pequeños pájaros y animales. Me di cuenta de que necesitaba trabajar en su empatía. Así que le pedí que pensara en algo bueno que pudiera hacer por mí. Me sorprendió. Se le ocurrió algo en seguida.","H","Jimmy dijo que lo había encontrado en alguna parte. Lo que estaba haciendo con ello es otra historia.","R","Harvey dijo que el mismo Jimmy probablemente lo había matado, pero yo no le creí."],
  ["P","Jimmy me estaba preparando un sándwich. Lo trajo a mi habitación, tal y como le pedí. Al principio no sospeché que algo no estaba bien.","H","El doctor estaba intentando educar a Jimmy para que echara una mano. Gran error.","R","El Doctor Bose seguía intentando que Jimmy hiciera cosas que no quería hacer."],
  ["P","Jimmy había metido cristales en mi sándwich. Casi muero atragantado. Guardé la tela y los cristales para poder ir a la policía, pero me di cuenta de que había subestimado la enfermedad de Jimmy. Tenía que acelerar su tratamiento, urgentemente.","H","Descubrió de lo que Jimmy era capaz, de la peor manera. Las bromas de Jimmy siempre iban demasiado lejos.","R","Se cortó él solo. Pero trató de culpar a Jimmy. Se lo hizo él mismo. No fue Jimmy."],
  ["P","Jimmy se negó a dejarme administrarle la droga. Tuve que perseguirlo por el hotel. Luego le dijo a Rose que había tratado de obligarlo, que había usado la violencia. ¡Era ridículo!","H","No lo sé. Yo no estaba allí.","R","Estaba tratando de medicar a Jimmy, sin mi permiso."],
  ["P","Me preocupaba que Rose creyera a Jimmy. Era una mentira descarada. Pero logré convencer a Rose de que Jimmy mentía.","H","Estaba preocupado de lo qué Jimmy se inventaría sobre él. Y tenía motivos.","R","Porque estaba preocupado por su reputación. Yo no sabía a quién creer. Pero decidí darle otra oportunidad."],
  ["P","Pensé que cuando se diera cuenta de que lo habían pillado, empezaría a confraternizar conmigo y a hacer lo que le pedía. En cambio, se inventó otra mentira. Solo que esta fue mucho peor. La peor.","R","Él hablaba con Jimmy, tratando de controlarlo. Intentando que hiciera cosas malas, muy malas. Nunca debí fiarme de él."],
  ["P","Rose me denunció. Sabía que me depondrían. No tenía carrera ni futuro. Decidí tomar el control, de una vez por todas.","H","Lo iban a arrestar. Jimmy le había arruinado la vida. Pero yo no me creí nada.","R","Vinieron a arrestarlo. Se merecía todo lo que le pasó."],
  ["P","Ya había tenido suficiente. No había vuelta atrás. Mi vida ya había acabado de todas maneras.","H","Porque lo impulsaron a ello. Todos pensaban que había... abusado de Jimmy. Jimmy era listo, muy listo. El médico no tenía ninguna posibilidad. Pobrecillo.","R","Porque sabía que era culpable. Hizo lo correcto."],
  ["P","Era Harvey. Sabía que Jimmy estaba mintiendo sobre mí. Harvey lo entendía.","H","Fui yo. Jimmy había hecho acusaciones sobre el doctor. Rose le creyó, pero yo ya había oído antes esa historia, en algún lugar.","R","Fue Harvey. No se creía lo que Jimmy estaba diciendo. Pero yo sabía que no estaba mintiendo."],
  ["P","Jimmy nunca reconoció que había mentido.","H","¡Por supuesto que no! Él solo se rió. Luego empezó a tenderme pequeñas trampas. Algunas de ellas no tan pequeñas.","R","No, ¿cómo podía Jimmy reconocer algo que no era cierto? Harvey se equivocó al increpar a Jimmy de esa manera."],
  ["H","Sabía que ese era mi calentador. Había conectado la carcasa directamente a la red eléctrica. Casi me mata. Lo hizo a propósito, pero Rose no quería ni hablar de ello. Sabía que necesitaba que le dieran una lección. Él había dañado mi propiedad, así que decidí dañar la suya.","R","Harvey culpó a Jimmy, pero ese calentador era defectuoso. Harvey debió haberse deshecho de él."],
  ["P","No lo sé, pero la violencia solo empeora las cosas.","H","Hice pedazos su televisión, sus consolas y más cosas. Estaba enfadado, pero no funcionó. Solo lo empeoró todo. Pronto tomó represalias.","R","Destrozó las cosas de Jimmy. No pudo controlar su ira."],
  ["H","Jimmy la había preparado para que se disparara al abrir la puerta. Tuve que ir a urgencias, donde me pusieron puntos y la vacuna del tétano. Cuando regresé, no lo encontré. Rose dijo que estaba escondido en el sótano. Eso me dio una idea.","R","Harvey dijo que Jimmy le había disparado con la ballesta, pero yo sabía que Jimmy no usaría un arma así."],
  ["H","Quería pagar a Jimmy con la misma moneda. Pensé que él no sería capaz de hacer ningún daño allí abajo. Pero me equivocaba.","R","No sé lo que estaba haciendo."],
  ["P","No me acuerdo.","H","Logramos contenerlo antes de que se descontrolara. Pero todas nuestras fotos y cartas y pertenencias antiguas estaban allí. Todo consumido por las llamas. Jimmy estaba fuera de control. Yo ya estaba harto. Quería que se fuera.","R","Harvey culpó a Jimmy, pero fue un cable suelto lo que inició el incendio. Fue un accidente."],
  ["P","No lo sé. Pero Harvey no pudo controlar su ira.","H","No sé qué iba a hacer. Amenazarlo, tirarlo del hotel. El problema era que no me di cuenta de que él también iba armado.","R","No lo sé. Harvey no debería haber tenido un arma en el hotel."],
  ["H","Estaba buscando a Jimmy."],
  ["H","Jimmy apareció detrás de mí. No lo vi venir. Jimmy siempre ganaba al final.","R","Harvey estaba fuera de sí. Jimmy solo se estaba defendiendo."],
  ["H","Rose. Rose solo creía a Jimmy. Ella lo defendió, hasta el final.","R","Fui yo. Tuve que explicarle a la policía que la daga era solo un abrecartas y que Harvey tenía un pistola cargada. Jimmy actuó en defensa propia. Lo entendieron."],
  ["H","Jimmy. Dejaron marchar a Jimmy. Dijeron que era en defensa propia, que yo había intentado dispararle a Jimmy. Pero todo eran mentiras.","R","A Jimmy. Él volvía a casa. La policía lo entendió. Le creyeron, pero algo cambió. Comenzó a ayudarme, a ayudar a llevar el hotel. Y encontró la manera de atraer más huéspedes."],
  ["H","No sé quién era.","R","Lo estaba disfrutando, estábamos ganando dinero de nuevo. Todo parecía estar mejorando hasta que ... Jimmy comenzó a comportarse de manera rara. Lo escuchaba gritar, clavándose los ojos. Parecía enfadado."],
  ["R","Jimmy. No entendí al principio. Estaba confundida. Pero luego me di cuenta. Jimmy no era el que estaba haciendo esto. Igual que los espejos, se estaba fracturando. Jimmy ya no estaba al mando."],
  ["H","No lo sé, pero sé que Jimmy siempre lo destrozaba todo al final.","R","Ya no era Jimmy en el escenario. Era Hugo Punch, el personaje de su comedia. Hugo empezó a insultar al público todas las noches. Parecía disfrutarlo. Entonces, una noche después del espectáculo, una invitada le dijo a Jimmy lo que pensaba de él. Jimmy perdió los estribos. Hizo algo muy estúpido."],
  ["R","Los periodistas. Querían a Jimmy. Pero Jimmy ya no estaba al mando. Era Hugo Punch quien ató a la mujer. Jimmy ya no podía controlarlo. Estaba deprimido. Solo quería dejarlo todo atrás e irse."],
  ["R","Fue Jimmy. Trató de suicidarse. Por eso tuve que decirle la verdad."],
  ["H","No lo sé. Hubo cosas que Rose nunca me contó.","R","Hugo - Lo enterré allí, en hormigón, en una habitación secreta. Debería haberlo hecho antes. Dejé que maltratara a Jimmy durante demasiado tiempo. Fue mi culpa que Jimmy saliera así. Pensé que la culpa se iría si se lo contaba a Jimmy. Estaba equivocada. Lo empeoró. No podía aceptar lo que había hecho. No podía vivir conmigo misma."],
  ["R","Si no lo hubiera hecho yo misma, Jimmy lo habría hecho. O mejor dicho, Hugo. Hugo aún está al mando, incluso ahora. Él está controlando a Jimmy. Pídele a Jimmy que te muestre dónde vive Hugo."],
  ["H","Nunca lo conocí.","R","Era un mago y artista. Compró el hotel para promocionar su espectáculo. Se hizo famoso y salía en la tele. Trabajé como su asistente. Después, las cosas... se aceleraron."],
  ["R","Nunca sabía lo que él quería. Solo había una cosa que yo podía darle."],
  ["R","Hugo era un hombre violento, malvado y enfermo."],
  ["A","Sí. Lo cogió cuando yo no miraba y me robó el dinero. Le regañé pero no quiso escuchar."],
  ["A","Empapó mi juguete con el contenido de la botella. ¡Lo odiaba!"],
  ["A","Sí. Lo descolgó de la pared. Parecía muy afilado. Me hizo prometer que no se lo diría a nadie y dijo que podía hacer que mi mano dejara de doler."],
  ["A","Quizás... Me dijo que siguiera bebiendo. Fue horrible. Entonces comencé a sentirme rara..."],
  ["P","Sí. Sugerían una personalidad turbia, pero no me preocupé en particular hasta que... comencé a darme cuenta de lo lejos que llegaba su imaginación."],
  ["P","Sí. Jimmy dijo que haría algo por mí, así que lo seguí para ver qué iba a hacer."],
  ["P","Fue mi primer encuentro con el sentido del humor de Jimmy."],
  ["P","No era el medicamento ideal, pero era todo lo que tenía. Jimmy necesitaba tratamiento de inmediato; era un peligro."],
  ["P","Jimmy dijo que había usado el remo para pegarle. Nunca usaría la violencia contra un paciente. ¡Era ridículo! Pero Rose le creyó."],
  ["P","Jimmy me acusó del peor crimen posible. Lo había sacado de un artículo de un periódico que había leído. Se lo estaba inventando todo."],
  ["P","Experimenté con la cuerda de tender, pero era demasiado fina. En su lugar encontré una cuerda. Todavía tenía la llave del hotel, así que entré una noche mientras estaba en libertad bajo fianza."],
  ["H","¡Lo había sacado de allí! En cuanto encontré los recortes, supe de dónde lo había sacado Jimmy. Era igual, hasta el último detalle."],
  ["H","Jimmy siempre estaba jugando con la electricidad. Es curioso cómo nunca era él el que se electrocutaba."],
  ["H","Guardaba esos bates para mi propia defensa, pero estaba enfadado. Agarré uno y fui directo a la habitación de Jimmy."],
  ["H","A Jimmy le gustaban las armas así. Tras hacer pedazos sus cosas, no lo vi en toda la noche. Debí haberme imaginado que estaba trabajando en su siguiente truquillo."],
  ["H","Bueno, si Jimmy eligió esconderse allí, pensé que debía gustarle."],
  ["H","Nadie se dio cuenta de hasta dónde podía llegar Jimmy para llamar la atención."],
  ["H","Se me fue de las manos. Estaba rabioso. Lo odiaba. Había perdido el control."],
  ["H","¡Ni siquiera era una daga! Pero nunca aprendí la lección. Jimmy siempre iba un paso por delante de mí."],
  ["R","Sí. Era el acto escénico de Jimmy. Él era cómico. Era bueno, muy bueno. La gente comenzó a venir solo para verlo."],
  ["R","Los espejos rotos fueron solo el comienzo. Le pregunté al respecto, pero no recordaba haberlo hecho. Luego otras cosas extrañas empezaron a ocurrir."],
  ["R","Jimmy la encerró en una habitación y la ató. No sabía qué iba a hacer. La encontré y la liberé. ¡Jimmy dijo que era una broma! Ella no presentó cargos, pero se lo contó a los periódicos."],
  ["R","Jimmy odiaba lo que había hecho. Había estado luchando contra Hugo Punch toda su vida. Estaba dentro de él, haciéndolo hacer todas esas cosas malas. Jimmy ya no quería vivir más."],
  ["R","Sí. Estábamos casados. Al principio éramos felices, antes de que las cosas empezaran a cambiar."],
  ["R","Pensé que tener un hijo lo arreglaría todo. Estaba equivocada."],
  ["R","Se lo conté todo a Jimmy. Jimmy no recordaba a Hugo. Había bloqueado el recuerdo. Hugo pegaba a Jimmy desde que nació, durante 2 años. Debí haberlo detenido antes."],
  ["R","No tenía otra opción. Jimmy había ido a buscar la tumba de Hugo. Estaba sola. Sabía lo que debía hacer."],

],

subob:[

  ["Vi unas maletas en un cofre. ¿De quién eran?",
  "¿está relacionado con lo que dijiste sobre las maletas?"],

  ["Encontré unos trofeos. ¿Quién los ganó?",
  "¿tiene algo que ver con lo que dijiste sobre los trofeos?"],

  ["¿De quién era el bolso de juguete?",
  "¿está relacionado con lo que dijiste sobre el bolso?"],

  ["Vi una botella de aguarrás y un mechero. ¿Para qué eran?",
  "¿tiene algo que ver con lo que dijiste sobre el aguarrás y el mechero?"],

  ["¿A quién pertenece la espada?",
  "¿tiene algo que ver con lo que dijiste sobre la espada?"],

  ["¿Por qué había una colección de botellas de whisky en una de las habitaciones?",
  "¿tiene algo que ver con lo que dijiste sobre las botellas de whisky?"],

  ["¿Quién hizo esos dibujos violentos?",
  "¿tiene algo que ver con lo que dijiste sobre los dibujos violentos?"],

  ["¿A quién pertenecía el gorro de cocina?",
  "¿está relacionado con lo que dijiste sobre el gorro de cocina?"],

  ["¿Por qué hay un paño manchado de sangre en uno de los cajones?",
  "¿tiene algo que ver con el paño manchado de sangre?"],

  ["¿De dónde salió el frasco de Diazepam?",
  "¿tiene algo que ver con lo que dijiste sobre el Diazepam?"],

  ["¿De dónde salió el remo de madera?",
  "¿está relacionado con lo que dijiste sobre el remo de madera?"],

  ["Vi un álbum de recortes con artículos de periódicos. ¿Quién lo hizo?",
  "¿tiene algo que ver con lo que dijiste sobre el álbum de recortes?"],

  ["¿Por qué había una cuerda de tender unida a un rodillo?",
  "¿tiene algo que ver con lo que dijiste sobre la cuerda de tender y el rodillo?"],

  ["¿Por qué hay un calentador antiguo marcado como 'peligroso'?",
  "¿tiene algo que ver con lo que dijiste sobre el calentador peligroso?"],

  ["¿Para qué eran todos los bates de cricket y béisbol?",
  "¿tiene algo que ver con lo que dijiste sobre los bates de cricket y béisbol?"],

  ["¿De salió la ballesta?",
  "¿tiene algo que ver con lo que dijiste sobre la ballesta?"],

  ["¿Para qué son esas viejas llaves oxidadas?",
  "¿tiene algo que ver con las llaves oxidadas?"],

  ["¿Hubo un incendio en el hotel?",
  "¿está relacionado con lo que dijiste sobre el incendio en el hotel?"],

  ["¿A quién pertenece la pistola?",
  "¿tiene algo que ver con lo que dijiste sobre la pistola?"],

  ["¿A quién pertenece la daga?",
  "¿tiene algo que ver con lo que dijiste sobre la daga?"],

  ["¿Quién es Hugo Punch?",
  "¿está relacionado con lo que dijiste sobre el cartel de Hugo Punch?"],

  ["¿Cómo se rompieron esos espejos?",
  "¿está relacionado con lo que dijiste sobre los espejos rotos?"],

  ["¿Para qué se utilizó la bobina de alambre?",
  "¿está relacionado con lo que dijiste sobre la bobina de alambre?"],

  ["¿Quién escribió la nota de despedida?",
  "¿está relacionado con la nota de despedida?"],

  ["¿A quién pertenecía el anillo de bodas?",
  "¿está relacionado con el anillo de bodas?"],

  ["¿De quién era el sonajero para bebés?",
  "¿tiene algo que ver con el sonajero?"],

  ["Encontré el certificado de nacimiento de Jimmy. Dice que Hugo Hall es el verdadero padre de Jimmy.",
  "¿tiene algo que ver con lo que dijiste sobre el certificado de nacimiento de Jimmy?"],

  ["Vi a una niña en el sótano, llorando. ¿Quién era ella?",
  "",
  "Cuando dijiste que Jimmy te había robado cosas,",
  "Cuando dijiste que Jimmy no se portaba bien con la niña,",
  "Lo que me dijiste sobre una niña que se alojaba en el hotel,",
  "Lo que dijiste sobre la niña que era huésped en el hotel,"],

  ["Vi a la niña gritándole a Jimmy que le devolviera su juguete. ¿Por qué se lo quitó?",
  "Te vi gritándole a Jimmy que te devolviera tu juguete. ¿Por qué te lo quitó?",
  "Lo que dijiste sobre Jimmy robando tu juguete,",
  "Cuando dijiste que robar era el tipo de cosas que Jimmy hacía,",
  "",
  "Cuando dijiste que Jimmy no robaba cosas,"],

  ["Vi a la niña pequeña, Amy, sosteniendo un juguete en llamas. ¿Qué pasó?",
  "Te vi sosteniendo un juguete en llamas. ¿Qué pasó?",
  "Dijiste que no podías decirle a nadie que te habías quemado la mano.",
  "Lo que dijiste sobre que Jimmy pensaba que quemar el juguete de Amy era una broma,",
  "Dijiste que la niña sufrió graves quemaduras.",
  "Cuando dijiste que la niña seguía haciendo cosas peligrosas y culpando a Jimmy de ellas,"],

  ["Vi a Amy en el pasillo. Algo la asustó. ¿Qué fue?",
  "Te vi en el pasillo. Algo te asustó. ¿Qué fue?",
  "Cuando dijiste que necesitabas un médico pero que Jimmy te amenazó para que no te fueras,",
  "",
  "Cuando dijiste que la niña probablemente le tenía miedo a Jimmy,",
  "Cuando dijiste que había algo extraño en la niña,"],

  ["Vi a Amy bebiendo algo. No parecía gustarle. ¿Qué era?",
  "Te vi bebiendo algo. No parecía gustarte. ¿Qué era?",
  "Cuando dijiste que la medicina sabía fatal,",
  "Lo que dijiste sobre la niña pequeña, Amy, bebiendo alcohol,",
  "",
  ""],

  ["Vi a la niña en lo alto de las escaleras, en la barandilla. ¿Qué estaba haciendo?",
  "Te vi en lo alto de las escaleras, en la barandilla. ¿Qué estabas haciendo?",
  "Cuando dijiste que pensabas que podías tirarte por las escaleras,",
  "Cuando dijiste que Jimmy hizo que la chica bebiera demasiado,",
  "Dijiste que Amy se había bebido una botella de whisky.",
  ""],

  ["Vi a Amy tirada al pie de las escaleras. ¿Qué le pasó?",
  "Te vi tirada al pie de las escaleras. ¿Qué te pasó?",
  "Dijiste que ya no podías despertar.",
  "Dijiste que la muerte de Amy fue la razón por la que Rose te llamó,",
  "Lo que dijiste acerca de que Jimmy estuvo detrás de la muerte de Amy,",
  "Lo que dijiste acerca de que Amy murió por su propia culpa,"],

  ["Vi a un hombre llamando a la puerta y diciéndole a Jimmy que estaba allí para ayudar. ¿Quién era?",
  "",
  "",
  "Cuando dijiste que Harvey estaba preocupado por la mente de Jimmy,",
  "Lo que dijiste acerca de que ya no había remedio para Jimmy,",
  "Dijiste que el Dr Bose vino para ayudar a Jimmy."],

  ["Vi al Dr Bose sosteniendo un animal muerto en un alambre. ¿Qué había pasado?",
  "Te vi sosteniendo un animal muerto en un alambre. ¿Qué había pasado?",
  "",
  "Cuando dijiste que a Jimmy se le ocurrió una idea para hacer algo bueno por ti,",
  "Lo que dijiste sobre Jimmy diciendo que encontró el animal muerto en alguna parte,",
  "Cuando dijiste que no creías que Jimmy hubiera matado a ese animal,"],

  ["Vi al Dr Bose fuera de la cocina, hablando con Jimmy. ¿Qué estaba haciendo?",
  "Te vi fuera de la cocina hablando con Jimmy. ¿Qué estabas haciendo?",
  "",
  "Cuando dijiste que no sospechabas de que algo andara mal,",
  "Cuando dijiste que fue un error que el Dr Bose intentara ayudar a Jimmy,",
  "Cuando dijiste que el Dr Bose estaba intentando que Jimmy hiciera cosas que no quería hacer,"],

  ["Vi al Dr Bose escupiendo sangre. ¿Qué pasó?",
  "Te vi escupiendo sangre. ¿Qué pasó?",
  "",
  "Cuando dijiste que tenías que acelerar el tratamiento de Jimmy urgentemente,",
  "Cuando dijiste que las bromas de Jimmy siempre llegaban demasiado lejos,",
  "Cuando dijiste que el Dr Bose se lastimó a sí mismo pero culpó a Jimmy,"],

  ["Vi al Dr Bose con una aguja hablando con Jimmy. ¿Qué estaba haciendo?",
  "Te vi con una aguja hablando con Jimmy. ¿Qué estabas haciendo?",
  "",
  "Cuando dijiste que Jimmy se negó a dejar que le administraras la medicina,",
  "",
  "Dijiste que el Dr Bose estaba tratando de medicar a Jimmy sin tu permiso."],

  ["Vi al Dr Bose tratando de explicar lo que había pasado con Jimmy. Parecía desesperado.",
  "Te vi tratando de explicar lo que había pasdo con Jimmy. Parecías desesperado.",
  "",
  "Cuando dijiste que lograste convencer a Rose de que Jimmy estaba mintiendo,",
  "Cuando dijiste que el Dr Bose tenía motivos para estar preocupado sobre lo qué Jimmy se inventaría sobre él,",
  "Cuando dijiste que decidiste darle al Dr Bose otra oportunidad,"],

  ["Vi al Dr Bose sentado en una cama hablando con Jimmy. ¿Qué estaba haciendo?",
  "Te vi sentado en una cama hablando con Jimmy. ¿Qué estabas haciendo?",
  "",
  "Dijiste que Jimmy se inventó otra mentira sobre ti, una mentira mucho peor.",
  "",
  "Cuando dijiste que nunca deberías haberte fiado del Dr Bose,"],

  ["Vi al Dr Bose perturbado. La policía estaba golpeando la puerta. ¿Qué estaba pasando?",
  "Te vi perturbado y escuché a la policía golpeando la puerta. ¿Qué estaba pasando?",
  "",
  "Cuando dijiste que decidiste tomar el control de una vez por todas,",
  "Dijiste que no creías la historia de Jimmy sobre el Dr Bose,",
  "Cuando dijiste que el Dr Bose merecía ser arrestado,"],

  ["Vi al Dr Bose atarse una cuerda alrededor de su cuello. Se suicidó. ¿Por qué?",
  "Te vi atando una cuerda alrededor de tu cuello. Te suicidaste. ¿Por qué?",
  "",
  "Dijiste que querías que todo parara,",
  "Cuando dijiste que el Dr Bose había sido impulsado a suicidarse,",
  "Cuando dijiste que el Dr Bose hizo lo correcto,"],

  ["Vi a un hombre que decía que Jimmy había mentido sobre el asalto. ¿Quién era?",
  "",
  "",
  "Cuando dijiste que Harvey sabía que Jimmy estaba mintiendo,",
  "Cuando dijiste que habías oído la historia en algún lugar antes,",
  "Cuando dijiste que Harvey estaba equivocado por no creer la historia de Jimmy,"],

  ["Vi a Harvey gritando, diciéndole a Jimmy que admitiera que mintió. ¿Lo hizo?",
  "Te vi gritar, diciéndole a Jimmy que admitiera que mintió. ¿Lo hizo?",
  "",
  "Lo que dijiste acerca de que Jimmy nunca reconoció sus mentiras,",
  "Cuando dijiste que Jimmy empezó a tenderte trampas,",
  "Dijiste que Harvey se estaba equivocando al increpar a Jimmy."],

  ["Vi a Harvey sufrir una descarga eléctrica. ¿Qué pasó?",
  "Te vi sufrir una descarga eléctrica. ¿Qué pasó?",
  "",
  "",
  "Cuando dijiste que decidiste dañar su propiedad,",
  "Dijiste que Harvey debería haberse deshecho de ese calentador defectuoso,"],

  ["Vi a Harvey con un bate, saliendo de una habitación. ¿Qué había hecho?",
  "Te vi con un bate, saliendo de una habitación. ¿Qué habías hecho?",
  "",
  "Cuando dijiste que la violencia solo empeora las cosas,",
  "Cuando dijiste que Jimmy pronto tomó represalias,",
  "Lo que dijiste acerca de que Harvey no pudo controlar su ira,"],

  ["Vi a Harvey recibir un disparo de ballesta en la pierna. ¿Qué pasó?",
  "Vi que te disparaban en la pierna con una ballesta. ¿Qué pasó?",
  "",
  "",
  "Cuando dijiste que pensabas que a Jimmy le gustaría esconderse en el sótano,",
  "Cuando dijiste que Jimmy no usaría un arma así,"],

  ["Vi a Harvey encerrar a Jimmy en el sótano. ¿Qué pasó?",
  "Te vi encerrando a Jimmy en el sótano. ¿Qué pasó?",
  "",
  "",
  "Dijiste que estabas equivocado al pensar que Jimmy no podría hacer ningún mal en el sótano,",
  ""],

  ["Vi un incendio en el sótano. ¿Qué le pasó al hotel?",
  "Vi un incendio en el sótano. ¿Qué le pasó al hotel?",
  "",
  "",
  "Cuando dijiste que querías que Jimmy se marchara,",
  "Dijiste que el incendio en el hotel fue un accidente,"],

  ["Vi a Harvey con una pistola, practicando con ella. ¿Qué iba a hacer?",
  "Te vi con una pistola, practicando con ella. ¿Qué ibas a hacer?",
  "",
  "Dijiste que Harvey no podía controlar su ira.",
  "Cuando dijiste que no te imaginabas que Jimmy también iría armado,",
  "Cuando dijiste que Harvey no debería haber tenido una pistola en el hotel,"],

  ["Vi a Harvey dirigiéndose hacia el salón de baile con una pistola. ¿Qué estaba haciendo?",
  "Te vi dirigiéndote hacia el salón de baile con una pistola. ¿Qué estabas haciendo?",
  "",
  "",
  "Cuando dijiste que buscabas a Jimmmy,",
  ""],

  ["Vi cómo apuñalaban a Harvey entre bastidores. ¿Qué pasó?",
  "Vi que te apuñalaban entre bastidores. ¿Qué pasó?",
  "",
  "",
  "Cuando dijiste que Jimmy siempre ganaba al final,",
  "Cuando dijiste que Jimmy se estaba defendiendo,"],

  ["Vi a una señora explicando que la daga era solo un abrecartas. ¿Quién era ella?",
  "",
  "",
  "",
  "Dijiste que Rose defendió a Jimmy hasta el final.",
  "Cuando dijiste que la policía entendió que Jimmy había actuado en defensa propia,"],

  ["¿A quién daba Rose la bienvenida en la entrada a la recepción?",
  "¿A quién dabas la bienvenida en la entrada a la recepción?",
  "",
  "",
  "Cuando dijiste que pensaban que habías intentado disparar a Jimmy,",
  "Cuando dijiste que Jimmy encontró una manera de atraer más huéspedes,"],

  ["Vi a Rose anunciando a Hugo Punch en el escenario.",
  "Te vi anunciando a Hugo Punch en el escenario.",
  "",
  "",
  "",
  "Lo que dijiste sobre Jimmy clavándose la mirada y enfadándose,"],

  ["Vi a Rose en un pasillo lleno de maniquíes. ¿Quién los puso allí?",
  "Te vi en un pasillo lleno de maniquíes. ¿Quién los puso ahí?",
  "",
  "",
  "",
  "Lo que dijiste acerca de que Jimmy ya no estaba al mando,"],

  ["Vi a Rose en el salón de baile. El público abucheaba y ella se disculpaba. ¿Qué estaba pasando?",
  "Te vi en el salón de baile. El público abucheaba y tú te disculpabas. ¿Qué estaba pasando?",
  "",
  "",
  "Dijiste que Jimmy lo destrozaba todo al final,",
  "Cuando dijiste que Jimmy perdió los estribos e hizo algo estúpido,"],

  ["Vi a Rose preocupada y gente llamando a la puerta haciendo preguntas. ¿Quiénes eran?",
  "Te vi preocupada. Había gente llamando a la puerta haciendo preguntas. ¿Quiénes eran?",
  "",
  "",
  "",
  "Cuando dijiste que Jimmy quería dejarlo todo e irse,"],

  ["Vi a Rose en una habitación. Parecía que había encontrado a alguien en el baño. ¿Qué pasó?",
  "Te vi en una habitación. Parecía que habías encontrado a alguien en el baño. ¿Qué pasó?",
  "",
  "",
  "",
  "Cuando dijiste que tenías que contarle a Jimmy la verdad,"],

  ["Vi a Rose con un bate de madera, atacando a alguien. ¿Quién era?",
  "Te vi con un bate de madera, atacando a alguien. ¿Quién era?",
  "",
  "Dijiste que Rose tenía una historia oscura.",
  "Dijiste que había cosas que Rose nunca te contó.",
  "Cuando dijiste que no podías vivir contigo misma,"],

  ["Vi a Rose. Estaba en llamas. ¿Qué pasó?",
  "Te vi. Estabas en llamas. ¿Qué pasó?",
  "",
  "",
  "",
  "Cuando dijiste que le pidiera a Jimmy que me enseñara dónde vive Hugo,"],

  ["Vi a alguien en el escenario. Un intérprete, anunciándose como El Gran Hugo.",
  "",
  "",
  "",
  "Cuando dijiste que Hugo era el primer marido de Rose,",
  "Cuando dijiste que las cosas se desarrollaron con Hugo,"],

  ["Escuché a un hombre gritarle a alguien, ordenándole que hiciera lo que él decía. ¿Quién era?",
  "",
  "",
  "",
  "",
  "Dijiste que solo había una cosa que podías darle a Hugo."],

  ["Escuché a un hombre gritar y a un niño llorar. ¿Qué pasó?",
  "",
  "",
  "",
  "",
  "Dijiste que Jimmy es hijo de Hugo."],

],

subs:[

  "INTRO",[
   13.6,5,"¡Jimmy!",14.6,4,"",
   16.2,4,"¡Jimmy!",17.4,4,"",
   18.8,2,"¡Jimmy!",20,4,"",
   20.1,6,"VOCES A TRAVÉS DEL ALTAVOZ",21.6,6,"",
   24.3,3,"Dejadme en paz ...",25.9,4,"",
   26.5,6,"SOLLOZOS",27.9,4,"",
   28.6,6,"LAS VOCES SE INTENSIFICAN",30.3,4,"",
   30.7,3,"¡Basta!",31.8,4,"",
   32.4,3,"¡Por favor, dejadme en paz!",34.8,4,"",
   35.8,6,"VOCES CON INTERFERENCIAS",37.3,4,"",
   44.5,6,"SUENA EL TELÉFONO",45.6,0,"",
   46.6,1,"Hola",47.6,0,"",
   47.7,3,"¿Maya? Soy Hannah.",48.8,0,"",
   49.4,1,"¿Hannah? ¿Dónde estáis?",51.2,0,"",
   51.3,1,"¡Os habéis marchado y me habéis dejado atrás!",53.6,0,"",
   53.7,1,"¿Dónde estás ahora? ¿Desde dónde llamas?",55.6,0,"",
   55.7,3,"Hemos reservado habitaciones en un hotel más adelante.",57.4,0,"",
   57.5,3,"¿Cómo de lejos estás?",58.8,0,"",
   58.9,1,"No lo sé. Tendré que llamar cuando llegue.",61.1,0,"",
   61.2,3,"No puedes. No hay cobertura.",62.9,0,"",
   63,1,"Bueno...",64.1,1,"",
   65,1,"Da igual. Vete a la cama, Hannah.",67,0,"",
   67.1,3,"Bueno, escucha. Asegúrate de estar...",68.3,0,"",
   68.6,6,"LA LLAMADA SE CORTA",70.1,0,"",
   71,6,"LLAMADA TERMINADA",72.5,0,"",
   84,6,"MÚSICA JAZZ DE LOS 50 EN LA RADIO",85.5,4,"",
   92.1,3,"Ah, Maya, ¿supongo?",94.1,0,"",
   94.5,3,"Oh, no te asustes.",96.4,0,"",
   96.6,3,"Tus amigos te han reservado una habitación...",99,0,"",
   99.1,3,"Déjame ver.",100.8,0,"",
   101.8,3,"Ah, sí.",102.8,0,"",
   102.9,3,"Habitación 101.",104,0,"",
   104.2,3,"Ya está pagado, así que no debes preocuparte por nada.",107.2,0,"",
   107.3,3,"Tienes muy buenos amigos.",109.1,0,"",
   109.9,3,"Muy buenos.",111.2,0,"",
   111.5,3,"Y sois un grupo grande.",115.6,0,"",
   116.2,3,"Es bueno ver tantas...",118.2,0,"",
   118.3,3,"caras frescas y jóvenes para variar.",122.7,0,"",
   123.5,3,"Estáis aquí por el festival de música de la ciudad, ¿supongo?",126.8,0,"",
   127.3,1,"Sí. Se suponía que íbamos a acampar allí esta noche, pero...",130.5,0,"",
   130.6,3,"No hace clima para ello, ¿verdad?",133.1,0,"",
   136,3,"¿Os quedaréis a desayunar?",137.5,0,"",
   137.6,1,"No creo. Probablemente saldremos pronto.",140.2,0,"",
   140.3,3,"Muy bien. Y si no te importa que te pregunte, Maya,",143.7,0,"",
   143.8,3,"¿estás interesada el espectáculo de esta noche?",147.5,0,"",
   147.9,1,"¿Esta noche?",148.9,0,"",
   149,3,"Comienza sobre medianoche, normalmente.",152.1,0,"",
   152.6,3,"Soy yo el que lo hace. Comedia.",155.8,0,"",
   155.9,3,"Interpreto un personaje de comedia llamado Hugo Punch.",161,0,"",
   161.1,3,"Es una especie de sociópata cómico.",164.8,0,"",
   164.9,3,"Dice cosas que se supone que no se deben decir, y eso.",169.6,0,"",
   169.7,3,"Es muy popular entre los estudiantes.",171.7,0,"",
   172.3,1,"No creo. Creo que todos nos vamos a ir a la cama ya.",175.7,0,"",
   175.8,3,"¿No hay ninguna forma de que pueda convencerte?",179.2,0,"",
   179.5,1,"No. Prefiero irme a la cama. Lo siento.",182.8,0,"",
   182.9,3,"De acuerdo, de acuerdo...",185.4,0,"",
   185.6,1,"¿Por dónde están las habitaciones?",186.7,0,"",
   187.2,3,"Toma el ascensor. Tu habitación está en el primer piso.",190.2,0,"",
   190.3,1,"Vale. Gracias.",191.6,0,"",
   193.1,3,"Ah, y mañana deja tu llave en la caja, por favor, Maya.",198.1,0,"",
   198.2,1,"¡Vale!",199.2,0,"",
   199.3,6,"SE CIERRA LA PUERTA",200.8,0,"",
   204.4,3,"El mejor espectáculo de la ciudad y sin público.",207.2,0,"",
   210.3,3,"¿Quién necesita entretenimiento del bueno cuando tienes 'YouTune' y 'My Face' o lo que sea?",216.6,0,"",
   216.7,3,"Estúpidos, incultos...",218.7,0,"",
   218.8,5,"A Hugo no le gustan los niños groseros. Son traviesos.",223,0,"",
   225.5,3,"No empieces de nuevo.",227.3,0,"",
   231.1,3,"No quiero oírte, ¿vale? Esta noche no.",234.2,0,"",
   237,5,"Los niños traviesos son como los huevos podridos. ¡Hay que darles una lección!",240.9,0,"",
   254.2,3,"¡Cállate! ¡Cállate ya!",256.5,0,"",
   257.3,3,"Siempre haces lo mismo. Son clientes que han pagado.",260.2,0,"",
   260.5,3,"No te han hecho nada.",262.4,0,"",
   263.3,3,"Déjalos en paz.",265.4,0,"",
   266.2,5,"¡Los huevos podridos hay que romperlos! Golpéalos con fuerza y ​​rómpeles la cáscara.",269.3,0,"",
   269.5,5,"¡Tíralos por las escaleras directos al infierno!",272.3,0,"",
   272.8,5,"Ya sabes lo que tienes que hacer, Jimmy.",275,0,"",
   275.6,5,"Muéstrales quién manda.",277.7,0,"",
   278.9,5,"¡Esa es la forma de hacerlo!",281.1,0,"",
   293.3,6,"GRITO DISTANTE",294.9,0,"",
   308,6,"RISA DE HOMBRE",309.6,0,"",
   310,3,"Eso es. Duérmete...",313,0,"",
   345.2,6,"RUDIO BLANCO",346.9,0,"",
   358.5,6,"VOCES A TRAVÉS DEL ALTAVOZ",361.9,0,"",
   362,1,"¡Sal del hotel!",363.6,0,"",
   363.7,1,"¡Sal mientras puedas!",365.7,0,"",
   367.6,1,"Tienes que averiguar lo que hizo...",369.3,0,"",
   369.4,1,"... y contárselo a todos.",371.3,0,"",
   371.4,1,"¡Haz que se dé cuenta de lo que hizo!",373.3,0,"",
   373.5,6,"LAS VOCES SE PIERDEN EN INTERFERENCIAS",376,0,"",
   382.1,1,"Sea View Hotel tiene un pasado oscuro.",386.1,0,"",
   389,1,"Sus fantasmas tienen una historia que contar.",393,0,"",
   395.7,1,"Usa el Detector de fantasmas y espíritus para hablar con ellos.",400.7,0,"",
   402.8,1,"Ellos te contarán los secretos de Jimmy.",406.8,0,"",
   409.5,1,"Pero Jimmy debe ocultar la verdad ...",413.5,0,"",
   416.9,1,"...cueste lo que cueste.",420.9,0,"X",
],
  "A2",[
   0.8,1,"¡Jimmy, devuélvemelo! ¡Es mío!",2.9,0,"",
   3,1,"¡Deja de robarme cosas!",4.3,0,"X",
],
  "A3",[
   0.7,6,"GRITOS",2,0,"X",
],
  "A4",[
   1.1,1,"Ya te lo he dicho, Jimmy, ¡no puedes hacer eso!",3.1,0,"",
   3.2,1,"Eres horrible...",4.7,0,"X",
   3.8,6,"LA VOZ SE DESVANECE",4.4,0,"X",
],
  "A5",[
   3.8,6,"TOS",4.8,0,"X",
],
  "A6",[
   4.2,6,"RISITAS",5.2,0,"X",
],
  "P1",[
   3.8,6,"GOLPES",4.8,0,"",
   5.8,2,"¿Jimmy?",6.8,0,"",
   7.2,2,"Soy el Doctor Bose.",8.9,0,"",
   9,2,"Solo he venido a charlar un poco, ¿de acuerdo?",11.5,0,"",
   14.5,2,"Gracias Jimmy. Seré breve.",16.6,2,"X",
],
  "P3",[
   1,2,"¡Es una gran idea, Jimmy!",3.4,0,"",
   3.5,2,"Creo que algún día serás un gran cocinero.",5.7,0,"",
   5.8,2,"¿Por qué no me lo traes cuando hayas terminado?",8,0,"",
   8.1,2,"Mientras te espero, ¿de acuerdo?",9.8,0,"X",
],
  "P4",[
   3,6,"BALBUCEOS",4,0,"",
   7.6,2,"¡Jimmy!",8.6,0,"X",
],
  "P5",[
   1.2,2,"No te dolerá, Jimmy.",2.9,0,"",
   3,2,"¡Lo único que tienes que hacer es estarte quieto y dejar de moverte!",6.6,0,"X",
],
  "P6",[
   0.6,2,"Yo nunca usaría la fuerza de esa manera con un paciente, Sra. Hall.",4.8,0,"",
   4.8,2,"Va en contra de todo en lo que creo.",7.3,0,"",
   7.4,2,"Trate de entenderlo. ¡Se lo está inventando todo!",10,0,"X",
],
  "P7",[
   1.1,2,"No escaparás tan fácilmente de mí, Jimmy.",3.9,0,"",
   4,2,"Creo que deberíamos empezar de cero, ¿no crees?",6.5,0,"",
   6.6,2,"¿Por qué no haces lo que te pido esta vez?",8.7,0,"",
   8.8,2,"Sería un buen comienzo, ¿no?",11,0,"X",
],
  "P8",[
   0.6,2,"Somos la policía, Sr. Bose.",2.1,0,"",
   2.2,2,"Necesitamos que nos acompañe a la comisaría.",4.1,0,"",
   4.4,2,"¿Puede abrir la puerta, por favor?",5.8,0,"X",
],
  "P9",[
   14.1,6,"ESTRANGULAMIENTOS",15.5,0,"",
   15.9,6,"ALARMA DEL ASCENSOR",16.9,0,"X",
],
  "H1",[
   0.8,3,"Se lo inventó. Te digo que ha estado mintiendo sobre absolutamente todo.",3.4,0,"",
   3.5,3,"Probablemente también ha mentido sobre el resto de cosas.",5,0,"",
   5.1,4,"¡No seas ridículo! ¡Él no mentiría sobre algo así!",7.3,0,"",
   7.4,3,"¿Estás segura de eso?",8.3,0,"",
   8.4,3,"¡Miente constantemente! ¡Abre los malditos ojos, Rose!",11.4,0,"",
   11.5,3,"¡Oh, de acuerdo! ¡Pasa de mí!",12.8,0,"",
   12.9,4,"No te estoy escuchando, Harvey. Simplemente le tienes manía.",14.7,0,"",
   14.9,3,"¡Es la verdad!",16.2,0,"X",
],
  "H2",[
   1.5,6,"GOLPES EN LA PUERTA",2.4,0,"",
   2.5,3,"¿Jimmy?",3.5,0,"",
   4.3,3,"¡Sé que puedes oírme!",5.8,0,"",
   6.2,3,"Sé que te inventaste tu historieta sobre ese psiquiatra.",10,0,"",
   10.1,3,"¡Sé de dónde lo sacaste!",11.6,0,"",
   12,3,"Sabía que lo había leído antes. ¡Está en tu maldito álbum de recortes!",15.3,0,"",
   16.1,3,"¡Sal afuera!",17.3,0,"",
   18.3,3,"¡Jimmy!",19.6,0,"X",
],
  "H3",[
   1.2,6,"CHISPAS ELÉCTRICAS",2.2,0,"",
   2.3,6,"GRITOS DE DOLOR",3.3,0,"",
   7.2,3,"¡Jimmy!",8.2,0,"X",
],
  "H4",[
   1,6,"COSAS SIENDO DESTROZADAS",2,0,"X",
],
  "H5",[
   0.8,6,"GRITOS DE DOLOR",1.9,0,"",
   4.1,3,"¡Jimmy!",5.1,0,"X",
],
  "H6",[
   1.3,3,"¡Quédate ahí toda la noche, Jimmy!",3.7,0,"",
   3.8,3,"Ya ha tenido bastante.",5,0,"",
   5.1,6,"GOLPEANDO LA PUERTA",6.6,0,"X",
],
  "H7",[
   0.3,6,"ALARMA DE INCENDIOS",1.8,0,"",
   2.7,3,"Jimmy, no seas tonto. ¡Abre la puerta!",4.9,0,"",
   5.2,3,"¡Vas a matarte, estúpido imbécil! ¡Abre la puerta!",8.4,0,"X",
],
  "H8",[
   2.7,3,"Vete del hotel, Jimmy.",4.6,0,"",
   6.6,3,"Sal de mi hotel...",8,0,"",
   8.6,3,"Este es mi hotel. Vete de mi hotel, Jimmy.",12,0,"X",
],
  "H9",[
   1.8,3,"Vete de mi hotel.",3.2,0,"",
   3.3,3,"Este es MI hotel.",5,0,"X",
],
  "R1",[
   0.8,8,"Harvey iba a disparar a Jimmy.",2.4,0,"",
   2.5,8,"Era solo un abrecartas. ¡Fue en defensa propia! ¡Mira!",5.9,0,"X",
],
  "R2",[
   3.5,4,"Jimmy",4.5,0,"X",
],
  "R3",[
   1.2,4,"Damas y caballeros.",2.4,0,"",
   2.5,4,"Demos la bienvenida al escenario,",3.9,0,"",
   4,4,"a su espectáculo de esta noche.",5.9,0,"",
   6,4,"¡El señor Hugo Punch!",8,0,"",
   8.1,6,"MÚSICA Y APLAUSOS",9.6,0,"X",
],
  "R4",[
   0,4,"",0,0,"",
],
  "R5",[
   0.7,4,"Es solo un acto cómico.",2.6,0,"",
   2.7,4,"¡Es su sentido del humor!",4.4,0,"",
   4.5,4,"Lo siento si le ha ofendido...",6.3,0,"",
   6.4,4,"Disculpe...",7.6,0,"X",
],
  "R6",[
   0.5,6,"GOLPES EN LA PUERTA PRINCIPAL",1.8,0,"",
   1.9,4,"¿Sra. Hall?",3.4,0,"",
   4.2,4,"Sra. Hall, ¿podemos hablar, por favor?",6.5,0,"X",
],
  "R7",[
   1.4,4,"¿Jimmy?",2.4,0,"",
   4.1,6,"GRITOS",5.1,0,"",
   5.2,4,"¡Jimmy! ¡Qué has hecho! ¡Jimmy!",8,0,"X",
],
  "R8",[
   0.5,6,"NIÑO LLORANDO",1.5,0,"",
   1.6,5,"¡Harás lo que yo te diga! ¿Lo entiendes?",4.2,0,"",
   4.3,5,"¡Estúpido desgraciado!",5.4,0,"",
   5.5,6,"NIÑO SIENDO ABOFETEADO",6.7,0,"",
   6.9,6,"BATE GOLPEANDO A ALGUIEN",8.3,0,"X",
],
  "R9",[
   1.4,6,"GRITOS",2.9,0,"X",
],
  "V1",[
   5.5,7,"¡Contemplad!",6.3,0,"",
   6.4,6,"GONG",7.4,0,"",
   7.5,7,"¡Soy el gran Hugo!",10.2,0,"",
   11.9,7,"Estoy por encima de todos los demás.",15.9,0,"",
   17.4,7,"Yo soy la luz que ilumina las tinieblas.",21.4,0,"",
   22.7,7,"Yo soy el único maestro.",26.5,0,"X",
],
  "V2",[
   5,6,"MUJER SOLLOZANDO",6.5,0,"",
   8,5,"¡No compres nada sin mi permiso!",10.5,0,"",
   10.6,6,"CRISTALES ROMPIÉNDOSE",11.5,0,"",
   11.6,5,"¡No permitiré que arruines mi vida!",14,0,"",
   14.1,6,"MÁS DESTROZOS",15.2,0,"",
   15.1,5,"¡Tu vida no vale nada!",16.8,0,"",
   16.9,5,"¿Entiendes lo que te estoy diciendo?",18.6,0,"",
   18.7,6,"DESTROZOS Y MUJER GRITANDO",20.9,0,"X",
],
  "V3",[
   3.1,6,"NIÑO LLORANDO",4.6,0,"",
   9,5,"¡Quédate quieto!",10,0,"",
   10.1,6,"SONIDO DE LATIGAZO",11.4,0,"",
   11.5,5,"¡Estúpido desgraciado!",12.8,0,"",
   12.9,5,"¡Haz lo que te digo!",14.9,0,"",
   15,6,"MUJER GRITA<br>¡No!",17,0,"X",
],
  "EPI",[
   17.9,3,"Damas y caballeros.",19,0,"",
   19.1,3,"Demos la bienvenida al escenario,",20.6,0,"",
   20.7,3,"a su espectáculo de esta noche.",22.5,0,"",
   22.6,3,"¡El señor Hugo Punch!",24.7,0,"",
   24.8,6,"APLAUSOS",26.4,0,"",
   33.5,5,"¡Maya!",34.5,0,"",
   36.1,5,"¡Maya!",37.1,0,"",
   40.5,5,"¿Maya?",41.5,0,"",
   42,5,"¡Maya!",43.5,0,"",
   44,6,"SOLLOZOS",46,0,"",
   47.5,3,"Para, para, para, para ...",49.9,0,"",
   50,3,"Basta.",51.5,0,"",
   52.6,3,"¿Por qué me obligas a hacer estas cosas?",55.3,0,"",
   56,3,"Por favor, para.",57.5,0,"",
   58.4,3,"Por favor, para, para...",60.4,0,"",
   63.2,5,"No puedes parar, Jimmy.",64.9,0,"",
   66.7,5,"Estoy al mando.",68.6,0,"",
   68.7,5,"No tú.",69.7,0,"",
   71,5,"Estoy al mando.",73.5,0,"",
],
  "BRO",[
   1.5,5,"¡Bienvenida a la tumba de Hugo!",5.5,5,"",
   5.6,5,"El pequeño secreto de mamá.",8.9,5,"",
   9,5,"Ella misma preparó el hormigón, ¿sabes?",11.8,5,"",
   11.9,5,"Luego lo derramó sobre su cadaver",15.1,5,"",
   15.2,5,"y lo vio secarse.",17.8,5,"",
   18.1,5,"Ella pensó que se había deshecho de él.",21,5,"",
   21.3,5,"Pero ella no lo entendía, Maya.",24.7,5,"",
   24.8,5,"Verás, Hugo no era más que uno de nosotros.",29.1,5,"",
   29.2,5,"Otro tronco en la hoguera.",33,5,"",
   33.2,5,"Pero se quemó.",35.8,5,"",
   36,5,"Pero el fuego ha estado vivo en la familia Hall durante siglos.",41.2,5,"",
   41.3,5,"Despejando el camino...",43.5,5,"",
   43.6,5,"Iluminando las tinieblas...",45.9,5,"",
   46,5,"Asolando lo viejo, lo pobre y lo débil.",52.3,5,"",
   52.4,5,"Y también está vivo en ti, Maya.",56.7,5,"",
   56.8,5,"¡Puedo notarlo!",58.8,5,"",
   59,5,"Estamos destinados a estar juntos, tú y yo.",62.9,5,"",
   63,5,"Te he estado esperando.",66.6,5,"",
   66.8,5,"Y por eso no puedo dejar que te vayas.",71,5,"",
   71.1,5,"Te vas a quedar aquí conmigo, Maya.",75.2,5,"",
   75.3,5,"Para siempre.",77.5,5,"X",
],
  "COR",[
   0.2,5,"¿Hablando con los muertos, Maya?",4.3,1,"",
   4.5,1,"Sé que Hugo es tu padre, Jimmy.",6.6,1,"",
   6.7,1,"Encontré tu certificado de nacimiento, y sé que Rose intentó matarlo.",10.5,1,"",
   10.6,5,"Pero no lo logró, ¿verdad?",13.6,1,"",
   13.7,1,"Dime, ¿dónde está él ahora?",15.5,1,"",
   15.8,6,"RISAS",17,1,"",
   20.3,5,"Bueno, ¿por qué no vienes a conocerlo?",22.8,1,"",
   22.9,5,"Es hora de que te presente a la familia, Maya.",27.8,1,"",
   27.9,6,"RISAS",29,1,"X",
],
  "AP",[
   2.6,5,"¡Hola Maya!",5,1,"",
   6.5,5,"¡Maya!",7.5,5,"",
   9,5,"¡Maya!",10.3,5,"",
   10.4,6,"GOLPEANDO LA PUERTA",11.4,5,"",
   11.9,5,"¡No puedes escapar de mí, Maya!",14.9,5,"",
   15,5,"¡Abre la puerta!",16.2,5,"X",
],
"TUT",[
 0.83,1,"LA SITUACIÓN",
 4.33,1,"",
 6.4,1,"Este es Jimmy Hall, el propietario",
 9.3,1,"Y psicópata peligroso",
 12.37,1,"",
 15.27,1,"Tiene planes malvados para los amigos de Maya",
 18.3,1,"",
 19.4,1,"Maya se ha escapado",
 22.4,1,"",
 24.23,1,"Jimmy sabe que tiene que detenerla",
 27.33,1,"",
 27.83,1,"LA PERSECUCIÓN",
 31.57,1,"",
 33.3,1,"Jimmy se esconde donde puede",
 36.8,1,"",
 39.37,1,"Alrededor de las esquinas",
 41.63,1,"",
 42.33,1,"En las sombras",
 44.33,1,"",
 45.27,1,"Esperando a que llegues",
 47.6,1,"",
 48.23,1,"o escondiéndose detrás de ti",
 50.57,1,"",
 51.2,1,"No puede esconderse en las escaleras",
 53.53,1,"",
 54.33,1,"O en la planta baja",
 56.47,1,"",
 57.33,1,"O en el sótano",
 60.27,1,"",
 60.7,1,"ESTRATEGIA",
 64.67,1,"",
 66.17,1,"Si Jimmy te ve, aléjate",
 67.67,1,"Fuera de su línea de visión",
 71.83,1,"",
 75.13,1,"Puedes esconderte en cualquier habitación sin cerrar",
 78.17,1,"",
 79.67,1,"Si Jimmy entra",
 81.73,1,"",
 84.13,1,"Esconderse en un armario",
 86.4,1,"",
 90.2,1,"O en el baño",
 92.33,1,"",
 94.73,1,"Utiliza la mirilla de las habitaciones de invitados",
 97.67,1,"",
 98.53,1,"Para ver si Jimmy está afuera",
 101.43,1,"",
 103.63,1,"Llama para atraerlo",
 105.2,1,"",
 106.67,1,"para controlar a dónde va",
 109.67,1,"",
 110.23,1,"Encuentra las llaves de las habitaciones en los cajones",
 112.67,1,"",
 114.17,1,"Encierra a Jimmy fuera de las habitaciones",
 116.4,1,"",
 117.83,1,"O encerrarlo",
 120.13,1,"Si puedes escapar primero",
 123.17,1,"",
 124.67,1,"Revisa rápidamente las habitaciones mirando a través de las cerraduras",
 127.7,1,"",
 129.67,1,"LOS MUERTOS",
 133.5,1,"",
 135.17,1,"Jimmy tiene un pasado asesino",
 138.2,1,"Sus víctimas nunca se fueron",
 141.17,1,"Todavía rondan el hotel",
 144.47,1,"",
 145.67,1,"Utiliza la 'Radio Fantasma' para hablar con ellos",
 150.2,1,"",
 153.23,1,"Pregúnteles sobre las cosas que ha visto y descubra su historia",
 159.07,1,"",
 159.13,1,"Preguntar por las conexiones importantes hará que aparezcan",
 166.63,1,"",
 168.17,1,"Luego sigue las luces parpadeantes",
 171.1,1,"y escucha los sonidos extraños",
 174.07,1,"",
 175.47,1,"Utiliza una brújula para guiarte",
 178.4,1,"",
 180.07,1,"Cuando estés cerca, sigue mirando a tu alrededor",
 183.07,1,"o quédate quieto y mira hacia adelante",
 186.17,1,"",
 186.7,1,"EL TALENTO DE MAYA",
 191.5,1,"",
 192.5,1,"Maya puede ver en el otro mundo",
 196.5,1,"",
 197.97,1,"Muévete a un lugar poco iluminado",
 200.43,1,"",
 201.43,1,"luego usa el espejo",
 204.67,1,"",
 206.27,1,"Verás: La ubicación de objetos importantes...",
 209.2,1,"la ubicación de los espíritus...",
 212.23,1,"las conexiones entre los objetos y los espíritus",
 217.23,1,"",
 218.3,1,"A veces Jimmy roba cosas si te pilla",
 222.77,1,"",
 224.27,1,"Busca tu 'Radio Fantasma' en el almacén del primer piso (cerca de las escaleras)",
 229.3,1,"",
 230.27,1,"Encuentra brújulas y llaves en las habitaciones de los huéspedes",
 234.77,1,"",
 236.23,1,"Lee las instrucciones de la 'Radio Fantasma' para obtener más consejos sobre la caza de fantasmas",
 241.47,1,"",
],
],

itexts:[

  "unas maletas viejas",
  "algunos trofeos y premios",
  "un bolso de juguete",
  "una botella de aguarrás y un mechero",
  "una espada de adorno",
  "algunas botellas de whisky y otras bebidas alcohólicas",
  "unos dibujos infantiles violentos",
  "un gorro de cocina",
  "un paño viejo cubierto de manchas de sangre",
  "una jeringuilla y un frasco de Diazepam",
  "una viejo remo de madera",
  "un álbum de recortes de artículos de periódicos",
  "una cuerda de tender y un rodillo",
  "un calentador viejo marcado como 'peligroso'",
  "algunos bates de cricket y béisbol",
  "una ballesta",
  "unas llaves viejas oxidadas",
  "unas fotos de humo saliendo del hotel",
  "una vieja pistola",
  "una daga decorada",
  "un cartel de la pieza cómica de Jimmy Hall",
  "algunos espejos de pared rotos",
  "una bobina de alambre de cobre",
  "una nota escrita a mano que dice 'Adiós'",
  "un anillo en su caja",
  "un juguete para un bebé",
  "el certificado de nacimiento de Jimmy Hall",

],

ketex:[

  "Llave de la habitación ",
  "Te has fijado en ",
  "Te has fijado en '",
  "Has cogido ",
  "Has cogido la llave de la habitación ",
  "Una Brújula",
  "Un Espejo de Adivinación",

],

patex:[

  ["H","Eran de a Rose, pero ella nunca llegó a usarlos.","R","[Las maletas] eran mías. Quería irme, pero nunca tuve la oportunidad."],
  ["R","Jimmy compró [los trofeos] para que pareciera que había ganado premios."],
  ["A","[El bolso] era mío. Fue un regalo de cumpleaños, pero me lo robaron.","H","Era el bolso de esa chica, pobrecita.","R","[El bolso] pertenecía a la niña."],
  ["A","No sabía qué eran [el aguarrás y el mechero] hasta que Jimmy me lo enseñó.","P","Será mejor que le preguntes a Jimmy.","H","[El aguarrás y el mechero] eran míos, pero no los guardaba juntos.","R","[El aguarrás y el mechero] pertenecían a Harvey."],
  ["A","Jimmy tenía [la espada]. No me gustaba.","P","Vi a Jimmy jugando con [la espada]. Pensé que era peligroso.","H","Teníamos una exhibición de armas medievales. Jimmy robó [la espada].","R","[La espada] pertenecía a una armadura que teníamos. Pero desapareció."],
  ["A","No sé [de dónde salieron las botellas], pero los niños no deben beber alcohol.","P","[Las botellas] probablemente eran del bar.","H","No recuerdo [de dónde salieron las botellas], pero no hay nada de malo en tomar una copa.","R","Harvey debió haber puesto [las botellas] allí."],
  ["A","El niño solía dibujar [los dibujos violentos].","P","Jimmy solía dibujar [los dibujos violentos].","H","¿Quién crees que [hizo los dibujos violentos]? ¡Jimmy! Tenía una imaginación muy violenta, el pequeño Jimmy.","R","Jimmy solía hacer dibujos [violentos] sobre la guerra. Era como la mayoría de los chicos."],
  ["P","Jimmy encontró [el gorro de cocina] y se lo puso.","H","Era del chef. ¿Quién más llevaría un gorro de cocina?","R","Nuestro chef solía llevar [el gorro de cocina]."],
  ["A","[El paño] podría haber sido mía.","P","[El paño] era mío. Lo guardé, por si lo necesitaba como prueba.","H","[El paño] podría haber tenido algo que ver con el doctor."],
  ["P","[El medicamento] puede ayudar a tratar la conducta impulsiva en algunas personas.","H","Probablemente el médico dejó [la medicina].","R","[La medicina] pertenecía al doctor Bose."],
  ["P","No lo sé, pero Jimmy encontró [el remo].","H","[El remo] siempre estaba debajo del mostrador en recepción. No sé de dónde salió.","R","[El remo] pertenecía a mi marido."],
  ["A","Jimmy hizo [el álbum de recortes]. No sé por qué. Era raro.","P","Jimmy hizo [el álbum de recortes]. Era una advertencia. Debí haberlo visto venir.","H","Jimmy solía guardar recortes de noticias sobre médicos y maestros maltratadores. No era un chico normal.","R","Harvey dijo que Jimmy hizo [el álbum de recortes], pero no lo recuerdo."],
  ["P","Yo uní [la cuerda de tender y el rodillo] juntos. Era un experimento."],
  ["H","[El viejo calentador] daba calambres. Lo guardé para que la policía pudiera comprobarlo.","R","Harvey guardó [el viejo calentador]. Dijo que era peligroso."],
  ["A","El niño jugaba con [los bates].","P","Harvey guardaba [los bates]. No sé por qué.","H","Guardaba [los bates] por si los necesitaba.","R","[Los bates] eran de mi marido, de cuando era profesor."],
  ["A","[La ballesta] estaba en un armario en el hotel. Yo lo vi.","P","El hotel solía tener una exhibición de armas antiguas.","H","[La ballesta] era de una exhibición de armas que solíamos tener. Jimmy le tenía cariño.","R","[La ballesta] era de una exhibición que Harvey solía tener. Pero no me gustaba que estuviera en el hotel."],
  ["H","[Las llaves oxidadas] eran para la puerta del viejo cuarto de calderas.","R","[Las llaves oxidadas] eran para el cuarto de calderas, pero tuvimos que cambiar la puerta."],
  ["P","Nunca escuché nada sobre eso.","H","Lograron contenerlo, pero yo perdí muchas cosas.","R","Lo pillamos a tiempo, antes de que se extendiera."],
  ["P","Harvey era el dueño de [la pistola]. No me gustaba que estuviera en el hotel.","H","[La pistola] era mía. Era de mi padre. Todavía tenía algunas balas.","R","[La pistola] pertenecía a Harvey, pero estaba guardada en mi habitación."],
  ["A","Jimmy me lo mostró, pero no era suyo.","H","No es una daga, es un abrecartas. No debería estar afilado.","R","[La daga] era un abrecartas. Fue un regalo de alguien."],
  ["R","[El cartel] era para la pieza cómica de Jimmy."],
  ["P","No vi [los espejos rotos].","H","No recuerdo eso.","R","Jimmy rompió [los espejos]."],
  ["A","Jimmy solía llevarlo consigo.","P","[El alambre de cobre] pertenecía a Jimmy. Siempre lo guardaba en su bolsillo. No me dijo para qué lo usaba.","H","Jimmy solía llevar [alambre de cobre] con él. No tengo idea de por qué.","R","Jimmy solía llevar cables con él. Le gustaba jugar con la electrónica."],
  ["R","Jimmy escribió [la nota de despedida]."],
  ["H","[El anillo] probablemente pertenece a Rose.","R","[El anillo] era mío. Alguien me hizo una oferta que no pude rechazar."],
  ["A","No lo sé. No vi a ningún bebé.","R","[El sonajero] era para el bebé. Lo guardé en el cajón de mi mesita de noche."],
  ["R","Jimmy es hijo de Hugo. En todos los sentidos."],
  ["A","Un chico llamado Jimmy me encerró en el sótano. Luego empezó a robarme cosas.","P","[La niña] era hija de un huésped del hotel. Jimmy no se portaba bien con ella.","H","[La niña] se hospedaba en el hotel con su familia.","R","[La niña] era una huésped del hotel."],
  ["A","[Jimmy] pensó que [robar mi juguete] era divertido. Lo devolvió, pero luego lo destrozó igualmente.","P","Es el tipo de cosas que [Jimmy] hacía.","H","[Jimmy] probablemente pensó que era divertido.","R","La niña estaba mintiendo. Jimmy no robaba nada."],
  ["A","Me quemé la mano. Me dolía mucho, pero no podía decirle nada a nadie.","P","La mano [de la niña] sufrió graves quemaduras, pero Jimmy pensó que todo era una broma.","H","[La niña] sufrió graves quemaduras.","R","[La niña] se quemó, pero siguió haciendo cosas peligrosas, como esa. Era rara."],
  ["A","Estaba tratando de encontrar un médico, pero Jimmy me amenazó y me obligó a quedarme.","H","[La niña] probablemente le tenía miedo a Jimmy.","R","[La razón por la que Amy estaba asustada] podría haber sido cualquier cosa. Ella era rara."],
  ["A","El niño me dijo que era medicina. Sabía fatal.","P","Yo no estaba allí entonces, pero creo que [la niña] bebió alcohol."],
  ["A","Me sentía muy ligera. Realmente pensé que podía tirarme sin peligro.","P","Jimmy hizo que la niña bebiera demasiado.","H","[La niña] se había bebido una botella de whisky. No sabía lo que estaba haciendo.","R","No sabía mucho sobre [la niña]."],
  ["A","Me tiré, pero luego todo se oscureció y no pude despertar. Ya no puedo despertar.","P","[La niña] se cayó por las escaleras desde el último piso. Estaba demasiado borracha para saber lo que estaba haciendo. Fue la razón por la que Rose me llamó.","H","[La niña] se cayó por las escaleras desde el último piso. Sabía que Jimmy estaba detrás de ello.","R","[La niña] se tiró. Harvey culpó a Jimmy por ello. Fue culpa de la niña, no de Jimmy."],
  ["P","Recibí una llamada de Rose. Quería que averiguara qué le pasaba a Jimmy. Pero Harvey estaba preocupado por las cosas que Jimmy estaba imaginando.","H","Se suponía que el Doctor Bose ayudaría a Jimmy, pero era demasiado tarde para Jimmy.","R","El Doctor Bose vino para ayudar a Jimmy."],
  ["P","Jimmy estaba matando cosas. Me di cuenta de que necesitaba trabajar en su empatía. Así que le pedí que pensara en algo bueno que pudiera hacer por mí. Se le ocurrió una idea de inmediato.","H","Jimmy dijo que había encontrado [el conejo muerto] en alguna parte. Lo que estaba haciendo con él, es otra historia.","R","Harvey dijo que Jimmy probablemente había matado [al conejo] él mismo, pero yo no le creí."],
  ["P","Jimmy me estaba haciendo un sándwich. Lo llevó a mi habitación, tal como le pedí. Al principio no sospeché que algo no iba bien.","H","El médico estaba tratando de educar a Jimmy para que ayudara. Gran error.","R","El doctor Bose intentaba que Jimmy hiciera cosas que no quería hacer."],
  ["P","Jimmy había puesto cristales en mi sándwich. Casi me atraganto. Me di cuenta de que había subestimado la enfermedad de Jimmy. Tuve que acelerar su tratamiento, urgentemente.","H","[Doctor Bose] supo de lo que Jimmy era capaz, de la peor manera. Las bromas de Jimmy siempre iban demasiado lejos.","R","[Doctor Bose] se cortó a sí mismo, pero luego intentó culpar a Jimmy. Se lo hizo a sí mismo. No fue Jimmy."],
  ["P","Jimmy se negó a dejarme administrarle la droga. Luego le dijo a Rose que había tratado de obligarlo usando la violencia. ¡Era ridículo!","H","No lo sé. Yo no estaba allí.","R","[Doctor Bose] estaba tratando de medicar a Jimmy, sin mi permiso."],
  ["P","Me preocupaba que Rose creyera a Jimmy. Era una mentira descarada. Pero me las arreglé para convencer a Rose de que Jimmy estaba mintiendo.","H","[El doctor Bose] estaba preocupado por lo que Jimmy inventaría sobre él. Y tenía motivos.","R","Porque [el doctor Bose] estaba preocupado por su reputación. Pero decidí darle otra oportunidad."],
  ["P","Pensé que cuando [Jimmy] se diera cuenta de que lo habían pillado, empezaría a confraternizar conmigo. En cambio, se inventó otra mentira. Solo que esta fue mucho peor. La peor.","R","[Doctor Bose] estaba hablando con Jimmy, tratando de controlarlo. Intentando que hiciera cosas feas. Nunca debí haberme fiado de él."],
  ["P","Rose me denunció. Sabía que me depondrían. No tenía carrera ni futuro. Decidí tomar el control, de una vez por todas.","H","Iban a arrestar al [Doctor Bose]. Jimmy le había arruinado la vida. Pero yo no creí nada de eso.","R","Vinieron a arrestar al [Doctor Bose]. Se merecía todo lo que le pasó."],
  ["P","Ya había tenido suficiente. No había vuelta atrás. De todas formas, mi vida había acabado ya.","H","[El doctor Bose] fue impulsado a ello. Todos pensaron que había 'tocado' a Jimmy. Jimmy era demasiado inteligente. El médico no tuvo ninguna posibilidad.","R","[El doctor Bose] sabía que era culpable. Hizo lo correcto."],
  ["P","Harvey sabía que Jimmy estaba mintiendo sobre mí. Harvey lo entendía.","H","Jimmy había hecho acusaciones sobre el médico. Rose le creyó, pero había oído esa historia en alguna parte antes.","R","Harvey no creía lo que Jimmy estaba diciendo [sobre el médico], pero yo sabía que no estaba mintiendo."],
  ["P","Jimmy nunca reconoció sus mentiras.","H","Jimmy solo se rió. Luego empezó a tenderme pequeñas trampas. Algunas de ellas no tan pequeñas.","R","¿Cómo podía Jimmy admitir algo que no era cierto? Harvey se equivocó al increpar a Jimmy de esa manera."],
  ["H","[Jimmy] sabía que era mi calentador. Conectó la carcasa directamente a la red eléctrica. Supe que había que darle una lección. Él había dañado mi propiedad, así que decidí dañar la suya.","R","Harvey culpó a Jimmy, pero ese calentador estaba defectuoso. Harvey debería haberse deshecho de él."],
  ["P","No sé [qué estaba haciendo Harvey con el bate], pero la violencia solo empeora las cosas.","H","Rompí la televisión y las consolas [de Jimmy]. Estaba enfadado. Pero no funcionó. Simplemente lo empeoró. Pronto tomó represalias.","R","[Harvey] destrozó las cosas de Jimmy. No pudo controlar su ira."],
  ["H","Jimmy había preparado [la ballesta] para que se disparara al abrir la puerta. Tuve que ir a Urgencias. Cuando regresé no lo encontré. Rose dijo que estaba escondido en el sótano. Eso me dio una idea.","R","Harvey dijo que Jimmy le había disparado con la ballesta, pero yo sabía que Jimmy no usaría un arma así."],
  ["H","Quería dpagarle a Jimmy con la misma moneda. Pensé que no podía hacer ningún mal [en el sótano]. Estaba equivocado.","R","No sé qué estaba haciendo [Harvey] [en el sótano]."],
  ["P","No recuerdo [el incendio del hotel].","H","Logramos contener [el incendio del hotel] antes de se descontrolara. Pero todas nuestras viejas fotos y cartas estaban allí. Todo se perdió. Jimmy estaba fuera de control. Yo ya estaba harto. Quería que se fuera.","R","Harvey culpó a Jimmy [por el incendio del hotel], pero fue un cable suelto lo que provocó el incendio. Fue un accidente."],
  ["P","No sé [de dónde vino la pistola]. Pero Harvey no pudo controlar su ira.","H","No sé qué iba a hacer [con la pistola]. El problema era que no me di cuenta de que él también iría armado.","R","No sé [de dónde vino la pistola]. Harvey no debería haber tenido una pistola en el hotel."],
  ["H","Estaba buscando a Jimmy."],
  ["H","Jimmy apareció detrás de mí. No lo vi venir. Jimmy siempre ganaba al final.","R","Harvey se había vuelto loco. Jimmy solo se estaba defendiendo."],
  ["H","Rose creyó a Jimmy. Ella lo defendió, hasta el final.","R","Tuve que explicarle a la policía que la daga era solo un abrecartas y que Harvey tenía un pistola cargada. Jimmy actuó en defensa propia. Ellos lo entendieron."],
  ["H","[La policía] dejó marchar a Jimmy. Dijeron que era en defensa propia, que habían intentado disparar a Jimmy. Pero todo era mentira.","R","Jimmy volvía a casa. La policía entendió que [fue en defensa propia]. Pero algo cambió. Comenzó a ayudar a llevar el hotel. Y encontró una manera de atraer más huéspedes."],
  ["H","No sé quién era [Hugo Punch].","R","Me lo estaba pasando bien. Estábamos ganando dinero de nuevo. Entonces Jimmy comenzó a comportarse de manera extraña. Lo escuché gritar, clavándose la mirada a sí mismo. Parecía enfadado."],
  ["R","No lo entendía al principio. Estaba confundida. Pero luego me di cuenta de que Jimmy no era el que estaba haciendo estas cosas. Igual que los espejos, se estaba fracturando. Jimmy ya no estaba al mando."],
  ["H","No lo sé, pero sé que Jimmy siempre lo destrozaba todo al final.","R","Ya no era Jimmy en el escenario. Era Hugo Punch. Comenzó a insultar al público todas las noches. Entonces, una noche después del espectáculo, una invitada le dijo a Jimmy lo que pensaba de él. Perdió los estribos e hizo algo estúpido."],
  ["R","Los periodistas [golpeaban la puerta]. Querían a Jimmy. Pero fue Hugo Punch quien ató a la mujer. Jimmy ya no podía controlarlo. Estaba deprimido. Solo quería dejarlo todo e irse."],
  ["R","Era Jimmy el que estaba [en el baño]. Trató de suicidarse. Por eso tuve que decirle la verdad."],
  ["H","No sé [a quién atacaba Rose]. Había cosas que Rose nunca me contó.","R","Enterré a Hugo [en el sótano] en hormigón, en una habitación secreta. Dejé que abusara de Jimmy durante demasiado tiempo. Fue mi culpa que Jimmy saliera como lo hizo. Pensé que la culpa se iría si se lo contaba a Jimmy. Me equivoqué. Lo empeoró. No podía aceptar lo que había hecho. No podía vivir conmigo misma."],
  ["R","Si no me hubiera matado, Jimmy lo habría hecho, o mejor dicho, Hugo. Hugo todavía está al mando, incluso ahora. Controla a Jimmy. Pídele a Jimmy que te muestre dónde vive Hugo."],
  ["H","Nunca conocí a [El Gran Hugo].","R","Hugo era mago y artista. Compró el hotel para promocionar su espectáculo. Él se hizo famoso. Trabajé como su asistente. Luego las cosas se aceleraron."],
  ["R","Nunca supe lo que quería. Solo había una cosa que podía darle."],
  ["R","Hugo era un hombre violento, malvado y enfermo."],
  ["A","¡Sí! [Jimmy] lo cogió cuando yo no miraba y robó mi dinero. Le regañé, pero él no escuchó."],
  ["A","[Jimmy] empapó mi juguete con el contenido de la botella. ¡Le odiaba!"],
  ["A","[Jimmy] descolgó la espada de la pared. Parecía muy afilada. Me hizo prometer que no se lo diría a nadie y dijo que podía hacer que mi mano dejara de doler."],
  ["A","[Jimmy] me dijo que siguiera bebiendo [la medicina]. Fue horrible. Entonces comencé a sentirme rara."],
  ["P","[Los dibujos violentos] sugerían una personalidad turbia, pero no estaba preocupado en particular hasta que comencé a darme cuenta de lo lejos que llegaba la imaginación [de Jimmy]."],
  ["P","Jimmy dijo que haría algo por mí, así que lo seguí para ver qué iba a hacer."],
  ["P","[Los cristales que Jimmy puso en el sándwich] fueron mi primer encuentro con el sentido del humor de Jimmy."],
  ["P","El [Diazepam] no era el medicamento ideal, pero era todo lo que tenía. Jimmy necesitaba tratamiento de inmediato. Era peligroso."],
  ["P","Jimmy dijo que había usado el remo para pegarle. Yo nunca usaría la violencia con un paciente. ¡Era ridículo! Pero Rose le creyó."],
  ["P","Jimmy me acusó del peor crimen posible. Lo sacó de una historia que había leído en el periódico. Se lo estaba inventando."],
  ["P","Probé con la cuerda de tender, pero era demasiado fina. En su lugar encontré una cuerda. Todavía tenía las llaves del hotel, así que entré una noche mientras estaba bajo fianza."],
  ["H","Tan pronto como encontré ese álbum, supe de dónde había sacado Jimmy [la historia]. Era igual, hasta el último detalle."],
  ["H","Jimmy siempre estaba jugando con la electricidad. Era curioso cómo nunca era él el que se electrocutaba."],
  ["H","Guardaba esos bates para defensa propia, pero estaba enfadado. Agarré uno y fui a la habitación de Jimmy."],
  ["H","Jimmy tenía aprecio a las armas como [la ballesta]. No volví a ver a Jimmy en toda la noche tras destrozar sus cosas. Debería haber sabido que estaba trabajando en su próximo truquillo."],
  ["H","Bueno, si Jimmy quería esconderse [en el sótano], pensé debía gustarle."],
  ["H","Nadie se saba cuenta de lo lejos que Jimmy podía llegar para llamar la atención."],
  ["H","Se me fue de las manos. Estaba rabioso. Lo odiaba. Perdí el control."],
  ["H","¡[El abrecartas] ni siquiera era una daga! Pero nunca aprendí la lección. Jimmy siempre iba un paso por delante de mí."],
  ["R","Jimmy empezó a representar un acto cómico: Hugo Punch. Era bueno. La gente empezó a venir solo para verlo."],
  ["R","Los espejos rotos eran solo el comienzo. Él no recordaba haberlo hecho. Entonces empezaron a suceder otras cosas extrañas."],
  ["R","Jimmy encerró [a la mujer que se había quejado] y la ató. La encontré y la liberé. Ella no presentó cargos, pero se lo contó a los periódicos."],
  ["R","Jimmy había estado luchando contra Hugo Punch toda su vida. Jimmy ya no quería seguir viviendo."],
  ["R","[Hugo y yo] estábamos casados. Al principio, éramos felices, antes de que las cosas empezaran a cambiar."],
  ["R","Pensé que tener un hijo lo arreglaría todo. Estaba equivocada."],
  ["R","Se lo conté todo a Jimmy. Hugo pegaba a Jimmy desde que nació, durante 2 años. Debería haberlo parado antes."],
  ["R","Jimmy había ido a buscar la tumba de Hugo. Estaba sola. Sabía lo que debía hacer."],
],

finwords:[

  "En cada uno de nosotros<br>hay otro a quien no conocemos.",7,
  "",0.5,
  "Nos habla en sueños,",6,
  "y nos cuenta lo diferente que nos ve<br>de cómo nos vemos a nosotros mismos.<br><span class='h8'>Carl Jung</span>",8,
  "V",5,
  "Puedes verlos,",4,
  "",0.5,
  "en la oscura noche.<br>(At Dead Of Night)",5,
  "",16,
  "<span class='hf'>Maya</span><br>Chloe Booyens",5,
  "<span class='hf'>Jimmy Hall</span><br>Huld Martha",5,
  "<span class='hf'>Rose Hall</span><br>Joanna Bond",5,
  "<span class='hf'>Harvey</span><br>Karl Haynes",5,
  "<span class='hf'>Dr Bose</span><br>Rohit Gokani",5,
  "<span class='hf'>Amy Bell</span><br>Daisy Follin",5,
  "<span class='hf'>Con actores de reparto</span><br>Rachel Alfieri<br>Paige Ryan<br>Sally Alfieri<br>Daniel Alfieri<br>Luke Chase",8,
  "<span class='hf'>Con actores de reparto</span><br>Sam Follin<br>Jamie Follin<br>Tom Follin<br>Clare Follin",7,
  "<span class='hf'>Agradecimientos especiales a</span><br>Mark Wilson<br>Fay Wilkins",7,
  "",1,
  "Gracias por jugar a<br>At Dead Of Night",8,
  "",

],

words:[

  "ENCENDER EL DISPOSITIVO",
  "APAGAR DISPOSITIVO",
  "GRITAR",
  "USAR ESPEJO VIDENTE",
  "PREGUNTAR",
  "CERRAR",
  "Pregunta<br>quién<br>está ahí",
  "Pregunta<br>su nombre",
  "¿Eres<br>",
  "CORRER HACIA ADELANTE",
  "PULSAR<br>SÓTANO",
  "PULSAR<br>PLANTA<br>BAJA",
  "PULSAR<br>PRIMER<br>PISO",
  "PULSAR<br>SEGUNDO<br>PISO",
  "PULSAR<br>TERCER<br>PISO",
  "VOLVER",
  "ABRIR<br>MENÚ",
  "Llamar a Jimmy",
  "PROBAR<br>PUERTA<br>",
  "PROBAR<br>HABITACIÓN<br>",
  "VOLVER A<br>LA HABITACIÓN",
  "ENVIAR<br>AMIGA<br>FUERA",
  "HAS EMPAREJADO<br>ESTO",
  "PROBAR<br>ALMACÉN<br>CINCO",
  "LLAMAR AL ASCENSOR",
  "PREGUNTAR POR ESTO",
  "ESCONDERSE<br>EN EL ARMARIO",
  "ESCONDERSE<br>EN EL BAÑO",
  "MIRAR POR<br>LA MIRILLA",
  "ENTRAR A<br>LA HABITACIÓN",
  "BUSCAR<br>AQUÍ",
  "DEJAR<br>LA HABITACIÓN",
  "PROBAR<br>ESTA PUERTA",
  "CERRAR",
  "ABRIR<br>NOTAS",
  "AÑADIR AL PAR",
  "VOLVER A<br>LA PUERTA",
  "EMPAREJA AVISTAMIENTOS<br><span style='font-family:arial'>Y</span> OBJETOS",
  "PREGUNTAR SI ESTÁN RELACIONADOS",
  "PREGUNTAR",
  "SIGUIENTE PÁGINA",
  "PÁGINA ANTERIOR",
  "PROBAR PUERTA DE LA ESCALERA",
  "DEMASIADO<br>OSCURO",
  "ENTRAR EN LA<br>HABITACIÓN",
  "SALIR DEL<br>TUTORIAL",
  "Busca el dispositivo en el almacén del primer piso cerca de las escaleras",
  "Necesitas encontrar un espejo vidente",
  "Necesitas encontrar una brújula",
  "Necesitas encontrar una brújula y un espejo vidente",
  "Juego<br>Guardado",
  "MIRA POR<br>LA VENTANA",
  "Espera A Que Sea Seguro",
  "SALIR",
  "Esa no es la llave correcta",
  "Puerta desbloqueada",
  "Mira hacia una puerta bloqueada para probar una llave",
  "Puerta bloqueada",
  "Prueba primero la puerta",
  "Usa la llave de la habitación<br>para bloquear la puerta",
  "Primero desbloquea la puerta",
  "SUBIR",
  "BAJAR",
  "Está demasiado oscuro aquí para usar el dispositivo",
  "Espera un momento antes de intentar establecer contacto otra vez",
  "¡Jimmy está a punto de entrar en la habitación!",
  "Escuchas a Jimmy en alguna parte",
  "Jimmy se ríe en voz baja",
  "Inicia el juego primero",
  "No puedes guardar ahora mismo",
  "Juego Actual Guardado",
  "Es demasiado pronto para volver a usar el espejo",
  "¡No lo hagas!<br>¡Jimmy está en esta habitación!",
  "MIRAR A TRAVÉS<br>DE LA CERRADURA",
  "Es mejor dejar los almacenes desbloqueados",
  "RECOGER<br>DISPOSITIVO",
  "Está demasiado oscuro aquí para usar el espejo",
  "Almacen",
  "Desconocido",
  "Hay demasiada luz aquí para usar el espejo",
  "VOLVER<br>AL MENÚ",
  "¿Guardar<br>Partida?",
  "GUARDAR",
  "Escuchas a Jimmy caminando cerca",
  "Escuchas a Jimmy moviéndose rápidamente",
  "La puerta de la habitación está cerrada",
  "SALTAR<br>DESPERTAR",
  "Busca el dispositivo en los almacenes",
  "OMITIR",
  "CERRAR MENSAJE",

],

ghostex:[

  "A",
  "En Contacto Con<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;AMY&#160;&#160;</span>&#10023;<br><br>Niña de 10 años",
  "P",
  "En Contacto Con<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;Dr BOSE&#160;&#160;</span>&#10023;<br><br>Psiquiatra clínico",
  "H",
  "En Contacto Con<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;HARVEY&#160;&#160;</span>&#10023;<br><br>Propietario del hotel",
  "R",
  "En Contacto Con<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;ROSE&#160;&#160;</span>&#10023;<br><br>Propietaria del hotel",

],

headtex:[

  "<span class='h3'>Encuentra el Receptor Espiritual.</span>",
  "<span class='h3'>Enciende el Receptor Espiritual para comunicarte con los espíritus.</span>",
  "<span class='h3'>Sube el volumen del Receptor Espiritual para escuchar las respuestas de los espíritus.</span>",
  "<span class='h3'>Trata de contactar con un espíritu</span><br><span class='h2'>(Usa el icono de Hablar de arriba)</span>",
  "<span class='h3'>Estás haciendo contacto con un espíritu.<br>Intenta confirmar su identidad.</span>",
  "<span class='h3'>Estás Ahora en Contacto con ",
  "<span class='h3'>El espíritu está demasiado lejos. Trata de acercarte más.</span>",
  "<span class='h2'>Cuando te encuentras con espíritus, puedes hacerles preguntas. Empareja sus respuestas para hacer conexiones. Cuando estás solo, puedes comprobar las respuestas de los espíritus aquí.</span>",

],

gametex:[

  "El Juego Estándar<br><br><span class='h2'>Encuentra espíritus, hazles preguntas y haz conexiones para que se manifiesten, mientras Jimmy intenta evitar que descubras sus secretos.</span>",
  "Búsqueda y Rescate<br><br><span class='h2'>Rescata a tus amigas mientras Jimmy intenta detenerte. Si te golpea una vez, se acabó el juego.</span>",
  "Búsqueda y Rescate<br><br><span class='h2'>Regresa al final de tu último juego.</span>",
  "<span class='h9'>Selecciona el juego</span><br><br><span class='h2'>Elige Juego Estándar o Juego extremo. Cuando juegas en Extremo, si Jimmy te pilla, se llevará casi todos los objetos, siempre.<br><br>Tu juego actual se perderá y tus logros se reiniciarán si empiezas un juego nuevo.</span>",
  "<span class='h9'>¿Estás seguro?</span><br><br><span class='h2'>Esto terminará tu juego actual y te devolverá a tu último juego guardado.</span>",
  "<span class='h9'>¡Un golpe y estás muerto!</span><br><br><span class='h2'>Este juego no se guarda. ¡Solo tienes una oportunidad de rescatar a todos!</span>",

],

getex:[

  "<br>Has encontrado<br><br>Un espejo vidente<br><br><span style='font-size:50%'>Revela pistas cuando lo usas en lugares oscuros</span>",
  "<br>Has Encontrado<br><br>Una Brújula<br><br><span style='font-size:50%'>Apunta hacia los espíritus cercanos</span>",
  "<span style='font-size:40%>'>Encontraste una llave etiquetada<br>",
  "Encontraste la llave para bloquear la habitación",
  "Encontraste la llave para bloquear la habitación",

],

roomtex:"Habitación",

foundtex:"Encontraste",

alreadytex:[

  "Ya tienes un espejo vidente",
  "Ya tienes una brújula"

],

adtext:[

  "Sonido de una<br>niña llorando",
  "Sonidos de unos recreativos",
  "Sonido de una niña<br>llorando en voz baja",
  "Una niña canturreando para sí misma",
  "Alguien que llama<br>discretamente a una puerta",
  "Sonido de trastos<br>siendo movidos",
  "Sonido de un<br>grifo abierto",
  "Sonido de un<br>teléfono marcando",
  "Golpes fuertes<br>en una puerta",
  "Sonido de alguien<br>golpeando una puerta",
  "Sonido de <br>chispas eléctricas",
  "Sonido de cosas<br>siendo destrozadas",
  "Sonido de golpes<br>intermitentes o chasquidos",
  "Alguien golpea<br>una puerta de metal",
  "Un sonido de alarma alto",
  "La voz de Harvey gritándole a Jimmy",
  "El suave murmullo de una multitud",
  "Música de radio",
  "Una multitud que abuchea y grita fuerte",
  "Un timbre sonando esporádicamente",
  "Sonido de agua vertida en un baño",
  "Un sonido esporádico de azotes",
  "Música sonando",

],

itdetext:[

  "Maletas",
  "Trofeos",
  "Bolso de juguete",
  "Aguarrás y mechero",
  "Espada",
  "Botellas de whisky",
  "Dibujos Violentos",
  "Gorro de cocina",
  "Paño manchado de sangre",
  "Droga Diazepam",
  "Remo de madera",
  "Álbum de recortes",
  "Cuarda de tender",
  "Calentador peligroso",
  "Bates deportivos",
  "Ballesta",
  "Llaves oxidadas",
  "Fotos de un incendio",
  "Pistola de mano",
  "Daga decorada",
  "Cartel de Hugo Punch",
  "Espejos rotos",
  "Bobina de alambre",
  "Nota de despedida",
  "Anillo de bodas",
  "Sonajero de bebé",
  "Certificado de nacimiento",
  "Chica en el sótano",
  "Jimmy robándole a Amy",
  "Amy con un juguete en llamas",
  "Amy asustada fuera de una habitación",
  "Amy bebiendo algo horrible",
  "Amy en lo alto de las escaleras",
  "Amy al fondo de las escaleras",
  "Hombre trajeado llamando a la puerta",
  "Dr Bose encontrando un animal muerto",
  "Dr Bose fuera de la cocina",
  "Dr Bose escupiendo sangre",
  "Dr Bose con una jeringuilla",
  "Dr Bose explicando lo que pasó",
  "Dr Bose sentado en una cama en una habitación",
  "Dr Bose en los recreativos",
  "Dr Bose suicidándose",
  "El hombre diciendo que Jimmy mintió",
  "Harvey gritando tras una puerta",
  "Harvey recibiendo una descarga eléctrica",
  "Harvey con un bate",
  "Harvey siendo disparado en la pierna",
  "Harvey encerrando a jimmy en el sótano",
  "Un incendio en el sótano",
  "Harvey con una pistola",
  "Harvey rumbo al salón de baile",
  "Harvey siendo apuñalado",
  "Mujer explicando la daga",
  "Rose en la puerta de entrada",
  "Rose entre bastidores anunciando a Hugo Punch",
  "Rose encontrando muchos maniquíes",
  "Rose disculpándose con una invitada",
  "Rose escondiéndose y gente golpeando una puerta",
  "Rose encontrando a Jimmy en el baño",
  "Rose atacando a alguien con un bate",
  "Rose en llamas",
  "El gran Hugo en el escenario",
  "Hombre gritando y niño llorando",
  "Gritos y ascensor desplomándose",
  "Jimmy no escucha",
  "Jimmy empapando el juguete de Amy",
  "Jimmy podría hacer que a Amy dejara de dolerle la mano",
  "Amy bebió algo horrible",
  "El Dr Bose vio los dibujos de Jimmy",
  "A Jimmy se le ocurrió una idea",
  "El Dr Bose conoció el humor de Jimmy",
  "El Dr Bose decidió medicar a Jimmy",
  "Jimmy acusó al Dr Bose de violencia",
  "Jimmy acusó al Dr Bose de abuso",
  "El Dr Bose sabía lo que debía hacer",
  "Harvey encontró el álbum de recortes de Jimmy",
  "Jimmy jugaba con la electricidad",
  "Harvey llevó un bate a la habitación de Jimmy",
  "Harvey sospechó de otra trampa",
  "Harvey usó la llave de la sala de calderas",
  "Harvey se dio cuenta de que Jimmy estaba loco",
  "Harvey perdió el control",
  "Jimmy iba un paso por delante",
  "Jimmy comenzó su acto cómico",
  "Cosas extrañas empezaron a suceder",
  "Los periódicos se enteraron",
  "Jimmy había tenido suficiente",
  "Las cosas cambiaron con Hugo",
  "Un bebé no soluciona nada",
  "La verdad fue revelada",
  "Rose no pudo con la culpa",
  "Llave del almacén",
  "",
  "",
  "Espejo vidente",
  "Brújula",
  "Llave de 'Escaleras del piso uno'",
  "",
  "",
  "Espejo vidente",
  "Brújula",
  "Llave del almacén",
  "",
  "",
  "Espejo vidente",
  "Brújula",
  "Llave de 'Escaleras del Piso Dos'",
  "",
  "",
  "Espejo vidente",
  "Brújula",
  "Llave del almacén",
  "",
  "",
  "Espejo vidente",
  "Brújula",
  "Llave de 'Escaleras del Piso Tres'",
  "",
  "",
  "Espejo vidente",
  "Brújula",
  "Llave del almacén",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Llave de la salida del hotel",
  "Llave del almacén del sótano",

],

keyfinds:[

    "TRASTERO",
    "ESCALERAS<br>PISO UNO",
    "ESCALERAS<br>PISO DOS",
    "ESCALERAS<br>PISO TRES",

  ],

gnames:[
  "Amy",
  "Dr Bose",
  "Harvey",
  "Rose",
  "Hugo"
],

extras:[
  "BIENVENIDO A<br>SEA VIEW HOTEL<br><span style='font-size:50%'>ENTRE AQUÍ</span>",
  "Maya:",
  "El juego se ha salvado",
  "Controlador de juego conectado",
  "Controlador de juego desconectado",
],

};
