var TUR={

mentex:[

"Edison<br><span class='bt1'>Ruh Sesi Alıcısı<br></span>Kullanma Kılavuzu<br><br><br><span style='font-size:120%'>Doğaüstü Varlıkla İletişime Geçme (Dikkat Edilmesi Gerekenler)<br><br>Bir ruh ile iletişime geçildiğinde, ruhların duygusal durumları doğrudan elektriğe veya 'enerji'ye dönüşür. Ruhlar yüksek veya düşük enerji yayabilirler, ancak sesli iletişim için düşük enerji gereklidir.</span><br><br><span style='font-size:120%'>Agresif veya kışkırtıcı sorgulamalar sırasında ruhların yaydıkları enerji değişebilir. Eğer ruh yüksek enerji yaymaya başlarsa, cihazda parazitlenmeye sebep olacak ve sesli iletişimi olanaksız hale getirecektir.</span><br><br><span style='font-size:120%'>Yüksek enerji akımı yaratan ruhlar, elektronik veya optik yardım almadan fiziksel forma bürünürler. Bu durum, genelde farklı yerlerde gerçekleşir. Bu doğaüstü varlıkların ölmüş insanlar olduğunu unutmayın. Lütfen onlara saygıda kusur etmeyin.</span>",

"İLETİŞM İLE ENERJİ<br>YÜKSELİR<br><br>DÜŞÜK AKIM<br><br><br><br><br>DUYULABİLİR<br>",

"<br><br><br>YÜKSEK AKIM<br><br><br><br><br>FİZİKSEL OLARAK<br>BELİREBİLİR<br><br>BELİRME İLE<br>ENERJİ HARCANDI",

"<div class='ht'><span style='font-size:170%'>TAVSİYELER</span><br><br><span style='font-size:120%'>At Dead Of Night'ı karanlık odada, mümkün olduğunca az arka plan sesi eşliğinde veya kulaklık takarak oynanmasını tavsiye ederiz.</span><br><br><span style='font-size:120%'>Otelin karanlık koridorlarında görüş zorluğu yaşarsan 'U/I' tuşlarını kullanarak oyunun parlaklığını ayarlayabilirsin.</span><br><br><span style='font-size:120%'>Jimmy'nin seslerini yalnızca seninle aynı kattaysa duyabilirsin. Eğer dikkatlice dinlersen Jimmy'nin ayak seslerini de duyabilir, böylece sana yakın olup olmadığını anlayabilirsin. Ruhlar da ses çıkartır. Eğer daha dikkatli dinlemek istersen 'D' tuşuna basarak ambiyans sesini kısa süreliğine azaltabilirsin.</span><br><br><span style='font-size:120%'>Eğer işitme konusunda sıkıntı çekiyorsan 'Altyazı' menüsünde yer alan 'Gelişmiş Açıklama' özelliğini açabilirsin. Ancak böyle bir yardıma ihtiyacın yoksa bu özelliği kapalı tutmanı öneririz.</span><br><br><span style='font-size:120%'>Pusula, duvarın arkasındaki ruhları gösterebilir. Eğer pusulanın gösterdiği tarafta bir şey göremiyorsan, koridoru kullanarak o duvarın arkasına geçmeye çalış. Yakınlarda bir ruh yoksa pusula, yavaşça yön değiştirir. Eğer hızlı dönüyorsa ruhların yakınındasın demektir.</span><br><br><span style='font-size:120%'>Anahtar deliklerinden bakabileceğini ve fareyi ekranın kenarlarına götürerek daha hızlı dönebileceğini unutma.</span></div>",

"<div class='ht'><span style='font-size:170%'>JIMMY VE DKB</span><br><br><span style='font-size:120%'>Jimmy'nin hikayesi tamamen kurgusal olmaktadır ve 'Dissosiyatif Kimlik Bozukluğu' (DKB) veya halk arasında bilinen adıyla: 'Çoklu Kişilik Bozukluğu' rahatsızlığı ile hiçbir bağlantısı olmaması amaçlanmıştır.</span><br><br><span style='font-size:120%'>DKB çoğunlukla (her zaman değil) bireyin çocukluk döneminde yaşadığı istismar nedeni ile oluşan bir rahatsızlıktır. DKB rahatsızlığının hiçbir ahlaksız davranış veya suç ile ilişkisi yoktur. DKB hastalarının ilgiye ihtiyaçları olsa da toplumun yanlış bilmesi nedeniyle, bu hastalara karşı güvensiz bir yaklaşım sergilenmektedir.</span><br><br><span style='font-size:120%'>Jimmy karakterini yaratırken amacımız hiçbir zaman DKB hastalarını karalamak veya onlarla alay etmek olmamıştır. Oyunumuz nedeniyle DKB hastaları ve hasta yakınlarında herhangi bir üzüntüye sebebiyet olduysak, özür dileriz.</span><br><br><span style='font-size:120%'>DKB rahatsızlığı hakkında daha fazla bilgi edinmek için lütfen şu siteyi ziyaret edin:</span><br><br>https://survivorsnetwork.org.uk/resource/dissociative-identity-disorder-d-i-d/</div>",

"MUHTEŞEM OYUNCULUK<br>BECERİLERİ İÇİN TEŞEKKÜRLER:<br><br><table><tr><td><span class='h5'>Jimmy</span><br><span class='ht'>Huld Martha</span><br><br><span class='h5'>Rose</span><br><span class='ht'>Joanna Bond</span><br><br><span class='h5'>Dr Bose</span><br><span class='ht'>Rohit Gokani</span><br><br></td><td><span class='h5'>Maya</span><br><span class='ht'>Chloe Booyens</span><br><br><span class='h5'>Harvey</span><br><span class='ht'>Karl Haynes</span><br><br><span class='h5'>Amy<span><br><span class='ht'>Daisy Follin</span><br><br></td></tr></table><span class='h5'>YARDIMCI OYUNCULAR:</span><table><tr><td><span class='ht'>Rachel Alfieri<br>Paige Ryan<br>Sam Follin</span></td><td><span class='ht'>Jamie Follin<br>Clare Follin<br>Tom Follin</span></td></tr></table><br><span class='h5'>ÖZEL TEŞEKKÜRLER:</span><br><table><tr><td><span class='ht'>Mark Wilson</span></td><td><span class='ht'>Fay Wilkins</span></td><td><span class='ht'>Daniel Alfieri<span></td><td><span class='ht'>Sally Alfieri</span></td><td><span class='ht'>Luke Chase</span></td></tr></table><br><span class='h7'>YAPIMCI: Tim 'Tahmin Edebileceğiniz Üzere' Follin<br>©2020 Baggy Cat Ltd<br></span></span>",

"&#160;&#160;&#160;&#160;&#160; GELİŞMİŞ AÇIKLAMA<br><br><span class='h2'><span style='font-size:150%'>Oyun sırasında çıkan seslere altyazı ekler.</span><br><br><span style='font-size:150%'>Eğer işitme sorununuz yoksa bu ayarı kapalı tutmanızı tavsiye ederiz.</span>",

"&#160;&#160;&#160;&#160;&#160; ALTYAZI<br><br><span class='h2'><span style='font-size:150%'>Oyundaki altyazıları açar veya kapatır.</span>",

"GÖSTERİLECEK BİR<br>ETKİNLİK YOK.",

"OYUNA BAŞLA",

"<span class='h9'>JIMMY HALL'UN HİKAYESİ</span><br><br><span class='h2'><span style='font-size:130%'>Ruhlara sorular sorarak Jimmy'nin gizemini ortaya çıkar. Jimmy gerçekleri öğrenmeni engellemek için elinden geleni yapacak.</span>",

"<span class='h9'>SON KAÇIŞ</span><br><br><span class='h2'><span style='font-size:130%'>Jimmy'nin seni Hugo ile tanışmaya davet ettiği andan itibaren oynamaya devam et.</span>",

"<span class='h9'>KURTARMA (YENİ OYUN)</span><br><br><span class='h2'><span style='font-size:130%'>Jimmy'ye yakalanmadan bütün arkadaşlarını kurtar. Yakalanırsan ölürsün! Bu oyun modunda kayıt yapılamaz.</span>",

"BÜTÜN EĞİTİM VİDEOLARINI İZLE",

"'KOVALAMACA' KONUSUNU İZLE",

"'STRATEJİ' KONUSUNU İZLE",

"'ÖLÜLER' KONUSUNU İZLE",

"'MAYA'NIN YETENEĞİ' KONUSUNU İZLE",

"BAŞLANGICI İZLE",

"'MAYA'NIN VARIŞI'NI İZLE",

"'HUGO'NUN OLAYA DAHİL OLMASI'NI İZLE",

"'SABAH 02:30'U İZLE",

"'RUH ALICISI'NI İZLE",

"<span style='font-size:75%'>OYUN İSTATİSTİKLERİ</span>",

"<span style='font-size:75%'>YENİ OYUNA BAŞLA</span>",

"<span style='font-size:75%'>GÖRÜLENLERİ İZLE</span>",

"<span style='font-size:75%'>ALICI TALİMATLARI</span>",

"<span style='font-size:75%'>EĞİTİM & AÇILIŞ VİDEOLARI</span>",

"<span style='font-size:75%'>ALTYAZI & AÇIKLAMALAR</span>",

"<span style='font-size:75%'>EMEĞİ GEÇENLER</span>",

"<span style='font-size:75%'>TAVSİYELER</span>",

"<span style='font-size:75%'>JIMMY & DKB</span>",

"OTELDEN AYRIL<br><span class='h2'>KAYDET & ÇIK</span>",

"OTELDEN AYRILMAK İSTEDİĞİNE<br>EMİN MİSİN?",

"EVET, GİTMEK İSTİYORUM",

"<br>GÖRÜNTÜLENECEK<br>BİR ŞEY<br>YOK",

"JIMMY SENİ YAKALADI.<br><br>HER ŞEY SONA ERDİ.<br><br>AMA TEKRAR DENEYEBİLİRSİN...",

"OTELE DÖN<br><span style='font-size:50%'>SON KAYIT NOKTASINI AÇ</span>",

"OTELE GİR<br><span style='font-size:70%'>YENİ OYUNA BAŞLA</span>",

"NORMAL SEVİYEDE BAŞLA",

"EXTREME SEVİYEDE BAŞLA",

"<span style='font-size:75%'>OYUNU KAYDET</span>",

],

achtex:[

  "HİKAYE",
  "TAMAMLANDI",
  "HİÇ YAKALANMADIN",
  "JIMMY SENİ BİR DEFA YAKALADI",
  "JIMMY SENİ İKİ DEFA YAKALADI",
  "JIMMY TARAFINDAN TOPLAM YAKALANMA:",
  " ",
  "OTELİN GİZEMİNİ ÇÖZDÜN",
  "HİKAYE",
  "TAMAMLANDI",
  "",
  "",
  "",
  "BÜTÜN ARKADAŞLARINI KURTARDIN",
  "OTELDEN KAÇMANIN YOLUNU BULMALISIN",
  "OYUNU BİTİRDİN!",
  "GÖSTERİLECEK VERİ YOK",
  "OYUN VERİLERİ",
  "BAŞARIMLAR",
  "AMY'NİN HİKAYESİNİ TAMAMLADIN",
  "DR BOSE'UN HİKAYESİNİ TAMAMLADIN",
  "HARVEY'NİN HİKAYESİNİ TAMAMLADIN",
  "ROSE'UN HİKAYESİNİ TAMAMLADIN",
  "HİKAYEYİ BİTİRDİN",
  "HİKAYEYİ HİÇ YAKALANMADAN BİTİRDİN",
  "AT DEAD OF NIGHT'I BİTİRDİN",
  "KURTARMA MODUNDA HERKESİ KURTARDIN",
  "AT DEAD OF NIGHT'I HİÇ YAKALANMADAN BİTİRDİN!",
  "SEA VIEW OTELİNE DÖN",
  "ŞU AN İÇİN GÖSTERİLECEK BİR BAŞARIM YOK",
  "BİR RUH GÖRDÜĞÜNDE VEYA JIMMY TARAFINDAN YAKALANDIĞINDA OYUN OTOMATİK KAYIT EDİLİR",
  "HİKAYEYİ EXTREME SEVİYESİNDE BİTİRDİN",
  "HİKAYEYİ EXTREME SEVİYESİNDE HİÇ YAKALANMADAN BİTİRDİN!",
  "AT DEAD OF NIGHT'I EXTREME SEVİYESİNDE BİTİRDİN",
  "AT DEAD OF NIGHT'I EXTREME SEVİYESİNDE HİÇ YAKALANMADAN BİTİRDİN!",
  "BÜTÜN ARKADAŞLARINI KURTARDIN",

],

selx:[

  "CEVAP VERMEDİ",
  "BUNU HENÜZ SORMADIN!",
  "RUH İLE İLETİŞİME GEÇEREK SORU SOR",
  "EŞYALARA TIKLAYARAK RUHLARDAN BİLGİ AL",
  "KİLİTLİ KAPIYA BAKARAK ANAHTARI KULLANABİLİRSİN",
  "NEYİ SORACAĞINI SEÇ",
  "CEVAP VEREMEDİ",
  ":",
  "İYİ YOLCULUKLAR<br>YİNE BEKLERİZ",
  "OYUN KAYIT EDİLDİ",
  "ÖNCE BİR<br><br>OYUNA BAŞLAMALISIN",

],

numwo:[

  "KURTARILMAYI BEKLEYEN BİR ARKADAŞIN VAR",
  "KURTARILMAYI BEKLEYEN İKİ ARKADAŞIN VAR",
  "KURTARILMAYI BEKLEYEN ÜÇ ARKADAŞIN VAR",
  "KURTARILMAYI BEKLEYEN DÖRT ARKADAŞIN VAR",
  "KURTARILMAYI BEKLEYEN BEŞ ARKADAŞIN VAR",

],

numwa:[

  "DÖRT ARKADAŞINI KURTARDIN",
  "ÜÇ ARKADAŞINI KURTARDIN",
  "İKİ ARKADAŞINI KURTARDIN",
  "BİR ARKADAŞINI KURTARDIN",
  "HENÜZ KİMSE KURTARILMADI",

],

helx:"<span class='ht'>&#8679;S</span> OYUNU KAYDET | <span class='ht'>ESC</span> MENÜYÜ AÇ | <span class='ht'>D</span> MÜZİĞİ KIS | <span class='ht'>Q/W</span> SES AYARLARI<br><span class='ht'>&#8679;X</span> KAYIT ET & KAPAT | <span class='ht'>U/I</span> PARLAKLIK AYARI | <span class='ht'>O/P</span> KOYULUK AYARI | <span class='ht'>R</span> AYARLARI SIFIRLAMA",

resk:[

  "BEŞ FARKLI ODANIN<br><br>ANAHTARINI BULDUN<br><br><span style='font-size:50%'>BEŞ ARKADAŞINI BULUP KURTARMALISIN</span>",
  "UZAKLAŞMASINI<br><br>BEKLE<br><br>",
  "<span style='font-size:50%'>BÜTÜN ARKADAŞLARINI KURTARDIN</span>",
  "<span style='font-size:50%'>KURTARMAN GEREKEN BİR ARKADAŞIN DAHA VAR</span>",
  "<span style='font-size:50%'>KURTARMAN GEREKEN İKİ ARKADAŞIN DAHA VAR</span>",
  "<span style='font-size:50%'>KURTARMAN GEREKEN ÜÇ ARKADAŞIN DAHA VAR</span>",
  "<span style='font-size:50%'>KURTARMAN GEREKEN DÖRT ARKADAŞIN DAHA VAR</span>",

],

ityptex:[

  "BÜTÜN ÖGELER",
  "BULUNAN EŞYALAR",
  "GÖRDÜKLERİN",
  "BAĞLANTILAR",
  "ANAHTARLAR"

],

intros:[

  "Bulduğun cihaz burada. Üzerine tıklayarak çalıştır.",
  "Eğer ruhlara yeterince yakınsan, bu cihaz ile onları duyabilirsin.",
  "Detaylı bilgi için ana menüde yer alan 'Eğitim Videoları' bölümüne bak.",
  "Bu cihaz, ruhları tespit eder. Onlara yeterince yaklaşarak sesli iletişime geçebilirsin.",

  "Detaylı bilgi için ana menüde yer alan 'Eğitim Videoları' bölümüne bak.",
  "Bulduğun eşyaları burada görebilirsin.",

  "Maya, ruhlara bu listede yer alan soruları sorabilir.",
  "Gördüğün ve yaşadığın olaylar bu listede yer alır.",

  "Maya, ruhlara bu listede yer alan soruları sorabilir.",
  "Ağlayan aynayı yalnızca simgesi belirdiğinde kullanabilirsin.",

  "Oda kapılarının önünde (içeride) ya da diğer güvenli alanlarda kullanılabilir.",
  "Gizemleri çözmek için aynayı kullanıp ipucu alabilirsin.",
  "Ayrıca anahtar ve diğer önemli eşyaları bulmanda da sana yardımcı olacaktır.",
  "Ağlayan aynayı yalnızca simgesi belirdiğinde kullanabilirsin.",

  "Oda kapılarının önünde (içeride) ya da diğer güvenli alanlarda kullanılabilir.",
  "Gizemleri çözmek için aynayı kullanıp ipucu alabilirsin.",
  "Ayrıca anahtar ve diğer önemli eşyaları bulmanda da sana yardımcı olacaktır.",
  "Pusula seni en yakınındaki ruha yönlendirir.",

  "Ruhlara gördüğün şeyleri sor.",

  "Ruhların verdikleri cevapları, fareyi simgelerin üzerinde tutarak da okuyabilirsin.",
  "Ruhların hikayelerini çözmek için bağlantılı iki soruyu birleştir.",

  "Daha hızlı sonuç almak için ruhların eşyalara ve gördüğün olaylara verdikleri cevapları birleştir.",
  "İletişimi kesen ruhlar başka bir yere gitmiş olabilirler.",

  "Pusulanın gösterdiği yönü, yanıp sönen ışıkları ve garip sesleri takip et.",
  "Soru sormaya başlayarak ruhlarla iletişime geç.",

  "Yakınında ruh yoksa cevap alamazsın.",
  "Eğer yüksek parazit sesi alıyorsan, ruhlar yüksek enerji akımı yayıyor demektir.",
  "Soru sormaya başlayarak ruhlarla iletişime geç.",

  "Yakınında ruh yoksa cevap alamazsın.",
  "Eğer yüksek parazit sesi alıyorsan, ruhlar yüksek enerji akımı yayıyor demektir.",
  "Jimmy Hall bulunduğun katta seni arıyor. Dikkatli ol!",

  "Envanterindeki anahtarları kullanmak için kapıya dön ve anahtarı seç.",

  "Kapılar yalnızca doğru anahtar ile açılabilir ve tekrar kilitlenebilir.",
  "Envanterindeki anahtarları kullanmak için kapıya dön ve anahtarı seç.",

  "Kapılar yalnızca doğru anahtar ile açılabilir ve tekrar kilitlenebilir.",
  "Oyun burada son defa kayıt edildi.",

  "Arkadaşlarını kurtarmalısın...<br>Ancak Jimmy seni yakalarsa her şey biter!",
  "Son kişi kurtarıldı.<br>Çıkışı bul ve kaç!",

  "Onları kurtarmak için bulundukları odalara gir",

],

substan:[

  "Bilmiyorum.",
  "Belki.",
  "Hayır",
  "ANLAŞILMAYAN<br>SESLER/",

],

subrepa:[
[
  "Merhaba?",
  "Merhaba",
  "Merhaba.",
  "Merhaba",
  "Merhaba.",
  "Merhaba"
],[
  "Merhaba?",
  "Merhaba?",
  "Merhaba?",
  "Merhaba?"
],[
  "Merhaba?",
  "Seni duyabiliyorum.",
  "Seni duyabiliyorum.",
  "Seni duyabiliyorum."
],[
  "Merhaba?",
  "Seni duyabiliyorum.",
  "Merhaba?",
  "Seni duyabiliyorum.",
  "Seni duyabiliyorum."
],
],

subrepb:[
[
  "Adım Amy Bell. On yaşındayım.",
  "Evet, ben Amy.",
  "Evet benim, Amy.",
  "Evet, benim.",
  "Evet, ben Amy.",
  "Evet. Ben Amy.",
  "Evet, ben Amy.",
  "Evet, benim."
],[
  "Doktor Bose. Ben bir psikiyatristim.",
  "Evet, ben Doktor Bose.",
  "Ben Doktor Bose.",
  "Evet. Ben Doktor Bose.",
  "Evet.",
  "Evet benim.",
  "Ben Doktor Bose, evet."
],[
  "Harvey. Mekanın işletmecisiyim.",
  "Evet.",
  "Evet ben Harvey.",
  "Evet. Ben Harvey.",
  "Evet. Ben Harvey.",
  "Evet ben Harvey."
],[
  "Rose, Rose Hall. Burası benim otelim.",
  "Evet.",
  "Evet. Ben Rose.",
  "Evet.",
  "Evet, ben Rose.",
  "Evet.",
  "Evet. Ben Rose."
],
],

subcall:[

  "JIMMY?",
  "HEY!",
  "BURADAYIM!",
  "BURADAYIM!",
  "BU TARAFA!",

],

subin:[

  "Orada kimse var mı?",
  "Kimse var mı?",
  "Kimse var mı?",
  "Orada kimse var mı?",
  "Orada kimse var mı?",
  "Orada kimse var mı?",
  "Kim var orada?",
  "Merhaba?",
  "Merhaba?",
  "Orada kimse var mı?",
  "Orada kimse var mı?",

],

subnm:[

  "Amy, bu sen misin?",
  "Dr&#160;Bose, bu sen misin?",
  "Harvey, bu sen misin?",
  "Rose, bu sen misin?",
  "Adın ne?",

],

subrepc:[

  ["H","Rose'a ait, ama hiç kullanamadı.","R","Bana aittiler. Buradan gitmek istedim, ama fırsatım olmadı."],
  ["R","Kendisini ödül kazanmış biri gibi göstermek için Jimmy onları satın aldı."],
  ["A","O benimdi. Doğum günümde alınmış bir hediyeydi, ama çalındı.","H","Küçük kıza aitti, zavallıcık.","R","O, küçük kıza aitti."],
  ["A","Jimmy onları bana gösterene kadar ne olduklarını bilmiyordum.","P","Jimmy'e sorsan daha iyi olur.","H","Onlar benim eşyalarım, ama onları hiç beraber bulundurmazdım.","R","Bilmiyorum. Onlar Harvey'nin."],
  ["A","O Jimmy'nin. Hiç sevmedim.","P","Jimmy'nin onunla oynadığını gördüm. Ona tehlikeli olduğunu söyledim.","H","Orta çağ silahlarını içeren bir sergimiz vardı. Sonra Jimmy onu çaldı","R","Sahip olduğumuz zırh takımına aitti. Sonra kayboldu."],
  ["A","Bilmiyorum, ama çocuklar alkol almamalı.","P","Muhtemelen bardan alındılar.","H","Hatırlamıyorum, ama biraz alkol almanın sakıncası olmaz.","R","Onları oraya Harvey koymuş olmalı."],
  ["A","Onları çocuk çiziyordu.","P","Onları Jimmy çiziyormuş.","H","Bil bakalım kim? Jimmy! Küçük Jimmy'nin şiddete meraklı bir hayal gücü vardı.","R","Jimmy de tıpkı diğer erkek çocukları gibi savaş resimleri çizerdi."],
  ["P","Onu Jimmy buldu, sonra takmaya başladı.","H","Aşçı şefimizin şapkasıydı! Başka kim aşçı şapkası takar ki?","R","Onu şefimiz takardı."],
  ["A","O benim olabilir.","P","Benimdi. Delile ihtiyacım olur diye saklıyordum.","H","Bilmiyorum, ama doktorla bir alakası olabilir."],
  ["P","Bazı insanlarda davranış bozukluklarını tedavi etmek için kullanılabilir.","H","Onu muhtemelen doktor bıraktı.","R","Doktor Bose'a aitti."],
  ["P","Bilmiyorum, ama onu Jimmy buldu.","H","Resepsiyon masasının altındaydı. Nereden geldiğini bilmiyorum.","R","O kocama aitti."],
  ["A","Jimmy yaptı. Nedenini bilmiyorum. Tuhaftı.","P","Jimmy'nin eseri, bir uyarıydı. Bunun olacağını tahmin etmeliydim.","H","Jimmy, tacizci öğretmenler ve doktorlarla ilgili haberleri keserdi. O normal bir çocuk değildi.","R","Harvey, Jimmy'nin karalama defterinden bahsetmişti. Ama tam hatırlamıyorum."],
  ["P","Bir deney için onları birbirine bağladım."],
  ["H","Elektrik kaçağı vardı. Polislerin kontrol etmesi için tutuyordum.","R","Harvey onu kaldırdı. Tehlikeli olduğunu söyledi."],
  ["A","Bilmiyorum. Çocuk onlarla oynardı.","P","Onları Harvey elinde bulunduruyordu. Nedenini bilmiyorum.","H","Onları bir gün lazım olur diye tutuyordum.","R","Onlar kocama aitti, öğretmen olduğu zamanlardan kalma."],
  ["A","Otelde dolabın içinde olduklarını gördüm.","P","Otelde eski silahlar sergisi vardı.","H","Eski silahlar sergimizde duruyordu. Jimmy oradan almış.","R","Harvey onu sergilerdi. Ama otelde bulunmasını sevmezdim."],
  ["H","Onlar eski kazan dairesinin.","R","Onlar kazan dairesinindi. Ama sonra kapıyı değiştirdik."],
  ["P","O olayı hiç duymadım.","H","Evet, kontrol altına almayı başardılar, ama çok eşyamızı kaybettik.","R","Evet. Ama fazla yayılmadan durumu fark ettik."],
  ["P","Harvey'nin. Otelde olmasını sevmediğim bir şey.","H","Benimdi. Daha önce de babamındı. İçinde hala birkaç mermi vardır.","R","Harvey'nin. Ama yatak odasında tutardı."],
  ["A","Onu Jimmy bana göstermişti. Ama ona ait değilmiş.","H","O bir hançer değil, mektup açacağı. Keskin olmaması gerekiyordu.","R","O bir mektup açacağı. Birinden hediye olarak geldi."],
  ["R","O, Jimmy'nin komedi gösterisi."],
  ["P","Onları görmedim.","H","Hatırlamıyorum.","R","Onları Jimmy kırdı."],
  ["A","Jimmy onu yanında taşırdı","P","Jimmy'e ait. Sürekli cebinde taşırdı. Neyde kullandığını hiç söylemedi.","H","Jimmy eskiden onu yanında taşırdı. Nedenini bilmiyorum.","R","Jimmy yanında tel taşırdı. Elektronik şeylerle oynamayı severdi."],
  ["R","Jimmy yazdı."],
  ["H","Muhtemelen Rose'a ait.","R","Benimdi. Birisi bana reddedemeyeceğim bir teklif yapmıştı."],
  ["A","Bilmiyorum. Ben bebek görmedim.","R","Bebek içindi. Yatağımın baş ucundaki çekmecede tutardım."],
  ["R","Jimmy, Hugo’nun oğlu. Hem de her yönüyle."],
  ["A","Bendim - Jimmy adındaki çocuk beni bodruma kilitledi. Sonra eşyalarımı çalmaya başladı.","P","Otele gelen misafirlerden birinin kızıymış. Jimmy ona iyi davranmamış.","H","Kız, ailesiyle otelde kalıyordu.","R","Kız otelin misafiriydi."],
  ["A","Çünkü bunun komik olduğunu düşünüyordu. Sonra geri verdi, ama çoktan mahvolmuştu.","P","Bilmiyorum, bu onun hep yaptığı bir şeymiş.","H","Kim bilir. Muhtemelen komik olduğunu düşünüyordu.","R","Yapmadı. Kız yalan söylüyordu. Jimmy hiçbir şey çalmadı."],
  ["A","Elim yandı, canım çok acıdı, ama kimseye söyleyemedim.","P","Kız fena yanmış, ama Jimmy bunu bir şaka olarak görüyordu.","H","Kız yanmıştı, hem de fena şekilde.","R","Kız yanmıştı, ancak tehlikeli şeyler yapmaya devam ediyordu. Garip bir kızdı."],
  ["A","Doktor bulmaya çalışıyordum, ama Jimmy orada kalmam için beni tehdit etti.","H","Kız herhalde Jimmy'den korkuyordu.","R","Bilmiyorum, nedeni her şey olabilir. Tuhaf bir kızdı."],
  ["A","Çocuk, onun bir ilaç olduğunu söyledi. Tadı korkunçtu.","P","O sırada orada değildim, ama sanırım kız alkol içmiş."],
  ["A","Kendimi çok hafif hissettim, En alt kata atlayabileceğimi sanmıştım.","P","Jimmy, kıza çok alkol içirmiş.","H","Kız bir şişe viski içmiş, ne yaptığını bilmiyordu.","R","Bilmem, bu konuda çok bilgim yok."],
  ["A","Atladım, ama sonra her şey karardı ve bir daha uyanamadım. Artık uyanamıyorum. Neredeyim bilmiyorum.","P","Kız en üst kattan düşmüş. Ne yaptığını anlamayacak kadar sarhoşmuş. Bu yüzden Rose benimle iletişime geçti.","H","Kız en üst kattaki merdivenlerden düştü. İşin arkasında Jimmy'nin olduğunu biliyordum.","R","Kız kendi düştü. Harvey ise Jimmy'i suçladı. Bu kızın suçuydu, Jimmy'nin değil."],
  ["P","Bendim - Jimmy'nin annesi Rose, beni aradı. Benden Jimmy ile konuşmamı ve onu rahatsız eden şeyi bulmamı istedi. Ancak Harvey, Jimmy'nin hayal gücünden endişeliydi.","H","O, Doktor Bose'tu. Sözde Jimmy'e yardım etmek için geldi, ama Jimmy'nin durumu yardımlık olmaktan çıkmıştı.","R","Doktor Bose. Jimmy'e yardım etmek için geldi."],
  ["P","Jimmy'nin öldürme huyu vardı. Kuşlar, küçük hayvanlar. Empati kurma üzerine çalışmamız gerektiğini düşündüm. Bu yüzden ondan benim için yapabileceği güzel bir şey düşünmesini istedim. Beni şaşırttı, hemen aklına bir fikir geldi.","H","Jimmy onu bir yerde bulduğunu söylemişti. Ama onunla ne yaptığı bambaşka bir hikaye.","R","Harvey, Jimmy'nin tavşan öldürmüş olabileceğini söyledi, ama ona inanmadım."],
  ["P","Jimmy bana sandviç yapmıştı. Ondan istediğim gibi odama getirmişti. Başlangıçta hiçbir şeyden şüphelenmemiştim.","H","Doktor, Jimmy'i yola sokmaya, yardım etmeye çalışıyordu. Ne büyük bir hata.","R","Doktor Bose, Jimmy'e istemediği şeyleri yaptırmaya çalışıyordu."],
  ["P","Jimmy sandviçimin içine cam koymuş. Neredeyse boğuluyordum. Polise gidebilmek için bezi ve camı sakladım, ama Jimmy'nin hastalığını hafife aldığımı fark ettim. Acilen tedavisini hızlandırmak zorundaydım.","H","Jimmy'i zor yoldan tanıdı. Jimmy'nin şakaları her zaman fazla ileri gider.","R","Kendisini kesti. Ancak suçu Jimmy'e atmak istedi. Bunu kendisine o yaptı, Jimmy değil."],
  ["P","Jimmy aşı yapmama izin vermedi. Onu otelde kovalamak zorunda kaldım. Sonra da Rose'a onu aşı yapmaya zorladığımı ve şiddet uyguladığımı söyledi. Bu çok saçmaydı!","H","Bilmiyorum, orada değildim.","R","Benim iznim olmadan Jimmy'e ilaç vermeye çalıştı."],
  ["P","Rose'un Jimmy'e inanmasından endişe ediyordum. Bariz yalan söylüyordu. Ama bütün bunları Jimmy'nin uydurduğuna dair Rose'u ikna ettim.","H","Jimmy'nin onun hakkında hikayeler uydurmasından endişeleniyordu. Ve endişelenmekte de haklıydı.","R","Çünkü itibarının zedelenmesinden endişe ediyordu. Kime inanacağımı bilemedim. Ama ona bir şans daha vermeye karar verdim."],
  ["P","Yalanları ortaya çıkınca Jimmy'nin benimle iletişime geçeceğini ve istediklerimi yapacağını düşünmüştüm. Ancak o bunun yerine yeni yalan uydurdu. Ama bu seferki kötüydü. Çok kötüydü.","R","Jimmy ile konuşarak onu kontrol altına almaya çalşıyordu. Ona kötü şeyler yaptıracaktı. Ona hiç güvenmemeliydim."],
  ["P","Rose beni ihbar etti. Beni tutuklayacaklarını biliyordum. Kariyerim, geleceğim bitmişti. Her şeyi bitirmeyi göze almıştım.","H","Onu tutuklayacaklardı. Jimmy adamın hayatını mahvetmişti. Ama bunların hiçbirine inanamadım.","R","Onu tutuklamaya gelmişlerdi. Başına gelen her şeyi hak etmişti."],
  ["P","Canıma tak etmişti. Buradan geri dönüş yoktu. Hayatım zaten mahvolmuştu.","H","Kafayı yemişti. Herkes onun Jimmy'e 'el sürdüğünü' düşünüyordu. Jimmy çok akıllıydı, hem de çok. Doktorun başka seçeneği yoktu. Zavallı adam.","R","Suçlu olduğunu biliyordu. Doğru olanı yaptı."],
  ["P","O Harvey'di. Jimmy'nin hakkımda söylediklerinin yalan olduğunu biliyordu. Anlamıştı.","H","Bendim. Jimmy, doktor hakkında hikayeler uydurdu. Rose da ona inandı, ama ben bu hikayeyi daha önce de duymuştum.","R","Harvey'di. Jimmy'nin dediklerine inanmıyordu. Ama ben onun yalan söylemediğini biliyordum."],
  ["P","Jimmy yalanlarını asla itiraf etmedi.","H","Tabii ki hayır! Sadece güldü. Sonrasında bana 'küçük' tuzaklar kurmaya başladı. Bazıları o kadar küçük değildi.","R","Hayır. Jimmy gerçek olmayan bir şeyi nasıl itiraf edebilirdi ki? Harvey'nin Jimmy'e zorbalık taslaması hiç doğru değildi."],
  ["H","Onun benim ısıtıcım olduğunu biliyordu, cihazı doğruca ana şebekeye bağlamış. Beni neredeyse öldürüyordu. Bilerek yapmıştı ama Rose anlamıyordu. Ona bir ders verilmesi gerekiyordu. O benim eşyalarıma zarar verdi, ben de onun eşyalarını kırmaya karar verdim.","R","Harvey, Jimmy'i suçladı, ama o ısıtıcı zaten arızalıydı. Harvey'nin onu çöpe atması gerekiyordu."],
  ["P","Bilmiyorum, ama şiddet bu tür durumları daha kötüleştirir.","H","Onun televizyonunu ve oyun konsolunu kırdım. Sinirliydim ama bir şey değişmedi, işler daha da kötüye gitti. Sonrasında bana karşılık vermeye başladı.","R","Jimmy'nin eşyalarını kırmıştı. Öfkesini kontrol edemiyordu."],
  ["H","Kapıyı açtığım sırada Jimmy arbalet ile ateş etti. Acile gidip, yarama dikiş attırmam ve tetenoz aşısı olmam gerekti. Geri döndüğümde onu bulamadım. Rose, onun bodrumda saklandığını söyledi. Bu da bana bir fikir verdi.","R","Harvey bana Jimmy'nin kendisini ok ile vurduğunu söyledi, ama Jimmy'nin öyle bir silahı kullanamayacağını biliyordum."],
  ["H","Jimmy'e kendi ilacından tattırmak istedim. Orada bir hasara sebep olamayacağını düşünmüştüm. Yanılmışım.","R","Ne yaptığını bilmiyordum."],
  ["P","Hatırlamıyorum.","H","Yangını çok yayılmadan kontrol altına almayı başardık. Ama eski fotoğraflarımız ve mektuplarımız oradaydı, hepsi kül oldu. Jimmy zıvanadan çıkmıştı, Benim de canıma tak etti. Onun gitmesini istiyordum.","R","Harvey, Jimmy'i suçladı, ama yangına kaçak sebep oldu. Bu bir kazaydı."],
  ["P","Bilmiyorum. Ama Harvey öfkesini kontrol edemiyordu.","H","Ne yapacağımı bilmiyordum. Onu otelden ayrılması için tehdit edecektim. Sorun şu ki; onun da silahlı olacağını tahmin edemedim.","R","Bilmiyorum. Harvey'nin otelde silah bulundurmaması gerekiyordu."],
  ["H","Jimmy'i arıyordum."],
  ["H","Jimmy arkamda belirdi, geldiğini göremedim. Jimmy her zaman son kazanan oldu.","R","Harvey delirmişti. Jimmy sadece kendisini korudu."],
  ["H","Rose - Rose, Jimmy'e inandı. En başından beri onu savundu.","R","O bendim. Polislere hançerin aslında bir mektup açacağı olduğunu ve Harvey'nin dolu silah taşıdığını açıklamalıydım. Jimmy sadece nefsi müdafaa yaptı. Polisler durumu anladı."],
  ["H","Jimmy - Jimmy'i serbest bıraktılar. Jimmy'i vurmaya çalıştığımı düşündükleri için bunun nefsi müdafaa olduğunu düşündüler. Ama hepsi yalandı.","R","Jimmy eve dönmüştü. Polisler durumu anladı. Ona inandılar, ama bu olay onu değiştirdi. Bana, oteli işletmemde yardım etmeye başladı. Ve otele daha fazla ziyaretçi çekmenin yolunu buldu."],
  ["H","Kim olduğunu bilmiyorum.","R","İzlemek hoşuma gidiyordu ve tekrar para kazanmaya başlamıştık. Her şey iyiye gidiyordu. Sonra Jimmy tuhaf davranmaya başladı. Kendisine bakıp bağırdığına şahit oldum. Sinirli görünüyordu."],
  ["R","Jimmy, başlangıçta anlamamıştım, kafam karışmıştı. Ama sonra anladım ki bunları yapan Jimmy değildi. O da tıpkı aynalar gibi kırılmaya başladı. Jimmy artık kontrolden çıkmıştı."],
  ["H","Bilmiyorum, ama Jimmy en sonunda her şeyi berbat etmiştir.","R","Bu artık Jimmy'nin değil, Hugo Punch'ın sahnesiydi. Hugo her akşam izleyicilere hakaret etmeye başladı. Bundan da hoşlanıyor gibi görünüyordu. Sonra bir akşam konuklardan biri Jimmy'e onun hakkında ne düşündüğünü söyledi. Jimmy de öfkesine yenik düştü ve aptalca bir şey yaptı."],
  ["R","Gazeteciler, Jimmy'i görmek istiyorlardı. Ama Jimmy artık kontrolden çıkmıştı, Kadını bağlayan Hugo Punch'tı. Jimmy kendisini kontrol altına alamıyordu. Depresyondaydı. Her şeyi geride bırakıp gitmek istiyordu."],
  ["R","Jimmy'di. İntihar etmeye çalıştı. Bu yüzden ona gerçeği söylemek zorundaydım."],
  ["H","Bilmiyorum. Rose'un bana söylemediği şeyler var.","R","Hugo'yu bodrumdaki gizli odaya gömdüm, üzerine de beton döktüm. Bunu daha önce yapmalıydım. Çok uzun süre boyunca Jimmy'i istismar etmesine göz yumdum. Jimmy'nin bu hale gelmesi benim suçumdu. Eğer Jimmy'e gerçekleri anlatırsam pişmanlıktan kurtulacağımı sanmıştım. Yanılmışım, her şey daha kötü bir hale geldi. Yaptıklarımı kabul edemedim. Bununla yaşayamazdım."],
  ["R","Eğer kendimi öldürmeseydim Jimmy, yani Hugo öldürecekti. Şu anda bile kontrol Hugo'da. Jimmy'i kontrol ediyor. Hugo'nun nerede yaşadığını Jimmy'e sor."],
  ["H","Onunla hiç tanışmadım.","R","O bir sihirbaz ve şovmendi. Oteli kendi şovunu tanıtmak için satın almıştı. Ünlü oldu, televizyona çıktı. O zamanlar asistanıydım, sonra işler gelişti."],
  ["R","Ne istediğini hiçbir zaman bilemedim. Ona verebileceğim tek şey vardı."],
  ["R","Hugo şiddete meraklı, kötü, hasta ruhlu bir adamdı."],
  ["A","Evet, bakmadığım bir sırada onu çaldı. Ona gitmesini söyledim ama beni dinlemedi."],
  ["A","Şişedeki şey ile oyuncağımı ıslattı, ondan nefret ettim!"],
  ["A","Evet - onu duvardan aldı, çok keskin görünüyordu. Eğer kimseye söylemeyeceğime söz verirsem elimin acısını durduracağını söyledi."],
  ["A","Galiba - içmeye devam etmemi söyledi. Tadı korkunçtu. Ardından kendimi tuhaf hissetmeye başladım."],
  ["P","Evet, bu sıkıntılı bir kişiliğin belirtisiydi, ama onun ne denli ileri gidebileceğini gördüğümde endişelenmeye başladım."],
  ["P","Evet - Jimmy benim için bir şeyler hazırlayacağını söyledi, ben de neler olduğunu anlamak için onu takip ettim."],
  ["P","Jimmy'nin espri anlayışı ile böyle tanıştım."],
  ["P","Bu iş için uygun ilaç değildi, ama elimde olan tek şeydi. Jimmy'nin acil tedaviye ihtiyacı vardı, tehlike arz ediyordu."],
  ["P","Jimmy onu kürekle dövdüğümü söyledi. Hastalarıma karşı asla şiddet uygulamadım, bu bir saçmalıktı! Ama Rose ona inandı."],
  ["P","Jimmy beni olabilecek en kötü şeyle suçladı. Bu fikri okuduğu gazete haberinden aldı. Her şeyi o uydurdu."],
  ["P","Çamaşır ipini denedim ama çok inceydi. Sonra biraz ip buldum. Otelin anahtarları hala bendeydi, kefaletle dışarı çıktıktan sonra gizlice içeri girdim."],
  ["H","Onun elinden çıktı! Çizim defterini bulduğum anda Jimmy'nin hikayeyi nereden uydurduğunu anladım. Her şey, her detayıyla bire bir aynıydı."],
  ["H","Jimmy her zaman elektrikle oynardı. Hiç akıma yakalanmamış olması ilginç."],
  ["H","Sopaları kendimi korumam gerekirse diye tutuyordum, ama öfkelenmiştim. Birini yanıma aldım ve Jimmy'nin odasına gittim."],
  ["H","Jimmy bu tür silahlar bulmuş. Eşyalarını kırdıktan sonra onu bir süre görmedim. Bir sonraki numarasına hazırlık yaptığını tahmin etmeliydim."],
  ["H","Eğer Jimmy bodrumda saklanmak istediyse, bunun hoşuna gideceğini düşünmüştüm."],
  ["H","Jimmy'nin ilgi çekmek için ne kadar ileri gidebileceğini kimse tahmin edemez."],
  ["H","Kendimi kaybettim. Her şeyi kırmızı görmeye başladım, ondan nefret ettim. Kontrolümü kaybetmiştim."],
  ["H","O bir hançer bile değildi! Ama demek ki dersimi hiç öğrenememişim, Jimmy her zaman benden bir adım öndeydi."],
  ["R","Evet - Jimmy sahneye çıkıp komedi yapıyordu. Bu işte de iyiydi, gerçekten iyi. İnsanlar sırf onu izlemek için geliyordu."],
  ["R","Aynaları kırması işin başlangıcıydı. Ona ne olduğunu sordum, ama yaptıklarını hatırlamıyordu. Sonra diğer tuhaf şeyler yaşanmaya başlandı."],
  ["R","Jimmy, kadını odaya kapatıp, bağladı. Ne olduğunu bilmiyordum. Onu buldum ve kurtulmasını sağladım. Jimmy bunun bir şaka olduğunu söyledi! Kadın bizden şikayetçi olmadı, ama olanları gazetecilere söylemiş."],
  ["R","Jimmy yaptıklarından nefret ediyordu. Hayatı boyunca Hugo Punch ile kavga içindeydi. Ona bütün bu kötü şeyleri yaptıran oydu. Jimmy artık yaşamak istemiyordu."],
  ["R","Evet - evlendik. Başlangıçta mutluyduk, sonra her şey değişti."],
  ["R","Bir çocuğumuz olduğunda bütün sorunlarımızın çözüleceğini sanmıştım. Yanılmışım."],
  ["R","Her şeyi Jimmy'e anlattım. Jimmy, Hugo'yu hafızasından silmiş, onu hatırlamıyordu. Hugo, Jimmy'i iki yaşına kadar dövdü. Onu daha önce durdurmalıydım."],
  ["R","Başka seçeneğim yoktu. Jimmy, Hugo'nun mezarını bulmaya gitmişti. Ben de yalnızdım. Ne yapmam gerektiğini biliyordum."],

],

subob:[

  ["Dolap içinde birkaç valiz buldum. Onlar kimin?",
  "bunun valizlerle bir alakası var mı?"],

  ["Birkaç kupa buldum. Onlar kimin?",
  "bunun kupalarla bir alakası var mı?"],

  ["Çocuk cüzdanının sahibi kim?",
  "bunun cüzdanla bir alakası var mı?"],

  ["Bir şişe terebentin ve çakmak buldum. Bunlar ne için orada?",
  "bunun terebentin ve çakmak ile bir alakası var mı?"],

  ["Kılıcın sahibi kim?",
  "bunun kılıçla bir alakası var mı?"],

  ["Neden odaların birinde viski şişeleri var?",
  "bunun viski şişeleri ile bir ilişkisi var mı?"],

  ["Bu korkunç resimleri kim çizdi?",
  "bunun çizimlerle bir alakası var mı?"],

  ["Aşçı şapkası kimin?",
  "bunun aşçı şapkası bir alakası var mı?"],

  ["Neden çekmecelerin birinde kanlı bir kumaş var?",
  "bunun kanlı kumaşla bir alakası var mı?"],

  ["Diazepam şişesinin orada ne işi var?",
  "bunun Diazepam ile bir alakası var mı?"],

  ["Tahta kürek nereden geldi?",
  "bunun tahta kürekle bir alakası var mı?"],

  ["İçinde gazete manşetleri olan bir karalama defteri gördüm. Bunu kim yaptı?",
  "bunun karalama defteri bir alakası var mı?"],

  ["Oklavanın etrafına neden çamaşır ipi bağlı?",
  "bunun oklava ve çamaşır ipi ile bir alakası var mı?"],

  ["Bu ısıtıcının üzerinde neden 'tehlikeli' yazıyor?",
  "bunun tehlikeli ısıtıcı ile bir alakası var mı?"],

  ["Burada neden kriket ve beyzbol sopaları var?",
  "bunun kriket ve beyzbol sopalarıyla bir alakası var mı?"],

  ["Arbaletin burada ne işi var?",
  "bunun arbalet ile bir alakası var mı?"],

  ["Bu paslı anahtarlar nereye ait?",
  "bunun paslı anahtarlarla bir alakası var mı?"],

  ["Otelde yangın mı çıktı?",
  "bunun otel yangınıyla bir alakası var mı?"],

  ["Bu silah kime ait?",
  "bunun silahla bir alakası var mı?"],

  ["Hançerin sahibi kim?",
  "bunun hançer ile bir alakası var mı?"],

  ["Hugo Punch kim?",
  "bunun Hugo Punch posteri ile bir alakası var mı?"],

  ["Bu aynalar nasıl kırıldı?",
  "bunun kırık aynalarla bir alakası var mı?"],

  ["Tel bobin ne için kullanıldı?",
  "bunun tel bobin ile bir alakası var mı?"],

  ["Üzerinde 'elveda' yazılı notu kim yazdı?",
  "bunun elveda notu ile bir alakası var mı?"],

  ["Bu nişan yüzüğü kime ait?",
  "bunun nişan yüzüğü ile bir alakası var mı?"],

  ["Bebek çıngırağının sahibi kim?",
  "bunun çıngırak ile bir alakası var mı?"],

  ["Jimmy'nin doğum belgesini buldum. Üzerinde Jimmy'nin babasının adının Hugo Hall olduğu yazıyor.",
  "bunun Jimmy'nin doğum belgesi ile bir alakası var mı?"],

  ["Bodrumda ağlayan bir kız gördüm. O kimdi?",
  "",
  "Jimmy'nin eşyalarını çaldığını söyledin,",
  "Jimmy'nin küçük kıza kaba davrandığını söyledin,",
  "Bana otelde küçük bir kızın kaldığını söyledin,",
  "Otelde misafir olan küçük bir kızdan bahsettin,"],

  ["Küçük kızı Jimmy'e oyuncağını geri vermesi için bağırırken gördüm. Onu neden almıştı?",
  "Jimmy'e oyuncağını geri vermesi için bağırırken gördüm. Bunu neden yaptı?",
  "Jimmy'nin oyuncağını çaldığını söyledin,",
  "Jimmy'nin eşya çalma huyu olduğunu söyledin,",
  "",
  "Jimmy'nin eşya çalmadığını söyledin,"],

  ["Küçük bir kız olan Amy'nin yanan bir oyuncak tuttuğunu gördüm. Orada ne oldu?",
  "Yanan bir oyuncak tuttuğunu gördüm. Orada ne oldu?",
  "Elinin yandığını kimseye söyleyemediğinden bahsettin,",
  "Jimmy, Amy'nin oyuncağını şaka amaçlı yaktığını söyledin,",
  "Küçük kızın kötü biçimde yandığını söyledin,",
  "Küçük kızın tehlikeli şeyler yapıp, Jimmy'yi suçlamaya devam ettiğini söyledin,"],

  ["Amy'i oda dışında gördüm. Bir şey onu çok korkutmuş. Neydi o?",
  "Seni odanın dışında gördüm. Bir şey seni çok korkutmuş. Neydi o?",
  "Doktor bulmaya çalıştığını ancak Jimmy'nin seni tehdit ettiğini söyledin,",
  "",
  "Küçük kızın Jimmy'den korkmuş olabileceğini söyledin,",
  "Küçük kızla ilgili bir şeyin yanlış olduğunu söyledin,"],

  ["Amy'i bir şey içerken gördüm. Pek hoşlanmışa benzemiyordu. Ne içti?",
  "Seni bir şey içerken gördüm. Pek hoşlanmış görünmüyordun. Ne içtin?",
  "İlacın tadının kötü olduğunu söyledin,",
  "Amy'nin alkol içtiğini söyledin,",
  "",
  ""],

  ["Küçük kızı merdivenlerde, korkuluğun başında gördüm. Ne yapıyordu?",
  "Seni merdivenlerde, korkuluğun başında gördüm. Ne yapıyordun?",
  "Merdivenlerden atlayabileceğini söyledin,",
  "Jimmy'nin küçük kıza çok fazla alkol içirdiğini söyledin,",
  "Amy'nin viski içerek sarhoş olduğunu söyledin,",
  ""],

  ["Amy'i merdivenlerin başında hareketsiz yatarken gördüm. Ona ne oldu?",
  "Seni yerde hareketsiz yatarken gördüm. Ne oldu?",
  "Artık uyanamadığını söyledin,",
  "Amy'nin ölümünün ardından Rose'un seninle iletişime geçtiğini söyledin,",
  "Amy'nin ölümünün arkasında Jimmy olduğunu söyledin,",
  "Amy'nin ölümünün kendi suçu olduğunu söyledin,"],

  ["Kapıyı çalan birini gördüm, Jimmy'e yardım etmek için geldiğini söylüyordu. O kimdi?",
  "",
  "",
  "Harvey'nin Jimmy'nin akıl sağlığından endişe ettiğini söyledin,",
  "Jimmy'nin durumunun vahim olduğunu söyledin,",
  "Dr Bose'un Jimmy'e yardım etmek için geldiğini söyledin,"],

  ["Dr Bose'un tele bağlanmış bir hayvan ölüsü tuttuğunu gördüm. Orada ne oldu?",
  "Seni tele bağlı bir hayvan ölüsü tutarken gördüm. Orada ne oldu?",
  "",
  "Jimmy'nin senin için güzel bir şey yapma fikrinin olduğunu söyledin,",
  "Jimmy'nin sana bir yerde hayvan ölüsü bulduğunu anlatmasından bahsettin,",
  "Jimmy'nin o hayvanı öldürmediğini inandığını söyledin,"],

  ["Dr Bose'u mutfağın dışında, Jimmy ile konuşurken gördüm. Orada ne yapıyordu?",
  "Seni mutfağın dışında Jimmy ile konuşurken gördüm. Orada ne yapıyordun?",
  "",
  "Hiçbir şeyden şüphelenmediğini söyledin,",
  "Dr Bose'un Jimmy'e yardım etmesinin hata olduğunu söyledin,",
  "Dr Bose'un Jimmy'e istemediği şeyler yaptırmaya çalıştığını söyledin,"],

  ["Dr Bose'un kan tükürdüğünü gördüm. Neler oldu?",
  "Seni kan tükürürken gördüm. Ne oldu?",
  "",
  "Jimmy'nin tedavisini hızlandırman gerektiğini söyledin,",
  "Jimmy'nin şakalarının hep ileri gittiğini söyledin,",
  "Dr Bose'un kendisini yaraladığını ve Jimmy'i suçladığını söyledin,"],

  ["Dr Bose'u elinde iğne Jimmy ile konuşurken gördüm. Ne yapıyordu?",
  "Seni elinde iğne Jimmy ile konuşurken gördüm. Ne yapıyordun?",
  "",
  "Jimmy'nin aşı olmak istemediğini söyledin,",
  "",
  "Dr Bose'un sizden izin almadan Jimmy'e aşı yapmaya çalıştığını söyledin."],

  ["Dr Bose'u, Jimmy ile yaşananları açıklamaya çalışırken gördüm. Çaresiz görünüyordu. ",
  "Seni Jimmy ile neler yaşandığını açıklamaya çalışırken gördüm. Çaresiz görünüyordun.",
  "",
  "Rose'u bütün bunları Jimmy'nin uydurduğuna ikna ettiğini söyledin,",
  "Dr Bose'un Jimmy'nin yalanlarından endişelenmesinde haklı olduğunu söyledin,",
  "Dr Bose'a bir şans daha verdiğini söyledin,"],

  ["Dr Bose'u yatağında oturmuş, Jimmy ile konuşurken gördüm. Ne yapıyordu?",
  "Seni yatağında oturmuş, Jimmy ile konuşurken gördüm. Ne yapıyordun?",
  "",
  "Jimmy'nin yeni bir yalan uydurduğunu ve bu seferkinin kötü olduğunu söyledin.",
  "",
  "Dr Bose'a hiç güvenmemen gerektiğini söyledin,"],

  ["Dr Bose'u üzgün gördüm, polisler kapısına vuruyordu. Neler oldu?",
  "Seni üzgün gördüm ve polisler kapıya vuruyordu. Neler oluyordu?",
  "",
  "Her şeyi bitirmeyi göze aldığını söyledin,",
  "Jimmy'nin Dr Bose ile olan hikayesine inanmadığını söyledin,",
  "Dr Bose'un tutuklanmayı hak ettiğini söyledin,"],

  ["Dr Bose'u boynuna ip geçirdiğini gördüm. İntihar etti. Neden?",
  "Seni boynunda bir iple gördüm. İntihar ettin. Neden?",
  "",
  "Her şeyin bitmesini istediğini söyledin,",
  "Dr Bose'un intihar etmeyi kafasına taktığını,",
  "Dr Bose'un doğru şeyi yaptığını söyledin,"],

  ["Jimmy'nin yalan söylediğinden bahseden birini gördüm. O kimdi?",
  "",
  "",
  "Harvey'nin Jimmy'nin yalan söylediğini bildiğini söyledin,",
  "Bu hikayeyi daha önce duyduğunu söyledin,",
  "Harvey'nin Jimmy'nin söylediklerine inanmamasının yanlış olduğunu söyledin,"],

  ["Harvey'i Jimmy'e yalanlarını itiraf etmesi için bağırırken gördüm. İtiraf etti mi?",
  "Seni Jimmy'e yalanlarını itiraf etmesi için bağırırken gördüm. İtiraf etti mi?",
  "",
  "Jimmy'nin yalanlarını asla itiraf etmediğini söyledin,",
  "Jimmy'nin sana tuzak kurmaya başladığını söyledin,",
  "Harvey'nin Jimmy'e zorbalık yapmasının yanlış olduğunu söyledin,"],

  ["Harvey'e elektrik çarptığını gördüm. Orada ne oldu?",
  "Sana elektrik çarptığını gördüm. Ne oldu?",
  "",
  "",
  "Onun eşyalarını kırmaya karar verdiğini söyledin,",
  "Harvey'nin arızalı ısıtıcıyı atması gerektiğini söyledin,"],

  ["Harvey'i elinde sopayla odadan çıktığını gördüm. Ne yaptı?",
  "Seni elinde bir sopayla odadan çıktığını gördüm. Ne yaptın?",
  "",
  "Şiddetin bu durumları daha da kötüye soktuğunu söyledin,",
  "Jimmy'nin karşılık verdiğini söyledin,",
  "Harvey'nin öfkesini kontrol edemediğini söyledin,"],

  ["Harvey'i bacağından okla vurulmuş halde gördüm. Neler oldu?",
  "Seni bacağından okla vurulmuş halde gördüm. Ne oldu?",
  "",
  "",
  "Jimmy'nin bodruma saklandığını söyledin,",
  "Jimmy'nin öyle bir silahı kullanamayacağını söyledin,"],

  ["Harvey'i Jimmy'i bodruma kilitlerken gördüm. Neler oldu?",
  "Seni Jimmy'i bodruma kilitlerken gördüm. Orada ne oldu?",
  "",
  "",
  "Jimmy'nin bodrumda zararsız olacağını düşünmekte hata yaptığını söyledin,",
  ""],

  ["Bodrumda yangın çıktığını gördüm. Otelde neler oldu?",
  "Bodrumda yangın çıktığını gördüm. Otelde neler oldu?",
  "",
  "",
  "Jimmy'nin gitmesini istediğini söyledin,",
  "Oteldeki yangının bir kaza olduğunu söyledin,"],

  ["Harvey'i elinde silahla gördüm, hazırlık yapıyordu. Ne yapmayı planlıyordu?",
  "Seni elinde silahla hazırlık yaparken gördüm. Ne yapacaktın?",
  "",
  "Harvey'nin öfkesini kontrol edemediğini söyledin,",
  "Jimmy'nin silahlı olacağını tahmin edemediğini söyledin,",
  "Harvey'nin otelde silah bulundurmaması gerektiğini söyledin,"],

  ["Harvey'i elinde silahla balo salonuna giderken gördüm. Ne yapacaktı?",
  "Seni elinde silahla balo salonuna giderken gördüm. Ne yapıyordun?",
  "",
  "",
  "Jimmy'i aradığını söyledin,",
  ""],

  ["Harvey'i sahne arkasında bıçaklandığını gördüm. Orada ne oldu?",
  "Sahne arkasında bıçaklandığını gördüm. Orada ne oldu?",
  "",
  "",
  "Jimmy'nin her zaman kazandığını söyledin,",
  "Jimmy'nin yalnızca kendisini koruduğunu söyledin,"],

  ["Bir bayanın mektup açacağının hançer olmadığını açıklarken gördüm. Kimdi o?",
  "",
  "",
  "",
  "Rose'un Jimmy'i en başından beri savunduğunu söyledin,",
  "Polislerin Jimmy'nin yalnızca nefsi müdafaa yaptığını anladığını söyledin"],

  ["Rose otelin girişinde kimi karşıladı?",
  "Otelin girişinde kimi karşıladı?",
  "",
  "",
  "Jimmy'i vurmaya çalıştığını düşündüklerini söyledin,",
  "Jimmy'nin daha fazla ziyaretçi çekmenin bir yolunu bulduğunu söyledin,"],

  ["Rose'un Hugo Punch'ı anons ederken gördüm.",
  "Seni sahneye Hugo Punch'ı anons ederken gördüm.",
  "",
  "",
  "",
  "Jimmy'nin kendisine sinirli baktığını söyledin,"],

  ["Rose'u mankenlerle dolu koridorda gördüm. Onları kim koydu?",
  "Seni mankenlerle dolu koridorda gördüm. Onları oraya kim koydu?",
  "",
  "",
  "",
  "Jimmy'nin kontrolünü kaybettiğini söyledin,"],

  ["Rose'u balo salonunda gördüm. Seyirciler yuhluyor ve Rose özür diliyordu. Neler oluyor?",
  "Seni balo salonunda gördüm. Seyirciler yuhluyor ve sen özür diliyordun. Neler oluyor?",
  "",
  "",
  "Jimmy'nin en sonunda her şeyi mahvettiğini söyledin,",
  "Jimmy'nin öfkesine yenik düştüğünü ve aptalca bir şey yaptığını söyledin,"],

  ["Rose'u üzgün gördüm ve insanlar kapıya vurup sorular soruyor. Kim onlar?",
  "Seni üzgün gördüm, insanlar da kapıya vurup sorular soruyordu. Onlar kim?",
  "",
  "",
  "",
  "Jimmy'nin her şeyi bırakıp gitmek istediğini söyledin,"],

  ["Rose'u yukarıdaki odaların birinde gördüm. Lavaboda birini görmüş gibi. Neler oldu?",
  "Seni yukarıdaki odaların birinde gördüm. Lavaboda birine bakıyordun. Neler oldu?",
  "",
  "",
  "",
  "Jimmy'e gerçeği söylemen gerektiğini söyledin,"],

  ["Rose'u birine sopayla saldırdığını gördüm. O kimdi?",
  "Birine sopayla saldırdığını gördüm. O kimdi?",
  "",
  "Rose'un kara geçmişi olduğunu söyledin,",
  "Rose'un senden sakladığı şeyler olduğunu söyledin,",
  "Bununla yaşayamayacağını söyledin,"],

  ["Rose'u gördüm, alevler içindeydi. Ne oldu?",
  "Seni gördüm, alevler içindeydin. Ne oldu?",
  "",
  "",
  "",
  "Jimmy'e Hugo'nun nerede yaşadığını sormamı söyledin,"],

  ["Sahnede kendisini 'Muhteşem Hugo' olarak tanıtan birisini gördüm.",
  "",
  "",
  "",
  "Hugo'nun Rose'un ilk kocası olduğunu söyledin,",
  "Hugo ile işleri ilerlettiğini söyledin,"],

  ["Bir adamın birine bağırdığını ve dediklerini yapmasını söylediğini duydum. O kimdi?",
  "",
  "",
  "",
  "",
  "Hugo'ya verebileceğin yalnızca bir şey olduğunu söyledin,"],

  ["Bir adamın bağırdığını ve çocuğun ağladığını duydum. Neler oldu?",
  "",
  "",
  "",
  "",
  "Jimmy'nin Hugo'nun olduğunu söyledin."],

],

subs:[

  "INTRO",[
   13.6,5,"Jimmy!",14.6,4,"",
   16.2,4,"Jimmy!",17.4,4,"",
   18.8,2,"Jimmy!",20,4,"",
   20.1,6,"HOPARLÖRDEN GELEN SES",21.6,6,"",
   24.3,3,"Beni yalnız bırakın!",25.9,4,"",
   26.5,6,"AĞLAMA SESLERİ",27.9,4,"",
   28.6,6,"YANKILANAN SESLER",30.3,4,"",
   30.7,3,"Kesin şunu!",31.8,4,"",
   32.4,3,"Lütfen, beni yalnız bırakın!",34.8,4,"",
   35.8,6,"PARAZİT SESLERİ",37.3,4,"",
   44.5,6,"TELEFON ÇALMA SESİ",45.6,0,"",
   46.6,1,"Alo?",47.6,0,"",
   47.7,3,"Maya? Ben Hannah.",48.8,0,"",
   49.4,1,"Hannah? Neredesiniz?",51.2,0,"",
   51.3,1,"Hepiniz beni geride bırakıp gittiniz!",53.6,0,"",
   53.7,1,"Şu an neredesiniz? Bu kimin numarası?",55.6,0,"",
   55.7,3,"Hepimiz yol üzerindeki otele kayıt yaptırdık.",57.4,0,"",
   57.5,3,"Ne kadar uzaktasın?",58.8,0,"",
   58.9,1,"Bilmem. Oraya vardığımda sizi ararım.",61.1,0,"",
   61.2,3,"Yapamazsın, burada telefonlar çekmiyor.",62.9,0,"",
   63,1,"Şey... ",64.1,1,"",
   65,1,"Neyse boş ver. Yatağına git, Hannah.",67,0,"",
   67.1,3,"Dinle. Buraya vardığında...",68.3,0,"",
   68.6,6,"SES KESİLİR",70.1,0,"",
   71,6,"TELEFONUN KAPANMA SESİ",72.5,0,"",
   84,6,"1950'LERİN JAZZ MUZİĞİ",85.5,4,"",
   92.1,3,"Sen Maya olmalısın.",94.1,0,"",
   94.5,3,"Telaşlanma.",96.4,0,"",
   96.6,3,"Arkadaşların kaydını yaptırdı.",99,0,"",
   99.1,3,"Bir bakayım.",100.8,0,"",
   101.8,3,"Evet...",102.8,0,"",
   102.9,3,"101 numaralı oda.",104,0,"",
   104.2,3,"Ödemesi yapılmış, hiçbir şey için endişelenmen gerekmiyor.",107.2,0,"",
   107.3,3,"İyi arkadaşların var.",109.1,0,"",
   109.9,3,"Çok hoş.",111.2,0,"",
   111.5,3,"Ve oldukça da kalabalıksınız gibi görünüyor.",115.6,0,"",
   116.2,3,"Sizler gibi yeni, genç yüzler...",118.2,0,"",
   118.3,3,"görmek ne güzel.",122.7,0,"",
   123.5,3,"Sanırım buraya müzik festivali için geldiniz.",126.8,0,"",
   127.3,1,"Evet, sözde bu gece kamp yapacaktık, ama...",130.5,0,"",
   130.6,3,"Hava buna pek müsaade etmedi!",133.1,0,"",
   136,3,"Kahvaltıya kalacak mısınız?",137.5,0,"",
   137.6,1,"Sanmıyorum, muhtemelen yola koyuluruz.",140.2,0,"",
   140.3,3,"Sorun yok. Ve sormamda bir sakınca yoksa Maya,",143.7,0,"",
   143.8,3,"bu akşamki gösteriyle ilgilenir misin?",147.5,0,"",
   147.9,1,"Bu akşam mı?",148.9,0,"",
   149,3,"Genelde gece yarısı başlar.",152.1,0,"",
   152.6,3,"Açıkçası benim yaptığım bir komedi gösterisi.",155.8,0,"",
   155.9,3,"Hugo Punch adlı karakteri canlandırıyorum...",161,0,"",
   161.1,3,"bir tür komedi sosyopatı,",164.8,0,"",
   164.9,3,"normalde söylemememiz gereken şeyler söylüyor, falan.",169.6,0,"",
   169.7,3,"Öğrenciler arasında oldukça popüler.",171.7,0,"",
   172.3,1,"Sanmıyorum, galiba hepimiz yatarız.",175.7,0,"",
   175.8,3,"Bunu kaçırmak istediğine emin misin?",179.2,0,"",
   179.5,1,"Evet, yatmayı tercih ederim. Üzgünüm.",182.8,0,"",
   182.9,3,"Tamam, tamam, tamam...",185.4,0,"",
   185.6,1,"Odaya nasıl gidebilirim?",186.7,0,"",
   187.2,3,"Asansörü kullan, odan birinci katta.",190.2,0,"",
   190.3,1,"Tamamdır, teşekkürler.",191.6,0,"",
   193.1,3,"Ve Maya, yarın oda anahtarını kutuya bırak, lütfen.",198.1,0,"",
   198.2,1,"Tamam!",199.2,0,"",
   199.3,6,"ASANSÖR KAPISININ KAPANMA SESİ",200.8,0,"",
   204.4,3,"Şehirdeki en iyi gösteri, ama kimsenin umurunda bile değil.",207.2,0,"",
   210.3,3,"Elinin altında 'You Tune' ve 'My Face' ve adı her neyse varken düzgün eğlenceyi kim ne yapsın?",216.6,0,"",
   216.7,3,"Aptal, kültürsüz...",218.7,0,"",
   218.8,5,"Hugo yaramaz çocukları sevmez.",223,0,"",
   225.5,3,"Yine başlama.",227.3,0,"",
   231.1,3,"Duymak istemiyorum, tamam mı? Bu gece olmaz.",234.2,0,"",
   237,5,"Yaramaz çocuklar çürük yumurta gibidir. Bir ders almaları gerekiyor!",240.9,0,"",
   254.2,3,"Kapa çeneni! Sus artık!",256.5,0,"",
   257.3,3,"Hep bunu yapıyorsun, onlar müşteri.",260.2,0,"",
   260.5,3,"Sana hiçbir şey yapmadılar.",262.4,0,"",
   263.3,3,"Onları yalnız bırak.",265.4,0,"",
   266.2,5,"Kötü yumurtaların çatlaması gerekir! Onlara sertçe vur ve kabuklarını kır,",269.3,0,"",
   269.5,5,"ardından da bas tekmeyi, gönder cehenneme!",272.3,0,"",
   272.8,5,"Yapman gerekeni biliyorsun, Jimmy.",275,0,"",
   275.6,5,"Onlara patronun kim olduğunu göster.",277.7,0,"",
   278.9,5,"Bu iş böyle yapılır!",281.1,0,"",
   293.3,6,"ÇIĞLIK SESİ",294.9,0,"",
   308,6,"KAHKAHA SESİ",309.6,0,"",
   310,3,"Evet, uyu bakalım...",313,0,"",
   345.2,6," ",346.9,0,"",
   358.5,6,"HOPÖRLERDEN GELEN SESLER",361.9,0,"",
   362,1,"Otelden kaç!",363.6,0,"",
   363.7,1,"Fırsatın varken kaç!",365.7,0,"",
   367.6,1,"Onun ne yaptığını öğrenmeli...",369.3,0,"",
   369.4,1,"...ve herkese anlatmalısın.",371.3,0,"",
   371.4,1,"Ona yaptıklarını hatırlat!",373.3,0,"",
   373.5,6,"PARAZİTLENEN SESLER",376,0,"",
   382.1,1,"SEA VIEW OTELİ KARANLIK BİR GEÇMİŞE SAHİP",386.1,0,"",
   389,1,"RUHLARIN ANLATACAĞI HİKAYELER VAR",393,0,"",
   395.7,1,"RUH SESİ ALICISINI KULLANARAK ONLARLA İLETİŞİME GEÇ",400.7,0,"",
   402.8,1,"SANA JIMMY'NİN SIRLARINI ANLATACAKLAR.",406.8,0,"",
   409.5,1,"AMA JIMMY, HER NE OLURSA OLSUN...",413.5,0,"",
   416.9,1,"...GERÇEĞİ SAKLAMALI.",
   420.9,0,"X",
],
  "A2",[
   0.8,1,"Jimmy, onu geri ver! O benim!",2.9,0,"",
   3,1,"Eşyalarımı çalmayı kes!",4.3,0,"X",
],
  "A3",[
   0.7,6,"ÇIĞLIK SESİ",2,0,"X",
],
  "A4",[
   1.1,1,"Sana söylüyorum Jimmy, bunu yapamazsın!",3.1,0,"",
   3.2,1,"Çok kötüsün...",4.7,0,"X",
   3.8,6,"SOLUMA SESLERİ",4.4,0,"X",
],
  "A5",[
   3.8,6,"ÖKSÜRME SESİ",4.8,0,"X",
],
  "A6",[
   4.2,6,"KAHKAHA SESİ",5.2,0,"X",
],
  "P1",[
   3.8,6,"KAPIYA VURMA SESİ",4.8,0,"",
   5.8,2,"Jimmy?",6.8,0,"",
   7.2,2,"Ben, Doktor Bose.",8.9,0,"",
   9,2,"Seninle yalnızca konuşmak istiyorum.",11.5,0,"",
   14.5,2,"Teşekkür ederim Jimmy, çok zamanını almayacağım.",16.6,2,"X",
],
  "P3",[
   1,2,"Bu harika bir fikir, Jimmy!",3.0,0,"",
   3.5,2,"Günün birinde harika bir aşçı olacağından eminim.",5.3,0,"",
   5.4,2,"Hazır ettiğinde onu neden bana getirmiyorsun?",8,0,"",
   8.1,2,"Seni bekliyor olacağım. Tamam mı?",11.8,0,"X",
],
  "P4",[
   3,6,"TÜKÜRME SESİ",4,0,"",
   7.6,2,"Jimmy!",8.6,0,"X",
],
  "P5",[
   1.2,2,"Canını acıtmayacağım Jimmy.",2.9,0,"",
   3,2,"Yalnızca sabit durmanı ve kıpırdamamanı istiyorum!",6.6,0,"X",
],
  "P6",[
   0.6,2,"Hastalarıma asla böyle bir şey yapmam, Bayan Hall.",4.8,0,"",
   4.9,0,"Bu benim inandığım her şeye ters.",7.3,0,"",
   7.4,2,"Anlamanızı istiyorum, bunların hepsini o uyduruyor!",10,0,"X",
],
  "P7",[
   1.1,2,"Benden bu kadar kolay kurtulamazsın, Jimmy.",3.9,0,"",
   4,2,"Her şeye sil baştan başlamamız gerektiğini düşünüyorum.",6.5,0,"",
   6.6,2,"Neden bu sefer yapmanı istediğim şeyi yapmıyorsun?",8.7,0,"",
   8.8,2,"Böylece iyi bir başlangıç yapmış oluruz, ne dersin?",11,0,"X",
],
  "P8",[
   0.6,2,"Polis konuşuyor, Bay Bose.",2.1,0,"",
   2.2,2,"Buraya gelmeniz gerekiyor.",4.1,0,"",
   4.4,2,"Lütfen kapıyı açar mısınız?",5.8,0,"X",
],
  "P9",[
   14.1,6,"TIKANMA SESİ",15.5,0,"",
   15.9,6,"ALARM SESİ",16.9,0,"X",
],
  "H1",[
   0.8,3,"Bunları o uydurdu. Sana söylüyorum, yalan söylüyor.",3.4,0,"",
   3.5,3,"Muhtemelen sana söylediği diğer şeyler de yalan.",5,0,"",
   5.1,4,"Saçmalama! O, böyle bir yalan söylemez!",7.3,0,"",
   7.4,3,"Bundan emin misin?",8.3,0,"",
   8.4,3,"Söylediği her şey yalan! Uyan artık, Rose!",11.4,0,"",
   11.5,3,"Tabii! Durma, git!",12.8,0,"",
   12.9,4,"Seni dinlemiyorum Harvey, bunları sen uydurdun.",14.7,0,"",
   14.9,3,"Bunlar gerçek!",16.2,0,"X",
],
  "H2",[
   1.5,6,"KAPIYA VURMA SESLERİ",2.4,0,"",
   2.5,3,"Jimmy?",3.5,0,"",
   4.3,3,"Beni duyduğunu biliyorum!",5.8,0,"",
   6.2,3,"Psikiyatrist ile olan hikayeyi uydurduğunu biliyorum.",10,0,"",
   10.1,3,"Hikayenin kaynağını biliyorum!",11.6,0,"",
   12,3,"Daha önce bir yerde okuduğumu biliyordum. Senin şu lanet karalama defterinde okumuştum!",15.3,0,"",
   16.1,3,"Çık dışarı!",17.3,0,"",
   18.3,3,"Jimmy!",19.6,0,"X",
],
  "H3",[
   1.2,6,"ELEKTRİK AKIMI SESLERİ",2.2,0,"",
   2.3,6,"ACI İÇİNDE BAĞIRMA SESİ",3.3,0,"",
   7.2,3,"Jimmy!",8.2,0,"X",
],
  "H4",[
   1,6,"KIRILAN EŞYA SESLERİ",2,0,"X",
],
  "H5",[
   0.8,6,"ACIYLA BAĞIRMA SESİ",1.9,0,"",
   4.1,3,"Jimmy!",5.1,0,"X",
],
  "H6",[
   1.3,3,"Bu gece orada kalıyorsun, Jimmy!",3.7,0,"",
   3.8,3,"Canıma tak etti artık.",5,0,"",
   5.1,6,"KAPIYA VURMA SESİ",6.6,0,"X",
],
  "H7",[
   0.3,6,"YANGIN ALARMI SESİ",1.8,0,"",
   2.7,3,"Jimmy aptal olma, aç şu kapıyı!",4.9,0,"",
   5.2,3,"İçeride ölüp gideceksin seni aptal! Aç şu kapıyı!",8.4,0,"X",
],
  "H8",[
   2.7,3,"Otelden defol Jimmy.",4.6,0,"",
   6.6,3,"Otelimden defol...",8,0,"",
   8.6,3,"Burası benim otelim. Otelimden defol Jimmy.",12,0,"X",
],
  "H9",[
   1.8,3,"Otelimden defol.",3.2,0,"",
   3.3,3,"Burası benim otelim.",5,0,"X",
],
  "R1",[
   0.8,8,"Harvey, Jimmy'i vuracaktı.",2.9,0,"",
   3.0,8,"Sadece bir mektup açacağı. Bu nefsi müdafaaydı! Bakın!",5.9,0,"X",
],
  "R2",[
   3.5,4,"Jimmy.",4.5,0,"X",
],
  "R3",[
   1.2,4,"Bayanlar ve baylar.",2.4,0,"",
   2.5,4,"Alkışlarınız huzurunda,",3.9,0,"",
   4,4,"bu akşamki eğlenceniz,",5.9,0,"",
   6,4,"Bay Hugo Punch!",8,0,"",
   8.1,6,"MÜZİK VE ALKIŞ SESLERİ",9.6,0,"X",
],
  "R4",[
   0,4,"",0,0,"",
],
  "R5",[
   0.7,4,"Bu sadece bir komedi gösterisi.",2.6,0,"",
   2.7,4,"Onun espri anlayışı bu!",4.4,0,"",
   4.5,4,"Alındıysanız özür dilerim...",6.3,0,"",
   6.4,4,"Affedersiniz...",7.6,0,"X",
],
  "R6",[
   0.5,6,"KAPIYA VURMA SESİ",1.8,0,"",
   1.9,4,"Bayan Hall?",3.4,0,"",
   4.2,4,"Bayan Hall, acaba sizinle konuşabilir miyiz?",6.5,0,"X",
],
  "R7",[
   1.4,4,"Jimmy?",2.4,0,"",
   4.1,6,"ÇIĞLIK SESİ",5.1,0,"",
   5.2,4,"Jimmy! Sen ne yaptın!? Jimmy!",8,0,"X",
],
  "R8",[
   0.5,6,"ÇOCUK AĞLAMA SESİ",1.5,0,"",
   1.6,5,"Sana söylediğimi yapacaksın! Beni anladın mı?",4.2,0,"",
   4.3,5,"Seni aptal velet!",5.4,0,"",
   5.5,6,"TOKAT SESİ",6.7,0,"",
   6.9,6,"SERT CİSİMLE VURMA SESİ",8.3,0,"X",
],
  "R9",[
   1.4,6,"ÇIĞLIK SESİ",2.9,0,"X",
],
  "V1",[
   5.5,7,"Karşınızda!",6.3,0,"",
   6.4,6,"GONG",7.4,0,"",
   7.5,7,"Ben, Muhteşem Hugo!",10.2,0,"",
   11.9,7,"Her şeyin üstünde tek başıma duruyorum.",15.9,0,"",
   17.4,7,"Ben, karanlığı aydınlatan ışığım.",21.4,0,"",
   22.7,7,"Ben yalnız bir ustayım.",26.5,0,"X",
],
  "V2",[
   5,6,"AĞLAMA SESİ",6.5,0,"",
   8,5,"Benim iznim olmadan hiçbir şey alma!",10.5,0,"",
   10.6,6,"CAM KIRILMA SESİ",11.5,0,"",
   11.6,5,"Hayatımı mahvetmene izin vermeyeceğim!",14,0,"",
   14.1,6,"KIRILMA SESLERİ",15.2,0,"",
   15.1,5,"Hayatının bir değeri yok!",16.8,0,"",
   16.9,5,"Sana söylediklerimi anlıyor musun?",18.6,0,"",
   18.7,6,"KIRILMA VE ÇIĞLIK SESLERİ",20.9,0,"X",
],
  "V3",[
   3.1,6,"ÇOCUĞUN AĞLAMA SESİ",4.6,0,"",
   9,5,"Otur oraya!",10,0,"",
   10.1,6,"TOKAT SESİ",11.4,0,"",
   11.5,5,"Seni aptal çocuk!",12.8,0,"",
   12.9,5,"Sana ne dedim!?",14.9,0,"",
   15,6,"ÇIĞLIK SESİ<br>Hayır!",17,0,"X",
],
  "EPI",[
   17.9,3,"Bayanlar ve baylar,",19,0,"",
   19.1,3,"Alkışlarınız eşliğinde,",20.6,0,"",
   20.7,3,"bu akşamki eğlenceniz,",22.5,0,"",
   22.6,3,"Bay Hugo Punch!",24.7,0,"",
   24.8,6,"ALKIŞ SESLERİ",26.4,0,"",
   33.5,5,"Maya!",34.5,0,"",
   36.1,5,"Maya!",37.1,0,"",
   40.5,5,"Maya?",41.5,0,"",
   42,5,"Maya!",43.5,0,"",
   44,6,"AĞLAMA SESİ",46,0,"",
   47.5,3,"Dur, dur, dur, dur...",49.9,0,"",
   50,3,"Kes şunu.",51.5,0,"",
   52.6,3,"Bana neden bunları yaptırıyorsun?",55.3,0,"",
   56,3,"Lütfen dur artık.",57.5,0,"",
   58.4,3,"Lütfen dur, kes şunu...",60.4,0,"",
   63.2,5,"Bunu yapmaya devam edeceksin, Jimmy.",64.9,0,"",
   66.7,5,"Yetki bende.",68.6,0,"",
   68.7,5,"Sende değil.",69.7,0,"",
   71,5,"Bende.",73.5,0,"",
],
  "BRO",[
   1.5,5,"Hugo'nun mezarına hoş geldin!",4.5,5,"",
   4.6,5,"Annemin küçük sırrına.",7.9,5,"",
   8,5,"Biliyor musun, betonu kendisi karıştırmış.",9.8,5,"",
   9.9,5,"Sonrasında da cansız bedenin üzerine dökmüş ve kurumasını beklemiş.",15.1,5,"",
   15.2,5," ",15.3,5,"",
   15.4,5,"Ondan kurtulduğunu sanmıştı.",17,5,"",
   18.3,5,"Ama olayı anlayamadı, Maya.",20.1,5,"",
   21.1,5,"Gördüğün gibi, Hugo sadece bizden biriydi.",23.9,5,"",
   24.1,5,"Yangındaki kütüklerden yalnızca biriydi.",27,5,"",
   27.6,5,"Yanıp kül oldu.",28.8,5,"",
   30,5,"Ama bu yangın nesiller boyunca Hall ailesini yakmaya devam ediyor.",33.2,5,"",
   34.3,5,"Yolu açıyor...",35.5,5,"",
   36.5,5,"karanlığı aydınlatıyor...",37.9,5,"",
   38,5,"yaşlıları, yoksulları ve zayıfları harcıyor.",44.3,5,"",
   44.7,5,"Ve bu ateş senin içinde de var, Maya.",47.7,5,"",
   47.8,5,"Bunu görebiliyorum!",48.8,5,"",
   49,5,"Birlikte olmak bizim kaderimizde var.",52.9,5,"",
   53,5,"Beklediğim kişi sensin.",54.6,5,"",
   55.8,5,"Bu yüzden gitmene izin veremem.",58,5,"",
   59.1,5,"Burada benimle kalacaksın, Maya.",61.2,5,"",
   62.3,5,"Sonsuza dek.",65.5,5,"X",
],
  "COR",[
   0.2,5,"Ölülerle mi konuşuyorsun, Maya?",4.0,1,"",
   4.1,1,"Hugo'nun baban olduğunu biliyorum, Jimmy.",6.0,1,"",
   6.1,1,"Doğum belgeni buldum ve Rose'un onu öldürmeye çalıştığını da biliyorum.",9.3,1,"",
   9.5,5,"Ama başaramadı, öyle değil mi?",11.6,1,"",
   11.7,1,"Peki şimdi nerede?",12.7,1,"",
   13.6,6,"KAHKAHA SESİ",15,3,"",
   16.5,5,"Neden gelip onunla tanışmıyorsun?",19.6,1,"",
   19.7,5,"Seni ailemle tanıştırma zamanı geldi, Maya.",22.8,1,"",
   22.9,6,"KAHKAHA SESİ",25,1,"X",
],
  "AP",[
   2.6,5,"Merhaba Maya!",5,1,"",
   5.5,5,"Maya!",6.5,5,"",
   8,5,"Maya!",9.1,5,"",
   9.2,6,"KAPIYA VURMA SESİ",10.1,5,"",
   10.2,5,"Benden kaçamazsın, Maya!",12.9,5,"",
   13,5,"Kapıyı aç!",15.2,5,"X",
],
  "TUT",[
   0.83,1,"DURUM",
   4.33,1,"",
   6.4,1,"Bu, otel sahibi Jimmy Hall.",
   9.3,1,"Kendisi ayrıca tehlikeli bir psikopat.",
   12.37,1,"",
   15.27,1,"Maya'nın arkadaşları için kötü planları var.",
   18.3,1,"",
   19.4,1,"Maya kaçtı.",
   22.4,1,"",
   24.23,1,"Jimmy ise onu durdurması gerektiğini biliyor.",
   27.33,1,"",
   27.83,1,"KOVALAMACA",
   31.57,1,"",
   33.3,1,"Jimmy istediği her yere saklanabilir.",
   36.8,1,"",
   39.37,1,"Koridor köşelerinde",
   41.63,1,"",
   42.33,1,"ve karanlık yerlerde",
   44.33,1,"",
   45.27,1,"senin gelmeni bekler,",
   47.6,1,"",
   48.23,1,"veya arkandan sinsice yaklaşır.",
   50.57,1,"",
   51.2,1,"Ancak merdivenlerde,",
   53.53,1,"",
   54.33,1,"zemin katta",
   56.47,1,"",
   57.33,1,"veya bodrum katında saklanamaz.",
   60.27,1,"",
   60.7,1,"STRATEJİ",
   64.67,1,"",
   66.17,1,"Eğer Jimmy seni görürse, oradan hemen uzaklaş.",
   67.67,1,"Onun görüş açısına girme.",
   71.83,1,"",
   75.13,1,"Kilidi açılmış olan her odada saklanabilirsin.",
   78.17,1,"",
   79.67,1,"Eğer Jimmy bulunduğun odaya girmeye çalışırsa,",
   81.73,1,"",
   84.13,1,"dolap içine",
   86.4,1,"",
   90.2,1,"veya banyoya saklan.",
   92.33,1,"",
   94.73,1,"Kapı gözlerinden bakarak",
   97.67,1,"",
   98.53,1,"Jimmy'nin ne tarafa gittiğini öğren.",
   101.43,1,"",
   103.63,1,"Ona seslenerek dikkatini çekebilir,",
   105.2,1,"",
   106.67,1,"böylece onu farklı yere yönlendirebilirsin.",
   109.67,1,"",
   110.23,1,"Çekmecelerde bulunan oda anahtarlarını kullanarak",
   112.67,1,"",
   114.17,1,"Jimmy'nin odalara girmesini engelleyebilir",
   116.4,1,"",
   117.83,1,"ya da onu oda içlerine kilitleyebilirsin.",
   120.13,1,"Tabii ki ona yakalanmadan odadan çıkabilirsen.",
   123.17,1,"",
   124.67,1,"Anahtar deliklerini kullanarak odaların içlerine hızlıca bakabilirsin.",
   127.7,1,"",
   129.67,1,"ÖLÜLER",
   133.5,1,"",
   135.17,1,"Jimmy'nin karanlık bir geçmişi var.",
   138.2,1,"Kurbanlarının ruhları hala...",
   141.17,1,"otelin içinde yer almaktadır.",
   144.47,1,"",
   145.67,1,"Ruh sesi alıcısını kullanarak onlarla iletişime geç.",
   150.2,1,"",
   153.23,1,"Onlara gördüğün şeyleri sorarak hikayelerini öğren.",
   159.07,1,"",
   159.13,1,"Önemli sorular sorarak, onların açığa çıkmasını sağla.",
   166.63,1,"",
   168.17,1,"Ardından yanıp sönen ışıkları takip et",
   171.1,1,"ve tuhaf sesleri dinle.",
   174.07,1,"",
   175.47,1,"Rehberlik etmesi için pusulayı kullan.",
   178.4,1,"",
   180.07,1,"Ruhlara yaklaştığında etrafa bak",
   183.07,1,"ya da sabit dur ve olacakları izle.",
   186.17,1,"",
   186.7,1,"MAYA'NIN YETENEĞİ",
   191.5,1,"",
   192.5,1,"Maya diğer dünyayı görebilir.",
   196.5,1,"",
   197.97,1,"Aydınlık bir yere git,",
   200.43,1,"",
   201.43,1,"sonra da aynayı kullan.",
   204.67,1,"",
   206.27,1,"Önemli eşyların yerlerini...",
   209.2,1,"ruhların konumlarını...",
   212.23,1,"ve eşyalar ile ruhlar arasındaki bağlantıyı göreceksin.",
   217.23,1,"",
   218.3,1,"Eğer Jimmy seni yakalarsa bazı eşyalarını çalabilir.",
   222.77,1,"",
   224.27,1,"Ruh sesi alıcısını bulmak için ilk kattaki depoya (merdivenlerin karşısındaki oda),",
   229.3,1,"",
   230.27,1,"pusula ve diğer anahtarlar için misafir odalarına bak.",
   234.77,1,"",
   236.23,1,"Ruhları bulma konusunda daha fazla bilgi almak için ruh sesi alıcısının talimatlarını oku.",
   241.47,1,"",
  ],
],

itexts:[

  "ESKİ VALİZLER VAR",
  "BAZI KUPALAR VAR",
  "ÇOCUK CÜZDANI VAR",
  "TEREBENTİN VE ÇAKMAK VAR",
  "BİR KILIÇ VAR",
  "BİRKAÇ VİSKİ ŞİŞESİ VAR",
  "BİR ÇOCUĞUN ELİNDEN ÇIKMIŞ KORKUNÇ ÇİZİMLER VAR",
  "AŞÇI ŞAPKASI VAR",
  "ÜZERİNDE KAN LEKESİ OLAN BİR KUMAŞ PARÇASI VAR",
  "ŞIRINGA İLE BİR ŞİŞE DIAZEPAM VAR",
  "ESKİ TAHTA KÜREK VAR",
  "İÇİNDE GAZETE MAKALELERİ OLAN BİR KARALAMA DEFTERİ VAR",
  "ÇAMAŞIR İPİ VE OKLAVA VAR",
  "ÜZERİNDE 'TEHLİKELİ' YAZAN BİR ISITICI VAR",
  "BİRKAÇ KRİKET VE BEYZBOL SOPASI VAR",
  "BİR ARBALET VAR",
  "BİRKAÇ PASLI ANAHTAR VAR",
  "OTELDE DUMANLARIN YÜKSELDİĞİNİ GÖSTEREN FOTOĞRAFLAR VAR",
  "ESKİ BİR TABANCA VAR",
  "SÜSLÜ BİR HANÇER VAR",
  "JIMMY HALL'UN KOMEDİ GÖSTERİSİNİN POSTERİ VAR",
  "BİRKAÇ KIRIK AYNA VAR",
  "BAKIR TEL BOBİNİ VAR",
  "ÜZERİNDE 'ELVEDA' YAZAN BİR NOT VAR",
  "BİR YÜZÜK VAR",
  "BİR ÇINGIRAK VAR",
  "JIMMY HALL'UN DOĞUM BELGESİ VAR",

],

ketex:[

  "ODA ANAHTARI ",
  "NOT EDİLDİ: ",
  "NOT EDİLDİ: '",
  "ALINAN EŞYA: ",
  "ALINAN ODA ANAHATARININ NUMARASI: ",
  "PUSULA",
  "AĞLAYAN AYNA",

],

patex:[

  ["H","ROSE'A AİT, AMA HİÇ KULLANAMADI.","R","BANA AİTTİLER. BURADAN GİTMEK İSTEDİM, AMA FIRSATIM OLMADI."],
  ["R","KENDİSİNİ ÖDÜL KAZANMIŞ BİRİ GİBİ GÖSTERMEK İÇİN JIMMY ONLARI SATIN ALDI."],
  ["A","O BENİMDİ. DOĞUM GÜNÜMDE ALINMIŞ BİR HEDİYEYDİ, AMA ÇALINDI.","H","O KÜÇÜK KIZA AİTTİ, ZAVALLICIK.","R","O, KÜÇÜK KIZA AİTTİ."],
  ["A","JIMMY ONLARI BANA GÖSTERENE KADAR NE OLDUKLARINI BİLMİYORDUM.","P","JIMMY'E SORSAN DAHA İYİ OLUR.","H","ONLAR BENİM EŞYALARIM, AMA ONLARI HİÇ BERABER BULUNDURMAZDIM.","R","ONLAR HARVEY'NİN."],
  ["A","O JIMMY'NİN. HİÇ SEVMEDİM.","P","JIMMY'NİN ONUNLA OYNADIĞINI GÖRDÜM. ONA TEHLİKELİ OLDUĞUNU SÖYLEDİM.","H","ORTA ÇAĞ SİLAHLARINI İÇEREN BİR SERGİMİZ VARDI. SONRA JIMMY ONU ÇALDI.","R","SAHİP OLDUĞUMUZ ZIRH TAKIMINA AİTTİ. SONRA KAYBOLDU."],
  ["A","BİLMİYORUM, AMA ÇOCUKLAR ALKOL ALMAMALI.","P","MUHTEMELEN BARDAN ALINDILAR.","H","HATIRLAMIYORUM, AMA BİRAZ ALKOL ALMANIN BİR SAKINCASI OLMAZ.","R","ONLARI ORAYA HARVEY KOYMUŞ OLMALI."],
  ["A","ONLARI ÇOCUK ÇİZİYORDU.","P","ONLARI JIMMY ÇİZİYORMUŞ.","H","BİL BAKALIM KİM? JIMMY! KÜÇÜK JIMMY'NİN ŞİDDETE MERAKLI BİR HAYAL GÜCÜ VARDI.","R","JIMMY DE TIPKI DİĞER ERKEK ÇOCUKLARI GİBİ SAVAŞ RESİMLERİ ÇİZERDİ."],
  ["P","ONU JIMMY BULDU, SONRA TAKMAYA BAŞLADI.","H","AŞÇI ŞEFİMİZİN ŞAPKASIYDI. BAŞKA KİM AŞÇI ŞAPKASI TAKAR Kİ?","R","ONU ŞEFİMİZ TAKARDI."],
  ["A","O BENİM OLABİLİR.","P","BENİMDİ. DELİLE İHTİYACIM OLUR DİYE SAKLIYORDUM.","H","DOKTORLA BİR ALAKASI OLABİLİR."],
  ["P","BAZI İNSANLARDA DAVRANIŞ BOZUKLUKLARINI TEDAVİ EDEBİLİR.","H","ONU MUHTEMELEN DOKTOR BIRAKTI.","R","İLAÇ DOKTOR BOSE'A AİTTİ."],
  ["P","BİLMİYORUM, AMA ONU JIMMY BULDU.","H","RESEPSİYON MASASININ ALTINDAYDI. NEREDEN GELDİĞİNİ BİLMİYORUM.","R","KOCAMA AİTTİ."],
  ["A","JIMMY YAPTI. NEDENİNİ BİLMİYORUM. TUHAFTI.","P","JIMMY'NİN ESERİ, BİR UYARIYDI. BUNUN OLACAĞINI TAHMİN ETMELİYDİM.","H","JIMMY, TACİZCİ ÖĞRETMENLER VE DOKTORLAR İLE İLGİLİ HABERLERİ KESERDİ. O NORMAL BİR ÇOCUK DEĞİLDİ.","R","HARVEY, JIMMY'NİN KARALAMA DEFTERİNDEN BAHSETMİŞTİ. AMA TAM HATIRLAMIYORUM."],
  ["P","BİR DENEY İÇİN ONLARI BİRBİRİNE BAĞLADIM."],
  ["H","ELEKTRİK KAÇAĞI VARDI. POLİSLERİN KONTROL ETMESİ İÇİN TUTUYORDUM.","R","HARVEY ONU KALDIRDI. TEHLİKELİ OLDUĞUNU SÖYLEDİ."],
  ["A","ÇOCUK ONLARLA OYNARDI.","P","ONLARI HARVEY ELİNDE BULUNDURUYORDU. NEDENİNİ BİLMİYORUM.","H","ONLARI BİR GÜN LAZIM OLUR DİYE TUTUYORDUM.","R","ONLAR KOCAMA AİTTİ, ÖĞRETMEN OLDUĞU ZAMANLARDAN KALMA."],
  ["A","OTELDE DOLABIN İÇİNDE OLDUKLARINI GÖRDÜM.","P","OTELDE ESKİ SİLAHLAR SERGİSİ VARDI.","H","ESKİ SİLAHLAR SERGİMİZDE DURUYORDU. JIMMY ORADAN ALMIŞ.","R","HARVEY O ARBALETİ SERGİLERDİ. OTELDE OLMASINI SEVMEZDİM."],
  ["H","ONLAR ESKİ KAZAN DAİRESİNİN.","R","ONLAR KAZAN DAİRESİNİNDİ, AMA SONRA KAPIYI DEĞİŞTİRDİK."],
  ["P","O OLAYI HİÇ DUYMADIM.","H","KONTROL ALTINA ALMAYI BAŞARDILAR, AMA ÇOK EŞYAMIZI KAYBETTİK.","R","FAZLA YAYILMADAN DURUMU FARK ETTİK."],
  ["P","HARVEY'NİN. OTELDE OLMASINI SEVMEDİĞİM BİR ŞEY.","H","BENİMDİ. DAHA ÖNCE DE BABAMINDI. İÇİNDE HALA BİRKAÇ MERMİ VARDIR.","R","HARVEY'NİN. AMA ONU YATAK ODASINDA TUTARDI."],
  ["A","ONU JIMMY BANA GÖSTERMİŞTİ. AMA ONA AİT DEĞİLMİŞ.","H","O BİR HANÇER DEĞİL, MEKTUP AÇACAĞI. KESKİN OLMAMASI GEREKİYORDU.","R","MEKTUP AÇACAĞI. BİRİNDEN HEDİYE GELDİ."],
  ["R","O, JIMMY'NIN KOMEDİ GÖSTERİSİ."],
  ["P","ONLARI GÖRMEDİM.","H","HATIRLAMIYORUM.","R","ONLARI JIMMY KIRDI."],
  ["A","JIMMY ONU YANINDA TAŞIRDI.","P","JIMMY'E AİT. SÜREKLİ CEBİNDE TAŞIRDI. AMA NEYDE KULLANDIĞINI HİÇ SÖYLEMEDİ.","H","JIMMY ESKİDEN ONU YANINDA TAŞIRDI. NEDENİNİ BİLMİYORUM.","R","JIMMY YANINDA TEL TAŞIRDI. ELEKTRONİK ŞEYLERLE OYNAMAYI SEVERDİ."],
  ["R","JIMMY YAZDI."],
  ["H","MUHTEMELEN ROSE'A AİT.","R","BENİMDİ. BİRİSİ BANA REDDEDEMEYECEĞİM BİR TEKLİF YAPMIŞTI."],
  ["A","BİLMİYORUM. BEN BEBEK GÖRMEDİM.","R","BEBEK İÇİNDİ. YATAĞIMIN BAŞ UCUNDAKİ ÇEKMECEDE TUTARDIM."],
  ["R","JIMMY, HUGO'NUN OĞLU. HEM DE HER YÖNÜYLE."],
  ["A","JIMMY ADLI ÇOCUK BENİ BODRUMA KİLİTLEDİ. ARDINDAN EŞYALARIMI ÇALMAYA BAŞLADI.","P","OTELE GELEN MİSAFİRLERDEN BİRİNİN KIZIYMIŞ. JIMMY ONA İYİ DAVRANMAMIŞ.","H","KIZ, AİLESİYLE OTELDE KALIYORDU.","R","KIZ OTELİN MİSİFİRİYDİ."],
  ["A","ÇÜNKÜ BUNUN KOMİK OLDUĞUNU DÜŞÜNÜYORDU. SONRA GERİ VERDİ, AMA ÇOKTAN MAHVOLMUŞTU.","P","ÇÜNKÜ BU JIMMY'NİN HEP YAPTIĞI BİR ŞEYMİŞ.","H","MUHTEMELEN KOMİK OLDUĞUNU DÜŞÜNÜYORDU.","R","KIZ YALAN SÖYLÜYORDU. JIMMY HİÇBİR ŞEY ÇALMADI."],
  ["A","ELİM YANDI, CANIM ÇOK ACIDI, AMA KİMSEYE SÖYLEYEMEDİM.","P","KIZ FENA YANMIŞ, AMA JIMMY BUNU BİR ŞAKA OLARAK GÖRÜYORDU.","H","KIZ YANMIŞTI, HEM DE FENA ŞEKİLDE.","R","KIZ YANMIŞTI, ANCAK TEHLİKELİ ŞEYLER YAPMAYA DEVAM EDİYORDU. GARİP BİR KIZDI."],
  ["A","DOKTOR BULMAYA ÇALIŞIYORDUM, AMA JIMMY ORADA KALMAM İÇİN BENİ TEHDİT ETTİ.","H","KIZ HERHALDE JIMMY'DEN KORKUYORDU.","R","NEDENİ HER ŞEY OLABİLİR. TUHAF BİR KIZDI."],
  ["A","ÇOCUK, ONUN İLAÇ OLDUĞUNU SÖYLEDİ. TADI KORKUNÇTU.","P","O SIRADA ORADA DEĞİLDİM, AMA SANIRIM KIZ ALKOL İÇMİŞ."],
  ["A","KENDİMİ ÇOK HAFİF HİSSETTİM, EN ALT KATA ATLAYABİLECEĞİMİ SANMIŞTIM.","P","JIMMY, KIZA ÇOK ALKOL İÇİRMİŞ.","H","KIZ BİR ŞİŞE VİSKİ İÇMİŞ, NE YAPTIĞINI BİLMİYORDU.","R","BU KONUDA ÇOK BİLGİM YOK."],
  ["A","ATLADIM, AMA SONRA HER ŞEY KARARDI VE BİR DAHA UYNAMADIM. ARTIK UYANAMIYORUM. NEREDEYİM BİLMİYORUM.","P","KIZ EN ÜST KATTAN DÜŞMÜŞ. NE YAPTIĞINI ANLAYAMAYACAK KADAR SARHOŞMUŞ. BU YÜZDEN ROSE BENİMLE İLETİŞİME GEÇTİ.","H","KIZ EN ÜST KATTAKİ MERDİVENLERDEN DÜŞTÜ. İŞİN ARKASINDA JIMMY'NİN OLDUĞUNU BİLİYORDUM.","R","KIZ KENDİ DÜŞTÜ. HARVEY İSE JIMMY'İ SUÇLADI. BU KIZIN SUÇUYDU, JIMMY'NİN DEĞİL."],
  ["P","ROSE BENİ ARADI. BENDEN JIMMY'İ RAHATSIZ EDEN ŞEYİ BULMAMI İSTEDİ. ANCAK HARVEY, JIMMY'NİN HAYAL GÜCÜNDEN ENDİŞELİYDİ.","H","DOKTOR BOSE, JIMMY'E YARDIM ETMEK İÇİN GELDİ, AMA JIMMY'NİN DURUMU YARDIMLIK OLMAKTAN ÇIKMIŞTI.","R","DOKTOR BOSE, JIMMY'E YARDIM ETMEK İÇİN GELDİ."],
  ["P","JIMMY'NİN ÖLDÜRME HUYU VARDI. EMPATİ KURMA ÜZERİNDE ÇALIŞMAMIZ GEREKTİĞİNİ DÜŞÜNDÜM. BU YÜZDEN ONDAN BENİM İÇİN YAPABİLECEĞİ GÜZEL BİR ŞEY DÜŞÜNMESİNİ İSTEDİM. AKLINA HEMEN BİR FİKİR GELDİ.","H","JIMMY ONU BİR YERDE BULDUĞUNU SÖYLEMİŞTİ. AMA ONUNLA NE YAPTIĞI BAMBAŞKA BİR HİKAYE.","R","HARVEY, JIMMY'NİN TAVŞAN ÖLDÜRMÜŞ OLABİLECEĞİNİ SÖYLEDİ, AMA ONA İNANMADIM."],
  ["P","JIMMY BANA SANDVİÇ YAPMIŞTI. ONDAN İSTEDİĞİM GİBİ ODAMA GETİRMİŞTİ. BAŞLANGIÇTA HİÇBİR ŞEYDEN ŞÜPHELENMEMİŞTİM.","H","DOKTOR, JIMMY'İ YOLA SOKMAYA, YARDIM ETMEYE ÇALIŞIYORDU. NE BÜYÜK BİR HATA.","R","DOKTOR BOSE, JIMMY'E İSTEMEDİĞİ ŞEYLERİ YAPTIRMAYA ÇALIŞIYORDU."],
  ["P","JIMMY SANDVİÇİMİN İÇİNE CAM KOYMUŞ. NEREDEYSE BOĞULUYORDUM. JIMMY'NİN HASTALIĞINI HAFİFE ALDIĞIMI FARK ETTİM. ACİLEN TEDAVİSİNİ HIZLANDIRMAK ZORUNDAYDIM.","H","DOKTOR BOSE, JIMMY'İ ZOR YOLDAN TANIDI. JIMMY'NİN ŞAKALARI HER ZAMAN FAZLA İLERİ GİDER.","R","DOKTOR BOSE KENDİSİNİ KESTİ, ANCAK SUÇU JIMMY'E ATMAK İSTEDİ. BUNU KENDİSİNE O YAPTI, JIMMY DEĞİL."],
  ["P","JIMMY AŞI YAPMAMA İZİN VERMEDİM. SONRA DA ROSE'A ONU AŞI YAPMAYA ZORLADIĞIMI VE ŞİDDET UYGULADIĞIMI SÖYLEDİ. BU ÇOK SAÇMAYDI!","H","BİLMİYORUM ORADA DEĞİLDİM.","R","DOKTOR BOSE BENİM İZNİM OLMADAN JIMMY'E İLAÇ VERMEYE ÇALIŞTI."],
  ["P","ROSE'UN JIMMY'E İNANMASINDAN ENDİŞE EDİYORDUM. BARİZ YALAN SÖYLÜYORDU. AMA BÜTÜN BUNLARI JIMMY'NİN UYDURDUĞUNA DAİR ROSE'U İKNA ETTİM.","H","DOKTOR BOSE, JIMMY'NİN ONUN HAKKINDA HİKAYELER UYDURMASINDAN ENDİŞELNİYORDU. VE ENDİŞELENMEKTE DE HAKLIYDI.","R","ÇÜNKÜ DOKTOR BOSE İTİBARININ ZEDELENMESİNDEN ENDİŞE EDİYORDU. AMA ONA BİR ŞANS DAHA VERMEYE KARAR VERDİM."],
  ["P","YALANLARI ORTAYA ÇIKINCA JIMMY'NİN BENİMLE İLETİŞİME GEÇECEĞİNİ DÜŞÜNMÜŞTÜM. ANCAK O BUNUN YERİNE YENİ YALAN UYDURDU. AMA BU SEFERKİ KÖTÜYDÜ. ÇOK KÖTÜ.","R","DOKTOR BOSE, JIMMY İLE KONUŞURAK ONU KONTROLÜ ALTINA ALMAYA ÇALIŞIYORDU. ONA KÖTÜ ŞEYLER YAPTIRACAKTI. ONA HİÇ GÜVENMEMEİYDİM."],
  ["P","ROSE BENİ İHBAR ETTİ. BENİ TUTUKLAYACAKLARINI BİLİYORDUM. KARİYETİM, GELECEĞİM BİTMİŞTİ. HER ŞEYİ BİTİRMEYİ GÖZE ALMIŞTIM.","H","DOKTOR BOSE'U TUTUKLAYACAKLARDI. JIMMY ADAMIN HAYATINI MAHVETMİŞTİ. AMA BUNLARIN HİÇBİRİNE İNANAMADIM.","R","DOKTOR BOSE'U TUTUKLAMAYA GELMİŞLERDİ. BAŞINA GELEN HER ŞEYİ HAK ETMİŞTİ."],
  ["P","CANIMA TAK ETMİŞTİ. BURADAN GERİ DÖNÜŞ YOKTU. HAYATIM ZATEN MAHVOLMUŞTU.","H","DOKTOR BOSE KAFAYI YEDİ. HERKES ONUN JIMMY'E 'EL SÜRDÜĞÜNÜ' DÜŞÜNÜYORDU. JIMMY ÇOK AKILLIYDI. DOKTORUN BAŞKA SEÇENEĞİ YOKTU.","R","SUÇLU OLDUĞUNU BİLİYORDU. DOĞRU OLANI YAPTI."],
  ["P","HARVEY, JIMMY'NİN HAKKIMDA SÖYLEDİKLERİNİN YALAN OLDUĞUNU BİLİYORDU.","H","JIMMY, DOKTOR HAKKINDA HİKAYELER UYDURDU. ROSE DA ONA İNANDI, AMA BU HİKAYEYİ DAHA ÖNCE DE DUYMUŞTUM.","R","HARVEY, JIMMY'NİN DEDİKLERİNE İNANMIYORDU, AMA BEN ONUN YALAN SÖYLEMEDİĞİNİ BİLİYORDUM."],
  ["P","JIMMY YALANLARINI ASLA İTİRAF ETMEDİ.","H","JIMMY SADECE GÜLDÜ. SONRASINDA BANA 'KÜÇÜK' TUZAKLAR KURMAYA BAŞLADI. BAZILARI O KADAR KÜÇÜK DEĞİLDİ.","R","JIMMY GERÇEK OLMAYAN BİR ŞEYİ NASIL İTİRAF EDEBİLİRDİ Kİ? HARVEY'NİN JIMMY'E ZORBALIK TASLAMASI HİÇ DOĞRU DEĞİLDİ."],
  ["H","JIMMY, ONUN BENİM ISITICIM OLDUĞUNU BİLİYORDU. CİHAZI DOĞRUCA ANA ŞEBEKEYE BAĞLAMIŞ. ONA BİR DERS VERİLMESİ GEREKİYORDU. O BENİM EŞYALARIMA ZARAR VERDİ, BEN DE ONUN EŞYALARINI KIRMAYA KARAR VERDİM.","R","HARVEY, JIMMY'İ SUÇLADI, AMA O ISITICI ZATEN ARIZALIYDI. HARVEY'NİN ONU ÇÖPE ATMASI GEREKİYORDU."],
  ["P","BİLMİYORUM, AMA ŞİDDET BU TÜR DURUMLARI DAHA KÖTÜLEŞTİRİR.","H","SİNİRDEN, JIMMY'NİN TELEVİZYONUNUN VE OYUN KONSOLUNU KIRDIM. AMA İŞE YARAMADI, İŞLER DAHA DA KÖTÜYE GİTTİ. SONRASINDA BANA KARŞILIK VERMEYE BAŞLADI.","R","HARVEY, JIMMY'NİN EŞYALARINI KIRMIŞTI. ÖFKESİNİ KONTROL EDEMİYORDU."],
  ["H","KAPIYI AÇTIĞIM SIRADA JIMMY ARBALET İLE ATEŞ ETTİ. ACİLE GİTMEM GEREKTİ. GERİ DÖNDÜĞÜMDE ONU BULAMADIM. ROSE, ONUN BODRUMDA SAKLANDIĞINI SÖYLEDİ. BU DA BANA BİR FİKİR VERDİ.","R","HARVEY BANA JIMMY'NİN KENDİSİNİ OK İLE VURDUĞUNU SÖYLEDİ, AMA JIMMY'NİN ÖYLE BİR SİLAHI KULLANAMAYACAĞINI BİLİYORDUM."],
  ["H","JIMMY'E KENDİ TATTIRMAK İSTEDİM. BODRUMDA BİR HASARA SEBEP OLAMAYACAĞINI DÜŞÜNMÜŞTÜM. YANILMIŞIM.","R","HARVEY'NİN BODRUMDA NE YAPTIĞINI BİLMİYORDUM."],
  ["P","HATIRLAMIYORUM.","H","YANGINI ÇOK YAYILMADAN KONTROL ALTINA ALMAYI BAŞARDIK. AMA ESKİ FOTOĞRAFLARIMIZ VE MEKTUPLARIMIZ ORADAYDI, HEPSİ KÜL OLDU. JIMMY ZIVANADAN ÇIKMIŞTI, BENİM DE CANIMA TAK ETTİ. ONUN GİTMESİNİ İSTİYORDUM.","R","HARVEY, JIMMY'İ SUÇLADI, AMA YANGINA KAÇAK SEBEP OLDU. BU BİR KAZAYDI."],
  ["P","BİLMİYORUM. AMA HARVEY ÖFKESİNİ KONTROL EDEMİYORDU.","H","NE YAPACAĞIMI BİLMİYORDUM. ONUN DA SİLAHLI OLACAĞINI TAHMİN EDEMEDİM","R","BİLMİYORUM. HARVEY'NİN OTELDE SİLAH BULUNDURMAMASI GEREKİYORDU."],
  ["H","JIMMY'İ ARIYORDUM."],
  ["H","JIMMY ARKAMDA BELİRDİ, GELDİĞİNİ GÖREMEDİM. JIMMY HER ZAMAN SON KAZANAN OLDU.","R","HARVEY DELİRMİŞTİ. JIMMY SADECE KENDİSİNİ KORUDU."],
  ["H","ROSE, JIMMY'E İNANDI. EN BAŞINDAN BERİ ONU SAVUNDU.","R","POLİSLERE HANÇERİN ASLINDA BİR MEKTUP AÇACAĞI OLDUĞUNU VE HARVEY'NİN DOLU SİLAH TAŞIDIĞINI AÇIKLAMALIYDIM. JIMMY SADECE NEFSİ MÜDAFAA YAPTI. POLİSLER DURUMU ANLADI."],
  ["H","POLİSLER, JIMMY'İ SERBEST BIRAKTILAR. JIMMY'İ VURMAYA ÇALIŞTIĞIMI DÜŞÜNDÜKLERİ İÇİN BUNUN NEFSİ MÜDAFAA OLDUĞUNU DÜŞÜNDÜLER. AMA HEPSİ YALANDI.","R","JIMMY EVE DÖNMÜŞTÜ. POLİSLER DURUMU ANLADI. AMA BU OLAY ONU DEĞİŞTİRDİ, OTELİ İŞLETMEMDE YARDIM ETMEYE BAŞLADI. VE OTELE DAHA FAZLA ZİYARETÇİ ÇEKMENİN YOLUNU BULDU."],
  ["H","HUGO PUNCH'IN KİM OLDUĞUNU BİLMİYORUM.","R","İZLEMEK HOŞUMA GİDİYORDU, VE TEKRAR PARA KAZANMAYA BAŞLAMIŞTIK. SONRA JIMMY TUHAF DAVRANMAYA BAŞLADI. KENDİSİNE BAKAKIP BAĞIRDIĞINA ŞAHİT OLDUM. SİNİRLİ GÖRÜNÜYORDU"],
  ["R","BAŞLANGIÇTA ANLAMAMIŞTIM, KAFAM KARIŞMIŞTI. AMA SONRA ANLADIM Kİ BUNLARI YAPAN JIMMY DEĞİDLİ. AYNALAR GİBİ KIRILMAYA BAŞLADI. JIMMY ARTIK KONTROLDEN ÇIKMIŞTI."],
  ["H","BİLMİYORUM, AMA JIMMY EN SONUNDA HER ŞEYİ BERBAT ETMİŞTİR.","R","BU ARTIK JIMMY'NİN DEĞİL, HUGO PUNCH'IN SAHNESİYDİ. HER AKŞAM İZLEYİCİLERE HAKARETLER EDİYORDU. SONRA BİR GECE KONUKLARDAN BİRİ, JIMMY'E ONUN HAKKINDA NE DÜŞÜNDÜĞÜNÜ SÖYLEDİ. O DA ÖFKESİNE YENİK DÜŞTÜ VE APTALCA BİR ŞEY YAPTI."],
  ["R","GAZETECİLER, JIMMY'İ GÖRMEK İSTİYORLARDI. AMA KADINI BAĞLAYAN HUGO PUNCH'TI. JIMMY ARTIK KONTROLDEN ÇIKMIŞTI. DEPRESYONDAYDI. HER ŞEYİ GERİDE BIRAKIP GİTMEK İSTİYORDU."],
  ["R","BANYODAKİ JIMMY'Dİ. İNTİHAR ETMEYE ÇALIŞTI. BU YÜZDEN ONA GERÇEĞİ SÖYLEMEK ZORUNDAYDIM."],
  ["H","BİLMİYORUM. ROSE'UN BANA SÖYLEMEDİĞİ ŞEYLER VAR.","R","HUGO'YU GÖMDÜM. UZUN SÜRE JIMMY'İ İSTİSMAR ETMESİNE GÖZ YUMDUM. JIMMY'NİN BU HALE GELMESİ BENİM SUÇUMDU. EĞER JIMMY'E ANLATIRSAM PİŞMANLIKTAN KURTULACAĞIMI SANMIŞTIM. YANILMIŞIM. BUNUNLA YAŞAYAMAZDIM."],
  ["R","EĞER KENDİMİ ÖLDÜRMESEYDİM JIMMY, YANİ HUGO ÖLDÜRECEKTİ. ŞU ANDA BİLE KONTROL HUGO'DA. JIMMY'İ KONTROL EDİYOR. HUGO'NUN NEREDE YAŞADIĞINI JIMMY'E SOR."],
  ["H","ONUNLA HİÇ TANIŞMADIM.","R","HUGO BİR SİHİRBAZ VE ŞOVMENDİ. OTELİ ŞOVUNU TANITMAK İÇİN SATIN ALMIŞTI, ÜNLÜ OLDU. O ZAMANLAR ASİSTANI OLARAK ÇALIŞTIM. SONRA İŞLER GELİŞTİ."],
  ["R","NE İSTEDİĞİNİ BİLMİYORDUM. ONA VEREBİLECEĞİM TEK ŞEY VARDI."],
  ["R","HUGO ŞİDDETE MERAKLI, KÖTÜ, HASTA RUHLU BİR ADAMDI."],
  ["A","EVET! BAKMADIĞIM BİR SIRADA JIMMY ONU ALDI VE PARAMI ÇALDI. ONA DURMASINI SÖYLEDİM AMA BENİ DİNLEMEDİ."],
  ["A","JIMMY ŞİŞEDEKİ ŞEY İLE OYUNCAĞIMI ISLATTI. ONDAN NEFRET ETTİM!"],
  ["A","JIMMY ONU DUVARDAN ALDI, ÇOK KESKİN GÖRÜNÜYORDU. EĞER KİMSEYE SÖYLEMEYECEĞİME SÖZ VERİRSEM, ELİMİN AĞRISINI DURDURACAĞINI SÖYLEDİ."],
  ["A","İÇMEYE DEVAM ETMEMİ SÖYLEDİ. TADI KORKUNÇTU. SONRA KENDİMİ GARİP HİSSETMEYE BAŞLADIM."],
  ["P","ÇİZİMLER, SIKINTILI BİR KİŞİLİĞİN BELİRTİSİYDİ, AMA ONUN NE DENLİ İLERİ GİDEBİLECEĞİNİ GÖRDÜĞÜMDE ENDİŞELENMEYE BAŞLADIM."],
  ["P","JIMMY BENİM İÇİN BİR ŞEYLER HAZIRLAYACAĞINI SÖYLEDİ, BEN DE NELER OLDUĞUNU ANLAMAK İÇİN ONU TAKİP ETTİM."],
  ["P","JIMMY'NİN ESPRİ ANLAYIŞI İLE BÖYLE TANIŞTIM."],
  ["P","DİAZEPAM BU İŞ İÇİN UYGUN İLAÇ DEĞİLDİ, AMA O AN ELİMDE OLAN TEK ŞEYDİ. JIMMY'NİN ACİL TEDAVİYE İHTİYACI VARDI. TEHLİKE ARZ EDİYORDU."],
  ["P","JIMMY ONU KÜREKLE DÖVDÜĞÜMÜ SÖYLEDİ. HASTALARIMA KARŞI ASLA ŞİDDET UYGULAMAM, BU BİR SAÇMALIKTI! AMA ROSE ONA İNANDI."],
  ["P","JIMMY BENİ OLABİLECEK EN KÖTÜ ŞEYLE SUÇLADI. BU FİKRİ OKUDUĞU GAZETE HABERİNDEN ALDI. HER ŞEYİ O UYDURDU."],
  ["P","ÇAMAŞIR İPİNİ DENEDİM AMA ÇOK İNCEYDİ. SONRA BİRAZ İP BULDUM. OTELİN ANAHTARI HALA BENDEYDİ, BİR GECE GİZLİCE İÇERİ GİRDİM."],
  ["H","ÇİZİM DEFTERİNİ BULDUĞUM ANDA JIMMY'NİN HİKAYEYİ NEREDEN UYDURDUĞUNU ANLADIM. HİKAYE HER DETAYIYLA BİRE BİR AYNIYDI."],
  ["H","JIMMY HER ZAMAN ELEKTRİKLE OYNARDI. HİÇ AKIMA YAKALANMAMIŞ OLMASI İLGİNÇ."],
  ["H","SOPALARI KENDİMİ KORUMAM GEREKİRSE DİYE TUTUYORDUM, AMA ÖFKELENMİŞTİM. BİRİNİ YANIMA ALDIM VE JIMMY'NİN ODASINA GİTTİM."],
  ["H","JIMMY BU TÜR SİLAHLAR BULMUŞ. EŞYALARINI KIRDIKTAN SONRA ONU BİR SÜRE GÖRMEDİM. BİR SONRAKİ NUMARASINA HAZIRLIK YAPTIĞINI TAHMİN ETMELİYDİM."],
  ["H","EĞER JIMMY BODRUMDA SAKLANMAK İSTEDİYSE, BUNUN HOŞUNA GİDECEĞİNİ DÜŞÜNMÜŞTÜM."],
  ["H","JIMMY'NİN İLGİ ÇEKMEK İÇİN NE KADAR İLERİ GİDEBİLECEĞİNİ KİMSE TAHMİN EDEMEZ."],
  ["H","KENDİMİ KAYBETTİM. HER ŞEYİ KIRMIZI GÖRMEYE BAŞLADIM, ONDAN NEFRET ETTİM. KONTROLÜMÜ KAYBETMİŞTİM."],
  ["H","O BİR HANÇER BİLE DEĞİLDİ! AMA DEMEK Kİ DERSİMİ HİÇ ÖĞRENEMEMİŞİM, JIMMY HER ZAMAN BENDEN BİR ADIM ÖNDEYDİ."],
  ["R","JIMMY 'HUGO PUNCH' ADLI GÖSTERİSİNİ SERGİLEMEYE BAŞLADI. İŞLER İYİ GİDİYORDU. İNSANLAR SIRF ONU İZLEMEK İÇİN GELİYORDU."],
  ["R","AYNALARI KIRMASI İŞİN BAŞLANGICIYDI. YAPTIKLARINI HATIRLAMIYORDU. SONRA DİĞER TUHAF ŞEYLER YAŞANMAYA BAŞLANDI."],
  ["R","JIMMY BİR KADINI ODAYA KAPATIP, BAĞLADI. ONU BULDUM VE KURTULMASINI SAĞLADIM. BİZDEN ŞİKAYETÇİ OLMADI, AMA OLANLARI GAZETECİLERE SÖYLEMİŞ."],
  ["R","JIMMY BÜTÜN HAYATI BOYUNCA HUGO PUCNH İLE KAVGA İÇİNDEYDİ. ARTIK YAŞAMAK İSTEMİYORDU."],
  ["R","HUGO VE BEN EVLENDİK. BAŞLANGIÇTA MUTLUYDUK, SONRA HER ŞEY DEĞİŞTİ."],
  ["R","BİR ÇOCUĞUMUZ OLDUĞUNDA BÜTÜN SORUNLARIMIZIN ÇÖZÜLECEĞİNİ SANMIŞTIM. YANILMIŞIM."],
  ["R","HER ŞEYİ JIMMY'E ANLATTIM. HUGO, JIMMY'İ İKİ YAŞINA KADAR DÖVDÜ. ONU DAHA ÖNCE DURDURMALIYDIM."],
  ["R","JIMMY, HUGO'NUN MEZARINI BULMAYA GİTMİŞTİ. BEN DE YALNIZDIM. NE YAPMAM GEREKTİĞİNİ BİLİYORDUM."],
],

finwords:[

  "Her birimizin içinde<br>tanımadığımız biri vardır.",7,
  "",0.5,
  "Bizimle rüyalarda konuşur,",6,
  "ve bize, bizi kendimizi gördüğümüzden<br>ne kadar farklı gördüğünü anlatır.<br><span class='h8'>Carl Jung</span>",8,
  "V",5,
  "Onları,",4,
  "",0.5,
  "Gecenin Köründe görebilirsin.",5,
  "",16,
  "<span class='hf'>Maya</span><br>Chloe Booyens",5,
  "<span class='hf'>Jimmy Hall</span><br>Huld Martha",5,
  "<span class='hf'>Rose Hall</span><br>Joanna Bond",5,
  "<span class='hf'>Harvey</span><br>Karl Haynes",5,
  "<span class='hf'>Dr Bose</span><br>Rohit Gokani",5,
  "<span class='hf'>Amy Bell</span><br>Daisy Follin",5,
  "<span class='hf'>Yardımcı Oyuncular</span><br>Rachel Alfieri<br>Paige Ryan<br>Sally Alfieri<br>Daniel Alfieri<br>Luke Chase",8,
  "<span class='hf'>Yardımcı Oyuncular</span><br>Sam Follin<br>Jamie Follin<br>Tom Follin<br>Clare Follin",7,
  "<span class='hf'>Özel Teşekkürler</span><br>Mark Wilson<br>Fay Wilkins",7,
  "<span class='hf'>Türkçe Çeviri/Forever Ekibi</span><br>Berkay Doru<br>Orçun Çavuşoğlu<br>Dilay Süllü<br>Bilal Karakuş<br>",7,
  "",1,
  "At Dead Of Night'ı<br>oynadığınız için teşekkür ederiz.",8,
  "",

],

words:[

  "CİHAZI AÇ",
  "CİHAZI KAPAT",
  "BAĞIR",
  "AĞLAYAN AYNAYI KULLAN",
  "SORU SOR",
  "KAPAT",
  "Orada kim var<br>diye sor",
  "Adını<br>sor",
  "Sen misin<br>",
  "İLERLE",
  "BODRUM<br>KATI",
  "ZEMİN<br>KAT",
  "BİRİNCİ<br>KAT",
  "İKİNCİ<br>KAT",
  "ÜÇÜNCÜ<br>KAT",
  "GERİ DÖN",
  "MENÜYÜ<br>AÇ",
  "Jimmy'e seslen",
  "KAPIYI<br>DENE<br>",
  "ODAYI<br>DENE<br>",
  "ODAYA<br>DÖN",
  "ARKADAŞINI<br>GÖNDER",
  "BU İKİSİNİ<br>EŞLEŞTİRDİN",
  "DENE",
  "ASANSÖRÜ<br>ÇAĞIR",
  "BUNU SOR",
  "DOLABA<br>SAKLAN",
  "BANYODA<br>SAKLAN",
  "KAPI GÖZÜNDEN<br>BAK",
  "ODAYA<br>GİR",
  "ARAŞTIR",
  "ODADAN<br>AYRIL",
  "KAPIYI<br>DENE",
  "KAPAT",
  "NOTLARI<br>AÇ",
  "EŞLEŞTİR",
  "KAPIYA<br>DÖN",
  "GÖRDÜKLERİNİ OBJELERLE<br><span style='font-family:arial'>&</span> EŞLEŞTİR",
  "BUNLARI SOR",
  "SOR",
  "SIRADAKİ SAYFA",
  "ÖNCEKİ SAYFA",
  "MERDİVEN KAPISINI DENE",
  "İLERLEMEK İÇİN<br>ÇOK KARANLIK",
  "ODAYA<br>GİR",
  "EĞİTİMDEN<br>ÇIK",
  "CİHAZI BİRİNCİ KATTAKİ DEPODAN AL",
  "AĞLAYAN AYNAYI<br>BULMALISIN",
  "PUSULAYI<br>BULMALISIN",
  "AĞLAYAN AYNA<br>VE PUSULAYI<br>BULMALISIN",
  "KAYIT<br>EDİLDİ",
  "CAMDAN<br>BAK",
  "GÜVENDE DEĞİLKEN MENÜ AÇILMAZ",
  "ÇIK",
  "YANLIŞ ANAHTAR",
  "KAPI AÇILDI",
  "KİLİTLİ KAPIYA DÖN<br>VE ANAHTARI DENE",
  "KAPI KİLİTLENDİ",
  "ÖNCE KAPIYI DENE",
  "ODA ANAHTARINI DENE",
  "ÖNCE KAPININ KİLİDİNİ AÇ",
  "YUKARI GİT",
  "AŞAĞIYA GİT",
  "CİHAZI KULLANMAK İÇİN ÇOK KARANLIK",
  "TEKRAR İLETİŞİME GEÇMEK İÇİN BİRAZ BEKLE",
  "JIMMY ODAYA GİRMEK ÜZERE!",
  "JIMMY'NİN SESİ DUYULUYOR",
  "JIMMY'NİN GÜLMESİ DUYULUYOR",
  "ÖNCE OYUNA BAŞLA",
  "ŞU AN KAYIT EDEMEZSİN",
  "OYUN KAYIT EDİLDİ",
  "AYNAYI KULLANMAK İÇİN ÇOK ERKEN!",
  "DİKKAT ET!<br>JIMMY BU ODADA!",
  "ANAHTAR<br>DELİĞİNDEN<br>BAK",
  "DEPO KAPILARINI KİLİTLEMEMEK EN İYİSİ",
  "CİHAZI<br>AL",
  "AYNAYI KULLANMAK İÇİN ÇOK KARANLIK",
  "DEPO",
  "BİLİNMİYOR",
  "AYNAYI KULLANMAK İÇİN FAZLA AYDINLIK",
  "MENÜYE<br>DÖN",
  "OYUN<br>KAYIT EDİLSİN Mİ?",
  "KURTAR",
  "JIMMY'NİN AYAK SESLERİ DUYULUYOR",
  "JIMMY HIZLICA YAKLAŞIYOR",
  "KAPI KAPANDI",
  "UYANIŞI<br>ATLA",
  "CİHAZI BULMAK İÇİN DEPOLARI ARAŞTIR",
  "ATLA",
  "MESAJI KAPAT",

],

ghostex:[

  "A",
  "İLETİŞİME GEÇİLEN:<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;AMY&#160;&#160;</span>&#10023;<br><br>10 YAŞINDAKİ KIZ",
  "P",
  "İLETİŞİME GEÇİLEN:<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;DR BOSE&#160;&#160;</span>&#10023;<br><br>PSİKİYATRİST",
  "H",
  "İLETİŞİME GEÇİLEN:<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;HARVEY&#160;&#160;</span>&#10023;<br><br>OTEL İŞLETMECİSİ",
  "R",
  "İLETİŞİME GEÇİLEN:<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;ROSE&#160;&#160;</span>&#10023;<br><br>OTEL SAHİBİ",

],

headtex:[

  "<span class='h3'>RUH TESPIT EDICIYI BUL.</span>",
  "<span class='h3'>RUHLARLA İLETİŞIME GEÇMEK İÇİN<br>CİHAZI AÇ.</span>",
  "<span class='h3'>RUHLARI DUYMAK IÇIN CIHAZı AÇ.</span>",
  "<span class='h3'>RUHLARLA İLETİŞİME GEÇMEYE ÇALIŞ</span><br><span class='h2'>(YUKARIDAKİ KONUŞMA SİMGESİNE BAS)</span>",
  "<span class='h3'>BİR RUH İLETİŞİME GEÇMEYE ÇALIŞIYOR.<br>ONA KİM OLDUĞUNU SOR.</span>",
  "<span class='h3'>İLETİŞİME GEÇİLEN: ",
  "<span class='h3'>RUHTAN UZAKTASIN. YAKLAŞMAYI DENE.</span>",
  "<span class='h2'>RUHLARLA İLETİŞİME GEÇTİĞİNDE ONLARA SORULAR SOR. VERDİKLERİ CEVAPLARI EŞLEŞTİR. ALDIĞIN CEVAPLARI YALNIZ OLDUĞUN SIRADA BURADAN GÖRÜNTÜLEYEBİLİRSİN.</span>",

],

gametex:[

  "NORMAL OYUN<br><br><span class='h2'><span style='font-size:150%'>Jimmy seni bulup yakalamaya çalışırken ruhları bulup, sorular sorarak gizemleri çözmeye çalış.</span>",
  "ARAMA & KURTARMA<br><br><span class='h2'><span style='font-size:150%'>Jimmy seni yakalamaya çalışırken arkadaşlarını kurtar. Eğer yakalanırsan oyun biter.</span>",
  "ARAMA & KURTARMA<br><br><span class='h2'><span style='font-size:150%'>Son kayıt noktasından devam et.</span>",
  "<span class='h9'>ZORLUK SEVİYESİNİ SEÇ</span><br><br><span class='h2'><span style='font-size:150%'>Normal veya Extreme seviyelerinden birini seç. Extreme seviyesinde Jimmy'e her yakalandığında daha çok eşya kaybedersin.<br><br>Yeni oyuna başlamak, eski oyun kaydını siler ve başarımlarını sıfırlar.</span>",
  "<span class='h9'>UYARI!</span><br><br><span class='h2'><span style='font-size:150%'>Eğer bunu yaparsan mevcut oyun kaydın silinecek.</span>",
  "<span class='h9'>UYARI!</span><br><br><span class='h2'><span style='font-size:150%'>Bu modda oyun kayıt edilmez. Herkesi tek seferde kurtarman gerekiyor!</span>",

],

getex:[

  "<br>AĞLAYAN AYNAYI<br><br>BULDUN<br><br><span style='font-size:50%'>BUNU KULLANARAK<br>İPUCU ALABİLİRSİN</span>",
  "<br>PUSULAYI<br><br>BULDUN<br><br><span style='font-size:50%'>RUHLARI BULMAK İÇİN<br>OKU TAKİP ET</span>",
  "<span style='font-size:40%>'>ÜZERİNDE ETİKET OLAN<br>BİR ANAHTAR BULDUN<br>",
  "ODA ANAHTARI<br>BULDUN",
  "ODA ANAHTARI<br>BULDUN",

],

roomtex:"ODA",

foundtex:"BURADA",

alreadytex:[

  "HALİHAZIRDA AĞLAYAN AYNAYA SAHİPSİN",
  "HALİHAZIRDA PUSULAYA SAHİPSİN"

],

adtext:[

  "KÜÇÜK KIZIN<br>AĞLAMA SESİ",
  "OYUN SALONU SESLERİ",
  "BİR KIZIN İÇTEN<br>AĞLAMA SESİ",
  "KIZ BİR ŞARKI<br>MIRILDANIYOR",
  "BİRİLERİ KAPIYA<br>NAZİKÇE VURUYOR",
  "TABAK ÇANAK SESLERİ",
  "MUSLUK<br>SESİ",
  "TELEFON ÇEVİRME<br>SESİ",
  "KAPIYA SERTÇE<br>VURMA SESİ",
  "KAPIYA SERTÇE<br>VURMA SESİ",
  "ELEKTRİK AKIMI<br>SESİ",
  "EŞYA KIRILMA<br>SESİ",
  "ARBALET<br>SESİ",
  "METAL KAPIYA<br>VURMA SESİ",
  "ALARM SESİ",
  "HARVEY, JIMMY'E SESLENİYOR",
  "KALABALIĞIN MIRILDANMA<br>SESLERİ",
  "RADYODA ÇALAN<br>MÜZİĞİN SESİ",
  "KALABALIĞIN YUHLAMA SESLERİ",
  "ARALIKLARLA ÇALAN KAPI ZİLİ SESİ",
  "BANYODAN GELEN SU SESİ",
  "VURMA<br>SESİ",
  "MÜZİK SESİ",

],

itdetext:[

  "VALİZLER",
  "KUPALAR",
  "ÇOCUK CÜZDANI",
  "TEREBENTİN VE ÇAKMAK",
  "KILIÇ",
  "VİSKİ ŞİŞELERİ",
  "KORKUNÇ ÇİZİMLER",
  "AŞÇI ŞAPKASI",
  "KANLI KUMAŞ",
  "DIAZEPAM",
  "TAHTA KÜREK",
  "KARALAMA DEFTERİ",
  "ÇAMAŞIR İPİ",
  "ARIZALI ISITICI",
  "KRİKET VE BEYZBOL SOPALARI",
  "ARBALET",
  "PASLI ANAHTARLAR",
  "YANGIN FOTOĞRAFLARI",
  "TABANCA",
  "SÜSLÜ HANÇER",
  "HUGO PUNCH POSTERİ",
  "KIRIK AYNALAR",
  "TEL BOBİN",
  "'ELVEDA' NOTU",
  "NİŞAN YÜZÜĞÜ",
  "ÇINGIRAK",
  "DOĞUM BELGESİ",
  "BODRUMDAKİ KIZ",
  "JIMMY, AMY'NİN EŞYALARINI ÇALIYOR",
  "AMY YANAN BİR OYUNCAĞI TUTUYOR",
  "AMY ODANIN DIŞINDA",
  "AMY TADI KORKUNÇ BİR ŞEY İÇİYOR",
  "AMY MERDİVENLERİN BAŞINDA",
  "AMY MERDİVENLERDE HAREKETSİZ YATIYOR",
  "TAKIM ELBİSELİ BİR ADAM KAPIYI ÇALIYOR",
  "DR BOSE ÖLÜ BİR HAYVAN BULUYOR",
  "DR BOSE MUTFAĞIN DIŞINDA",
  "DR BOSE KAN TÜKÜRÜYOR",
  "DR BOSE BİR İĞNE TUTUYOR",
  "DR BOSE NELER OLDUĞUNU AÇIKLIYOR",
  "DR BOSE ODASINDA OTURUYOR",
  "DR BOSE OYUN ODASINDA",
  "DR BOSE İNTİHAR EDİYOR",
  "BİR ADAM, JIMMY'NİN YALAN SÖYLEDİĞİNDEN BAHSEDİYOR",
  "HARVEY KAPIDAN BAĞIRIYOR",
  "HARVEY ELEKTRİĞE KAPILDI",
  "HARVEY SOPAYLA BEKLİYOR",
  "HARVEY BACAĞINDAN VURULDU",
  "HARVEY, JIMMY'İ BODRUMA KİLİTLEDİ",
  "BODRUMDA YANGIN ÇIKTI",
  "HARVEY SİLAHINI HAZIRLIYOR",
  "HARVEY BALO SALONUNA DOĞRU İLERLİYOR",
  "HARVEY BIÇAKLANDI",
  "BİR BAYAN BIÇAKLAMA OLAYINI ANLATIYOR",
  "ROSE GİRİŞ KAPISINDA BEKLİYOR",
  "ROSE, HUGO PUNCH'I ANONS EDİYOR",
  "ROSE ÇOK SAYIDA MANKEN BULDU",
  "ROSE MİSAFİRLERDEN ÖZÜR DİLİYOR",
  "ROSE SAKLANIYOR VE İNSANLAR KAPIYI YUMRUKLUYOR",
  "ROSE, JIMMY'İ BULDU",
  "ROSE BİRİNE SALDIRIYOR",
  "ROSE YANIYOR",
  "MUHTEŞEM HUGO SAHNEDE",
  "BAĞIRMA VE ÇIĞLIK SESLERİ",
  "BAĞIRMA SESLERİ VE AŞAĞIYA GİDEN ASANSÖR",
  "JIMMY SÖZ DİNLEMİYOR",
  "JIMMY, AMY'NİN OYUNCAĞINI ISLATTI",
  "JIMMY, AMY'NİN ELİNİN ACISINI DİNDİREMİYOR",
  "AMY KORKUNÇ BİR ŞEY İÇİYOR",
  "DR BOSE JIMMY'NİN ÇİZİMLERİ GÖRDÜ",
  "JIMMY'NİN BİR PLANI VAR",
  "DR BOSE, JIMMY'NİN MİZAHINA ŞAHİT OLDU",
  "DR BOSE, JIMMY ÜZERİNDE İLAÇ KULLANMYA KARAR VERDİ",
  "JIMMY, DR BOSE'U ŞİDDET KULLANMAKLA SUÇLADI",
  "JIMMY, DR BOSE'U TEKRAR SUÇLADI",
  "DR BOSE BİR ŞEYLER YAPIYOR",
  "HARVEY, JIMMY'NİN KARALAMA DEFTERİNİ BULDU",
  "JIMMY ELEKTRİK İLE OYNUYOR",
  "HARVEY, JIMMY'NİN ODASINA SOPAYLA GİTTİ",
  "HARVEY BAŞKA BİR TUZAKTAN ŞÜPHELENDİ",
  "HARVEY KAZAN DAİRESİ ANAHTARINI KULLANDI",
  "HARVEY, JIMMY'NİN DELİRDİĞİNİ FARK ETTİ",
  "HARVEY KONTROLÜNÜ KAYBETTİ",
  "JIMMY BİR ADMI ÖNDE",
  "JIMMY GÖSTERSİNE BAŞLADI",
  "TUHAF ŞEYLER OLMAYA BAŞLADI",
  "GAZETELER BULUNDU",
  "JIMMY'NIN CANINA TAK ETTİ",
  "HUGO İLE İŞLER DEĞİŞTİ",
  "BEBEK HİÇBİR ŞEYİ ÇÖZMEDİ",
  "GERÇEK ORTAYA ÇIKTI",
  "ROSE SUÇUNU KABUL ETTİ",
  "DEPO ANAHTARI",
  "",
  "",
  "AĞLAYAN AYNA",
  "PUSULA",
  "BİRİNCİ KATIN MERDİVEN ANAHTARI",
  "",
  "",
  "AĞLAYAN AYNA",
  "PUSULA",
  "DEPO ANAHTARI",
  "",
  "",
  "AĞLAYAN AYNA",
  "PUSULA",
  "İKİNCİ KATIN MERDİVEN ANAHTARI",
  "",
  "",
  "AĞLAYAN AYNA",
  "PUSULA",
  "DEPO ANAHTARI",
  "",
  "",
  "AĞLAYAN AYNA",
  "PUSULA",
  "ÜÇÜNCÜ KATIN MERDİVEN ANAHTARI",
  "",
  "",
  "AĞLAYAN AYNA",
  "PUSULA",
  "DEPO ANAHTARI",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "OTELİN ÇIKIŞ KAPISININ ANAHTARI",
  "BODRUMDAKİ DEPONUN ANAHTARI",

],

keyfinds:[

    "'DEPO'",
    "'MERDİVEN<br>(1. KAT)'",
    "'MERDİVEN<br>(2. KAT)'",
    "'MERDİVEN<br>(3. KAT)'",

  ],

gnames:[
  "AMY",
  "DR BOSE",
  "HARVEY",
  "ROSE",
  "HUGO"
],

transcred:"TÜRKÇE ÇEVİRİ 'FOREVER EKİBİ' TARAFINDAN YAPILDI",

extras:[
  "SEA VIEW OTELİNE<br>HOŞ GELDİNİZ<br><span style='font-size:50%'>İÇERİ BUYURUN</span>",
  "MAYA:",
  "OYUN KAYIT EDİLDİ",
  "OYUN KUMANDASI BAĞLANDI",
  "OYUN KUMANDASI ÇIKARILDI",
],

};
