var ITA={

mentex:[

"Guida all'Uso del<br><span class='bt1'>Ricevitore Vocale Fantasmi e Spiriti<br></span>Edison<br><br><br>Sulla Comunicazione Sovrannaturale (un avvertimento)<br><br>Quando si contatta un Fantasma o uno Spirito, il loro stato emotivo si traduce direttamente nel loro potenziale elettrico o stato 'energetico'. I Fantasmi possono manifestarsi in stati energetici alti o bassi, ma per la comunicazione vocale serve uno stato energetico basso.<br><br>Si può spingere i Fantasmi a passare da uno stato energetico all'altro con domande provocatorie o aggressive. Se un Fantasma entra in uno stato energetico alto, questo dispositivo riceverà solo un forte rumore statico e la comunicazione non potrà procedere oltre.<br><br>I Fantasmi in uno stato energetico alto spesso si manifestano fisicamente, senza aiuti elettronici o ottici. Questo di solito si verifica in un luogo diverso. Tieni presente che le entità soprannaturali sono le anime dei Morti. Cerca di trattarle con il dovuto rispetto.",

"energia aumentata<br>dalla conversazione<br><br>STATO BASSO<br><br><br><br><br>LA VOCE SI<br>PUÒ SENTIRE",

"<br><br><br>STATO ALTO<br><br><br><br><br>POTREBBE MANIFESTARSI<br>FISICAMENTE<br><br>energia dissipata<br>dalla manifestazione",

"<div class='ht'><span style='font-size:170%'>Consigli per Giocare</span><br><br>Gioca At Dead Of Night nel cuore della notte, o almeno in una stanza buia, e assicurati che ci siano meno rumori di sottofondo possibili, oppure usa le cuffie se giochi da solo.<br><br>Dovrai essere in grado di vedere nelle aree più scure dell'immagine poiché gran parte dell'hotel è buio e l'ombra di Jimmy si vede appena a volte. Usa la luminosità (tasti U/I) per far apparire le ombre, se necessario.<br><br>Puoi sentire la voce di Jimmy se si trova sul tuo stesso piano. Se ascolti attentamente puoi anche sentire i suoi passi, che ti fanno capire quanto è vicino. Anche i fantasmi emettono suoni. Se vuoi ascoltare con più attenzione, premi 'D' per ridurre un attimo i suoni di sottofondo.<br><br>Se ti serve assistenza uditiva, seleziona l'opzione 'Descrizione Avanzata' in 'Sottotitoli'. Se non ti serve questa assistenza, ti consigliamo di lasciarla disattivata.<br><br>Le bussole puntano verso i fantasmi anche attraverso i muri, quindi se non riesci a trovare un fantasma nella direzione in cui sta puntando, prova a camminare per i corridoi. Le bussole girano lentamente quando non ci sono fantasmi nelle vicinanze e vanno più veloce quando sei proprio vicino a uno di essi.<br><br>Ricorda che puoi guardare attraverso i buchi delle serrature per vedere nelle stanze e puoi correre più velocemente nei corridoi lunghi spostando la freccia verso la parte alta dello schermo.</div>",

"<div class='ht'><span style='font-size:170%'>Jimmy e il DDI</span><br><br>La storia di Jimmy è una rappresentazione teatrale e simbolica di qualcuno che lotta tra due percorsi morali opposti e non vuole essere una raffigurazione letterale del vero disturbo psicologico noto come DDI, o Disturbo Dissociativo d'Identità.<br><br>Il vero DDI è una malattia angosciante e debilitante, spesso (ma non sempre) associata a un abuso nell'infanzia. Il DDI non è in alcun modo correlato a comportamenti immorali o criminali. I malati di DDI hanno bisogno di compassione, ma spesso vengono giudicati male e non degni di fiducia, di solito a seguito d'incomprensioni pubbliche.<br><br>Non era nostra intenzione implicare che Jimmy avesse questo disturbo e accettiamo pienamente che il perpetuare gli stereotipi è dannoso per i malati e impedisce il progresso e la comprensione. Ci scusiamo sinceramente per qualsiasi angoscia o dolore causato a coloro che soffrono di DDI.<br><br>Per altre informazioni, leggere qui:<br><br>https://survivorsnetwork.org.uk/resource/dissociative-identity-disorder-d-i-d/</div>",

"Un Ringraziamento ai<br>Favolosi Talenti Recitativi di<br><br><table><tr><td><span class='h5'>Jimmy</span><br><span class='ht'>Huld Martha</span><br><br><span class='h5'>Rose</span><br><span class='ht'>Joanna Bond</span><br><br><span class='h5'>Dr. Bose</span><br><span class='ht'>Rohit Gokani</span><br><br></td><td><span class='h5'>Maya</span><br><span class='ht'>Chloe Booyens</span><br><br><span class='h5'>Harvey</span><br><span class='ht'>Karl Haynes</span><br><br><span class='h5'>Amy<span><br><span class='ht'>Daisy Follin</span><br><br></td></tr></table><span class='h5'>E Agli Attori Non Protagonisti</span><table><tr><td><span class='ht'>Rachel Alfieri<br>Paige Ryan<br>Sam Follin</span></td><td><span class='ht'>Jamie Follin<br>Clare Follin<br>Tom Follin</span></td></tr></table><br><span class='h5'>Un Ringraziamento Speciale A</span><br><table><tr><td><span class='ht'>Mark Wilson</span></td><td><span class='ht'>Fay Wilkins</span></td><td><span class='ht'>Daniel Alfieri<span></td><td><span class='ht'>Sally Alfieri</span></td><td><span class='ht'>Luke Chase</span></td></tr></table><br><span class='h7'>Creato da Tim 'quindi cosa fai ora' Follin<br>©2020 Baggy Cat Ltd</span></span>",

"&#160;&#160;&#160;&#160;&#160;&#160;&#160;Descrizione Avanzata<br><br><span class='h2'>Aggiunge sottotitoli migliorati e una descrizione testuale dei suoni sentiti durante il gioco, insieme a un indicatore del volume.<br><br>Se non ti serve assistenza, è meglio lasciare questa opzione disattivata.</span>",

"&#160;&#160;&#160;&#160;&#160;&#160;&#160;Sottotitoli<br><br><span class='h2'>Aggiunge sottotitoli base al gioco e al prologo.</span>",

"Non ci sono ancora eventi<br>da rivedere.",

"INIZIA NUOVA PARTITA",

"<span class='h9'>La Storia Di Jimmy Hall</span><br><br><span class='h2'>Scopri i segreti di Jimmy chiedendo agli spiriti riguardo le cose che trovi, quindi stabilisci dei collegamenti per spingerli ad apparire. Jimmy farà del suo meglio per impedirti di scoprire la verità.</span>",

"<span class='h9'>Finale Ultima Partita</span><br><br><span class='h2'>Gioca alla tua ultima partita completata dal punto in cui Jimmy ti ha invitato a incontrare Hugo.</span>",

"<span class='h9'>Il Salvataggio Finale (nuova partita)</span><br><br><span class='h2'>Salva tutte le tue amiche evitando di venir attaccato da Jimmy. Un colpo e sei morto! Questa partita non viene salvata e potrai tornare a quella attuale quando scappi o se vieni attaccato.</span>",

"Guarda Tutorial Completo",

"Guarda da 'L'Inseguimento'",

"Guarda da 'Strategia'",

"Guarda da 'I Morti'",

"Guarda da 'Il Talento di Maya'",

"Guarda Prologo",

"Guarda da 'L'Arrivo di Maya'",

"Guarda da 'Subentra Hugo'",

"Guarda da '2:30 am'",

"Guarda da 'Il Ricevitore Spiritico'",

"Statistiche Partita",

"Inizia Nuova Partita",

"Rivedi Avvistamenti",

"Istruzioni Ricevitore",

"Guarda Tutorial e Intro",

"Sottotitoli e Descrizioni",

"Crediti",

"Consigli per Giocare",

"Jimmy e il DDI",

"Abbandona l'Hotel<br><span class='h2'>Salva ed Esci</span>",

"Sicuro di voler<br>lasciare l'hotel adesso?",

"SÌ, FAMMI USCIRE!",

"<br>NON HAI ANCORA<br>OGGETTI<br>DA VEDERE",

"Jimmy ti ha colpito per l'ultima volta.<br><br>La tua fuga finisce qui.<br><br>Ma puoi sempre riprovare...",

"Entra Nell'Hotel<br><span style='font-size:50%'>Torna all'ultima partita salvata</span>",

"Entra Nell'Hotel<br><span style='font-size:70%'>Inizia Nuova Partita</span>",

"INIZIA PARTITA STANDARD",

"INIZIA PARTITA ESTREMA",

"Salva Partita Attuale",

],

achtex:[

  "Hai completato il",
  "della storia",
  "Hai evitato di essere attaccato",
  "Jimmy ti ha attaccato una volta",
  "Jimmy ti ha attaccato due volte",
  "Jimmy ti ha attaccato",
  "volte",
  "Hai scoperto il segreto dell'hotel",
  "Storia",
  "Completata",
  "Hai",
  "Da Salvare",
  "Hai salvato",
  "Hai salvato tutte le tue amiche",
  "Devi trovare l'uscita dall'hotel",
  "Hai completato il gioco!",
  "Non ci sono ancora statistiche da mostrare",
  "Statistiche di Gioco",
  "Obiettivi",
  "Hai completato la storia di Amy",
  "Hai completato la storia del Dr. Bose",
  "Hai completato la storia di Harvey",
  "Hai completato la storia di Rose",
  "Hai completato la storia principale",
  "Hai completato la storia principale senza venir colpito",
  "Hai completato At Dead Of Night",
  "Hai salvato tutti in una partita veloce",
  "Hai completato At Dead Of Night senza venir colpito!",
  "Ritorna A Sea View",
  "Non hai obiettivi al momento",
  "Il gioco salva dopo gli avvistamenti di fantasmi, quando provochi loro delle reazioni (ma solo dopo aver spento il rilevatore di fantasmi) e se Jimmy ti mette KO.",
  "Hai completato la storia principale in MODALITÀ ESTREMA",
  "Hai completato la storia principale in MODALITÀ ESTREMA senza venir colpito",
  "Hai completato At Dead Of Night in MODALITÀ ESTREMA",
  "Hai completato At Dead Of Night in MODALITÀ ESTREMA senza venir colpito!",
  "Tutte le tue amiche sono uscite sane e salve.",

],

selx:[

  "Non Ho Avuto Una Risposta",
  "Non Hai Ancora Chiesto A Riguardo",
  "Entra in contatto con uno spirito per chiedere di questo",
  "Clicca Un Oggetto Per Vedere La Risposta Di Ogni Spirito",
  "Mettiti davanti alla porta chiusa per provare la chiave",
  "Selezionalo Per Chiedere Di Questo",
  "non ho avuto una risposta",
  "Ha Detto:",
  "FAI BUON VIAGGIO<br>torna presto",
  "Partita Attuale Salvata",
  "Inizia Una Partita Prima",

],

numwo:[

  "Hai solo un amico da salvare",
  "Hai ancora due amici da salvare",
  "Hai ancora tre amici da salvare",
  "Hai quattro amici da salvare",
  "Hai cinque amici da salvare",

],

numwa:[

  "Hai salvato cinque amici",
  "Hai salvato quattro amici",
  "Hai salvato tre amici",
  "Hai salvato due amici",
  "Hai salvato un amico",

],

helx:"<span class='ht'>&#8679;S</span> Salva Partita | <span class='ht'>Esc</span> Attiva/Disattiva Menu | <span class='ht'>D</span> Abbassa Soundtrack | <span class='ht'>Q/W</span> Volume Audio<br><span class='ht'>&#8679;X</span> Uscita Rapida | <span class='ht'>U/I</span> Regola Luminosità | <span class='ht'>O/P</span> Regola Saturazione | <span class='ht'>R</span> Resetta Livelli",

resk:[

  "Hai Trovato<br><br>Cinque Chiavi<br><br><span style='font-size:50%'>Hai cinque amiche da salvare</span>",
  "Aspetta Che<br><br>Se Ne Vada<br><br>",
  "<span style='font-size:50%'>Hai salvato tutti i tuoi amici</span>",
  "<span style='font-size:50%'>Hai 1 amico da salvare</span>",
  "<span style='font-size:50%'>Hai 2 amici da salvare/span>",
  "<span style='font-size:50%'>Hai 3 amici da salvare</span>",
  "<span style='font-size:50%'>Hai 4 amici da salvare</span>",

],

ityptex:[

  "Mostra Tutto",
  "Mostra Oggetti Trovati",
  "Mostra Avvistamenti",
  "Mostra Connessioni",
  "Mostrando chiavi"

],

intros:[

  "Questo è il dispositivo che hai trovato. Selezionalo per accenderlo.",
  "Può rilevare le voci degli spiriti se sei abbastanza vicino a loro.",
  "Se non l'hai ancora fatto, vai al MENU e guarda il Video Tutorial prima di continuare!",
  "Il dispositivo che hai trovato può rilevare le voci degli spiriti se sei abbastanza vicino a loro.",

  "Se non l'hai ancora fatto, vai al MENU e guarda il Video Tutorial prima di continuare!",
  "Questa è una lista delle cose che hai visto e delle chiavi raccolte.",

  "Maya può chiedere agli spiriti riguardo le cose di questa lista.",
  "Questa è una lista delle cose che hai visto e delle chiavi raccolte.",

  "Maya può chiedere agli spiriti riguardo le cose di questa lista.",
  "Puoi usare lo specchio rivelatore solo quando l'icona è visibile,",

  "sia vicino la porta delle camere che nella cucina al piano terra.",
  "Usa lo specchio per avere indizi su dove andare o quali oggetti usare dopo.",
  "Ti aiuterà anche a localizzare chiavi smarrite, bussole e la scatola spiritica.",
  "Puoi usare lo specchio rivelatore solo quando l'icona è visibile,",

  "sia vicino la porta delle camere che nella cucina al piano terra.",
  "Usa lo specchio per avere indizi su dove andare o quali oggetti usare dopo.",
  "Ti aiuterà anche a localizzare chiavi smarrite, bussole e la scatola spiritica.",
  "La bussola punterà verso gli spiriti nelle vicinanze.",

  "Chiedi agli spiriti riguardo le cose che hai visto.",

  "Vedrai la loro risposta quando selezioni l'oggetto.",
  "Abbina due risposte che pensi siano collegate per capire la storia dello spirito.",

  "Accoppia le risposte dell'avvistamento con quelle dell'oggetto per progredire più in fretta.",
  "Se lo spirito smette di rispondere, potrebbe essersi allontanato.",

  "Usa una bussola, cerca luci che sfarfallano e ascolta i suoni.",
  "Inizia le conversazioni con gli spiriti ponendo loro domande introduttive.",

  "Se non ottieni risposta, non ci sono spiriti in giro.",
  "Un forte rumore significa che c'è uno spirito in uno stato energetico alto nelle vicinanze.",
  "Inizia le conversazioni con gli spiriti ponendo loro domande introduttive.",

  "Se non ottieni risposta, non ci sono spiriti in giro.",
  "Un forte rumore significa che c'è uno spirito in uno stato energetico alto nelle vicinanze.",
  "Jimmy Hall ti sta cercando su questo piano. Stagli lontano!",

  "Per provare le chiavi, apri l'inventario, rivolgiti verso la porta e seleziona una chiave.",

  "Le porte si possono bloccare o sbloccare con la chiave giusta.",
  "Per provare le chiavi, apri l'inventario, rivolgiti verso la porta e seleziona una chiave.",

  "Le porte si possono bloccare o sbloccare con la chiave giusta.",
  "Il gioco salverà qui per l'ultima volta.",

  "Ora devi salvare le tue amiche...<br>ma se Jimmy ti prende, hai perso!",
  "Quella era l'ultima<br>persona da liberare.<br>Ora trova l'uscita<br>e scappa!",

  "Muoviti in avanti per mandarla fuori dalla stanza.",

],

substan:[

  "Non lo so.",
  "Forse.",
  "No",
  "VOCE<br>VAGAMENTE<br>UDIBILE/",
  "RADIO<br>STATICA/"

],

subrepa:[
[
  "Pronto?",
  "Ciao",
  "Ciao.",
  "Ciao",
  "Ciao.",
  "Ciao"
],[
  "Pronto?",
  "Pronto?",
  "Salve?",
  "Salve?"
],[
  "Pronto?",
  "Posso sentirti",
  "Posso sentirti.",
  "Posso sentirti."
],[
  "Pronto?",
  "Posso sentirti.",
  "Pronto?",
  "Posso sentirti.",
  "Posso sentirti."
],
],

subrepb:[
[
  "Sono Amy Bell. Ho dieci anni.",
  "Sì, sono Amy.",
  "Sì, sono Amy.",
  "Sì, sono io.",
  "Sì, sono Amy.",
  "Sì, sono Amy.",
  "Sì, sono Amy.",
  "Sì, sono io."
],[
  "Dottor Bose. Sono uno psichiatra clinico.",
  "Sì, sono il Dottor Bose.",
  "Sono il Dottore Bose.",
  "Sì, sono il Dottor Bose.",
  "Sì.",
  "Sì, sono io.",
  "Sono il Dottor Bose, sì."
],[
  "Harvey. Gestisco il posto.",
  "Sì.",
  "Sì, sono Harvey.",
  "Sì. Sono Harvey.",
  "Sì. Sono Harvey.",
  "Sì, sono Harvey."
],[
  "Rose, Rose Hall. Questo è il mio hotel.",
  "Sì.",
  "Sì. Sono Rose.",
  "Sì.",
  "Sì, sono Rose.",
  "Sì.",
  "Sì. Sono Rose."
],
],

subcall:[

  "JIMMY?",
  "EHI!",
  "SONO QUI!",
  "QUAGGIÙ!",
  "DA QUESTA PARTE!",

],

subin:[

  "C'è nessuno?",
  "C'è nessuno?",
  "C'è nessuno?",
  "C'è qualcuno?",
  "C'è qualcuno?",
  "C'è qualcuno?",
  "Chi c'è?",
  "Pronto?",
  "Pronto?",
  "C'è qualcuno?",
  "C'è qualcuno?",

],

subnm:[

  "Sei Amy?",
  "È il Dr. Bose?",
  "Sei Harvey?",
  "Sei Rose?",
  "Come ti chiami?",

],

subrepc:[

  ["H","A Rose, ma non le ha mai usate.","R","Erano mie. Volevo andarmene, ma non ne ho mai avuto la possibilità."],
  ["R","Li aveva comprati Jimmy, per far sembrare che li avesse vinti lui."],
  ["A","Era mia. Era per il mio compleanno, ma me l'hanno rubata.","H","Era la borsetta di quella bambina, poverina.","R","Apparteneva alla bambina."],
  ["A","Non sapevo cosa fossero, finché Jimmy non me l'ha mostrato.","P","Faresti meglio a chiederlo a Jimmy.","H","Erano cose mie, ma non le tenevo insieme.","R","Non lo so. Appartenevano ad Harvey."],
  ["A","Ce l'aveva Jimmy. Non mi piaceva.","P","Ho visto Jimmy che ci giocava. Ho pensato che fosse pericoloso.","H","Avevamo un espositore di armi medievali. L'aveva rubata Jimmy.","R","Apparteneva a un'armatura che avevamo. Ma è scomparsa."],
  ["A","Non lo so, ma i bambini non dovrebbero bere alcolici.","P","Probabilmente erano del bar.","H","Non ricordo, ma non c'è niente di sbagliato nel bersi qualcosa.","R","Harvey deve averle messe lì."],
  ["A","Li disegnava il ragazzo.","P","Jimmy. Era solito disegnarli.","H","Secondo te? Jimmy! Aveva un'immaginazione molto violenta, il piccolo Jimmy.","R","Jimmy disegnava immagini sulla guerra. Era come la maggior parte dei ragazzi."],
  ["P","Jimmy l'aveva trovato e indossato.","H","Del cuoco! Chi altro indossa un cappello da cuoco?","R","Lo indossava il nostro cuoco."],
  ["A","Potrebbe essere mio.","P","Era mio. L'avevo tenuto, nel caso mi fosse servito come prova.","H","Non lo so, ma potrebbe aver avuto qualcosa a che fare con il dottore."],
  ["P","Può aiutare a trattare il comportamento impulsivo in alcune persone.","H","Probabilmente l'ha lasciato il dottore","R","Apparteneva al Dottor Bose."],
  ["P","Non lo so, ma l'aveva trovata Jimmy.","H","Era sempre sotto il bancone alla reception. Non so da dove venisse.","R"," Apparteneva a mio marito."],
  ["A","L'aveva fatto Jimmy. Non so perché. Era strano.","P","L'aveva fatto Jimmy. Era un avvertimento, me lo sarei dovuto aspettare.","H","Jimmy - teneva ritagli di notizie su insegnanti e medici violenti. Non era un bambino normale.","R","Harvey disse che l'aveva fatto Jimmy. Non ricordo."],
  ["P","Li avevo legati insieme. È stato un esperimento."],
  ["H","Dava delle scosse elettriche. L'avevo tenuta in modo che la polizia potesse controllarla.","R","Harvey l'aveva messa via. Disse che era pericolosa."],
  ["A","Non lo so. Ci giocava il ragazzo.","P","Le teneva Harvey. Non so perché.","H","Le avevo tenute, in caso mi fossero servite.","R","Appartenevano a mio marito, quando faceva l'insegnante."],
  ["A","Era nell'armadietto, in albergo. L'ho vista.","P","L'hotel aveva un espositore di vecchie armi.","H","Era di un espositore d'armeria che avevamo. A Jimmy piaceva molto.","R","Viene da un espositore che aveva Harvey. Ma non mi piaceva che stesse in albergo."],
  ["H","Erano per la vecchia porta del locale caldaia.","R","Erano del locale caldaia. Ma abbiamo dovuto sostituire la porta."],
  ["P","Non ne ho mai sentito parlare.","H","Sì - sono riusciti a contenerlo, ma ho perso un sacco di cose.","R","Sì. Ma l'abbiamo fermato in tempo, prima che si espandesse."],
  ["P","Era di Harvey. Non mi piaceva averla in albergo.","H","Era mia. Apparteneva a mio padre. Aveva ancora qualche colpo dentro.","R","Di Harvey. Ma stava nella mia camera da letto."],
  ["A","Me l'aveva mostrato Jimmy. Ma non era suo.","H","Non è un pugnale, è un tagliacarte. Non dovrebbe essere affilato.","R","Era un tagliacarte. Era un regalo di qualcuno."],
  ["R","Era lo spettacolo comico di Jimmy."],
  ["P","Non li ho mai visti.","H","Non me lo ricordo.","R","Li aveva rotti Jimmy."],
  ["A","Jimmy lo portava in giro con sé.","P","Apparteneva a Jimmy. Lo teneva sempre in tasca. Non mi ha mai detto per cosa lo usava.","H","Jimmy lo portava con sé. Non ho idea del perché.","R","Jimmy si portava dei cavi con sé. Gli piaceva giocare con l'elettronica."],
  ["R","L'ha scritto Jimmy."],
  ["H","Probabilmente appartiene a Rose.","R","Era mio. Qualcuno mi aveva fatto un'offerta che non potevo rifiutare."],
  ["A","Non lo so. Non ho visto nessun neonato.","R","Era per il piccolino. Lo tenevo nel cassetto del comodino."],
  ["R","Jimmy è il figlio di Hugo. Sotto ogni aspetto."],
  ["A","Ero io - un ragazzo di nome Jimmy mi aveva rinchiusa nel seminterrato. Poi ha iniziato a rubarmi delle cose.","P","Era la figlia di un ospite dell'hotel. Jimmy non era gentile con lei.","H","Alloggiava in hotel con la sua famiglia.","R","Era un'ospite dell'hotel."],
  ["A","Perché pensava che fosse divertente. Me l'ha restituito, ma poi l'ha rovinato lo stesso.","P","Non ne ho idea, è solo il genere di cose che faceva.","H","Chissà. Probabilmente pensava che fosse divertente.","R","Non era stato lui. La bambina mentiva. Jimmy non aveva rubato nulla."],
  ["A","La mia mano si era bruciata, faceva davvero male, ma non potevo dirlo a nessuno.","P","La sua mano era ustionata abbastanza gravemente, ma Jimmy pensava che fosse tutto uno scherzo.","H","Era ustionata, piuttosto gravemente.","R","Era ustionata, ma continuava a fare cose così pericolose. Era strana."],
  ["A","Stavo cercando di trovare un dottore, ma Jimmy mi ha minacciata e mi ha fatta restare.","H","Probabilmente aveva paura di Jimmy.","R","Non lo so, poteva essere qualsiasi cosa. Era una ragazza strana."],
  ["A","Il ragazzo mi aveva detto che era una medicina. Aveva un sapore orribile.","P","Non ero lì allora, ma penso che abbia bevuto degli alcolici."],
  ["A","Mi sentivo molto leggera, pensavo davvero di poter saltare e arrivare in fondo.","P","Jimmy aveva fatto bere troppo la ragazza.","H","Aveva bevuto una bottiglia di whisky, non sapeva cosa stava facendo.","R","Non lo so. Non sapevo molto di lei."],
  ["A","Sono saltata, ma poi è diventato tutto buio e non sono riuscita a svegliarmi. Non posso più svegliarmi. Non so dove sono.","P","È caduta per le scale dall'ultimo piano. Era troppo ubriaca per sapere cosa stava facendo. Era il motivo per cui Rose mi aveva contattato.","H","È caduta dall'ultimo piano, giù per le scale. Sapevo che c'era Jimmy dietro, doveva essere così.","R","È caduta. Harvey aveva incolpato Jimmy per questo. Era colpa della bambina, non di Jimmy."],
  ["P","Ero io - Avevo ricevuto una chiamata da Rose, la madre di Jimmy. Voleva che parlassi con lui, che scoprissi cosa lo turbava. Ma Harvey era preoccupato per la mente di Jimmy, per le cose che immaginava.","H","Era il Dottor Bose. Doveva aiutare Jimmy, ma era senza speranza.","R","Dottor Bose. Era venuto ad aiutare Jimmy."],
  ["P","Jimmy stava uccidendo cose, uccellini, animali. Avevo capito che doveva lavorare sulle sue capacità empatiche. Così gli ho chiesto di pensare a qualcosa di carino da fare per me. Rimasi sorpreso nel vedere che ebbe subito un'idea.","H","Jimmy aveva detto di averlo trovato da qualche parte. Cosa ci stesse facendo è un'altra storia.","R","Harvey disse che probabilmente era stato proprio Jimmy a ucciderlo, ma io non gli ho creduto."],
  ["P","Jimmy mi stava preparando un panino. Lo portò in camera mia, come avevo chiesto. All'inizio non sospettavo che ci fosse qualcosa che non andava.","H","Il dottore stava cercando d'istruire Jimmy, di convincerlo ad aiutare. Grosso errore.","R","Il Dottor Bose continuava a cercare di far fare a Jimmy cose che non voleva fare."],
  ["P","Jimmy aveva messo dei vetri rotti nel mio panino. Mi sono quasi strozzato. Avevo tenuto il panno e il vetro in modo da poter andare alla polizia, ma mi resi conto di aver sottovalutato la malattia di Jimmy. Dovevo semplicemente intensificare il suo trattamento, con urgenza.","H","Ha imparato a conoscere Jimmy con le cattive. Gli scherzi di Jimmy andavano sempre troppo oltre.","R","Si era tagliato. Ma poi ha cercato d'incolpare Jimmy. Ha fatto tutto da solo, non è stato Jimmy."],
  ["P","Jimmy si era rifiutato di farsi somministrare il farmaco. Ho dovuto inseguirlo in giro per l'albergo. Poi ha detto a Rose che avevo cercato di costringerlo a prenderlo, che avevo usato la violenza. Era ridicolo!","H","Non lo so, non ero lì.","R","Stava cercando di curare Jimmy, senza il mio permesso."],
  ["P","Ero preoccupato che Rose avrebbe creduto a Jimmy. Era una palese bugia. Ma sono riuscito a convincere Rose che Jimmy stava mentendo.","H","Era preoccupato per cos'altro avrebbe potuto dire Jimmy su di lui. E aveva ragione ad esserlo.","R","Perché era preoccupato per la sua reputazione. Non sapevo a chi credere. Ma decisi di dargli un'altra possibilità."],
  ["P","Quando si accorse di essere stato sorpreso a mentire, pensavo che avrebbe iniziato a interagire con me e a fare quello che gli chiedevo. Invece s'inventò un'altra bugia. Solo che questa era molto peggio. La peggiore.","R","Stava parlando con Jimmy, cercava di controllarlo. Voleva fargli fare cose cattive. Non avrei mai dovuto fidarmi di lui."],
  ["P","Rose mi ha denunciato. Sapevo che mi avrebbero rovinato. Non avevo carriera, né futuro. Decisi di prendere il controllo, una volta per tutte.","H","Stavano per arrestarlo. Jimmy l'aveva rovinato. Ma io non ci credevo.","R","Erano venuti ad arrestarlo. Ha avuto quello che si meritava"],
  ["P","Ne avevo abbastanza. Non c'era modo di tornare indietro. La mia vita era finita in ogni caso.","H","Perché era stato spinto a farlo. Tutti pensavano che avesse... toccato Jimmy. Jimmy era intelligente, vedi, troppo intelligente. Il dottore non aveva possibilità. Povera anima.","R","Perché sapeva di essere colpevole. Ha fatto la cosa giusta."],
  ["P","Era Harvey. Sapeva che Jimmy mentiva su di me. Harvey capiva.","H","Ero io. Jimmy aveva accusato il dottore. Rose gli credeva, ma avevo già sentito quella storia da qualche parte.","R","Era Harvey. Non credeva a quello che diceva Jimmy. Ma sapevo che non stava mentendo."],
  ["P","Jimmy non ha mai ammesso le sue bugie.","H","Certo che non lo fece! Si mise solo a ridere. Poi ha iniziato a prepararmi delle piccole trappole. Alcune non così piccole.","R","No - come poteva Jimmy ammettere qualcosa che non era vero? Harvey aveva torto a fare il prepotente con Jimmy in quel modo."],
  ["H","Sapeva che quella era la mia stufa, aveva collegato il rivestimento direttamente alla rete elettrica. Mi aveva quasi ucciso. L'ha fatto deliberatamente, ma Rose non ci credeva. Sapevo che gli serviva una lezione. Aveva danneggiato la mia proprietà, quindi io decisi di danneggiare la sua.","R","Harvey incolpò Jimmy, ma quella stufa era difettosa. Harvey avrebbe dovuto buttarla via."],
  ["P","Non lo so, ma la violenza non fa che peggiorare le cose.","H","Avevo distrutto la sua televisione, le console e roba del genere. Ero arrabbiato, ma non ha funzionato. Lo fece solo peggiorare. Presto si vendicò.","R","Aveva rovinato le cose di Jimmy. Non riusciva a controllare la sua rabbia."],
  ["H","Jimmy l'aveva impostata per sparare quando avessi aperto la porta. Sono dovuto andare al pronto soccorso, mi hanno messo dei punti e fatto l'antitetanica. Quando sono tornato non sono riuscito a trovarlo. Rose disse che si stava nascondendo nel seminterrato. Mi aveva dato un'idea.","R","Harvey disse che Jimmy gli aveva sparato una freccia, ma sapevo che Jimmy non avrebbe usato un'arma del genere."],
  ["H","Volevo dare a Jimmy una dose della sua stessa medicina. Pensavo che non potesse fare alcun danno laggiù. Mi sbagliavo.","R","Non so cosa stesse facendo."],
  ["P","Non me lo ricordo.","H","Siamo riusciti a contenerlo prima che sfuggisse di mano. Ma tutte le nostre vecchie foto, lettere e altro erano laggiù; era andato tutto in fumo. Jimmy era fuori controllo, ne avevo abbastanza di lui. Volevo che se ne andasse.","R","Harvey incolpò Jimmy, ma era stato un filo scoperto a provocare l'incendio. È stato un incidente."],
  ["P","Non lo so. Ma Harvey non riusciva a controllare la sua rabbia.","H","Non so cosa avrei fatto. Minacciarlo, buttarlo fuori dall'hotel.... Il problema era che non sapevo che anche lui sarebbe stato armato.","R","Non lo so. Harvey non avrebbe dovuto tenere una pistola in albergo."],
  ["H","Stavo cercando Jimmy."],
  ["H","Jimmy si è avvicinato di soppiatto dietro di me, non l'avevo visto. Jimmy vince sempre alla fine.","R","Harvey era impazzito. Jimmy si stava solo difendendo."],
  ["H","Rose - Rose credeva a Jimmy. L'ha difeso, fino alla fine.","R","Ero io. Ho dovuto spiegare alla polizia che il pugnale era solo un tagliacarte e che Harvey aveva una pistola carica. Jimmy ha agito per legittima difesa. Hanno capito."],
  ["H","Jimmy - avevano lasciato andare Jimmy. Hanno detto che era legittima difesa, che avevo provato a sparargli. Ma erano tutte bugie.","R","Jimmy - stava tornando a casa. La polizia aveva capito. Gli avevano creduto, ma era cambiato. Ha iniziato ad aiutarmi, per gestire l'albergo. E ha trovato un modo per portare altri ospiti."],
  ["H","Non so chi fosse.","R","Mi stavo divertendo, stavamo guadagnando di nuovo. Tutto sembrava migliorare fino a quando... Jimmy ha iniziato a comportarsi in modo strano. Lo sentii gridare, si fissava. Sembrava arrabbiato."],
  ["R","Jimmy - all'inizio non capivo, ero confusa. Ma poi capii. Non era Jimmy che faceva queste cose. Come gli specchi, stava iniziando a frantumarsi. Jimmy non aveva più il controllo."],
  ["H","Non lo so, ma so che alla fine Jimmy ha sempre rovinato tutto.","R","Non era più Jimmy quello sul palco, era Hugo Punch, il suo personaggio comico. Hugo ha iniziato a insultare il suo pubblico ogni sera. Sembrava divertirsi. Poi un giorno, dopo lo spettacolo, un'ospite disse a Jimmy cosa pensava di lui. Jimmy perse la pazienza. Fece qualcosa di stupido."],
  ["R","Giornalisti, volevano Jimmy. Ma Jimmy non aveva il controllo, era Hugo Punch che aveva legato la donna. Jimmy non poteva più controllarlo. Era depresso. Voleva solo lasciarsi tutto alle spalle e andarsene."],
  ["R","Era Jimmy. Aveva cercato di uccidersi. Ecco perché dovevo dirgli la verità."],
  ["H","Non lo so. C'erano cose che Rose non mi ha mai detto.","R","Hugo - L'ho seppellito laggiù nel cemento, in una stanza segreta. Avrei dovuto farlo prima. L'ho lasciato abusare di Jimmy per troppo tempo. È stata colpa mia se Jimmy è diventato quello che è. Pensavo che il senso di colpa sarebbe svanito se glielo avessi detto. Mi sbagliavo, ha peggiorato solo le cose. Non potevo accettare quello che avevo fatto. Non potevo convivere con me stessa."],
  ["R","Se non l'avessi fatto io ci avrebbe pensato Jimmy, o meglio, Hugo a farlo. È ancora al comando, anche adesso. Lo sta controllando. Chiedi a Jimmy di mostrarti dove vive Hugo."],
  ["H","Non l'ho mai conosciuto.","R","Era un mago e un intrattenitore. Aveva comprato l'albergo per promuovere il suo spettacolo teatrale. Era diventato famoso, era in televisione. Ho lavorato come sua assistente, poi le cose si sono.... sviluppate."],
  ["R","Non ho mai saputo cosa voleva. C'era solo una cosa che potevo dargli."],
  ["R","Hugo era un uomo violento, malvagio e malato."],
  ["A","Sì, l'ha presa quando non stavo guardando e mi ha rubato i soldi. L'ho rimproverato ma non mi ha voluta ascoltare."],
  ["A","Ha inzuppato il mio giocattolo con quella roba nella bottiglia, lo odiavo!"],
  ["A","Sì - l'ha tirata giù dal muro, sembrava davvero affilata. Mi ha fatto promettere di non dirlo a nessuno e ha detto che poteva far sparire il dolore alla mia mano."],
  ["A","Forse - mi ha detto di continuare a berlo. Era orribile. Poi ho iniziato a sentirmi strana...."],
  ["P","Sì, suggerivano una personalità turbolenta, ma non ero particolarmente preoccupato finché... non ho iniziato a capire fino a che punto arrivava la sua immaginazione."],
  ["P","Sì - Jimmy disse che avrebbe fatto qualcosa per me, quindi l'ho seguito per vedere cosa intendeva."],
  ["P","È stato il mio primo incontro con il senso dell'umorismo di Jimmy."],
  ["P","Non era il farmaco ideale, ma era tutto quello che avevo. Jimmy aveva bisogno di cure immediate; era pericoloso."],
  ["P","Jimmy disse che avevo usato la pagaia per picchiarlo. Non avrei mai usato la violenza su un paziente, era ridicolo! Ma Rose gli credeva."],
  ["P","Jimmy mi ha accusato del peggior crimine possibile. L'ha preso da un articolo di giornale che aveva letto. Si stava inventando tutto."],
  ["P","Ho provato con lo stendibiancheria, ma era troppo sottile. Poi ho trovato un po' di corda. Avevo ancora le chiavi dell'hotel, quindi una notte mi ci sono intrufolato mentre ero in libertà provvisoria."],
  ["H","È venuto direttamente da lì! Non appena ho trovato quell'album di ritagli, ho capito da dove l'aveva preso Jimmy. Era lo stesso, fin nei minimi dettagli."],
  ["H","Jimmy giocava sempre con l'elettricità. Buffo che non sia mai stato lui a prendere la scossa."],
  ["H","Ho tenuto quelle mazze per autodifesa, ma ero arrabbiato. Ne presi una e andai nella stanza di Jimmy."],
  ["H","Jimmy amava armi del genere. Non l'avevo visto per tutta la notte dopo aver distrutto le sue cose. Avrei dovuto immaginare che stesse lavorando al suo prossimo scherzetto."],
  ["H","Beh, se Jimmy voleva nascondersi laggiù, immaginavo che gli piacesse stare lì."],
  ["H","Nessuno si rese conto fino a che punto Jimmy si sarebbe spinto per attirare l'attenzione."],
  ["H","L'avevo perso. Vedevo rosso, lo odiavo. Avevo perso il controllo."],
  ["H","Non era nemmeno un pugnale! Ma non ho mai imparato la lezione, Jimmy era sempre un passo avanti a me."],
  ["R","Sì, quello era lo spettacolo di Jimmy. Era un comico. Era bravo, davvero bravo. La gente ha iniziato a venire solo per vederlo."],
  ["R","Rompere gli specchi è stato solo l'inizio. Gli chiesi spiegazioni ma non si ricordava di averlo fatto. Poi sono iniziate altre cose strane."],
  ["R","Jimmy la chiuse a chiave in una stanza e la legò. Non sapevo cosa avrebbe fatto. L'ho trovata e l'ho lasciata andare. Jimmy disse che era uno scherzo! Lei non ha sporto denuncia, ma l'ha detto ai giornali."],
  ["R","Jimmy odiava quello che aveva fatto. Aveva combattuto contro Hugo Punch per tutta la vita. Era dentro di lui, gli faceva fare tutte quelle brutte cose. Jimmy non voleva più vivere."],
  ["R","Sì - eravamo sposati. All'inizio eravamo felici, prima che le cose iniziassero a cambiare."],
  ["R","Pensavo che avere un figlio avrebbe risolto tutto. Mi sbagliavo."],
  ["R","Ho ammesso tutto a Jimmy. Lui non si ricordava di Hugo, aveva bloccato il suo ricordo. Hugo aveva picchiato Jimmy da quando era nato, per 2 anni. Avrei dovuto fermarlo prima."],
  ["R","Non avevo scelta. Jimmy era andato a cercare la tomba di Hugo. Ero sola. Sapevo cosa avrei dovuto fare."],

],

subob:[

  ["Ho visto delle valigie in una cassa. A chi appartenevano?",
  "è collegato a quello che avevi detto sulle valigie?"],

  ["Ho trovato dei trofei. Chi li ha vinti?",
  "ha qualcosa a che fare con quello che avevi detto sui trofei?"],

  ["A chi apparteneva la borsetta da bambina?",
  "è collegato a quello che hai detto riguardo la borsetta?"],

  ["Ho visto una bottiglia di trementina e un accendino. A cosa servivano?",
  "ha a che fare con quello che hai detto sulla trementina e l'accendino?"],

  ["A chi appartiene la spada?",
  "ha a che fare con quello che avevi detto riguardo la spada?"],

  ["Perché c'era una serie di bottiglie di whisky in una delle stanze?",
  "c'entra qualcosa con quello che hai detto sulle bottiglie di whisky?"],

  ["Chi ha disegnato quelle immagini violente?",
  "ha qualcosa a che fare con quello che hai detto sulle immagini violente?"],

  ["A chi apparteneva il cappello da cuoco?",
  "è collegato a quello che avevi detto sul cappello da cuoco?"],

  ["Perché c'è un panno macchiato di sangue in uno dei cassetti?",
  "ha a che fare con il panno macchiato di sangue?"],

  ["Da dove viene la boccetta di Diazepam?",
  "ha qualcosa a che fare con quello che hai detto riguardo il diazepam?"],

  ["Da dove viene la pagaia di legno?",
  "è collegato a quello che hai detto sulla pagaia di legno?"],

  ["Ho visto un album con ritagli di articoli di giornale. Chi l'ha fatto?",
  "ha qualcosa a che fare con quello che hai detto sull'album di ritagli?"],

  ["Perché c'era uno stendibiancheria legato attorno a un mattarello?",
  "c'entra qualcosa con quello che hai detto sullo stendibiancheria e il mattarello?"],

  ["Perché c'è una vecchia stufa etichettata come 'pericolosa'?",
  "ha a che fare con quello che avevi detto a proposito della stufa pericolosa?"],

  ["A cosa servivano tutte le mazze da cricket e da baseball?",
  "ha a che fare con quello che hai detto sulle mazze da baseball e da cricket?"],

  ["Da dove viene la balestra?",
  "ha qualcosa a che fare con quello che hai detto riguardo la balestra?"],

  ["A cosa servono quelle vecchie chiavi arrugginite?",
  "ha a che fare con quelle chiavi arrugginite?"],

  ["C'è stato un incendio nell'hotel?",
  "è collegato a quello che avevi detto a proposito dell'incendio all'hotel?"],

  ["A chi appartiene la pistola?",
  "ha qualcosa a che fare con quello che avevi detto sulla pistola?"],

  ["A chi appartiene il pugnale?",
  "ha qualcosa a che fare con quello che hai detto sul pugnale?"],

  ["Chi è Hugo Punch?",
  "è collegato a quello che avevi detto sul poster di Hugo Punch?"],

  ["Come si sono rotti quegli specchi?",
  "c'entra con quello che hai detto sugli specchi rotti?"],

  ["A cosa serviva il rotolo di cavo?",
  "ha a che fare con quello che avevi detto sul rotolo di cavo?"],

  ["Chi ha scritto la nota che dice 'Addio'?",
  "è collegato al biglietto d'addio?"],

  ["A chi apparteneva l'anello nuziale?",
  "ha a che fare con la fede nuziale?"],

  ["A chi apparteneva il sonaglio da neonato?",
  "ha qualcosa a che fare con il sonaglio da neonato?"],

  ["Ho trovato il certificato di nascita di Jimmy. Dice che Hugo Hall è il vero padre di Jimmy.",
  "c'entra con quello che hai detto sul certificato di nascita di Jimmy?"],

  ["Ho visto una bambina nel seminterrato, piangeva. Chi era?",
  "",
  "Quando hai detto che Jimmy ti ha rubato delle cose,",
  "Quando hai detto che Jimmy non era gentile con la bambina,",
  "Riguardo quello che hai detto su una bambina che soggiornava in hotel,",
  "Riguardo quello che hai detto sulla bambina che era ospite all'hotel,"],

  ["Ho visto la bambina gridare a Jimmy di ridarle il giocattolo. Perché l'aveva preso?",
  "Ti ho vista gridare a Jimmy di restituirti il giocattolo. Perché l'aveva preso?",
  "Riguardo quello che hai detto di Jimmy che ti aveva rubato il giocattolo,",
  "Quando hai detto che rubare era il genere di cose che faceva Jimmy,",
  "",
  "Quando hai detto che Jimmy non aveva rubato niente,"],

  ["Ho visto la bambina, Amy, che teneva in mano un giocattolo in fiamme. Cos'è successo?",
  "Ti ho vista tenere in mano un giocattolo in fiamme. Cos'è successo?",
  "Hai detto che non potevi dire a nessuno che la tua mano si era bruciata.",
  "Riguardo quello che hai detto sul fatto che per Jimmy, aver dato fuoco al giocattolo di Amy fosse uno scherzo,",
  "Hai detto che la bambina si è gravemente ustionata.",
  "Quando hai detto che la bambina continuava a fare cose pericolose e incolpava Jimmy,"],

  ["Ho visto Amy fuori da una stanza. Qualcosa l'ha spaventata. Cos'era?",
  "Ti ho vista fuori da una stanza. Qualcosa ti ha spaventata. Cos'era?",
  "Quando hai detto che avevi bisogno di un medico, ma Jimmy ti ha minacciata di restare,",
  "",
  "Quando hai detto che la bambina aveva probabilmente paura di Jimmy,",
  "Quando hai detto che c'era qualcosa di strano nella bambina,"],

  ["Ho visto Amy bere qualcosa. Sembrava che non le piacesse. Cos'era?",
  "Ti ho vista bere qualcosa. Sembrava che non ti piacesse. Cos'era?",
  "Quando hai detto che la medicina aveva un sapore orribile,",
  "Riguardo quello che hai detto della bambina, Amy, che beveva alcolici,",
  "",
  ""],

  ["Ho visto la bambina in cima alle scale, sulla ringhiera. Che stava facendo?",
  "Ti ho vista in cima alle scale, sulla ringhiera. Cosa stavi facendo?",
  "Quando hai detto che pensavi di poter saltare fino in fondo alle scale,",
  "Quando hai detto che Jimmy ha fatto bere troppo la bambina,",
  "Hai detto che Amy aveva bevuto una bottiglia di whisky.",
  ""],

  ["Ho visto Amy riversa in fondo alle scale. Cosa le è successo?",
  "Ti ho vista riversa in fondo alle scale. Cosa ti è successo?",
  "Hai detto che non ti puoi più svegliare.",
  "Hai detto che la morte di Amy era il motivo per cui Rose ti ha contattato.",
  "Riguardo quello che hai detto sul fatto che ci fosse Jimmy dietro la morte di Amy,",
  "Riguardo quello che hai detto sul fatto che è solo colpa di Amy se è morta,"],

  ["Ho visto un uomo bussare a una porta, dicendo a Jimmy che era lì per aiutare. Chi era?",
  "",
  "",
  "Quando hai detto che Harvey era preoccupato per la mente di Jimmy,",
  "Riguardo quello che hai detto sul fatto che Jimmy era senza speranze,",
  "Hai detto che il Dottor Bose era venuto ad aiutare Jimmy."],

  ["Ho visto il Dottor Bose tenere un animale morto su un cavo. Cos'era successo?",
  "Ti ho visto reggere un animale morto su un cavo. Cos'era successo?",
  "",
  "Quando hai detto che Jimmy ha avuto un'idea per fare qualcosa di carino per te,",
  "Riguardo quello che hai detto su Jimmy che diceva di aver trovato l'animale morto da qualche parte,",
  "Quando hai detto che non credevi che Jimmy avesse ucciso quell'animale,"],

  ["Ho visto il Dottor Bose fuori dalla cucina che parlava con Jimmy. Cosa stava facendo?",
  "Ti ho visto fuori dalla cucina che parlavi con Jimmy. Cosa stavi facendo?",
  "",
  "Quando hai detto che non sospettavi che ci fosse qualcosa di strano,",
  "Quando hai detto che è stato un errore per il Dottor Bose cercare di aiutare Jimmy,",
  "Quando hai detto che il Dottor Bose stava cercando di far fare a Jimmy cose che non voleva,"],

  ["Ho visto il Dottor Bose sputare sangue. Cos'è successo?",
  "Ti ho visto sputare sangue. Cos'è successo?",
  "",
  "Quando hai detto che dovevi intensificare urgentemente il trattamento di Jimmy,",
  "Quando hai detto che gli scherzi di Jimmy andavano sempre troppo oltre,",
  "Quando hai detto che il Dottor Bose si è ferito ma ha incolpato Jimmy,"],

  ["Ho visto il Dottor Bose con in mano un ago mentre parlava con Jimmy. Cosa stava facendo?",
  "Ti ho visto con un ago in mano mentre parlavi con Jimmy. Cosa stavi facendo?",
  "",
  "Quando hai detto che Jimmy si rifiutava di farsi somministrare la medicina,",
  "",
  "Hai detto che il Dottor Bose stava cercando di curare Jimmy senza il tuo permesso."],

  ["Ho visto il Dottor Bose cercare di spiegare cos'era successo con Jimmy. Sembrava disperato.",
  "Ti ho visto mentre cercavi di spiegare cos'era successo con Jimmy. Sembravi disperato.",
  "",
  "Quando hai detto di essere riuscito a convincere Rose che Jimmy stava mentendo,",
  "Quando hai detto che il Dottor Bose aveva ragione a preoccuparsi per cos'altro avrebbe inventato Jimmy su di lui,",
  "Quando hai detto che avevi deciso di dare al Dottor Bose un'altra possibilità,"],

  ["Ho visto il Dottor Bose seduto su un letto a parlare con Jimmy. Cosa stava facendo?",
  "Ti ho visto seduto su un letto a parlare con Jimmy. Cosa stavi facendo?",
  "",
  "Hai detto che Jimmy si era inventato un'altra bugia su di te, una bugia molto grave.",
  "",
  "Quando hai detto che non avresti mai dovuto fidarti del Dottor Bose,"],

  ["Ho visto il Dottor Bose sconvolto, la polizia bussava alla porta. Cosa stava succedendo?",
  "Ti ho visto sconvolto e ho sentito la polizia bussare alla porta. Cosa stava succedendo?",
  "",
  "Quando hai detto che avevi deciso di prendere il controllo una volta per tutte,",
  "Hai detto che non credevi alla storia di Jimmy sul Dottor Bose.",
  "Quando hai detto che il Dottor Bose meritava di essere arrestato,"],

  ["Ho visto il Dottor Bose legarsi una corda al collo. Si è ucciso. Perché?",
  "Ti ho visto legarti una corda al collo. Ti sei ucciso. Perché?",
  "",
  "Hai detto che volevi che tutto finisse.",
  "Quando hai detto che il Dottor Bose era stato spinto a suicidarsi,",
  "Quando hai detto che il Dottor Bose aveva fatto la cosa giusta,"],

  ["Ho visto un uomo dire che Jimmy aveva mentito sull'aggressione. Chi era?",
  "",
  "",
  "Quando hai detto che Harvey sapeva che Jimmy mentiva,",
  "Quando hai detto di aver già sentito la storia da qualche parte,",
  "Quando hai detto che Harvey aveva torto a non credere alla storia di Jimmy,"],

  ["Ho visto Harvey gridare, dicendo a Jimmy di ammettere che aveva mentito. Era vero?",
  "Ti ho visto gridare, dicendo a Jimmy di ammettere che aveva mentito. Era vero?",
  "",
  "Riguardo quello che hai detto su Jimmy che non ha mai ammesso le sue bugie,",
  "Quando hai detto che Jimmy ha iniziato a prepararti delle trappole",
  "Hai detto che Harvey non doveva fare il prepotente con Jimmy."],

  ["Ho visto Harvey prendere una scossa elettrica. Cos'è successo?",
  "Ti ho visto prendere una scossa elettrica. Cos'è successo?",
  "",
  "",
  "Quando hai detto che avevi deciso di danneggiare la sua proprietà,",
  "Hai detto che Harvey avrebbe dovuto buttare via quella stufa difettosa."],

  ["Ho visto Harvey con una mazza uscire da una stanza. Cos'ha fatto?",
  "Ti ho visto uscire da una stanza con una mazza. Cos'hai fatto?",
  "",
  "Quando hai detto che la violenza non fa che peggiorare le cose.",
  "Quando hai detto che Jimmy si è subito vendicato,",
  "Riguardo quello che hai detto sul fatto che Harvey non era in grado di controllare la sua rabbia,"],

  ["Ho visto Harvey che veniva colpito a una gamba da una freccia. Cos'è successo?",
  "Ti ho visto venir colpito a una gamba da una freccia. Cos'è successo?",
  "",
  "",
  "Quando hai detto che pensavi che a Jimmy piacesse nascondersi nel seminterrato,",
  "Quando hai detto che Jimmy non avrebbe usato un'arma del genere,"],

  ["Ho visto Harvey rinchiudere Jimmy in cantina. Cos'è successo?",
  "Ti ho visto rinchiudere Jimmy in cantina. Cos'è successo?",
  "",
  "",
  "Hai detto che avevi torto nel pensare che Jimmy non potesse fare alcun danno in cantina.",
  ""],

  ["Ho visto un incendio nel seminterrato. Cos'è successo all'hotel?",
  "Ho visto un incendio nel seminterrato. Cos'è successo all'hotel?",
  "",
  "",
  "Quando hai detto che volevi che Jimmy se ne andasse,",
  "Hai detto che l'incendio nell'hotel era stato un incidente."],

  ["Ho visto Harvey far pratica con una pistola. Cosa voleva fare?",
  "Ti ho visto far pratica con una pistola. Cosa volevi fare?",
  "",
  "Hai detto che Harvey non riusciva a controllare la sua rabbia.",
  "Quando hai detto che non sapevi che anche Jimmy sarebbe stato armato,",
  "Quando hai detto che Harvey non avrebbe dovuto avere una pistola in albergo,"],

  ["Ho visto Harvey dirigersi verso la sala da ballo con una pistola. Cosa stava facendo?",
  "Ti ho visto dirigerti verso la sala da ballo con una pistola. Cosa stavi facendo?",
  "",
  "",
  "Quando hai detto che stavi cercando Jimmy,",
  ""],

  ["Ho visto Harvey venir accoltellato nel backstage. Cos'è successo?",
  "Ti ho visto venir pugnalato nel backstage. Cos'è successo?",
  "",
  "",
  "Quando hai detto che alla fine Jimmy vince sempre,",
  "Quando hai detto che Jimmy si stava solo difendendo,"],

  ["Ho visto una signora spiegare che il pugnale era un tagliacarte. Chi era?",
  "",
  "",
  "",
  "Hai detto che Rose ha difeso Jimmy fino alla fine.",
  "Quando hai detto che la polizia aveva capito che Jimmy aveva agito per legittima difesa,"],

  ["Chi stava salutando Rose all'ingresso della reception?",
  "Chi stavi salutando all'ingresso della reception?",
  "",
  "",
  "Quando hai detto che pensavano avessi provato a sparare a Jimmy,",
  "Quando hai detto che Jimmy ha trovato un modo per portare altri ospiti,"],

  ["Ho visto Rose che annunciava Hugo Punch sul palco.",
  "Ti ho vista annunciare Hugo Punch sul palco.",
  "",
  "",
  "",
  "Riguardo quello che hai detto su Jimmy che si fissava e si arrabbiava,"],

  ["Ho visto Rose in un corridoio pieno di manichini. Chi ce li ha messi?",
  "Ti ho vista in piedi in un corridoio pieno di manichini. Chi ce li ha messi?",
  "",
  "",
  "",
  "Riguardo quello che hai detto su Jimmy che non aveva più il controllo,"],

  ["Ho visto Rose nella sala da ballo. Il pubblico fischiava e lei si scusava. Cosa stava succedendo?",
  "Ti ho vista nella sala da ballo. Il pubblico fischiava e tu chiedevi scusa. Cosa stava succedendo?",
  "",
  "",
  "Hai detto che alla fine Jimmy ha rovinato tutto.",
  "Quando hai detto che Jimmy ha perso la pazienza e ha fatto qualcosa di stupido,"],

  ["Ho visto Rose irritata e persone che bussavano alla porta facendo domande. Chi erano?",
  "Ti ho vista irritata, della gente bussava alla porta facendo domande. Chi erano?",
  "",
  "",
  "",
  "Quando hai detto che Jimmy voleva lasciarsi tutto alle spalle e andarsene,"],

  ["Ho visto Rose in una stanza al piano di sopra. Sembrava che avesse trovato qualcuno in un bagno. Cos'è successo?",
  "Ti ho vista in una stanza al piano di sopra. Sembrava che avessi trovato qualcuno in un bagno. Cos'è successo?",
  "",
  "",
  "",
  "Quando hai detto che dovevi dire a Jimmy la verità,"],

  ["Ho visto Rose attaccare qualcuno con una mazza di legno. Chi era?",
  "Ti ho vista attaccare qualcuno con una mazza di legno. Chi era?",
  "",
  "Hai detto che Rose aveva una storia oscura.",
  "Hai detto che c'erano cose che Rose non ti ha mai detto.",
  "Quando hai detto che non potevi convivere con te stessa,"],

  ["Ho visto Rose, era in fiamme. Cos'è successo?",
  "Ti ho vista, stavi andando a fuoco. Cos'è successo?",
  "",
  "",
  "",
  "Quando hai detto di chiedere a Jimmy di mostrarmi dove vive Hugo,"],

  ["Ho visto qualcuno sul palco. Un artista, che si annunciava come Il Grande Hugo.",
  "",
  "",
  "",
  "Quando hai detto che Hugo era il primo marito di Rose,",
  "Quando hai detto che le cose si sono sviluppate con Hugo,"],

  ["Ho sentito un uomo gridare a qualcuno, dicendogli di fare come diceva lui. Chi era?",
  "",
  "",
  "",
  "",
  "Hai detto che c'era solo una cosa che avresti potuto dare a Hugo."],

  ["Ho sentito un uomo gridare e un bambino piangere. Cos'è successo?",
  "",
  "",
  "",
  "",
  "Hai detto che Jimmy è il figlio di Hugo."],

],

subs:[

  "INTRO",[
   13.6,5,"Jimmy!",14.6,4,"",
   16.2,4,"Jimmy!",17.4,4,"",
   18.8,2,"Jimmy!",20,4,"",
   20.1,6,"VOCI DALL'ALTOPARLANTE",21.6,6,"",
   24.3,3,"Lasciatemi in pace...",25.9,4,"",
   26.5,6,"SINGHIOZZI",27.9,4,"",
   28.6,6,"LE VOCI ECHEGGIANO PIÙ FORTE",30.3,4,"",
   30.7,3,"Smettetela!",31.8,4,"",
   32.4,3,"Vi prego, lasciatemi in pace!",34.8,4,"",
   35.8,6,"VOCI ATTRAVERSO LA STATICA",37.3,4,"",
   44.5,6,"IL TELEFONO SQUILLA",45.6,0,"",
   46.6,1,"Pronto?",47.6,0,"",
   47.7,3,"Maya? Sono Hannah.",48.8,0,"",
   49.4,1,"Hannah? Dove sei?",51.2,0,"",
   51.3,1,"Siete andate tutte via e mi avete lasciata indietro!",53.6,0,"",
   53.7,1,"Dove siete adesso? Che numero è questo?",55.6,0,"",
   55.7,3,"Abbiamo tutti prenotato un hotel lungo la strada.",57.4,0,"",
   57.5,3,"Quanto sei lontana?",58.8,0,"",
   58.9,1,"Non lo so. Dovrò chiamare quando arrivo.",61.1,0,"",
   61.2,3,"Non puoi, non c'è segnale.",62.9,0,"",
   63,1,"Beh...",64.1,1,"",
   65,1,"Non importa. Vai a letto Hannah.",67,0,"",
   67.1,3,"Beh, ascolta. Assicurati di essere...",68.3,0,"",
   68.6,6,"LA CHIAMATA S'INTERROMPE",70.1,0,"",
   71,6,"CHIAMATA CONCLUSA",72.5,0,"",
   84,6,"MUSICA JAZZ ANNI '50 ALLA RADIO",85.5,4,"",
   92.1,3,"Ah, Maya immagino?",94.1,0,"",
   94.5,3,"Oh, non essere allarmata.",96.4,0,"",
   96.6,3,"Le tue amiche ti hanno prenotata nella...",99,0,"",
   99.1,3,"fammi controllare.",100.8,0,"",
   101.8,3,"Ah, sì.",102.8,0,"",
   102.9,3,"Stanza 101.",104,0,"",
   104.2,3,"È stato tutto pagato, quindi non devi preoccuparti di nulla.",107.2,0,"",
   107.3,3,"Hai delle ottime amiche.",109.1,0,"",
   109.9,3,"Davvero ottime.",111.2,0,"",
   111.5,3,"E ho visto che siete anche in parecchie.",115.6,0,"",
   116.2,3,"È bello vedere così tanti...",118.2,0,"",
   118.3,3,"volti freschi e giovani per cambiare un po'.",122.7,0,"",
   123.5,3,"Er... Siete qui per il festival musicale in città, presumo?",126.8,0,"",
   127.3,1,"Sì, dovevamo accamparci lì stasera, ma...",130.5,0,"",
   130.6,3,"Ma il tempo è pessimo per farlo!",133.1,0,"",
   136,3,"Resterete per colazione?",137.5,0,"",
   137.6,1,"Non credo, probabilmente ci rimetteremo in marcia.",140.2,0,"",
   140.3,3,"Va benissimo. E, se posso chiedertelo, Maya,",143.7,0,"",
   143.8,3,"potrebbe interessarvi dell'intrattenimento stasera?",147.5,0,"",
   147.9,1,"Stasera?",148.9,0,"",
   149,3,"Er, di solito inizia intorno a mezzanotte.",152.1,0,"",
   152.6,3,"In realtà sono io che lo faccio, commedia.",155.8,0,"",
   155.9,3,"Interpreto questo personaggio comico chiamato Hugo Punch,",161,0,"",
   161.1,3,"è una specie di sociopatico comico,",164.8,0,"",
   164.9,3,"dice cose che non dovresti dire e cose simili.",169.6,0,"",
   169.7,3,"È abbastanza popolare tra gli studenti.",171.7,0,"",
   172.3,1,"Non credo, probabilmente andremo tutte a letto.",175.7,0,"",
   175.8,3,"Sei sicura che non posso costringerti a venire?",179.2,0,"",
   179.5,1,"Sono a posto, preferisco andare a letto. Scusa.",182.8,0,"",
   182.9,3,"Va bene, va bene, va bene...",185.4,0,"",
   185.6,1,"Da che parte sono le stanze?",186.7,0,"",
   187.2,3,"Ehm, prendi l'ascensore, sei al primo piano.",190.2,0,"",
   190.3,1,"Ok, grazie.",191.6,0,"",
   193.1,3,"Oh Maya, domani, se vuoi, lascia la chiave nella scatola per favore.",198.1,0,"",
   198.2,1,"Ok!",199.2,0,"",
   199.3,6,"LE PORTE DELL'ASCENSORE SI CHIUDONO",200.8,0,"",
   204.4,3,"Miglior spettacolo in città e nessuno partecipa.",207.2,0,"",
   210.3,3,"Chi ha bisogno di un giusto intrattenimento quando hai 'You Tune' e 'My Face' e altro.",216.6,0,"",
   216.7,3,"Stupidi, incolti...",218.7,0,"",
   218.8,5,"Hugo non ama i bambini maleducati, sono cattivi.",223,0,"",
   225.5,3,"Non ricominciare.",227.3,0,"",
   231.1,3,"Non voglio sentirlo, ok? Non stasera.",234.2,0,"",
   237,5,"I bambini cattivi sono uova marce. Devono ricevere una lezione!",240.9,0,"",
   254.2,3,"Taci! Taci e basta!",256.5,0,"",
   257.3,3,"Lo fai sempre, sono clienti paganti.",260.2,0,"",
   260.5,3,"Non ti hanno fatto niente.",262.4,0,"",
   263.3,3,"Lasciali in pace.",265.4,0,"",
   266.2,5,"Bisogna spaccare le uova marce! Colpiscile e rompigli il guscio,",269.3,0,"",
   269.5,5,"buttali giù per le scale che portano all'Inferno!",272.3,0,"",
   272.8,5,"Sai cosa devi fare, Jimmy.",275,0,"",
   275.6,5,"Mostra loro chi comanda.",277.7,0,"",
   278.9,5,"È così che bisogna fare.",281.1,0,"",
   293.3,6,"URLO LONTANO",294.9,0,"",
   308,6,"UN UOMO RIDE",309.6,0,"",
   310,3,"Ecco, vai a dormire...",313,0,"",
   345.2,6,"IL TELEFONO CREPITA",346.9,0,"",
   358.5,6,"VOCI DALL'ALTOPARLANTE",361.9,0,"",
   362,1,"Vattene dall'hotel!",363.6,0,"",
   363.7,1,"Vattene finché puoi!",365.7,0,"",
   367.6,1,"Devi scoprire cosa ha fatto...",369.3,0,"",
   369.4,1,"...e dirlo a tutti.",371.3,0,"",
   371.4,1,"Fagli capire cosa ha fatto!",373.3,0,"",
   373.5,6,"LE VOCI SVANISCONO NELLA STATICA",376,0,"",
   382.1,1,"Sea View Hotel ha un passato oscuro.",386.1,0,"",
   389,1,"I suoi fantasmi hanno una storia da raccontare.",393,0,"",
   395.7,1,"Usa il rilevatore di fantasmi e spiriti per parlare con loro.",400.7,0,"",
   402.8,1,"Ti diranno i segreti di Jimmy.",406.8,0,"",
   409.5,1,"Ma Jimmy deve nascondere la verità...",413.5,0,"",
   416.9,1,"...a tutti i costi.",420.9,0,"X",
],
  "A2",[
   0.8,1,"Jimmy, ridammelo! È mio!",2.9,0,"",
   3,1,"Smettila di rubarmi le cose!",4.3,0,"X",
],
  "A3",[
   0.7,6,"URLA",2,0,"X",
],
  "A4",[
   1.1,1,"Ti sto dicendo, Jimmy, che non puoi farlo!",3.1,0,"",
   3.2,1,"Sei orribile...",4.7,0,"X",
   3.8,6,"LA VOCE SI AFFIEVOLISCE",4.4,0,"X",
],
  "A5",[
   3.8,6,"TOSSISCE",4.8,0,"X",
],
  "A6",[
   4.2,6,"RIDACCHIA",5.2,0,"X",
],
  "P1",[
   3.8,6,"BUSSA",4.8,0,"",
   5.8,2,"Jimmy?",6.8,0,"",
   7.2,2,"Sono il Dottor Bose.",8.9,0,"",
   9,2,"Sono qui solo per fare due chiacchiere, ok?",11.5,0,"",
   14.5,2,"Grazie Jimmy, non ci vorrà molto.",16.6,2,"X",
],
  "P3",[
   1,2,"È un'ottima idea, Jimmy!",3.4,0,"",
   3.5,2,"Penso che un giorno diventerai un ottimo cuoco.",5.7,0,"",
   5.8,2,"Perché non lo porti su da me quando hai finito?",8,0,"",
   8.1,2,"Ti aspetto, ok?",9.8,0,"X",
],
  "P4",[
   3,6,"TOSSISCE E SPUTA",4,0,"",
   7.6,2,"Jimmy!",8.6,0,"X",
],
  "P5",[
   1.2,2,"Non ti farà male, Jimmy.",2.9,0,"",
   3,2,"Tutto quello che devi fare è stare fermo e smettere di muoverti!",6.6,0,"X",
],
  "P6",[
   0.6,2,"Non userei mai la forza su una paziente, Signora Hall.",4.8,0,"",
   4.8,2,"Va contro tutto ciò in cui credo.",7.3,0,"",
   7.4,2,"Deve capire che si sta inventando tutto!",10,0,"X",
],
  "P7",[
   1.1,2,"Non puoi fuggire da me così facilmente, Jimmy.",3.9,0,"",
   4,2,"Penso che dovremmo ricominciare da capo, non credi?",6.5,0,"",
   6.6,2,"Perché non fai quello che ti chiedo, questa volta?",8.7,0,"",
   8.8,2,"Sarebbe un buon inizio, no?",11,0,"X",
],
  "P8",[
   0.6,2,"È la polizia, Signor Bose.",2.1,0,"",
   2.2,2,"Abbiamo bisogno che lei venga alla centrale.",4.1,0,"",
   4.4,2,"Può aprire la porta, per favore?",5.8,0,"X",
],
  "P9",[
   14.1,6,"SOFFOCA",15.5,0,"",
   15.9,6,"L'ALLARME DELL'ASCENSORE SUONA",16.9,0,"X",
],
  "H1",[
   0.8,3,"Si è inventato tutto. Ti sto dicendo che ha mentito su ogni cosa,",3.4,0,"",
   3.5,3,"probabilmente ha mentito anche su altro.",5,0,"",
   5.1,4,"Non essere ridicolo! Non mentirebbe su una cosa del genere!",7.3,0,"",
   7.4,3,"Ne sei sicura?",8.3,0,"",
   8.4,3,"Lui mente su tutto! Apri i tuoi dannati occhi Rose!",11.4,0,"",
   11.5,3,"Oh, brava! Vai via!",12.8,0,"",
   12.9,4,"Non sto ascoltando Harvey, ce l'hai solo con lui.",14.7,0,"",
   14.9,3,"È la verità!",16.2,0,"X",
],
  "H2",[
   1.5,6,"COLPI SULLA PORTA",2.4,0,"",
   2.5,3,"Jimmy?",3.5,0,"",
   4.3,3,"So che puoi sentirmi!",5.8,0,"",
   6.2,3,"So che ti sei inventato la tua piccola storia su quello psichiatra.",10,0,"",
   10.1,3,"So da dove l'hai presa!",11.6,0,"",
   12,3,"Sapevo di averla già letta, è nel tuo dannato album di ritagli!",15.3,0,"",
   16.1,3,"Vieni fuori!",17.3,0,"",
   18.3,3,"Jimmy!",19.6,0,"X",
],
  "H3",[
   1.2,6,"SCINTILLE ELETTRICHE",2.2,0,"",
   2.3,6,"GRIDA DAL DOLORE",3.3,0,"",
   7.2,3,"Jimmy!",8.2,0,"X",
],
  "H4",[
   1,6,"COSE CHE SI ROMPONO",2,0,"X",
],
  "H5",[
   0.8,6,"URLA DAL DOLORE",1.9,0,"",
   4.1,3,"Jimmy!",5.1,0,"X",
],
  "H6",[
   1.3,3,"Puoi restare lì per la notte, Jimmy!",3.7,0,"",
   3.8,3,"Ne ho avuto abbastanza.",5,0,"",
   5.1,6,"COLPI SULLA PORTA",6.6,0,"X",
],
  "H7",[
   0.3,6,"ALLARME ANTINCENDIO",1.8,0,"",
   2.7,3,"Jimmy, non essere stupido, apri la porta!",4.9,0,"",
   5.2,3,"Finirai ucciso, stupido idiota! Apri la porta!",8.4,0,"X",
],
  "H8",[
   2.7,3,"Vattene dall'hotel, Jimmy.",4.6,0,"",
   6.6,3,"Vattene dal mio hotel...",8,0,"",
   8.6,3,"Questo è il mio hotel. Vattene dal mio hotel, Jimmy.",12,0,"X",
],
  "H9",[
   1.8,3,"Vattene dal mio hotel.",3.2,0,"",
   3.3,3,"Questo è il MIO hotel.",5,0,"X",
],
  "R1",[
   0.8,8,"Harvey stava per sparare a Jimmy.",2.4,0,"",
   2.5,8,"Era solo un tagliacarte. Era legittima difesa! Guardate!",5.9,0,"X",
],
  "R2",[
   3.5,4,"Jimmy",4.5,0,"X",
],
  "R3",[
   1.2,4,"Signore e signori.",2.4,0,"",
   2.5,4,"Accogliete sul palco,",3.9,0,"",
   4,4,"il vostro intrattenimento per questa sera.",5.9,0,"",
   6,4,"Mr. Hugo Punch!",8,0,"",
   8.1,6,"MUSICA E APPLAUSI",9.6,0,"X",
],
  "R4",[
   0,4,"",0,0,"",
],
  "R5",[
   0.7,4,"È solo il suo spettacolo comico.",2.6,0,"",
   2.7,4,"È il suo senso dell'umorismo!",4.4,0,"",
   4.5,4,"Mi spiace che si sia offesa...",6.3,0,"",
   6.4,4,"Mi scusi...",7.6,0,"X",
],
  "R6",[
   0.5,6,"COLPI SULLA PORTA D'INGRESSO",1.8,0,"",
   1.9,4,"Signora Hall?",3.4,0,"",
   4.2,4,"Signora Hall, possiamo scambiare due parole?",6.5,0,"X",
],
  "R7",[
   1.4,4,"Jimmy?",2.4,0,"",
   4.1,6,"URLA",5.1,0,"",
   5.2,4,"Jimmy! Cos'hai fatto! Jimmy!",8,0,"X",
],
  "R8",[
   0.5,6,"BAMBINO CHE PIANGE",1.5,0,"",
   1.6,5,"Farai quello che ti dico! Mi hai capito?",4.2,0,"",
   4.3,5,"Stupido piccolo disgraziato!",5.4,0,"",
   5.5,6,"BAMBINO CHE VIENE SCHIAFFEGGIATO",6.7,0,"",
   6.9,6,"UOMO COLPITO DA UNA MAZZA",8.3,0,"X",
],
  "R9",[
   1.4,6,"URLA",2.9,0,"X",
],
  "V1",[
   5.5,7,"Ammirate!",6.3,0,"",
   6.4,6,"GONG",7.4,0,"",
   7.5,7,"Sono il grande Hugo!",10.2,0,"",
   11.9,7,"Io sono il solo al di sopra degli altri.",15.9,0,"",
   17.4,7,"Sono la luce che illumina l'oscurità.",21.4,0,"",
   22.7,7,"Io sono il solo padrone.",26.5,0,"X",
],
  "V2",[
   5,6,"DONNA CHE SINGHIOZZA",6.5,0,"",
   8,5,"Non comprare nulla senza il mio permesso!",10.5,0,"",
   10.6,6,"VETRI ROTTI",11.5,0,"",
   11.6,5,"Non ti permetterò di rovinarmi la vita!",14,0,"",
   14.1,6,"ALTRE COSE CHE SI ROMPONO",15.2,0,"",
   15.1,5,"La tua vita non significa nulla!",16.8,0,"",
   16.9,5,"Hai capito cosa ti sto dicendo?",18.6,0,"",
   18.7,6,"COSE CHE SI ROMPONO E DONNA CHE URLA",20.9,0,"X",
],
  "V3",[
   3.1,6,"BAMBINO CHE PIANGE",4.6,0,"",
   9,5,"Stai seduto!",10,0,"",
   10.1,6,"SUONO DI FRUSTATE",11.4,0,"",
   11.5,5,"Stupido piccolo disgraziato!",12.8,0,"",
   12.9,5,"Fai quello che ti dico!",14.9,0,"",
   15,6,"DONNA CHE URLA<br>No!",17,0,"X",
],
  "EPI",[
   17.9,3,"Signore e signori,",19,0,"",
   19.1,3,"date il benvenuto sul palco,",20.6,0,"",
   20.7,3,"al vostro intrattenimento per questa sera.",22.5,0,"",
   22.6,3,"Mr. Hugo Punch!",24.7,0,"",
   24.8,6,"APPLAUSI",26.4,0,"",
   33.5,5,"Maya!",34.5,0,"",
   36.1,5,"Maya!",37.1,0,"",
   40.5,5,"Maya?",41.5,0,"",
   42,5,"Maya!",43.5,0,"",
   44,6,"SINGHIOZZI",46,0,"",
   47.5,3,"Basta, basta, basta, basta...",49.9,0,"",
   50,3,"Smettila.",51.5,0,"",
   52.6,3,"Perché continui a farmi fare queste cose?",55.3,0,"",
   56,3,"Per favore, smettila.",57.5,0,"",
   58.4,3,"Per favore, smettila, smettila...",60.4,0,"",
   63.2,5,"Lo farai sempre, Jimmy.",64.9,0,"",
   66.7,5,"Comando io.",68.6,0,"",
   68.7,5,"Non tu.",69.7,0,"",
   71,5,"Comando io.",73.5,0,"",
],
  "BRO",[
   1.5,5,"Benvenuta alla tomba di Hugo!",5.5,5,"",
   5.6,5,"Il piccolo segreto di mia madre.",8.9,5,"",
   9,5,"Ha mescolato il cemento lei stessa,",11.8,5,"",
   11.9,5,"poi l'ha versato sul suo corpo senza vita",15.1,5,"",
   15.2,5,"e l'ha guardato rapprendersi.",17.8,5,"",
   18.1,5,"Pensava di essersi sbarazzata di lui.",21,5,"",
   21.3,5,"Ma non aveva capito, Maya.",24.7,5,"",
   24.8,5,"Vedi, Hugo era solo uno di noi.",29.1,5,"",
   29.2,5,"Solo un altro ceppo nel fuoco.",33,5,"",
   33.2,5,"È bruciato.",35.8,5,"",
   36,5,"Ma le fiamme hanno bruciato gli Hall per secoli.",41.2,5,"",
   41.3,5,"Spianando la strada...",43.5,5,"",
   43.6,5,"Illuminando l'oscurità...",45.9,5,"",
   46,5,"Devastando i vecchi, i poveri e i deboli.",52.3,5,"",
   52.4,5,"E brucia anche dentro di te, Maya.",56.7,5,"",
   56.8,5,"Lo so!",58.8,5,"",
   59,5,"Siamo destinati a stare insieme io e te.",62.9,5,"",
   63,5,"Sei tu quella che stavo aspettando.",66.6,5,"",
   66.8,5,"Ecco perché non posso lasciarti andare.",71,5,"",
   71.1,5,"Rimarrai qui con me, Maya.",75.2,5,"",
   75.3,5,"Per sempre.",77.5,5,"X",
],
  "COR",[
   0.2,5,"Parli con i morti, Maya?",4.3,1,"",
   4.5,1,"So che Hugo è tuo padre, Jimmy.",6.6,1,"",
   6.7,1,"Ho trovato il tuo certificato di nascita e so che Rose ha cercato di ucciderlo.",10.5,1,"",
   10.6,5,"Ma ha fallito, non è vero?",13.6,1,"",
   13.7,1,"Adesso dov'è, allora?",15.5,1,"",
   15.8,6,"RISATA",17,1,"",
   20.3,5,"Beh, perché non vieni a conoscerlo?",22.8,1,"",
   22.9,5,"È ora che ti presenti alla famiglia, Maya.",27.8,1,"",
   27.9,6,"RISATA",29,1,"X",
],
  "AP",[
   2.6,5,"Ciao Maya!",5,1,"",
   6.5,5,"Maya!",7.5,5,"",
   9,5,"Maya!",10.3,5,"",
   10.4,6,"COLPI SULLA PORTA",11.4,5,"",
   11.9,5,"Non puoi sfuggirmi, Maya!",14.9,5,"",
   15,5,"Apri la porta!",16.2,5,"X",
],
  "TUT",[
   0.83,1,"LA SITUAZIONE",
   4.33,1,"",
   6.4,1,"Questo è Jimmy Hall, il proprietario",
   9.3,1,"E pericoloso psicopatico",
   12.37,1,"",
   15.27,1,"Ha piani oscuri per gli amici di Maya",
   18.3,1,"",
   19.4,1,"Maya è scappata",
   22.4,1,"",
   24.23,1,"Jimmy sa che deve fermarla",
   27.33,1,"",
   27.83,1,"L'INSEGUIMENTO",
   31.57,1,"",
   33.3,1,"Jimmy si nasconde dove può",
   36.8,1,"",
   39.37,1,"dietro gli angoli",
   41.63,1,"",
   42.33,1,"Nell'ombra",
   44.33,1,"",
   45.27,1,"aspettando il tuo arrivo",
   47.6,1,"",
   48.23,1,"o si avvicina di soppiatto alle tue spalle",
   50.57,1,"",
   51.2,1,"Non può nascondersi sulle scale",
   53.53,1,"",
   54.33,1,"o al piano terra",
   56.47,1,"",
   57.33,1,"o nel seminterrato",
   60.27,1,"",
   60.7,1,"STRATEGIA",
   64.67,1,"",
   66.17,1,"Se Jimmy ti vede, allontanati",
   67.67,1,"Fuori dal suo campo visivo",
   71.83,1,"",
   75.13,1,"Puoi nasconderti in qualsiasi stanza sbloccata",
   78.17,1,"",
   79.67,1,"Se arriva Jimmy",
   81.73,1,"",
   84.13,1,"nasconditi in un armadio",
   86.4,1,"",
   90.2,1,"o nel bagno",
   92.33,1,"",
   94.73,1,"Usa la 'Radio dei Fantasmi' per parlare con loro",
   97.67,1,"",
   98.53,1,"Per vedere se Jimmy è fuori",
   101.43,1,"",
   103.63,1,"Chiama per attirarlo",
   105.2,1,"",
   106.67,1,"Per controllare dove va",
   109.67,1,"",
   110.23,1,"Trova le chiavi della stanza nei cassetti",
   112.67,1,"",
   114.17,1,"Chiudete Jimmy fuori dalle stanze",
   116.4,1,"",
   117.83,1,"O rinchiudilo dentro",
   120.13,1,"Se puoi scappare prima",
   123.17,1,"",
   124.67,1,"Controlla rapidamente le stanze guardando attraverso i buchi della serratura",
   127.7,1,"",
   129.67,1,"IL MORTO",
   133.5,1,"",
   135.17,1,"Jimmy ha un passato omicida",
   138.2,1,"Le sue vittime non se ne sono mai andate",
   141.17,1,"Infestano ancora l'hotel",
   144.47,1,"",
   145.67,1,"Usa la 'Radio degli spiriti' per parlare con loro",
   150.2,1,"",
   153.23,1,"Chiedi loro le cose che hai visto e scopri la loro storia",
   159.07,1,"",
   159.13,1,"Chiedere delle connessioni importanti li farà apparire",
   166.63,1,"",
   168.17,1,"Poi segui le luci tremolanti",
   171.1,1,"e ascolta i suoni strani",
   174.07,1,"",
   175.47,1,"Usa una bussola per guidarti",
   178.4,1,"",
   180.07,1,"Quando sei vicino, continua a guardarti intorno",
   183.07,1,"Oppure stai fermo e guarda avanti",
   186.17,1,"",
   186.7,1,"IL TALENTO DI MAYA",
   191.5,1,"",
   192.5,1,"Maya può vedere nell'altro mondo",
   196.5,1,"",
   197.97,1,"Spostati in un luogo poco illuminato",
   200.43,1,"",
   201.43,1,"Allora usa lo specchio",
   204.67,1,"",
   206.27,1,"Vedrai: La posizione degli elementi importanti...",
   209.2,1,"I luoghi degli spiriti...",
   212.23,1,"Connessioni tra oggetti e spiriti",
   217.23,1,"",
   218.3,1,"A volte Jimmy ruba delle cose se ti becca",
   222.77,1,"",
   224.27,1,"Cerca la tua 'Radio Fantasma' nel magazzino del primo piano (vicino alle scale)",
   229.3,1,"",
   230.27,1,"Trova bussole e chiavi nelle stanze degli ospiti",
   234.77,1,"",
   236.23,1,"Leggi le istruzioni della 'Radio Fantasma' per ulteriori consigli sulla caccia ai fantasmi",
   241.47,1,"",
  ],
],

itexts:[

  "delle vecchie valigie",
  "alcuni trofei e premi",
  "una borsetta da bambina",
  "una bottiglia di trementina e un accendino",
  "una spada ornamentale",
  "alcune bottiglie di whisky e altri liquori",
  "alcuni disegni violenti infantili",
  "un cappello da cuoco",
  "un vecchio panno pieno di macchie di sangue",
  "una siringa e una boccetta di Diazepam",
  "una vecchia pagaia o mazza di legno",
  "un album con ritagli di articoli di giornale",
  "una corda per stendere e un mattarello",
  "una vecchia stufa etichettata come 'pericolosa'",
  "delle mazze da cricket e da baseball",
  "una balestra",
  "delle vecchie chiavi arrugginite",
  "alcune foto con del fumo che esce dall'hotel",
  "una vecchia pistola",
  "un pugnale decorato",
  "un poster per lo spettacolo comico di Jimmy Hall",
  "degli specchi rotti",
  "un rotolo di filo di rame",
  "una nota scritta a mano che dice 'Addio'",
  "un anello nella sua scatola",
  "un giocattolo per un neonato",
  "certificato di nascita di Jimmy Hall",

],

ketex:[

  "Chiave Per La Stanza ",
  "Hai annotato ",
  "Hai annotato '",
  "Hai raccolto ",
  "",
  "Una Bussola",
  "Uno Specchio Rivelatore",

],

patex:[

  ["H","Appartenevano a Rose, ma non le ha mai usate.","R","[Le valigie] erano mie. Volevo andarmene, ma non ne ho mai avuto la possibilità."],
  ["R","Jimmy ha comprato [i trofei] per far sembrare che li avesse vinti lui."],
  ["A","[La borsetta] era mia. Era per il mio compleanno, ma mi è stata rubata.","H","Era la borsetta di quella bambina, poverina.","R","[La borsetta] apparteneva alla bambina."],
  ["A","Non sapevo cosa fossero [la trementina e l'accendino], finché Jimmy non me l'ha mostrato.","P","Dovresti chiedere a Jimmy.","H","[La trementina e l'accendino] erano cose mie, ma non li tenevo insieme.","R","[La trementina e l'accendino] appartenevano ad Harvey."],
  ["A","Jimmy aveva [la spada]. Non mi piaceva.","P","Ho visto Jimmy giocare con [la spada]. Pensavo fosse pericoloso.","H","Avevamo un espositore di armi medievali. Jimmy aveva rubato [la spada].","R","[La spada] apparteneva a un'armatura che avevamo. Ma è scomparsa."],
  ["A","Non so [da dove vengono le bottiglie], ma i bambini non dovrebbero bere alcolici.","P","[Le bottiglie] erano probabilmente del bar.","H","Non ricordo [da dove venissero le bottiglie], ma non c'è niente di male nel bersi qualcosa.","R","Harvey deve aver messo lì [le bottiglie]."],
  ["A","Il ragazzo disegnava [le immagini violente].","P","Jimmy disegnava [le immagini violente].","H","Chi pensi [che disegnasse le immagini violente]? Jimmy! Aveva un'immaginazione molto violenta, il piccolo Jimmy.","R","Jimmy disegnava [immagini violente] sulla guerra. Era come la maggior parte dei ragazzi."],
  ["P","Jimmy ha trovato [il cappello da cuoco] e l'ha indossato.","H","Era del cuoco, chi altro indossa un cappello da cuoco?","R","Il nostro cuoco indossava [il cappello da cuoco]."],
  ["A","[Il panno] poteva essere mio.","P","[Il panno] era mio. L'ho conservato, nel caso ne avessi avuto bisogno come prova.","H","[Il panno] potrebbe aver avuto qualcosa a che fare con il dottore."],
  ["P","[La medicina] può aiutare a trattare il comportamento impulsivo in alcune persone.","H","Probabilmente il dottore ha lasciato [la medicina].","R","[La medicina] apparteneva al Dottor Bose."],
  ["P","Non lo so, ma Jimmy aveva trovato [la pagaia].","H","[La pagaia] era sempre sotto il bancone alla reception. Non so da dove venisse.","R","[La pagaia] apparteneva a mio marito."],
  ["A","Jimmy ha creato [l'album di ritagli]. Non so perché. Era strano.","P","Jimmy ha creato [l'album di ritagli]. Era un avvertimento, avrei dovuto capirlo.","H","Jimmy era solito tenere dei ritagli di notizie su insegnanti e medici violenti. Non era un ragazzo normale.","R","Harvey ha detto che Jimmy aveva creato [l'album di ritagli], ma io non ricordo."],
  ["P","Ho legato [lo stendibiancheria e il mattarello] insieme. È stato un esperimento."],
  ["H","[La vecchia stufa] dava scosse elettriche. L'ho tenuta in modo che la polizia potesse controllarla.","R","Harvey ha messo via [la vecchia stufa]. Aveva detto che era pericolosa."],
  ["A","Il ragazzo giocava con [le mazze].","P","Harvey teneva [le mazze]. Non so perché.","H","Tenevo [le mazze], nel caso mi fossero servite.","R","[Le mazze] appartenevano a mio marito, quando faceva l'insegnante."],
  ["A","[La balestra] era in un armadietto, in albergo. L'ho vista.","P","L'albergo aveva un espositore di vecchie armi.","H","[La balestra] proveniva da un espositore d'armeria che avevamo. A Jimmy piaceva molto.","R","[La balestra] proveniva da un espositore che aveva Harvey. Ma non mi piaceva che stesse in albergo."],
  ["H","[Le chiavi arrugginite] erano per la vecchia porta del locale caldaia.","R","[Le chiavi arrugginite] erano per il locale caldaia, ma abbiamo dovuto sostituire la porta."],
  ["P","Non ne ho mai sentito parlare.","H","Sono riusciti a contenerlo, ma ho perso un sacco di roba.","R","L'abbiamo fermato in tempo, prima che si diffondesse."],
  ["P","Harvey possedeva [la pistola]. Non mi piaceva che stesse in albergo.","H","[La pistola] era mia. Apparteneva a mio padre. Aveva ancora qualche colpo dentro.","R","[La pistola] apparteneva ad Harvey, ma stava nella mia camera da letto."],
  ["A","Me l'ha mostrato Jimmy, ma non era suo.","H","Non è un pugnale, è un tagliacarte. Non dovrebbe essere affilato.","R","[Il pugnale] era un tagliacarte. Era un regalo di qualcuno."],
  ["R","[Il poster] era per lo spettacolo comico di Jimmy."],
  ["P","Non ho visto [gli specchi rotti].","H","Non me lo ricordo.","R","Jimmy ha rotto [gli specchi]."],
  ["A","Jimmy lo portava sempre con sé.","P","[Il cavo di rame] apparteneva a Jimmy. Lo teneva sempre in tasca. Non mi ha detto per cosa lo usava.","H","Jimmy si portava in giro del [cavo di rame]. Non ho idea del perché.","R","Jimmy si portava dei cavi con sé. Gli piaceva giocare con l'elettronica."],
  ["R","Jimmy ha scritto [la nota d'addio]."],
  ["H","[L'anello] probabilmente appartiene a Rose.","R","[L'anello] era mio. Qualcuno mi ha fatto un'offerta che non potevo rifiutare."],
  ["A","Non lo so. Non ho visto nessun neonato.","R","[Il sonaglio] era per il neonato. L'ho tenevo nel cassetto del comodino."],
  ["R","Jimmy è il figlio di Hugo. In ogni senso."],
  ["A","Un ragazzo di nome Jimmy mi ha chiusa nel seminterrato. Poi ha iniziato a rubarmi delle cose.","P","[La bambina] era la figlia di un ospite dell'hotel. Jimmy non era gentile con lei.","H","[La bambina] stava in hotel con la sua famiglia.","R","[La bambina] era un'ospite dell'hotel."],
  ["A","[Jimmy] pensava che [rubare il mio giocattolo] fosse divertente. Me l'ha restituito, ma poi l'ha rovinato lo stesso.","P","È proprio il genere di cose che [Jimmy] faceva.","H","Probabilmente [Jimmy] pensava che fosse divertente.","R","La bambina mentiva. Jimmy non rubava nulla."],
  ["A","La mia mano si è bruciata, faceva davvero male, ma non potevo dirlo a nessuno.","P","La mano della [bambina] era gravemente bruciata, ma Jimmy pensava che fosse tutto uno scherzo.","H","[La bambina] si è ustionata, piuttosto gravemente.","R","[La bambina] si era ustionata, ma continuava a fare cose pericolose. Era strana."],
  ["A","Stavo cercando di trovare un dottore, ma Jimmy mi ha minacciata e mi ha fatta restare.","H","[La bambina] probabilmente aveva paura di Jimmy.","R","[Il motivo per cui Amy era spaventata] poteva essere uno qualsiasi. Era una bambina strana."],
  ["A","Il ragazzo mi ha detto che era una medicina. Aveva un sapore orribile.","P","Non ero lì allora, ma penso che [la bambina] abbia bevuto degli alcolici."],
  ["A","Mi sentivo molto leggera, pensavo davvero di poter raggiungere il fondo saltando.","P","Jimmy ha fatto bere troppo la bambina.","H","[La bambina aveva] bevuto una bottiglia di whisky, non sapeva cosa stava facendo.","R","Non sapevo molto di quella [bambina]."],
  ["A","Sono saltata, ma poi è diventato tutto buio e non sono riuscita a svegliarmi. Non posso più svegliarmi.","P","[La bambina] è caduta dalle scale dall'ultimo piano. Era troppo ubriaca per sapere cosa stava facendo. Era il motivo per cui Rose mi ha contattato.","H","[La ragazza] è caduta giù per le scale dall'ultimo piano. Sapevo che doveva esserci Jimmy dietro tutto.","R","[La bambina] cadde. Harvey incolpò Jimmy per quello. Era colpa della bambina, non di Jimmy."],
  ["P","Ho ricevuto una chiamata da Rose. Voleva che scoprissi cosa turbava Jimmy. Ma Harvey era preoccupato per le cose che immaginava.","H","Il Dottor Bose avrebbe dovuto aiutare Jimmy, ma era irrecuperabile.","R","Il Dottor Bose era venuto ad aiutare Jimmy."],
  ["P","Jimmy stava uccidendo degli animali. Ho capito che aveva bisogno di lavorare sulle sue capacità empatiche. Così gli ho chiesto di pensare a qualcosa di carino che poteva fare per me. Ha avuto subito un'idea.","H","Jimmy ha detto di aver trovato [il coniglio morto] da qualche parte. Cosa ci stesse facendo è un'altra storia.","R","Harvey ha detto che probabilmente Jimmy aveva ucciso [il coniglio], ma io non gli ho creduto."],
  ["P","Jimmy mi stava preparando un panino. L'aveva portato in camera mia, come avevo chiesto. All'inizio non sospettavo che ci fosse qualcosa che non andava.","H","Il dottore stava cercando di istruire Jimmy, di fargli aiutare gli altri. Grosso errore.","R","Il Dottor Bose continuava a cercare di far fare a Jimmy cose che non voleva fare."],
  ["P","Jimmy aveva messo dei vetri rotti nel mio panino. Sono quasi soffocato. Mi resi conto di aver sottovalutato la malattia di Jimmy. Dovevo intensificare il suo trattamento, con urgenza.","H","Il [Dottor Bose] ha imparato a conoscere Jimmy con le cattive. Gli scherzi di Jimmy andavano sempre troppo oltre.","R","Il [Dottor Bose] si è tagliato, ma poi ha cercato d'incolpare Jimmy. Se l'era fatto da solo, non era stato Jimmy."],
  ["P","Jimmy si rifiutava di farmi somministrare il farmaco. Poi disse a Rose che avevo cercato di costringerlo a prenderlo, che avevo usato la violenza. Era ridicolo!","H","Non lo non so, non c'ero.","R","Il [Dottor Bose] stava cercando di curare Jimmy senza il mio permesso."],
  ["P","Ero preoccupato che Rose potesse credere a Jimmy. Era una palese bugia. Ma sono riuscito a convincere Rose che Jimmy stava mentendo.","H","Il [Dottor Bose] era preoccupato su cos'altro Jimmy si sarebbe inventato su di lui. E aveva ragione.","R","Perché il [Dottor Bose] era preoccupato per la sua reputazione. Ma decisi di dargli un'altra possibilità."],
  ["P","Ho pensato che quando [Jimmy] si fosse reso conto di essere stato sorpreso a mentire avrebbe iniziato a interagire con me. Invece s'inventò un'altra bugia. Solo che questa era molto peggio. La peggiore.","R","Il [Dottor Bose] stava parlando con Jimmy, cercava di controllarlo. Voleva convincerlo a fare cose cattive. Non avrei mai dovuto fidarmi di lui."],
  ["P","Rose mi ha denunciato. Sapevo che mi avrebbero rovinato. Non avevo carriera, né futuro. Decisi di prendere il controllo, una volta per tutte.","H","Stavano per arrestare il [Dottor Bose]. Jimmy lo aveva rovinato. Ma io non ci credevo.","R","Erano venuti per arrestare il [Dottor Bose]. Si era meritato tutto."],
  ["P","Ne avevo abbastanza. Non potevo tornare indietro. La mia vita era comunque finita.","H","Il [Dottor Bose] era stato spinto a farlo. Tutti pensavano che avesse 'toccato' Jimmy. Era troppo intelligente. Il dottore non aveva possibilità.","R","Il [Dottor Bose] sapeva di essere colpevole. Ha fatto la cosa giusta."],
  ["P","Harvey sapeva che Jimmy mentiva su di me. Harvey capiva.","H","Jimmy aveva fatto delle accuse contro il dottore. Rose gli credeva, ma avevo già sentito quella storia da qualche parte.","R","Harvey non credeva a quello che diceva Jimmy [sul dottore], ma sapevo che non mentiva."],
  ["P","Jimmy non ha mai ammesso le sue bugie.","H","Jimmy si è limitato a ridere. Poi ha iniziato a prepararmi delle piccole trappole. Alcune non così piccole.","R","Come poteva Jimmy ammettere qualcosa che non era vero? Harvey ha sbagliato a prendersela con Jimmy in quel modo."],
  ["H","[Jimmy] sapeva che quella era la mia stufa, aveva collegato il rivestimento direttamente alla rete elettrica. Gli serviva una lezione. Aveva danneggiato la mia proprietà, quindi decisi di danneggiare la sua.","R","Harvey incolpava Jimmy, ma quella stufa era difettosa. Harvey avrebbe dovuto buttarla via."],
  ["P","Non so [cosa ci stesse facendo Harvey con la mazza], ma la violenza non fa che peggiorare le cose.","H","Ho distrutto la televisione e le console [di Jimmy]. Ero arrabbiato. Ma non ha funzionato. Lo fece solo peggiorare. Presto si vendicò.","R","[Harvey] ha rovinato le cose di Jimmy. Non riusciva a controllare la sua rabbia."],
  ["H","Jimmy ha sistemato [la balestra] per farla sparare quando avessi aperto la porta. Sono dovuto andare al pronto soccorso. Quando sono tornato non sono riuscito a trovarlo. Rose mi aveva detto che si era nascosto nel seminterrato. Questo mi diede un'idea.","R","Harvey disse che Jimmy gli aveva sparato addosso una freccia, ma sapevo che Jimmy non avrebbe usato un'arma del genere."],
  ["H","Volevo dare a Jimmy una dose della sua stessa medicina. Pensavo che non potesse fare alcun danno [nel seminterrato]. Mi sbagliavo.","R","Non so cosa [Harvey] stesse facendo [nel seminterrato]."],
  ["P","Non ricordo [l'incendio dell'hotel].","H","Siamo riusciti a contenere [l'incendio dell'hotel] prima che ci sfuggisse di mano. Ma tutte le nostre vecchie foto e lettere erano laggiù, era andato tutto in fumo. Jimmy era fuori controllo, ne avevo abbastanza di lui. Volevo che sparisse.","R","Harvey incolpò Jimmy [per l'incendio dell'hotel], ma era stato un filo scoperto ad appiccato quell'incendio. È stato un incidente."],
  ["P","Non so [da dove provenisse la pistola]. Ma Harvey non riusciva a controllare la sua rabbia.","H","Non so cosa avrei fatto [con la pistola]. Il problema era che non sapevo che anche lui sarebbe stato armato.","R","Non so [da dove provenisse la pistola]. Harvey non avrebbe dovuto avere un'arma in albergo."],
  ["H","Stavo cercando Jimmy."],
  ["H","Jimmy si è avvicinato di soppiatto dietro di me, non l'avevo visto. Jimmy ha sempre vinto alla fine.","R","Harvey era impazzito. Jimmy si stava solo difendendo."],
  ["H","Rose credeva a Jimmy. L'ha difeso, fino alla fine.","R","Ho dovuto spiegare alla polizia che il pugnale era solo un tagliacarte e che Harvey aveva una pistola carica. Jimmy ha agito per legittima difesa. Hanno capito."],
  ["H","[La polizia] lasciò andare Jimmy. Dissero che era legittima difesa, che avevo provato a sparargli. Ma erano tutte bugie.","R","Jimmy stava tornando a casa. La polizia capì che [era legittima difesa]. Ma era cambiato, iniziò ad aiutare nella gestione dell'hotel. E trovò un modo per portare altri ospiti."],
  ["H","Non so chi fosse [Hugo Punch].","R","Mi stavo divertendo, stavamo guadagnando di nuovo. Poi Jimmy iniziò a comportarsi in modo strano. L'ho sentito gridare mentre si fissava. Sembrava arrabbiato."],
  ["R","All'inizio non capivo, ero confusa. Ma poi capii che non era Jimmy a fare quelle cose. Come gli specchi, stava iniziando a frantumarsi. Jimmy non aveva più il controllo."],
  ["H","Non lo so, ma so che alla fine Jimmy ha sempre rovinato tutto.","R","Non era più Jimmy quello sul palco, era Hugo Punch. Iniziò a insultare il suo pubblico ogni sera. Poi una notte, dopo lo spettacolo, un'ospite disse a Jimmy cosa pensava di lui. Perse la pazienza e fece qualcosa di stupido."],
  ["R","I giornalisti [stavano bussando alla porta], volevano Jimmy. Ma era stato Hugo Punch a legare la donna. Jimmy non poteva più controllarlo. Era depresso. Voleva solo lasciarsi tutto alle spalle e andarsene."],
  ["R","C'era Jimmy [nella vasca da bagno]. Aveva cercato di uccidersi. Ecco perché ho dovuto dirgli la verità."],
  ["H","Non so [chi stesse attaccando Rose]. C'erano cose che Rose non mi ha mai detto.","R","Ho seppellito Hugo [nel seminterrato], nel cemento, in una stanza segreta. L'ho lasciato abusare di Jimmy per troppo tempo. È stata colpa mia se Jimmy è diventato così. Pensavo che il senso di colpa sarebbe svanito se glielo avessi detto. Ma mi sbagliavo, ha peggiorato solo le cose. Non potevo accettare quello che avevo fatto. Non potevo più convivere con me stessa."],
  ["R","Se non mi fossi [uccisa] ci avrebbe pensato Jimmy, o per meglio dire, Hugo a farlo. Hugo è ancora al comando, anche adesso. Lo sta controllando. Chiedi a Jimmy di mostrarti dove vive Hugo."],
  ["H","Non ho mai conosciuto [Il Grande Hugo].","R","Hugo era un mago e un intrattenitore. Aveva comprato l'albergo per promuovere il suo spettacolo teatrale. Diventò famoso. Lavorai come sua assistente, poi le cose si sono sviluppate."],
  ["R","Non ho mai saputo cosa voleva. C'era solo una cosa che potevo dargli."],
  ["R","Hugo era un uomo violento, malvagio, malato."],
  ["A","Sì! [Jimmy] l'ha presa quando non stavo guardando e mi ha rubato i soldi. L'ho rimproverato ma non mi ha voluta ascoltare."],
  ["A","[Jimmy] ha inzuppato il mio giocattolo con quella roba nella bottiglia. Lo odiavo!"],
  ["A","[Jimmy] aveva tirato giù la spada dal muro, sembrava davvero affilata. Mi ha fatto promettere di non dirlo a nessuno e disse che avrebbe potuto farmi passare il dolore alla mano."],
  ["A","[Jimmy] mi ha detto di continuare a bere [la medicina]. Era orribile. Poi ho iniziato a sentirmi strana."],
  ["P","[I disegni violenti] suggerivano una personalità turbolenta, ma non ero particolarmente preoccupato finché non ho iniziato a rendermi conto fin dove arrivava l'immaginazione di [Jimmy]."],
  ["P","Jimmy disse che avrebbe fatto qualcosa per me, quindi l'ho seguito per vedere di cosa si trattasse."],
  ["P","[Il vetro che Jimmy ha messo nel panino] è stato il mio primo incontro con il suo senso dell'umorismo."],
  ["P","Il [Diazepam] non era il farmaco ideale, ma era tutto quello che avevo. Jimmy aveva bisogno di cure immediatamente. Era pericoloso."],
  ["P","Jimmy disse che avevo usato la pagaia per picchiarlo. Non avrei mai usato la violenza contro un paziente, era ridicolo! Ma Rose gli credette."],
  ["P","Jimmy mi accusò del peggior crimine possibile. Lo prese da un articolo di giornale che aveva letto. Si stava inventando tutto."],
  ["P","Ho provato con lo stendibiancheria, ma era troppo sottile. Poi trovai un po' di corda. Avevo ancora le chiavi dell'hotel, quindi una notte mi sono intrufolato dentro mentre ero in libertà provvisoria."],
  ["H","Non appena trovai quell'album di ritagli capii da dove Jimmy aveva preso [la storia]. Era uguale, fin nei minimi dettagli."],
  ["H","Jimmy giocava sempre con l'elettricità. Buffo come non fosse mai lui a prendere la scossa."],
  ["H","Tenevo quelle mazze per autodifesa, ma ero arrabbiato. Ne presi una e andai nella stanza di Jimmy."],
  ["H","Jimmy amava le armi come [la balestra]. Non lo avevo visto per tutta la notte dopo aver distrutto la sua roba. Avrei dovuto immaginare che stesse lavorando al suo prossimo scherzetto."],
  ["H","Beh, se Jimmy voleva nascondersi [nel seminterrato], ho pensato che gli piacesse stare lì."],
  ["H","Nessuno si rese conto fin dove Jimmy si sarebbe spinto per attirare l'attenzione."],
  ["H","L'avevo perso. Vedevo rosso, lo odiavo. Avevo perso il controllo."],
  ["H","[Il tagliacarte] non era nemmeno un pugnale! Ma non ho mai imparato la lezione, Jimmy era sempre un passo avanti a me."],
  ["R","Jimmy aveva iniziato a fare uno spettacolo comico sul palco: Hugo Punch. Era bravo. La gente ha iniziato a venire solo per vederlo."],
  ["R","Rompere gli specchi era solo l'inizio. Non ricordava di averlo fatto. Poi sono cominciate altre cose strane."],
  ["R","Jimmy aveva rinchiuso [la donna che si era lamentata] in una stanza e l'ha legata. L'ho trovata e l'ho lasciata andare. Non ha sporto denuncia, ma l'ha detto ai giornali."],
  ["R","Jimmy ha combattuto contro Hugo Punch per tutta la vita. Jimmy non voleva più vivere."],
  ["R","[Hugo e io] eravamo sposati. All'inizio eravamo felici, prima che le cose iniziassero a cambiare."],
  ["R","Pensavo che avere un figlio avrebbe risolto tutto. Mi sbagliavo."],
  ["R","Ho ammesso tutto a Jimmy. Hugo ha picchiato Jimmy da quando è nato, per 2 anni. Avrei dovuto fermarlo prima."],
  ["R","Jimmy era andato a cercare la tomba di Hugo. Ero sola. Sapevo cosa avrei dovuto fare."],
],

finwords:[

  "In ognuno di noi c'è<br>un altro che non conosciamo.",7,
  "",0.5,
  "Ci parla nei sogni,",6,
  "e ci dice in che modo ci vede lui,<br>che è diverso da quello in cui vediamo noi stessi.<br><span class='h8'>Carl Jung</span>",8,
  "V",5,
  "Puoi vederli,",4,
  "",0.5,
  "Nel Cuore Della Notte",5,
  "",16,
  "<span class='hf'>Maya</span><br>Chloe Booyens",5,
  "<span class='hf'>Jimmy Hall</span><br>Huld Martha",5,
  "<span class='hf'>Rose Hall</span><br>Joanna Bond",5,
  "<span class='hf'>Harvey</span><br>Karl Haynes",5,
  "<span class='hf'>Dottor Bose</span><br>Rohit Gokani",5,
  "<span class='hf'>Amy Bell</span><br>Daisy Follin",5,
  "<span class='hf'>Con attori non protagonisti come</span><br>Rachel Alfieri<br>Paige Ryan<br>Sally Alfieri<br>Daniel Alfieri<br>Luke Chase",8,
  "<span class='hf'>Con attori non protagonisti come</span><br>Sam Follin<br>Jamie Follin<br>Tom Follin<br>Clare Follin",7,
  "<span class='hf'>Ringraziamento speciale a</span><br>Mark Wilson<br>Fay Wilkins",7,
  "",1,
  "Grazie per aver giocato a<br>At Dead Of Night",8,
  "",

],

words:[

  "ACCENDI DISPOSITIVO",
  "SPEGNI DISPOSITIVO",
  "URLA",
  "USA SPECCHIO RIVELATORE",
  "FAI UNA DOMANDA",
  "CHIUDI",
  "Chiedi<br>chi<br>c'è",
  "Chiedi<br>il<br>nome",
  "Sei<br>",
  "CORRI IN AVANTI",
  "PREMI<br>SEMINTERRATO",
  "PREMI<br>PIANO<br>TERRA",
  "PREMI<br>PRIMO<br>PIANO",
  "PREMI<br>SECONDO<br>PIANO",
  "PREMI<br>TERZO<br>PIANO",
  "INDIETRO",
  "APRI<br>MENU",
  "Attira Attenzione Di Jimmy",
  "PROVA<br>PORTA<br>",
  "PROVA<br>STANZA<br>",
  "RITORNA<br>NELLA STANZA",
  "MANDA<br>FUORI<br>AMICA",
  "HAI<br>ABBINATO QUESTI",
  "PROVA<br>RIPOSTIGLIO<br>CINQUE",
  "CHIAMA<br>L'ASCENSORE",
  "CHIEDI DI QUESTO",
  "NASCONDITI<br>DENTRO<br>L'ARMADIO",
  "NASCONDITI<br>NEL<br>BAGNO",
  "GUARDA<br>DENTRO<br>LO SPIONCINO",
  "ENTRA<br>NELLA<br>STANZA",
  "CERCA<br>QUI",
  "LASCIA<br>LA<br>STANZA",
  "PROVA<br>QUESTA<br>PORTA",
  "CHIUDI",
  "APRI<br>NOTE",
  "AGGIUNGI PER<br>ABBINARE",
  "TORNA<br>ALLA<br>PORTA",
  "ACCOPPIA OGGETTI<br><span style='font-family:arial'>&</span> D'AVVISTAMENTO",
  "CHIEDI SE SONO COLLEGATI",
  "CHIEDI",
  "PAGINA SUCCESSIVA",
  "PAGINA PRECEDENTE",
  "PROVA LA PORTA DELLE SCALE",
  "TROPPO BUIO<br>DAVANTI",
  "ENTRA<br>NELLA STANZA",
  "ESCI DAL<br>TUTORIAL",
  "Cerca il dispositivo nel ripostiglio al primo piano vicino alle scale",
  "Devi<br>trovare uno<br>specchio rivelatore",
  "Devi<br>trovare una<br>bussola",
  "Devi<br>trovare una bussola e<br>uno specchio rivelatore",
  "Partita<br>Salvata",
  "GUARDA<br>DALLA FINESTRA",
  "Aspetta Di Essere Al Sicuro Prima",
  "ESCI",
  "È la chiave sbagliata",
  "Porta sbloccata",
  "Vai davanti una porta chiusa<br>per provare una chiave",
  "Porta chiusa",
  "Prova la porta prima",
  "Usa la chiave della stanza<br>per chiudere la porta",
  "Sblocca la porta prima",
  "VAI SU",
  "VAI GIÙ",
  "È troppo buio qui per usare il dispositivo",
  "Aspetta un po' prima di rimetterti in contatto.",
  "Jimmy sta per entrare nella stanza!",
  "Si può sentire Jimmy da qualche parte",
  "Jimmy ridacchia piano",
  "Inizia la partita prima",
  "Non puoi salvare al momento",
  "Partita Attuale Salvata",
  "È Troppo Presto Per Usare Di Nuovo Lo Specchio",
  "Non provarci!<br>Jimmy è in questa stanza!",
  "GUARDA<br>DALLA<br>SERRATURA",
  "È meglio lasciare aperti i ripostigli",
  "RACCOGLI<br>DISPOSITIVO",
  "È troppo buio qui per usare lo specchio",
  "Ripostiglio",
  "Sconosciuto",
  "È troppo luminoso qui per usare lo specchio",
  "TORNA<br>AL MENU",
  "Vuoi Salvare<br>La Partita?",
  "SALVA",
  "Si sente Jimmy camminare nelle vicinanze",
  "Si sente Jimmy muoversi velocemente",
  "La porta della stanza viene chiusa",
  "SALTA<br>RISVEGLIO",
  "Cerca il dispositivo nei ripostigli",
  "SALTA",
  "CHIUDI MESSAGGIO",

],

ghostex:[

  "A",
  "In Contatto Con<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;AMY&#160;&#160;</span>&#10023;<br><br>Bambina Di 10 Anni",
  "P",
  "In Contatto Con<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;Dr. BOSE&#160;&#160;</span>&#10023;<br><br>Psichiatra Clinico",
  "H",
  "In Contatto Con<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;HARVEY&#160;&#160;</span>&#10023;<br><br>Proprietario Dell'Hotel",
  "R",
  "In Contatto Con<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;ROSE&#160;&#160;</span>&#10023;<br><br>Proprietaria Dell'Hotel",

],

headtex:[

  "<span class='h3'>Trova Il Ricevitore Spiritico</span>",
  "<span class='h3'>Attiva Il Ricevitore Spiritico<br>Per Comunicare Con Gli Spiriti.</span>",
  "<span class='h3'>Alza Il Volume Del Ricevitore Spiritico Per Sentire Le Risposte Dello Spirito.</span>",
  "<span class='h3'>Prova A Entrare In Contatto Con Uno Spirito</span><br><span class='h2'>(Usa L'Icona Parla In Alto)</span>",
  "<span class='h3'>Uno Spirito Sta Stabilendo Un Contatto.<br>Prova A Confermare La Sua Identità.</span>",
  "<span class='h3'>Attualmente In Contatto Con ",
  "<span class='h3'>Lo Spirito È Troppo Distante. Prova Ad Avvicinarti.</span>",
  "<span class='h2'>Quando Incontri Gli Spiriti Puoi Fare Loro Delle Domande. Associa Le Loro Risposte Per Creare Collegamenti. Quando Sei Solo Puoi Rivedere Qui Le Risposte Degli Spiriti.</span>",

],

gametex:[

  "Partita Standard<br><br><span class='h2'>Trova spiriti, fai loro domande e crea collegamenti per farli apparire, mentre Jimmy cercherà d'impedirti di scoprire i suoi segreti.</span>",
  "Cerca e Salva<br><br><span class='h2'>Salva le tue amiche mentre Jimmy cerca di fermarti. Se ti colpisce una volta hai perso.</span>",
  "Cerca e Salva<br><br><span class='h2'>Torna alla fine della tua ultima partita.</span>",
  "<span class='h9'>Seleziona La Tua Partita</span><br><br><span class='h2'>Scegli tra Partita Standard o Estrema. Quando giochi l'Estrema, se Jimmy ti attacca, ti prenderà quasi tutto, ogni volta.<br><br>La partita in corso andrà persa quando ne inizi una nuova e i tuoi obiettivi verranno resettati.</span>",
  "<span class='h9'>Sei sicuro?</span><br><br><span class='h2'>Questa operazione terminerà la tua partita attuale e tornerai all'ultima salvata.</span>",
  "<span class='h9'>Un Colpo E Sei Morto!</span><br><br><span class='h2'>Questa partita non viene salvata, quindi hai solo una possibilità di salvare tutte!</span>",

],

getex:[

  "<br>Hai Trovato<br><br>Uno Specchio Rivelatore<br><br><span style='font-size:50%'>Rivela Suggerimenti e Indizi<br>Quando Usato In<br>Luoghi Bui</span>",
  "<br>Hai Trovato<br><br>Un Compasso<br><br><span style='font-size:50%'>Punta Verso Gli<br>Spiriti Nelle Vicinanze</span>",
  "<span style='font-size:40%>'>Hai Trovato Una<br>Chiave Etichettata Come<br>",
  "Hai Trovato La<br>Chiave Per Chiusura A Scatto<br>Della Stanza",
  "Hai Trovato La<br>Chiave Per Chiusura A Scatto<br>Della Stanza",

],


roomtex:"Stanza",

foundtex:"Hai Trovato",

alreadytex:[

  "Hai Già Uno Specchio Rivelatore",
  "Hai Già Una Bussola"

],

adtext:[

  "Suono di una<br>bambina che piange",
  "Suoni da una sala giochi",
  "Suoni sommessi di una<br>bambina che piange",
  "Una bambina canticchia<br>tra se e se",
  "Qualcuno bussa<br>debolmente a una porta",
  "Rumore di stoviglie che vengono spostate",
  "Suono di acqua che<br>scorre da un rubinetto",
  "Suono di un numero<br>composto al telefono",
  "Forte bussata<br>su una porta",
  "Rumore di qualcuno che<br>colpisce una porta",
  "Suono di scintille<br>e scosse elettriche",
  "Rumore di cose<br>che vengono spaccate",
  "Rumore di colpi<br>intermittenti o schiocchi",
  "Qualcuno colpisce<br>una porta metallica",
  "Rumore di un forte allarme",
  "Voce di Harvey che grida a Jimmy",
  "Tenue mormorio<br>di una folla",
  "Musica proveniente<br>da una radio",
  "Una folla fischia e urla ad alta voce",
  "Un campanello suona sporadicamente",
  "Suono di acqua che scorre in un bagno",
  "Un suono sporadico<br>di frustate",
  "Viene riprodotta della musica",

],

itdetext:[

  "Valigie",
  "Trofei",
  "Borsetta Da Bambina",
  "Trementina E Accendino",
  "Spada",
  "Bottiglie Di Whisky",
  "Disegni Violenti",
  "Cappello Da Cuoco",
  "Panno Macchiato Di Sangue",
  "Diazepam",
  "Pagaia Di Legno",
  "Album Di Ritagli",
  "Stendibiancheria",
  "Stufa Pericolosa",
  "Mazze Sportive",
  "Balestra",
  "Chiavi Arrugginite",
  "Foto Di Un Incendio",
  "Pistola",
  "Pugnale Decorato",
  "Poster Di Hugo Punch",
  "Specchi Rotti",
  "Rotolo Di Cavo",
  "Nota D'Addio",
  "Fede Nuziale",
  "Sonaglio Da Neonato",
  "Certificato Di Nascita",
  "Ragazza Nel Seminterrato",
  "Jimmy Ruba Ad Amy",
  "Amy Tiene In Mano Un Giocattolo In Fiamme",
  "Amy Spaventata Fuori Da Una Stanza",
  "Amy Beve Qualcosa Di Orribile",
  "Amy In Cima Alle Scale",
  "Amy In Fondo Alle Scale",
  "Uomo In Giacca E Cravatta Che Bussa A Una Porta",
  "Dr. Bose Trova Un Animale Morto",
  "Dr. Bose Fuori Dalla Cucina",
  "Dr. Bose Sputa Sangue",
  "Dr. Bose Con Un Ago Da Iniezione",
  "Dr. Bose Spiega Cos'è Successo",
  "Dr. Bose Seduto Su Un Letto In Una Stanza",
  "Dr. Bose Nella Sala Giochi",
  "Dr. Bose Si Uccide",
  "Uomo Che Dice Che Jimmy Aveva Mentito",
  "Harvey Che Grida Attraverso Una Porta",
  "Harvey Riceve Una Scossa Elettrica",
  "Harvey Con Una Mazza",
  "Harvey Che Viene Colpito Alla Gamba",
  "Harvey Rinchiude Jimmy Nel Seminterrato",
  "Un Incendio Nel Seminterrato",
  "Harvey Con Una Pistola",
  "Harvey Che Si Dirige Verso La Sala Da Ballo",
  "Harvey Viene Pugnalato",
  "Signora Che Spiega Del Pugnale",
  "Rose Alle Porte D'Ingresso",
  "Rose Dal Backstage Annuncia Hugo Punch",
  "Rose Che Trova Un Sacco Di Manichini",
  "Rose Che Si Scusa Con Un'Ospite",
  "Rose Che Si Nasconde E Persone Che Colpiscono Una Porta",
  "Rose Che Trova Jimmy Nel Bagno",
  "Rose Che Attacca Qualcuno Con Una Mazza",
  "Rose Che Va A Fuoco",
  "Il Grande Hugo Sul Palco",
  "Uomo Che Grida E Bambino Che Piange",
  "Urla E Ascensore che Cade",
  "Jimmy Non Ascoltava",
  "Jimmy Ha Imbevuto Il Giocattolo Di Amy",
  "Jimmy Poteva Curare Il Dolore Alla Mano Di Amy",
  "Amy Ha Bevuto Qualcosa Di Orribile",
  "Il Dr. Bose Ha Visto I Disegni Di Jimmy",
  "Jimmy Ebbe Un'Idea",
  "Il Dr. Bose Ha Conosciuto L'Umorismo Di Jimmy",
  "Il Dr. Bose Ha Deciso Di Curare Jimmy",
  "Jimmy Ha Accusato Il Dr. Bose Di Violenza",
  "Jimmy Ha Accusato Il Dr. Bose Di Abuso",
  "Il Dr. Bose Sapeva Cosa Doveva Fare",
  "Harvey Ha Trovato L'Album Di Jimmy",
  "Jimmy Giocava Con L'Elettricità",
  "Harvey È Andato Nella Stanza Di Jimmy Con Una Mazza",
  "Harvey Sospettava Di Un'Altra Trappola",
  "Harvey Ha Usato La Chiave Del Locale Caldaia",
  "Harvey Ha Capito Che Jimmy Era Pazzo",
  "Harvey Ha Perso Il Controllo",
  "Jimmy Era Un Passo Avanti",
  "Jimmy Ha Iniziato Il Suo Spettacolo Comico",
  "Cominciarono Ad Accadere Cose Strane",
  "I Giornali Lo Scoprirono",
  "Jimmy Ne Aveva Abbastanza",
  "Le Cose Erano Cambiate Con Hugo",
  "Un Bambino Non Risolve Nulla",
  "La Verità Era Stata Rivelata",
  "Rose Era Sopraffatta Dal Senso Di Colpa",
  "Chiave per il 'Ripostiglio'",
  "",
  "",
  "Specchio Rivelatore",
  "Bussola",
  "Chiave per 'Scale Primo Piano'",
  "",
  "",
  "Specchio Rivelatore",
  "Bussola",
  "Chiave per il 'Ripostiglio'",
  "",
  "",
  "Specchio Rivelatore",
  "Bussola",
  "Chiave per 'Scale Secondo Piano'",
  "",
  "",
  "Specchio Rivelatore",
  "Bussola",
  "Chiave per il 'Ripostiglio'",
  "",
  "",
  "Specchio Rivelatore",
  "Bussola",
  "Chiave per 'Scale Terzo Piano'",
  "",
  "",
  "Specchio Rivelatore",
  "Bussola",
  "Chiave per il 'Ripostiglio'",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Chiave Per L'Uscita Dell'Hotel",
  "Chiave Del Ripostiglio Nel Seminterrato",

],

keyfinds:[

    "MAGAZZINO",
    "SCALE PRIMO PIANO",
    "SCALE SECONDO PIANO",
    "SCALE PIANO TRE",

  ],

gnames:[
  "Amy",
  "Dr Bose",
  "Harvey",
  "Rose",
  "Hugo"
],

transcred:"LOCALIZZAZIONE ITALIANA DI LUCA CASSINELLI",

extras:[
  "BENVENUTO A<br>SEA VIEW HOTEL<br><span style='font-size:50%'>PRENOTATI QUI</span>",
  "Maya:",
  "Il gioco è stato salvato",
  "Controller di gioco collegato",
  "Controller di gioco disconnesso",
],

};
