var ENG={

mentex:[

"The Edison<br><span class='bt1'>Ghost & Spirit Voice Receiver<br></span>Usage Guide<br><br><br>On Supernatural Communication (a word of caution)<br><br>When contacting a Ghost or Spirit, their emotional state translates directly to their electrical potential or 'energy' state. Ghosts can manifest in either high or low energy states, but for voice communication a low energy state is required.<br><br>Ghosts may be prompted to shift between energy states by provocative or aggressive questioning. If a Ghost enters a high energy state, this device will receive only a loud static noise and communication cannot proceed any further.<br><br>Ghosts in a high energy state often manifest physically, without electronic or optical aid. This usually occurs at a different location. Please bear in mind that supernatural entities are the souls of the Dead. Please treat them with due respect.",

"energy increased<br>by conversation<br><br>LOW STATE<br><br><br><br><br>VOICE CAN<br>BE HEARD",

"<br><br><br>HIGH STATE<br><br><br><br><br>MAY MANIFEST<br>PHYSICALLY<br><br>energy dissipated<br>by manifestation",

"<div class='ht'><span style='font-size:170%'>Game Play Advice</span><br><br>Play At Dead Of Night at dead of night, or at least in a dark room, and make sure there are as few background sounds as possible, or use headphones if you're playing alone.<br><br>You'll need to be able to see into the darkest areas of the image since much of the hotel is dark and Jimmy's shadow can sometimes only just be seen. Use the brightness (U/I keys) to bring up the shadows if you need to.<br><br>Jimmy's voice can be heard if he's on the same floor. If you listen carefully you can also hear his footsteps, which help tell you how close he is. Ghosts also make sounds. If you want to listen more carefully, press 'D' to dip the background ambience for a moment.<br><br>If you need hearing assistance select the 'Enhanced Description' option under 'Subtitles.' If you don't need this assistance it's advisable to leave this switched off.<br><br>Compasses point towards ghosts even through walls, so if you can't find a ghost in the direction it's pointing, try walking around the corridors. Compasses spin slowly when there's no ghosts around and spin more quickly when you're right near one.<br><br>Remember you can look through keyholes to see into rooms and you can run faster down long corridors by moving the arrow to the top of the screen.</div>",

"<div class='ht'><span style='font-size:170%'>Jimmy and DID</span><br><br>Jimmy's story is a theatrical and symbolic representation of someone struggling with two opposing moral paths and is not intended to be a literal depiction of the very real psychological disorder known as DID, or Dissociative Identity Disorder.<br><br>Real DID is a distressing and debilitating illness, often (but not always) associated with childhood abuse. DID does not in any way correlate with immoral or criminal behaviour. DID sufferers are in need of compassion, yet often experience condemnation or mistrust, usually as a result of public misunderstanding.<br><br>It was not our intention to imply that Jimmy has this disorder and we fully accept that perpetuating stereotypes is damaging to sufferers and prevents progress and understanding. We sincerely apologise for any distress or pain caused to those suffering from DID.<br><br>For more information please see:<br><br>https://survivorsnetwork.org.uk/resource/dissociative-identity-disorder-d-i-d/</div>",

"With Thanks to the<br>Fabulous Acting Talents of<br><br><table><tr><td><span class='h5'>Jimmy</span><br><span class='ht'>Huld Martha</span><br><br><span class='h5'>Rose</span><br><span class='ht'>Joanna Bond</span><br><br><span class='h5'>Dr Bose</span><br><span class='ht'>Rohit Gokani</span><br><br></td><td><span class='h5'>Maya</span><br><span class='ht'>Chloe Booyens</span><br><br><span class='h5'>Harvey</span><br><span class='ht'>Karl Haynes</span><br><br><span class='h5'>Amy<span><br><span class='ht'>Daisy Follin</span><br><br></td></tr></table><span class='h5'>And Supporting Actors</span><table><tr><td><span class='ht'>Rachel Alfieri<br>Paige Ryan<br>Sam Follin</span></td><td><span class='ht'>Jamie Follin<br>Clare Follin<br>Tom Follin</span></td></tr></table><br><span class='h5'>With Special Thanks To</span><br><table><tr><td><span class='ht'>Mark Wilson</span></td><td><span class='ht'>Fay Wilkins</span></td><td><span class='ht'>Daniel Alfieri<span></td><td><span class='ht'>Sally Alfieri</span></td><td><span class='ht'>Luke Chase</span></td></tr></table><br><span class='h7'>Created by Tim 'so what do you do now' Follin<br>©2020 Baggy Cat Ltd</span></span>",

"&#160;&#160;&#160;&#160;&#160;Enhanced Description<br><br><span class='h2'>Adds enhanced subtitles and a text description of sounds heard during the game, along with a volume indicator.<br><br>If you don't need assistance it's best to leave this option switched off.</span>",

"&#160;&#160;&#160;&#160;&#160;Subtitles<br><br><span class='h2'>Adds basic subtitles in game and for the prologue.</span>",

"There are no events<br>to review yet.",

"BEGIN NEW GAME",

"<span class='h9'>The Story Of Jimmy Hall</span><br><br><span class='h2'>Find out Jimmy's secrets by asking spirits about the things you find then making connections to prompt them to appear. Jimmy will do his best to stop you finding out the truth.</span>",

"<span class='h9'>Last Game Finale</span><br><br><span class='h2'>Play your last game completed from when Jimmy invited you to meet Hugo.</span>",

"<span class='h9'>The Final Rescue (new game)</span><br><br><span class='h2'>Rescue all your friends while avoiding being attacked by Jimmy. One hit and you're dead! This game doesn't save and you can return to your current game when you escape or if you're attacked.</span>",

"Watch Full Tutorial",

"Watch from 'The Chase'",

"Watch from 'Strategy'",

"Watch from 'The Dead'",

"Watch from 'Maya's Talent'",

"Watch Prologue",

"Watch from 'Maya Arrives'",

"Watch from 'Hugo Takes Over'",

"Watch from '2:30am'",

"Watch from 'The Spirit Receiver'",

"Game Stats",

"Start New Game",

"Review Sightings",

"Receiver Instructions",

"Watch Tutorial & Intro",

"Subtitles & Descriptions",

"Credits",

"Game Play Advice",

"Jimmy & DID",

"Leave The Hotel<br><span class='h2'>Save & Exit</span>",

"Sure you want to<br>leave the hotel now?",

"YES LET ME OUT!",

"<br>YOU HAVE<br>NO ITEMS<br>TO SEE YET",

"Jimmy hit you for the last time.<br><br>Your escape ends here.<br><br>But you can always try again...",

"Enter The Hotel<br><span style='font-size:50%'>Return to your last saved game</span>",

"Enter The Hotel<br><span style='font-size:70%'>Start New Game</span>",

"BEGIN STANDARD GAME",

"BEGIN EXTREME GAME",

"Save Current Game",

],

achtex:[

  "You have completed",
  "of the story",
  "You've avoided being attacked",
  "Jimmy has attacked you once",
  "Jimmy has attacked you twice",
  "Jimmy has attacked you",
  "times",
  "You learned the hotel's secret",
  "Story",
  "Complete",
  "",
  "",
  "",
  "You rescued all your friends",
  "You need to find the hotel exit",
  "You completed the game!",
  "There are no stats to show yet",
  "Game Stats",
  "Achievements",
  "You completed Amy's story",
  "You completed Dr Bose's story",
  "You completed Harvey's story",
  "You completed Rose's story",
  "You completed the main story",
  "You completed the main story without being hit",
  "You completed At Dead Of Night",
  "You rescued everyone in a quick game",
  "You completed At Dead Of Night without being hit!",
  "Return To Sea View",
  "You have no achievements at the moment",
  "The game saves after sightings of ghosts, prompting ghosts' reactions (but only after you turn off the ghost detector) and if Jimmy knocks you out.",
  "You completed the main story in EXTREME MODE",
  "You completed the main story in EXTREME MODE without being hit",
  "You completed At Dead Of Night in EXTREME MODE",
  "You completed At Dead Of Night in EXTREME MODE without being hit!",
  "All your friends got out safely.",

],

selx:[

  "Didn't Have An Answer",
  "You Haven't Asked About This Yet",
  "Make contact with a spirit to ask about this",
  "Click Item To See Each Spirit's Reply",
  "Face the locked door to try the key",
  "Select To Ask About This",
  "didn't have an answer",
  "Said:",
  "HAVE A SAFE TRIP<br>come back soon",
  "Current Game Saved",
  "Begin A Game First",

],

numwo:[

  "You Have Just One Friend Left To Rescue",
  "You Have Two Friends To Rescue",
  "You Have Three Friends To Rescue",
  "You Have Four Friends To Rescue",
  "You Have Five Friends To Rescue",

],

numwa:[

  "You Have Rescued Five Friends",
  "You Have Rescued Four Friends",
  "You Have Rescued Three Friends",
  "You Have Rescued Two Friends",
  "You Have Rescued One Friend",

],

helx:"<span class='ht'>&#8679;S</span> Save Game | <span class='ht'>Esc</span> Toggle Menu | <span class='ht'>D</span> Dip Soundtrack | <span class='ht'>Q/W</span> Audio Loudness<br><span class='ht'>&#8679;X</span> Quick Exit | <span class='ht'>U/I</span> Brightness Adjust | <span class='ht'>O/P</span> Saturation Adjust | <span class='ht'>R</span> Reset Levels",

resk:[

  "You Found<br><br>Five Deadlock Keys<br><br><span style='font-size:50%'>You have five friends to rescue</span>",
  "Wait For Them<br><br>To Get Away<br><br>",
  "<span style='font-size:50%'>You have rescued all your friends</span>",
  "<span style='font-size:50%'>You have one more friend to rescue</span>",
  "<span style='font-size:50%'>You have two more friends to rescue</span>",
  "<span style='font-size:50%'>You have three more friends to rescue</span>",
  "<span style='font-size:50%'>You have four more friends to rescue</span>",

],

ityptex:[

  "Showing Everything",
  "Showing Found Items",
  "Showing Sightings",
  "Showing Connections",
  "Showing Keys"

],

intros:[

  "This is the device you found. Select this to switch it on.",
  "It can detect spirits' voices if you're near enough to them.",
  "If you haven't seen it, go to the MENU and watch the Tutorial Video before you continue!",
  "The device you found can detect spirits' voices if you're near enough to them.",

  "If you haven't seen it, go to the MENU and watch the Tutorial Video before you continue!",
  "This is a list of things you've seen and keys collected.",

  "Maya can ask spirits about things from this list.",
  "This is a list of things you've seen and keys collected.",

  "Maya can ask spirits about things from this list.",
  "You can only use the scrying mirror when the icon is visible,",

  "either by the door in rooms or in the ground floor kitchen.",
  "Use the mirror to see clues about where to go or which items to use next,",
  "It will also help you locate lost keys, compasses and the ghost box.",
  "You can only use the scrying mirror when the icon is visible,",

  "either by the door in rooms or in the ground floor kitchen.",
  "Use the mirror to see clues about where to go or which items to use next,",
  "It will also help you locate lost keys, compasses and the ghost box.",
  "The compass will point towards nearby spirits.",

  "Ask spirits about the things you've seen.",

  "You'll see their reply when selecting the item.",
  "Match two replies you think connect to work out the spirit's story.",

  "Pair sighting replies with item replies for faster progress.",
  "If the spirit stops replying they may have moved away.",

  "Use a compass, look for flickering lights and listen out for sounds.",
  "Start conversations with spirits by asking introductory questions.",

  "If there's no reply there are no spirits around.",
  "A loud noise means there's a spirit in a high energy state near.",
  "Start conversations with spirits by asking introductory questions.",

  "If there's no reply there are no spirits around.",
  "A loud noise means there's a spirit in a high energy state near.",
  "Jimmy Hall is on this floor looking for you. Stay away from him!",

  "To try keys open the inventory, face the door and select a key.",

  "Doors can be locked or unlocked with the right key.",
  "To try keys open the inventory, face the door and select a key.",

  "Doors can be locked or unlocked with the right key.",
  "The game will save here for the last time.",

  "You now have to rescue your friends...<br>but if Jimmy catches you it's game over!",
  "That's the last<br>person released.<br>Now find the exit<br>and get out!",

  "Move forward to send them out of the room",

],

substan:[

  "I don't know.",
  "Maybe.",
  "No",
  "VOICE<br>VAGUELY<br>HEARD/",
  "RADIO<br>STATIC/"

],

subrepa:[
[
  "Hello?",
  "Hello",
  "Hello.",
  "Hello",
  "Hello.",
  "Hello"
],[
  "Hello?",
  "Hello?",
  "Hello?",
  "Hello?"
],[
  "Hello?",
  "I can hear you",
  "I can hear you.",
  "I can hear you."
],[
  "Hello?",
  "I can hear you.",
  "Hello?",
  "I can hear you.",
  "I can hear you."
],
],

subrepb:[
[
  "I'm Amy Bell. I'm ten.",
  "Yes, I'm Amy.",
  "Yes, I'm Amy.",
  "Yes, it's me.",
  "Yes I'm Amy.",
  "Yes. I'm Amy.",
  "Yes, it's Amy.",
  "Yes, it's me."
],[
  "Doctor Bose. I'm a clinical psychiatrist.",
  "Yes, I'm Doctor Bose.",
  "I'm Doctor Bose.",
  "Yes. I'm Doctor Bose.",
  "Yes.",
  "Yes it's me.",
  "I'm Doctor Bose, yes."
],[
  "Harvey. I run the place.",
  "Yes.",
  "Yeah it's Harvey.",
  "Yeah. It's Harvey.",
  "Yeah. It's Harvey.",
  "Yeah it's Harvey."
],[
  "Rose, Rose Hall. This is my hotel.",
  "Yes.",
  "Yes. I'm Rose.",
  "Yes.",
  "Yes, I'm Rose.",
  "Yes.",
  "Yes. I'm Rose."
],
],

subcall:[

  "JIMMY?",
  "HEY!",
  "I'M HERE!",
  "DOWN HERE!",
  "THIS WAY!",

],

subin:[

  "Is anyone there?",
  "Is anyone there?",
  "Is anyone there?",
  "Is someone there?",
  "Is someone there?",
  "Is someone there?",
  "Who's there?",
  "Hello?",
  "Hello?",
  "Is someone there?",
  "Is someone there?",

],

subnm:[

  "Is it Amy?",
  "Is it Dr&#160;Bose?",
  "Is it Harvey?",
  "Is it Rose?",
  "What's your name?",

],

subrepc:[

  ["H","Rose, but she never used them.","R","They were mine. I wanted to go away, but I never got chance."],
  ["R","Jimmy bought them, to make it look like he'd won awards."],
  ["A","It was mine. It was for my birthday, but it was stolen.","H","It was that girl's purse, poor thing.","R","It belonged to the little girl."],
  ["A","I didn't know what they were, until Jimmy showed me.","P","You'd better ask Jimmy.","H","They were my things, but I didn't keep them together.","R","I don't know. They belonged to Harvey."],
  ["A","Jimmy had it. I didn't like it.","P","I saw Jimmy playing with it. I thought it was dangerous.","H","We had a display of Medieval weapons. Jimmy stole it.","R","It belonged with a suit of armour we had. But it went missing."],
  ["A","I don't know, but children shouldn't drink alcohol.","P","They were probably from the bar.","H","I don't remember, but there's nothing wrong with having a drink.","R","Harvey must have put them there."],
  ["A","The boy used to draw them.","P","Jimmy. He used to draw them.","H","Who do you think? Jimmy! He had a very violent imagination, did little Jimmy.","R","Jimmy used to draw pictures about the war. He was like most boys."],
  ["P","Jimmy found it and put it on.","H","The chef! Who else wears a chef's hat?","R","Our chef used to wear it."],
  ["A","It could have been mine.","P","It was mine. I kept it, in case I needed it as evidence.","H","I don't know, but it might have had something to do with the doctor."],
  ["P","It can help treat impulsive behaviour, in some people.","H","Probably the doctor left it.","R","It belonged to Doctor Bose."],
  ["P","I don't know, but Jimmy found it.","H","It was always under the counter in reception. I don't know where it came from.","R","It belonged to my husband."],
  ["A","Jimmy made it. I don't know why. He was strange.","P","Jimmy made it. It was a warning, I should have seen it coming.","H","Jimmy - he used to keep cut outs of news stories about abusive teachers and doctors. He wasn't a normal boy.","R","Harvey said Jimmy made it. I don't remember."],
  ["P","I tied them together. It was an experiment."],
  ["H","It was giving electric shocks. I kept it so the police could check it.","R","Harvey put it away. He said it was dangerous."],
  ["A","I don't know. The boy used to play with them.","P","Harvey kept them. I don't know why.","H","I kept them, in case I needed them.","R","They used to belong to my husband, when he was a teacher."],
  ["A","It was in the cabinet, in the hotel. I saw it.","P","The hotel used to have a display of old weapons.","H","It was from an armoury display we used to have. Jimmy was fond of it.","R","It was from a display Harvey used to have. But I didn't like it being in the hotel."],
  ["H","They were for the old boiler room door.","R","They were to the boiler room. But we had to have the door replaced."],
  ["P","I never heard about that.","H","Yes - they managed to contain it, but I lost a lot of stuff.","R","Yes. But we caught it in time, before it spread."],
  ["P","Harvey owned it. I didn't like it being in the hotel.","H","It was mine. Belonged to my father. Still had a few rounds with it.","R","Harvey. But it was kept in my bedroom."],
  ["A","Jimmy showed it to me. But it wasn't his.","H","It's not a dagger, it's a letter opener. It's not supposed to be sharp.","R","It was a letter opener. It was a present from someone."],
  ["R","It was Jimmy's comedy act."],
  ["P","I didn't see them.","H","I don't remember that.","R","Jimmy broke them."],
  ["A","Jimmy used to carry it around with him","P","It belonged to Jimmy. He always kept it in his pocket. He didn't tell me what he used it for.","H","Jimmy used to carry it around with him. No idea why.","R","Jimmy used to carry wire around with him. He liked playing around with electronics."],
  ["R","Jimmy wrote it."],

  ["H","Probably belongs to Rose.","R","It was mine. Someone made me an offer I couldn't refuse."],
  ["A","I don't know. I didn't see a baby.","R","It was for the baby. I kept it in my bedside drawer."],
  ["R","Jimmy is Hugo’s son. In every way."],
  ["A","It was me - a boy called Jimmy locked me in the basement. Then he started stealing things from me.","P","It was the daughter of a hotel guest. Jimmy wasn't nice to her.","H","She was staying in the hotel with her family.","R","She was a guest in the hotel."],
  ["A","Because he thought it was funny. He gave it back, but then he ruined it anyway.","P","I've no idea, it's just the kind of thing he did.","H","Who knows. He probably thought it was funny.","R","He didn't. The girl was lying. Jimmy didn't steal things."],
  ["A","My hand got burned, it was really hurting, but I couldn't tell anyone.","P","Her hand was badly burned quite badly, but Jimmy thought it was all a joke.","H","She was burned, pretty badly.","R","She was burned, but she kept doing dangerous things like that. She was odd."],
  ["A","I was trying to find a doctor, but Jimmy threatened me and made me stay.","H","She was probably scared of Jimmy.","R","I don't know, could have been anything. She was a strange girl."],
  ["A","The boy said it was medicine. It tasted horrible.","P","I wasn't there then, but I think she drank alcohol."],
  ["A","I felt really light, I really thought I could jump down to the bottom.","P","Jimmy made the girl drink too much.","H","She'd drunk a bottle of whiskey, she didn't know what she was doing.","R","I don't know. I didn't know much about her."],
  ["A","I jumped, but then it all went dark and I couldn't wake up. I can't wake up anymore. I don't know where I am.","P","She fell down the stairs from the top floor. She was too drunk to know what she was doing. It was the reason Rose got in touch with me.","H","She fell from the top floor, down the stairs. I knew Jimmy was behind it, he had to be.","R","She fell. Harvey blamed Jimmy for it. It was the girl's own fault, not Jimmy's."],
  ["P","It was me - I got a call from Rose, Jimmy's mother. She wanted me to talk to Jimmy, find out what was bothering him. But Harvey was worried about Jimmy's mind, the things he was imagining.","H","It was Doctor Bose. He was supposed to help Jimmy, but Jimmy was beyond help.","R","Doctor Bose. He came to help Jimmy."],
  ["P","Jimmy was killing things, small birds, animals. I realised he needed to work on his empathy skills. So I asked him to think of something nice he could do for me. I was surprised, he came up with an idea right away.","H","Jimmy said he'd found it somewhere. What he was doing with it is another story.","R","Harvey said Jimmy had probably killed it himself, but I didn't believe him."],
  ["P","Jimmy was making me a sandwich. He brought it up to my room, as I asked. I didn't suspect anything was wrong at first.","H","The doctor was trying to educate Jimmy, get him to help out. Big mistake.","R","Doctor Bose kept trying to make Jimmy do things he didn't want to."],
  ["P","Jimmy had put broken glass in my sandwich. I nearly choked on it. I kept the cloth and glass so I could go to the police, but I realised I'd underestimated Jimmy's illness. I simply had to step up his treatment, urgently.","H","He learned about Jimmy the hard way. Jimmy's pranks always went too far.","R","He cut himself. But then he tried to blame Jimmy. He did it to himself, it wasn't Jimmy."],
  ["P","Jimmy refused to let me administer the drug. I had to chase him around the hotel. Then he told Rose I'd tried to force him to take it, that I'd used violence. It was ridiculous!","H","I don't know, I wasn't there.","R","He was trying to medicate Jimmy, without my permission."],
  ["P","I was worried Rose would believe Jimmy. It was a bare faced lie. But I managed to convince Rose Jimmy was making it up.","H","He was worried about what else Jimmy would make up about him. And he was right to be.","R","Because he was worried about his reputation. I didn't know who to believe. but I decided to give him another chance."],
  ["P","I thought when he realised he'd been caught lying he'd start to engage with me and do what I asked. Instead he just made up another lie. Only this one was much worse. The worst.","R","He was talking to Jimmy, trying to control him. Get him to do things, bad things. I should never have trusted him."],
  ["P","Rose reported me. I knew they'd strike me off. I had no career, no future. I decided to take control, once and for all.","H","They were going to arrest him. Jimmy had ruined him. But I didn't believe any of it.","R","They came to arrest him. He deserved everything he got."],
  ["P","I'd had enough. There was no going back. My life was over anyway.","H","Because he'd been driven to it. Everyone thought he'd.... touched Jimmy. Jimmy was clever, you see, too clever. The doctor had no chance. Poor soul.","R","Because he knew he was guilty. He did the right thing."],
  ["P","It was Harvey. He knew Jimmy was lying about me. Harvey understood.","H","It was me. Jimmy had made accusations about the doctor. Rose believed him, but I'd heard that story somewhere before.","R","It was Harvey. He didn't believe what Jimmy was saying. But I knew he wasn't lying."],
  ["P","Jimmy never admitted his lies.","H","Course he didn't! He just laughed. Then he started setting little traps for me. Some of them not so little.","R","No - how could Jimmy admit to something that wasn't true? Harvey was wrong to bully Jimmy like that."],
  ["H","He knew that was my heater, he'd wired the casing straight to the mains. Almost killed me. He did it deliberately, but Rose wouldn't have it. I knew he needed to be taught a lesson. He'd damaged my property so I decided to damage his.","R","Harvey blamed Jimmy, but that heater was faulty. Harvey should have thrown it away."],
  ["P","I don't know, but violence only makes things worse.","H","I smashed up his television and games consoles and stuff. I was angry; but it didn't work. It just made him worse. He soon retaliated.","R","He ruined Jimmy's things. He couldn't control his anger."],
  ["H","Jimmy had set it up to fire when I opened the door. I had to go to into A&E, get stitches and tetanus shots. When I got back I couldn't find him. Rose said he was hiding in the basement. That gave me an idea.","R","Harvey said Jimmy had shot him with an arrow, but I knew Jimmy wouldn’t use a weapon like that."],
  ["H","I wanted to give Jimmy a dose of his own medicine. I thought he couldn’t do any damage down there. I was wrong.","R","I don’t know what he was doing."],
  ["P","I don’t remember it.","H","We managed to contain it before it got out of hand. But all our old photos and letters and everything were down there, it all went up in flames. Jimmy was out of control, I’d had enough of him. I wanted him gone.","R","Harvey blamed Jimmy, but it was a loose wire that started that fire. It was an accident."],
  ["P","I don’t know. But Harvey couldn’t control his anger.","H","I don’t know what I was going to do. Threaten him, get him out of the hotel.... Problem was, I didn’t realise he was going to be armed too.","R","I don’t know. Harvey shouldn’t have had a gun in the hotel."],
  ["H","I was looking for Jimmy."],

  ["H","Jimmy crept up behind me, I didn’t see him. Jimmy always won in the end.","R","Harvey had gone mad. Jimmy was just defending himself."],
  ["H","Rose - Rose believed Jimmy. She defended him, right to the end.","R","It was me. I had to explain to the police that the dagger was just a letter opener and that Harvey had a loaded gun. Jimmy acted in self-defence. They understood."],
  ["H","Jimmy - they let Jimmy go. They said it was self-defence, that I’d tried to shoot Jimmy. But it was all lies.","R","Jimmy - he was coming home. The police understood. They believed him, but it changed him. He started helping me, helping run the hotel. And he found a way of bringing in more guests."],
  ["H","I don’t know who he was.","R","I was enjoying it, we were making money again. Everything seemed to be getting better until.... Jimmy started behaving oddly. I heard him shouting, staring at himself. He seemed angry."],
  ["R","Jimmy - I didn't understand at first, I was confused. But then I realised. Jimmy wasn’t the one doing these things. Like the mirrors, he was starting to fracture. Jimmy wasn’t in control anymore."],
  ["H","I don't know, but I know Jimmy always ruined everything eventually.","R","It wasn't Jimmy on stage anymore, it was Hugo Punch, his comedy character. Hugo started insulting his audience every night. He seemed to be enjoying it. Then one night after the show a guest told Jimmy what she thought of him. Jimmy lost his temper. He did something stupid."],
  ["R","Journalists, they wanted Jimmy. But Jimmy wasn't in control, it was Hugo Punch who tied the woman up. Jimmy couldn't control it anymore. He was depressed. He just wanted to leave everything behind and go."],
  ["R","It was Jimmy. He tried to kill himself. That's why I had to tell him the truth."],
  ["H","I don't know. There were things Rose never told me.","R","Hugo - I buried him down there in concrete, in a secret room. I should have done it sooner. I let him abuse Jimmy for too long. It was my fault Jimmy turned out the way he did. I thought the guilt would go away if I told Jimmy. I was wrong, it made it worse. I couldn’t accept what I'd done. I couldn't live with myself."],
  ["R","If I hadn't done it myself Jimmy would have, or rather, Hugo would have. Hugo’s still in charge, even now. He's controlling Jimmy. Ask Jimmy to show you where Hugo lives."],
  ["H","I never knew him.","R","He was a magician and an entertainer. He bought the hotel to promote his stage show. He became famous, he was on television. I worked as his assistant, then things.... developed."],
  ["R","I never knew what he wanted. There was only one thing I could give him."],
  ["R","Hugo was a violent, evil, sick man."],
  ["A","Yes, he took it when I wasn’t looking and stole my money. I told him off but he wouldn’t listen."],
  ["A","He soaked my toy with that stuff in the bottle, I hated him!"],
  ["A","Yes - he got it down from the wall, it looked really sharp. He made me promise not to tell anyone and he said he could make my hand stop hurting."],
  ["A","Maybe - he told me to keep drinking it. It was horrible. Then I started to feel strange...."],
  ["P","Yes - they suggested a turbulent personality, but I wasn't particularly concerned until.... I started to realise how far his imagination went."],
  ["P","Yes - Jimmy said he'd make something for me, so I followed him to see what he was going to do."],
  ["P","It was my first encounter with Jimmy’s sense of humour."],
  ["P","It wasn’t the ideal medication, but it was all I had. Jimmy needed treating immediately; he was dangerous."],
  ["P","Jimmy said I’d used the paddle to beat him. I would never use violence against a patient, it was ridiculous! But Rose believed him."],
  ["P","Jimmy accused me of the worst crime possible. He took it from a newspaper story he'd read. He was making it all up."],
  ["P","I experimented with the washing line, but it was too thin. I found some rope instead. I still had my keys to the hotel so I crept in one night while I was on bail."],
  ["H","It came straight out of it! As soon as I found that scrapbook I knew where Jimmy had got it from. It was the same, down to every detail."],
  ["H","Jimmy was always playing with electricity. Funny how he was never the one who got shocked."],
  ["H","I kept those bats for self-defence, but I was angry. I took one and went to Jimmy’s room."],
  ["H","Jimmy was fond of weapons like that. I hadn’t seen him all night after I'd smashed his stuff. I should have guessed he’d been working on his next little trick."],
  ["H","Well if Jimmy wanted to hide down there I thought he must like it."],
  ["H","Nobody realised how far Jimmy would go to get attention."],
  ["H","I'd lost it. I was seeing red, I hated him. I'd lost control."],
  ["H","It wasn't even a dagger! But I never learned my lesson, Jimmy was always one step ahead of me."],
  ["R","Yes - that was Jimmy's stage act. He was a comedian. He was good, really good. People started to come just to watch him."],
  ["R","Breaking the mirrors was just the start. I asked him about it but he didn't remember doing any of it. Then other strange things started happening."],
  ["R","Jimmy locked her in a room and tied her up. I didn't know what he was going to do. I found her and let her go. Jimmy said it was a joke! She didn’t press charges, but she told the newspapers."],
  ["R","Jimmy hated what he'd done. He'd been fighting Hugo Punch all his life. It was inside him, making him do all those bad things. Jimmy didn’t want to live anymore."],
  ["R","Yes - we were married. We were happy at first, before things started to change."],
  ["R","I thought having a child would solve everything. I was wrong."],
  ["R","I admitted it all to Jimmy. Jimmy didn't remember Hugo, he'd blocked out the memory. Hugo beat Jimmy from when he was born, for 2 years. I should have stopped it earlier."],
  ["R","I had no choice. Jimmy had gone to find Hugo's grave. I was alone. I knew what I should do."],

],

subob:[

  ["I saw some suitcases in a chest. Who did they belong to?",
  "is that connected to what you said about the suitcases?"],

  ["I found some trophies. Who won them?",
  "does that have anything to do with what you said about the trophies?"],

  ["Who did the child's purse belong to?",
  "is that connected to what you said about the purse?"],

  ["I saw a bottle of turpentine and a lighter. What were they for?",
  "does that have something to do with what you said about the turpentine and lighter?"],

  ["Who does the sword belong to?",
  "does that have anything to do with what you said about the sword?"],

  ["Why was there a collection of whiskey bottles in one of the rooms?",
  "does that have anything to do with what you said about the whiskey bottles?"],

  ["Who drew those violent pictures?",
  "does that have anything to do with what you said about those violent pictures?"],

  ["Who did the chef's hat belong to?",
  "is that connected to what you said about the chef's hat?"],

  ["Why is there a blood-stained cloth in one of the drawers?",
  "does that have something to do with the blood-stained cloth?"],

  ["Where did the bottle of Diazepam come from?",
  "does that have something to do with what you said about the Diazepam?"],

  ["Where did the wooden paddle come from?",
  "is that connected to what you said about the wooden paddle?"],

  ["I saw a scrapbook with newspaper articles in it. Who made it?",
  "does that have something to do with what you said about the scrapbook?"],

  ["Why was there a washing line tied around a rolling pin?",
  "does that have anything to do with what you said about the washing line and rolling pin?"],

  ["Why is there an old heater marked 'dangerous'?",
  "does that have anything to do with what you said about the dangerous heater?"],

  ["What were all the cricket and baseball bats for?",
  "does that have something to do with what you said about the cricket and baseball bats?"],

  ["Where was the crossbow from?",
  "does that have anything to do with what you said about the crossbow?"],

  ["What are those rusty old keys for?",
  "does that have something to do with those rusty keys?"],

  ["Was there a fire at the hotel?",
  "is that connected to what you said about the fire in the hotel?"],

  ["Who does the gun belong to?",
  "does that have something to do with what you said about the gun?"],

  ["Who does the dagger belong to?",
  "does that have anything to do with what you said about the dagger?"],

  ["Who is Hugo Punch?",
  "is that connected to what you said about the Hugo Punch poster?"],

  ["How did those mirrors get broken?",
  "is that connected to what you said about the broken mirrors?"],

  ["What was the coil of wire used for?",
  "is that connected to what you said about the coil of wire?"],

  ["Who wrote the note that says 'goodbye'?",
  "is that connected to the goodbye note?"],

  ["Who did the wedding ring belong to?",
  "is that connected to the wedding ring?"],

  ["Who did the baby's rattle belong to?",
  "does that have something to do with the baby's rattle?"],

  ["I found Jimmy's birth certificate. It says Hugo Hall is Jimmy's real father.",
  "does that have something to do with what you said about Jimmy's birth certificate?"],

  ["I saw a girl in the basement, crying. Who was she?",
  "",
  "When you said Jimmy stole things from you,",
  "When you said Jimmy wasn't nice to the little girl,",
  "What you told me about a young girl staying in the hotel,",
  "What you said about the young girl who was a guest in the hotel,"],

  ["I saw the little girl shouting to Jimmy to give her toy back. Why did he take it?",
  "I saw you shouting to Jimmy to give your toy back. Why did he take it?",
  "What you said about Jimmy stealing your toy,",
  "When you said stealing was the kind of thing Jimmy did,",
  "",
  "When you said Jimmy didn't steal things,"],

  ["I saw the little girl, Amy, holding a toy on fire. What happened?",
  "I saw you holding a toy on fire. What happened?",
  "You said you couldn't tell anyone about your hand getting burned.",
  "What you said about Jimmy thinking setting Amy's toy on fire was a joke,",
  "You said that the little girl got badly burned.",
  "When you said the little girl kept doing dangerous things and blaming Jimmy,"],

  ["I saw Amy outside a room. Something frightened her. What was it?",
  "I saw you outside a room. Something frightened you. What was it?",
  "When you said you needed a doctor but Jimmy threatened you to stay,",
  "",
  "When you said the little girl was probably scared of Jimmy,",
  "When you said there was something strange about the little girl,"],

  ["I saw Amy drinking something. She didn't seem to like it. What was it?",
  "I saw you drinking something. You didn't seem to like it. What was it?",
  "When you said the medicine tasted horrible,",
  "What you said about the little girl, Amy, drinking alcohol,",
  "",
  ""],

  ["I saw the little girl at the top of the stairs, on the banister. What was she doing?",
  "I saw you at the top of the stairs, on the banister. What were you doing?",
  "When you said you thought you could jump down to the bottom of the stairs,",
  "When you said Jimmy made the girl drink too much,",
  "You said Amy had drunk a bottle of whiskey.",
  ""],

  ["I saw Amy lying at the bottom of the stairs. What happened to her?",
  "I saw you lying at the bottom of the stairs. What happened to you?",
  "You said you can't wake up anymore.",
  "You said Amy dying was why Rose got in touch with you.",
  "What you said about Jimmy being behind Amy's death,",
  "What you said about it being Amy's own fault she died,"],

  ["I saw a man knocking on a door, telling Jimmy he was there to help. Who was it?",
  "",
  "",
  "When you said Harvey was worried about Jimmy's mind,",
  "What you said about Jimmy being beyond help,",
  "You said Dr Bose came to help Jimmy."],

  ["I saw Dr Bose holding a dead animal on a wire. What had happened?",
  "I saw you holding up a dead animal on a wire. What had happened?",
  "",
  "When you said Jimmy came up with an idea to do something nice for you,",
  "What you said about Jimmy saying he found the dead animal somewhere,",
  "When you said you didn't believe Jimmy had killed that animal,"],

  ["I saw Dr Bose outside the kitchen, talking to Jimmy. What was he doing?",
  "I saw you outside the kitchen talking to Jimmy. What were you doing?",
  "",
  "When you said you didn't suspect anything was wrong,",
  "When you said it was a mistake for Dr Bose to try to help Jimmy,",
  "When you said Dr Bose was trying to Make Jimmy do things he didn't want to,"],

  ["I saw Dr Bose spitting out blood. What happened?",
  "I saw you spitting out blood. What happened?",
  "",
  "When you said you needed to step up Jimmy's treatment urgently,",
  "When you said about Jimmy's pranks always going too far,",
  "When you said Dr Bose injured himself but blamed Jimmy,"],

  ["I saw Dr Bose with a needle talking to Jimmy. What was he doing?",
  "I saw you with a needle talking to Jimmy. What were you doing?",
  "",
  "When you said Jimmy refused to let you administer his medicine,",
  "",
  "You said Dr Bose was trying to medicate Jimmy without your permission."],

  ["I saw Dr Bose trying to explain what happened with Jimmy. He seemed desperate. ",
  "I saw you trying to explain what happened with Jimmy. You seemed desperate.",
  "",
  "When you said you managed to convince Rose Jimmy was making it up,",
  "When you said Dr Bose was right to be worried, about what else Jimmy would make up about him,",
  "When you said you decided to give Dr Bose another chance,"],

  ["I saw Dr Bose sitting on a bed talking to Jimmy. What was he doing?",
  "I saw you sitting on a bed talking to Jimmy. What were you doing?",
  "",
  "You said Jimmy made up another lie about you, a much worse lie.",
  "",
  "When you said you should never have trusted Dr Bose,"],

  ["I saw Dr Bose upset, the police were banging on the door. What was going on?",
  "I saw you upset and heard the police banging on the door. What was going on?",
  "",
  "When you said you decided to take control once and for all,",
  "You said you didn't believe Jimmy's story about Dr Bose.",
  "When you said Dr Bose deserved to be arrested,"],

  ["I saw Dr Bose tying a rope around his neck. He killed himself. Why?",
  "I saw you tying a rope around your neck. You killed yourself. Why?",
  "",
  "You said you wanted it all to stop.",
  "When you said Dr Bose had been driven to kill himself,",
  "When you said Dr Bose did the right thing,"],

  ["I saw a man saying Jimmy had lied about the assault. Who was he?",
  "",
  "",
  "When you said Harvey knew Jimmy was lying,",
  "When you said you'd heard the story somewhere before,",
  "When you said Harvey was wrong not to believe Jimmy's story,"],

  ["I saw Harvey shouting, telling Jimmy to admit he lied. Did he?",
  "I saw you shouting, telling Jimmy to admit he lied. Did he?",
  "",
  "What you said about Jimmy never admitting his lies,",
  "When you said Jimmy started setting traps for you,",
  "You said Harvey was wrong to bully Jimmy."],

  ["I saw Harvey suffering an electric shock. What happened?",
  "I saw you suffering an electric shock. What happened?",
  "",
  "",
  "When you said you decided to damage his property,",
  "You said Harvey should have thrown that faulty heater away."],

  ["I saw Harvey with a bat, coming out of a room. What had he done?",
  "I saw you with a bat, coming out of a room. What had you done?",
  "",
  "When you said violence only makes things worse.",
  "When you said Jimmy soon retaliated,",
  "What you said about Harvey not being able to control his anger,"],

  ["I saw Harvey being shot in the leg with an arrow. What happened?",
  "I saw you being shot in the leg with an arrow. What happened?",
  "",
  "",
  "When you said you thought Jimmy would like hiding in the basement,",
  "When you said Jimmy wouldn't use a weapon like that,"],

  ["I saw Harvey locking Jimmy in the basement. What happened?",
  "I saw you locking Jimmy in the basement. What happened?",
  "",
  "",
  "You said you were wrong to think Jimmy couldn't do any damage in the basement.",
  ""],

  ["I saw a fire in the basement. What happened to the hotel?",
  "I saw a fire in the basement. What happened to the hotel?",
  "",
  "",
  "When you said you wanted Jimmy gone,",
  "You said the fire in the hotel was an accident."],

  ["I saw Harvey with a gun, practising with it. What was he going to do?",
  "I saw you with a gun, practising with it. What were you going to do?",
  "",
  "You said Harvey couldn't control his anger.",
  "When you said you didn't realise Jimmy would be armed too,",
  "When you said Harvey shouldn't have had a gun in the hotel,"],

  ["I saw Harvey heading towards the ballroom with a gun. What was he doing?",
  "I saw you heading towards the ballroom with a gun. What were you doing?",
  "",
  "",
  "When you said you were looking for Jimmy,",
  ""],

  ["I saw Harvey being stabbed backstage. What happened?",
  "I saw you being stabbed backstage. What happened?",
  "",
  "",
  "When you said Jimmy always won in the end,",
  "When you said Jimmy was just defending himself,"],

  ["I saw a lady explaining that the dagger was a letter opener. Who was she?",
  "",
  "",
  "",
  "You said Rose defended Jimmy right to the end.",
  "When you said the police understood Jimmy had acted in self-defence"],

  ["Who was Rose greeting at the entrance to reception?",
  "Who were you greeting at the entrance in reception?",
  "",
  "",
  "When you said they thought you'd tried to shoot Jimmy,",
  "When you said Jimmy found a way of bringing in more guests,"],

  ["I saw Rose announcing Hugo Punch onto the stage.",
  "I saw you announcing Hugo Punch onto the stage.",
  "",
  "",
  "",
  "What you said about Jimmy staring at himself and becoming angry,"],

  ["I saw Rose in a corridor full of mannequins. Who put them there?",
  "I saw you standing in a corridor full of mannequins. Who put them there?",
  "",
  "",
  "",
  "What you said about Jimmy not being in control anymore,"],

  ["I saw Rose by the ballroom. The audience was booing and she was apologising. What was happening?",
  "I saw you in the ballroom. The audience was booing and you were apologising. What was happening?",
  "",
  "",
  "You said Jimmy ruined everything eventually.",
  "When you said Jimmy lost his temper and did something stupid,"],

  ["I saw Rose upset and people knocking on the door asking questions. Who were they?",
  "I saw you upset, people were knocking on the door asking questions. Who were they?",
  "",
  "",
  "",
  "When you said Jimmy wanted to leave everything behind and go,"],

  ["I saw Rose in a room upstairs. It looked like she found someone in a bathroom. What happened?",
  "I saw you in a room upstairs. It looked like you found someone in a bathroom. What happened?",
  "",
  "",
  "",
  "When you said you had to tell Jimmy the truth,"],

  ["I saw Rose with a wooden bat, attacking someone. Who was it?",
  "I saw you with a wooden bat, attacking someone. Who was it?",
  "",
  "You said Rose had a dark history.",
  "You said there were things Rose never told you.",
  "When you said you couldn't live with yourself,"],

  ["I saw Rose, she was on fire. What happened?",
  "I saw you, you were on fire. What happened?",
  "",
  "",
  "",
  "When you said ask Jimmy to show me where Hugo lives,"],

  ["I saw someone on stage. A performer, announcing himself as The Great Hugo.",
  "",
  "",
  "",
  "When you said Hugo was Rose's first husband,",
  "When you said things developed with Hugo,"],

  ["I heard a man shouting at someone, telling them to do as he says. Who was he?",
  "",
  "",
  "",
  "",
  "You said there was only one thing you could give Hugo."],

  ["I heard a man shouting and a child crying. What happened?",
  "",
  "",
  "",
  "",
  "You said Jimmy is Hugo's son."],

],

subs:[

  "INTRO",[
   13.6,5,"Jimmy!",14.6,4,"",
   16.2,4,"Jimmy!",17.4,4,"",
   18.8,2,"Jimmy!",20,4,"",
   20.1,6,"VOICES FROM SPEAKER",21.6,6,"",
   24.3,3,"Just leave me alone...",25.9,4,"",
   26.5,6,"SOBBING",27.9,4,"",
   28.6,6,"VOICES ECHO LOUDER",30.3,4,"",
   30.7,3,"Stop it!",31.8,4,"",
   32.4,3,"Please just leave me alone!",34.8,4,"",
   35.8,6,"VOICES THROUGH STATIC",37.3,4,"",
   44.5,6,"PHONE RINGS",45.6,0,"",
   46.6,1,"Hello?",47.6,0,"",
   47.7,3,"Maya? It's Hannah.",48.8,0,"",
   49.4,1,"Hannah? Where are you?",51.2,0,"",
   51.3,1,"You all went off and left me behind!",53.6,0,"",
   53.7,1,"Where are you now? What's this number?",55.6,0,"",
   55.7,3,"We've all booked into a hotel up the road.",57.4,0,"",
   57.5,3,"How far away are you?",58.8,0,"",
   58.9,1,"I don't know. I'll have to call when I get there.",61.1,0,"",
   61.2,3,"You can't, there's no signal.",62.9,0,"",
   63,1,"Well... ",64.1,1,"",
   65,1,"Doesn't matter. Just go to bed Hannah.",67,0,"",
   67.1,3,"Well listen. Make sure you're...",68.3,0,"",
   68.6,6,"CALL BREAKS UP",70.1,0,"",
   71,6,"CALL ENDS",72.5,0,"",
   84,6,"1950s JAZZ MUSIC ON RADIO",85.5,4,"",
   92.1,3,"Ah, Maya I presume?",94.1,0,"",
   94.5,3,"Oh, don't be alarmed.",96.4,0,"",
   96.6,3,"Your friends booked you in...",99,0,"",
   99.1,3,"let me just check.",100.8,0,"",
   101.8,3,"Ah. Yes.",102.8,0,"",
   102.9,3,"Room 101.",104,0,"",
   104.2,3,"It's all been paid for so you don't have to worry about anything.",107.2,0,"",
   107.3,3,"You have very nice friends.",109.1,0,"",
   109.9,3,"Very nice.",111.2,0,"",
   111.5,3,"And there's quite a few of you I see as well.",115.6,0,"",
   116.2,3,"Nice to see so many...",118.2,0,"",
   118.3,3,"fresh, young faces for a change.",122.7,0,"",
   123.5,3,"Er... you're here for the music festival in town I presume?",126.8,0,"",
   127.3,1,"Yeah, we were supposed to be camping there tonight, but...",130.5,0,"",
   130.6,3,"There's hardly weather for that is there!",133.1,0,"",
   136,3,"Will you be staying for breakfast?",137.5,0,"",
   137.6,1,"I don't think so, we'll probably just get going.",140.2,0,"",
   140.3,3,"That's fine. And if you don't mind me asking Maya,",143.7,0,"",
   143.8,3,"would you be interested in the entertainment tonight?",147.5,0,"",
   147.9,1,"Tonight?",148.9,0,"",
   149,3,"Er, starts around midnight, usually.",152.1,0,"",
   152.6,3,"It's me doing it actually, comedy.",155.8,0,"",
   155.9,3,"I do this comedy character called Hugo Punch,",161,0,"",
   161.1,3,"he's sort of this comedic sociopath,",164.8,0,"",
   164.9,3,"says things that you're not supposed to say and that sort of thing.",169.6,0,"",
   169.7,3,"It's quite popular with students.",171.7,0,"",
   172.3,1,"I don't think so, we're all just going to bed I think.",175.7,0,"",
   175.8,3,"You're sure I can't twist your arm on this?",179.2,0,"",
   179.5,1,"It's OK I'd rather just go to bed. Sorry.",182.8,0,"",
   182.9,3,"Fine, fine, fine...",185.4,0,"",
   185.6,1,"Which way are the rooms?",186.7,0,"",
   187.2,3,"Erm just take the lifts, you're on the first floor.",190.2,0,"",
   190.3,1,"OK thanks.",191.6,0,"",
   193.1,3,"Oh and drop your key off in the box if you will Maya, please, tomorrow.",198.1,0,"",
   198.2,1,"OK!",199.2,0,"",
   199.3,6,"LIFT DOOR CLOSES",200.8,0,"",
   204.4,3,"Best show in town and no takers.",207.2,0,"",
   210.3,3,"Who needs proper entertainment when you've got 'You Tune' and 'My Face' and whatever.",216.6,0,"",
   216.7,3,"Stupid, uncultured...",218.7,0,"",
   218.8,5,"Hugo doesn't like rude children, they're naughty.",223,0,"",
   225.5,3,"Don't start this again.",227.3,0,"",
   231.1,3,"I don't want to hear it, OK. Not tonight.",234.2,0,"",
   237,5,"Naughty children are bad eggs. They need to be taught a lesson!",240.9,0,"",
   254.2,3,"Shut up! Just shut up!",256.5,0,"",
   257.3,3,"You always do this, they're paying customers.",260.2,0,"",
   260.5,3,"They haven't done anything to you.",262.4,0,"",
   263.3,3,"Just leave them alone.",265.4,0,"",
   266.2,5,"Bad eggs need cracking! Whack 'em hard and crack their shell,",269.3,0,"",
   269.5,5,"kick 'em down the stairs to Hell!",272.3,0,"",
   272.8,5,"You know what you need to do, Jimmy.",275,0,"",
   275.6,5,"Show them who's boss.",277.7,0,"",
   278.9,5,"That's the way to do it!",281.1,0,"",
   293.3,6,"DISTANT SCREAM",294.9,0,"",
   308,6,"MAN LAUGHS",309.6,0,"",
   310,3,"That's it, go to sleep...",313,0,"",
   345.2,6,"PHONE CRACKLES",346.9,0,"",
   358.5,6,"VOICES FROM SPEAKER",361.9,0,"",
   362,1,"Get out of the hotel!",363.6,0,"",
   363.7,1,"Get out while you can!",365.7,0,"",
   367.6,1,"You have to find out what he did...",369.3,0,"",
   369.4,1,"...and tell everyone.",371.3,0,"",
   371.4,1,"Make him realise what he did!",373.3,0,"",
   373.5,6,"VOICES FADE INTO STATIC",376,0,"",
   420,1,"",420.9,0,"X",
],
  "A2",[
   0.8,1,"Jimmy, give it back! That's mine!",2.9,0,"",
   3,1,"Stop stealing my things!",4.3,0,"X",
],
  "A3",[
   0.7,6,"SCREAMS",2,0,"X",
],
  "A4",[
   1.1,1,"I'm telling you Jimmy, you can't do that!",3.1,0,"",
   3.2,1,"You're horrible...",4.7,0,"X",
   3.8,6,"VOICE TRAILS OFF",4.4,0,"X",
],
  "A5",[
   3.8,6,"COUGHS",4.8,0,"X",
],
  "A6",[
   4.2,6,"GIGGLES",5.2,0,"X",
],
  "P1",[
   3.8,6,"KNOCKS",4.8,0,"",
   5.8,2,"Jimmy?",6.8,0,"",
   7.2,2,"I'm Doctor Bose.",8.9,0,"",
   9,2,"I'm just here to have a little chat, OK?",11.5,0,"",
   14.5,2,"Thank you Jimmy, I won't be long.",16.6,2,"X",
],
  "P3",[
   1,2,"This is a great idea, Jimmy!",3.4,0,"",
   3.5,2,"I reckon you'll make a great cook one day.",5.7,0,"",
   5.8,2,"Why don't you bring it up to me when you're done?",8,0,"",
   8.1,2,"I'll wait for you, OK?",9.8,0,"X",
],
  "P4",[
   3,6,"SPLUTTERS",4,0,"",
   7.6,2,"Jimmy!",8.6,0,"X",
],
  "P5",[
   1.2,2,"This won't hurt Jimmy.",2.9,0,"",
   3,2,"All you have to do is to stand still and stop moving around!",6.6,0,"X",
],
  "P6",[
   0.6,2,"I would never use force like that on a patient Mrs Hall.",4.8,0,"",
   4.8,2,"It goes against everything I believe in.",7.3,0,"",
   7.4,2,"You have to understand, he's making it all up!",10,0,"X",
],
  "P7",[
   1.1,2,"You can't get away from me that easily Jimmy.",3.9,0,"",
   4,2,"I think we should start again, don't you?",6.5,0,"",
   6.6,2,"Why don't you do what I ask you to do this time?",8.7,0,"",
   8.8,2,"That would be a good start, wouldn't it?",11,0,"X",
],
  "P8",[
   0.6,2,"It's the police, Mr Bose.",2.1,0,"",
   2.2,2,"We need you to come down to the station.",4.1,0,"",
   4.4,2,"Can you open the door please?",5.8,0,"X",
],
  "P9",[
   14.1,6,"CHOKES",15.5,0,"",
   15.9,6,"LIFT ALARM SOUNDS",16.9,0,"X",
],
  "H1",[
   0.8,3,"He made it up. I'm telling you he's been lying about everything,",3.4,0,"",
   3.5,3,"Probably lied about the other stuff as well.",5,0,"",
   5.1,4,"Don't be ridiculous! He wouldn't lie about something like that!",7.3,0,"",
   7.4,3,"You sure about that?",8.3,0,"",
   8.4,3,"He lies about everything! Open your bloody eyes Rose!",11.4,0,"",
   11.5,3,"Oh that's right! Walk off!",12.8,0,"",
   12.9,4,"I'm not listening Harvey, you've just got it in for him.",14.7,0,"",
   14.9,3,"It's the truth!",16.2,0,"X",
],
  "H2",[
   1.5,6,"BANGS ON DOOR",2.4,0,"",
   2.5,3,"Jimmy?",3.5,0,"",
   4.3,3,"I know you can hear me!",5.8,0,"",
   6.2,3,"I know you made it up, your little story about that psychiatrist.",10,0,"",
   10.1,3,"I know where you got it from!",11.6,0,"",
   12,3,"I knew I'd read it before, it's in your bloody scrap book!",15.3,0,"",
   16.1,3,"Come out here!",17.3,0,"",
   18.3,3,"Jimmy!",19.6,0,"X",
],
  "H3",[
   1.2,6,"ELECTRICAL SPARKING",2.2,0,"",
   2.3,6,"CRIES OUT IN PAIN",3.3,0,"",
   7.2,3,"Jimmy!",8.2,0,"X",
],
  "H4",[
   1,6,"THINGS SMASHING",2,0,"X",
],
  "H5",[
   0.8,6,"SHOUTS IN PAIN",1.9,0,"",
   4.1,3,"Jimmy!",5.1,0,"X",
],
  "H6",[
   1.3,3,"You can stay in there for the night, Jimmy!",3.7,0,"",
   3.8,3,"I've had enough.",5,0,"",
   5.1,6,"BANGING ON DOOR",6.6,0,"X",
],
  "H7",[
   0.3,6,"FIRE ALARM",1.8,0,"",
   2.7,3,"Jimmy don't be stupid, open the door!",4.9,0,"",
   5.2,3,"You'll just get killed you stupid idiot! Open the door!",8.4,0,"X",
],
  "H8",[
   2.7,3,"Get out of the hotel Jimmy.",4.6,0,"",
   6.6,3,"Get out of my hotel...",8,0,"",
   8.6,3,"This is my hotel. Get out of my hotel Jimmy.",12,0,"X",
],
  "H9",[
   1.8,3,"Get out of my hotel.",3.2,0,"",
   3.3,3,"This is MY hotel.",5,0,"X",
],
  "R1",[
   0.8,8,"Harvey was going to shoot Jimmy.",2.4,0,"",
   2.5,8,"It was just a letter opener. It was self-defence! Look!",5.9,0,"X",
],
  "R2",[
   3.5,4,"Jimmy",4.5,0,"X",
],
  "R3",[
   1.2,4,"Ladies and gentlemen.",2.4,0,"",
   2.5,4,"Please welcome to the stage,",3.9,0,"",
   4,4,"your entertainment for this evening,",5.9,0,"",
   6,4,"Mr Hugo Punch!",8,0,"",
   8.1,6,"MUSIC AND APPLAUSE",9.6,0,"X",
],
  "R4",[
   0,4,"",0,0,"",
],
  "R5",[
   0.7,4,"It's just his comedy routine.",2.6,0,"",
   2.7,4,"It's his sense of humour!",4.4,0,"",
   4.5,4,"I'm sorry if you've been offended...",6.3,0,"",
   6.4,4,"Excuse me...",7.6,0,"X",
],
  "R6",[
   0.5,6,"BANGING ON FRONT DOOR",1.8,0,"",
   1.9,4,"Mrs Hall?",3.4,0,"",
   4.2,4,"Mrs Hall, can we have a word please?",6.5,0,"X",
],
  "R7",[
   1.4,4,"Jimmy?",2.4,0,"",
   4.1,6,"SCREAMS",5.1,0,"",
   5.2,4,"Jimmy! What have you done! Jimmy!",8,0,"X",
],
  "R8",[
   0.5,6,"CHILD CRYING",1.5,0,"",
   1.6,5,"You will do what I tell you to! Do you understand me?",4.2,0,"",
   4.3,5,"Stupid little wretch!",5.4,0,"",
   5.5,6,"CHILD BEING SLAPPED",6.7,0,"",
   6.9,6,"BAT HITTING MAN",8.3,0,"X",
],
  "R9",[
   1.4,6,"SCREAMS",2.9,0,"X",
],
  "V1",[
   5.5,7,"Behold!",6.3,0,"",
   6.4,6,"GONG",7.4,0,"",
   7.5,7,"I am the great Hugo!",10.2,0,"",
   11.9,7,"I stand alone above all others.",15.9,0,"",
   17.4,7,"I am the light which illuminates the darkness.",21.4,0,"",
   22.7,7,"I alone am master.",26.5,0,"X",
],
  "V2",[
   5,6,"WOMAN SOBBING",6.5,0,"",
   8,5,"Do not buy anything without my permission!",10.5,0,"",
   10.6,6,"GLASS SMASHING",11.5,0,"",
   11.6,5,"I will not allow you to ruin my life!",14,0,"",
   14.1,6,"MORE SMASHING",15.2,0,"",
   15.1,5,"Your life means nothing!",16.8,0,"",
   16.9,5,"Do you understand what I'm telling you?",18.6,0,"",
   18.7,6,"SMASHING AND WOMAN SCREAMS",20.9,0,"X",
],
  "V3",[
   3.1,6,"CHILD CRYING",4.6,0,"",
   9,5,"Sit still!",10,0,"",
   10.1,6,"WHIPPING SOUND",11.4,0,"",
   11.5,5,"You stupid little wretch!",12.8,0,"",
   12.9,5,"Do what I tell you to!",14.9,0,"",
   15,6,"WOMAN SCREAMS<br>No!",17,0,"X",
],
  "EPI",[
   17.9,3,"Ladies and gentlemen,",19,0,"",
   19.1,3,"Please welcome to the stage,",20.6,0,"",
   20.7,3,"your entertainment for this evening,",22.5,0,"",
   22.6,3,"Mr Hugo Punch!",24.7,0,"",
   24.8,6,"APPLAUSE",26.4,0,"",
   33.5,5,"Maya!",34.5,0,"",
   36.1,5,"Maya!",37.1,0,"",
   40.5,5,"Maya?",41.5,0,"",
   42,5,"Maya!",43.5,0,"",
   44,6,"SOBBING",46,0,"",
   47.5,3,"Stop, stop, stop, stop...",49.9,0,"",
   50,3,"Stop it.",51.5,0,"",
   52.6,3,"Why do you keep making me do these things?",55.3,0,"",
   56,3,"Please just stop.",57.5,0,"",
   58.4,3,"Please just stop it, stop it...",60.4,0,"",
   63.2,5,"You're always going to do it, Jimmy.",64.9,0,"",
   66.7,5,"I'm in charge.",68.6,0,"",
   68.7,5,"Not you.",69.7,0,"",
   71,5,"I'm in charge.",73.5,0,"",
],
  "BRO",[
   1.5,5,"Welcome to Hugo's grave!",5.5,5,"",
   5.6,5,"Mother's little secret.",8.9,5,"",
   9,5,"She mixed the concrete herself you know,",11.8,5,"",
   11.9,5,"then poured it over his lifeless body",15.1,5,"",
   15.2,5,"and watched it set.",17.8,5,"",
   18.1,5,"She thought she'd got rid of him.",21,5,"",
   21.3,5,"But she didn't get it, Maya.",24.7,5,"",
   24.8,5,"You see, Hugo was just one of us.",29.1,5,"",
   29.2,5,"Just another log on the fire.",33,5,"",
   33.2,5,"He burned out.",35.8,5,"",
   36,5,"But the fire's been burning down the Halls for centuries.",41.2,5,"",
   41.3,5,"Clearing the way...",43.5,5,"",
   43.6,5,"lighting the darkness...",45.9,5,"",
   46,5,"laying waste to the old and the poor and the weak.",52.3,5,"",
   52.4,5,"And it's burning in you too, Maya.",56.7,5,"",
   56.8,5,"I can tell!",58.8,5,"",
   59,5,"We are destined to be together you and I.",62.9,5,"",
   63,5,"You're the one I've been waiting for.",66.6,5,"",
   66.8,5,"Which is why I can't let you leave.",71,5,"",
   71.1,5,"You're staying here with me, Maya.",75.2,5,"",
   75.3,5,"Forever.",77.5,5,"X",
],
  "COR",[
   0.2,5,"Talking to the dead, Maya?",4.3,1,"",
   4.5,1,"I know Hugo's your father, Jimmy.",6.6,1,"",
   6.7,1,"I found your birth certificate, and I know Rose tried to kill him.",10.5,1,"",
   10.6,5,"But she failed, didn't she.",13.6,1,"",
   13.7,1,"Then where is he now?",15.5,1,"",
   15.8,6,"LAUGHS",17,1,"",
   20.3,5,"Well why don't you come and meet him?",22.8,1,"",
   22.9,5,"It's time I introduced you to the family, Maya.",27.8,1,"",
   27.9,6,"LAUGHS",29,1,"X",
],
  "AP",[
   2.6,5,"Hello Maya!",5,1,"",
   6.5,5,"Maya!",7.5,5,"",
   9,5,"Maya!",10.3,5,"",
   10.4,6,"BANGING ON DOOR",11.4,5,"",
   11.9,5,"You can't escape me, Maya!",14.9,5,"",
   15,5,"Open the door!",16.2,5,"X",
],
  "TUT",[
   0.83,1,"THE SITUATION",
   4.33,1,"",
   6.4,1,"This is Jimmy Hall the proprietor",
   9.3,1,"And dangerous Psychopath",
   12.37,1,"",
   15.27,1,"He has dark plans for Maya’s friends",
   18.3,1,"",
   19.4,1,"Maya has escaped",
   22.4,1,"",
   24.23,1,"Jimmy knows he has to stop her",
   27.33,1,"",
   27.83,1,"THE CHASE",
   31.57,1,"",
   33.3,1,"Jimmy hides wherever he can",
   36.8,1,"",
   39.37,1,"Around corners",
   41.63,1,"",
   42.33,1,"In the shadows",
   44.33,1,"",
   45.27,1,"Waiting for you to arrive",
   47.6,1,"",
   48.23,1,"Or sneaking up behind you",
   50.57,1,"",
   51.2,1,"He can’t hide on the stairs",
   53.53,1,"",
   54.33,1,"Or on the ground floor",
   56.47,1,"",
   57.33,1,"Or in the basement",
   60.27,1,"",
   60.7,1,"STRATEGY",
   64.67,1,"",
   66.17,1,"If Jimmy sees you, move away",
   67.67,1,"Out of his line of sight",
   71.83,1,"",
   75.13,1,"You can hide in any unlocked room",
   78.17,1,"",
   79.67,1,"If Jimmy comes in",
   81.73,1,"",
   84.13,1,"Hide in a wardrobe",
   86.4,1,"",
   90.2,1,"Or in the bathroom",
   92.33,1,"",
   94.73,1,"Use the spy glass in guest rooms",
   97.67,1,"",
   98.53,1,"To see if Jimmy is outside",
   101.43,1,"",
   103.63,1,"Call out to attract him",
   105.2,1,"",
   106.67,1,"To control where he goes",
   109.67,1,"",
   110.23,1,"Find room keys in drawers",
   112.67,1,"",
   114.17,1,"Lock Jimmy out of rooms",
   116.4,1,"",
   117.83,1,"Or lock him in",
   120.13,1,"If you can escape first",
   123.17,1,"",
   124.67,1,"Quickly check rooms by looking through keyholes",
   127.7,1,"",
   129.67,1,"THE DEAD",
   133.5,1,"",
   135.17,1,"Jimmy has a murderous past",
   138.2,1,"His victims never left",
   141.17,1,"They still haunt the hotel",
   144.47,1,"",
   145.67,1,"Use the spirit receiver to talk to them",
   150.2,1,"",
   153.23,1,"Ask them about the things you’ve seen and uncover their story",
   159.07,1,"",
   159.13,1,"Asking about important connections will make them appear",
   166.63,1,"",
   168.17,1,"Then follow the flickering lights",
   171.1,1,"And listen for strange sounds",
   174.07,1,"",
   175.47,1,"Use a compass to guide you",
   178.4,1,"",
   180.07,1,"When you’re near, keep looking around",
   183.07,1,"Or keep still and watch ahead",
   186.17,1,"",
   186.7,1,"MAYA’S TALENT",
   191.5,1,"",
   192.5,1,"Maya can see into the otherworld",
   196.5,1,"",
   197.97,1,"Move to a dimly lit place",
   200.43,1,"",
   201.43,1,"Then use the mirror",
   204.67,1,"",
   206.27,1,"You will see: The location of important items...",
   209.2,1,"The locations of spirits...",
   212.23,1,"Connections between items & spirits",
   217.23,1,"",
   218.3,1,"Sometimes Jimmy steals things if he catches you",
   222.77,1,"",
   224.27,1,"Look for your spirit receiver in the first floor store room (near the stairs)",
   229.3,1,"",
   230.27,1,"Find compasses & keys in guest rooms",
   234.77,1,"",
   236.23,1,"Read the ghost receiver instructions for more advice on ghost hunting",
   241.47,1,"",
],
],

itexts:[

  "some old suitcases",
  "some trophies and awards",
  "a child's purse",
  "a bottle of turpentine and a lighter",
  "an ornamental sword",
  "some bottles of whiskey and other spirits",
  "some childish violent drawings",
  "a chef's hat",
  "an old cloth covered in blood stains",
  "a syringe and a bottle of Diazepam medicine",
  "an old wooden paddle or beater",
  "a scrapbook of newspaper articles",
  "a washing line and a rolling pin",
  "an old heater marked 'dangerous'",
  "some cricket and baseball bats",
  "a crossbow",
  "some old rusty keys",
  "some photos of smoke coming out of the hotel",
  "an old hand gun",
  "an ornate dagger",
  "a poster for Jimmy Hall's comedy act",
  "some broken wall mirrors",
  "a coil of copper wire",
  "a hand written note which reads 'Good bye'",
  "a ring in its box",
  "a toy for a baby",
  "Jimmy Hall's birth certificate",

],

ketex:[

  "Key To Room ",
  "You noted the ",
  "You noted '",
  "You collected the ",
  "You collected the key for room ",
  "A Compass",
  "A Scrying Mirror",

],

patex:[

  ["H","They belonged to Rose, but she never used them.","R","[The suitcases] were mine. I wanted to go away, but I never got chance."],
  ["R","Jimmy bought [the trophies], to make it look like he'd won awards."],
  ["A","[The purse] was mine. It was for my birthday, but it was stolen.","H","It was that girl's purse, poor thing.","R","[The purse] belonged to the little girl."],
  ["A","I didn't know what [the turpentine and lighter] were, until Jimmy showed me.","P","You'd better ask Jimmy.","H","[The turpentine and lighter] were my things, but I didn't keep them together.","R","[The turpentine and lighter] belonged to Harvey."],
  ["A","Jimmy had [the sword]. I didn't like it.","P","I saw Jimmy playing with [the sword]. I thought it was dangerous.","H","We had a display of medieval weapons. Jimmy stole [the sword].","R","[The sword] belonged with a suit of armour we had. But it went missing."],
  ["A","I don't know [where the bottles came from], but children shouldn't drink alcohol.","P","[The bottles] were probably from the bar.","H","I don't remember [where the bottles came from], but there's nothing wrong with having a drink.","R","Harvey must have put [the bottles] there."],
  ["A","The boy used to draw [the violent pictures].","P","Jimmy used to draw [the violent pictures].","H","Who do you think [drew the violent pictures]? Jimmy! He had a very violent imagination, did little Jimmy.","R","Jimmy used to draw [violent] pictures about the war. He was like most boys."],
  ["P","Jimmy found [the chef's hat] and put it on.","H","It was the chef's, who else wears a chef's hat?","R","Our chef used to wear [the chef's hat]."],
  ["A","[The cloth] could have been mine.","P","[The cloth] was mine. I kept it, in case I needed it as evidence.","H","[The cloth] might have had something to do with the doctor."],
  ["P","[The medicine] can help treat impulsive behaviour, in some people.","H","Probably the doctor left [the medicine].","R","[The medicine] belonged to Doctor Bose."],
  ["P","I don't know, but Jimmy found [the paddle].","H","[The paddle] was always under the counter in reception. I don't know where it came from.","R","[The paddle] belonged to my husband."],
  ["A","Jimmy made [the scrapbook]. I don't know why. He was strange.","P","Jimmy made [the scrapbook]. It was a warning, I should have seen it coming.","H","Jimmy used to keep cut outs of news stories about abusive teachers and doctors. He wasn't a normal boy.","R","Harvey said Jimmy made [the scrapbook], but I don't remember."],
  ["P","I tied [the washing line and rolling pin] together. It was an experiment."],
  ["H","[The old heater] was giving electric shocks. I kept it so the police could check it.","R","Harvey put [the old heater] away. He said it was dangerous."],
  ["A","The boy played with [the bats].","P","Harvey kept [the bats]. I don't know why.","H","I kept [the bats], in case I needed them.","R","[The bats] belonged to my husband, when he was a teacher."],
  ["A","[The crossbow] was in a cabinet, in the hotel. I saw it.","P","The hotel used to have a display of old weapons.","H","[The crossbow] was from an armoury display we used to have. Jimmy was fond of it.","R","[The crossbow] was from a display Harvey used to have. But I didn't like it being in the hotel."],
  ["H","[The rusty keys] were for the old boiler room door.","R","[The rusty keys] were to the boiler room, but we had to have the door replaced."],
  ["P","I never heard about that.","H","They managed to contain it, but I lost a lot of stuff.","R","We caught it in time, before it spread."],
  ["P","Harvey owned [the gun]. I didn't like it being in the hotel.","H","[The gun] was mine. Belonged to my father. Still had a few rounds with it.","R","[The gun] belonged to Harvey, but it was kept in my bedroom."],
  ["A","Jimmy showed it to me, but it wasn't his.","H","It's not a dagger, it's a letter opener. It's not supposed to be sharp.","R","[The dagger] was a letter opener. It was a present from someone."],
  ["R","[The poster] was for Jimmy's comedy act."],
  ["P","I didn't see [the broken mirrors].","H","I don't remember that.","R","Jimmy broke [the mirrors]."],
  ["A","Jimmy used to carry it around with him.","P","[The copper wire] belonged to Jimmy. He always kept it in his pocket. He didn't tell me what he used it for.","H","Jimmy used to carry [copper wire] around with him. No idea why.","R","Jimmy used to carry wire around with him. He liked playing around with electronics."],
  ["R","Jimmy wrote [the 'goodbye' note]."],
  ["H","[The ring] probably belongs to Rose.","R","[The ring] was mine. Someone made me an offer I couldn't refuse."],
  ["A","I don't know. I didn't see a baby.","R","[The rattle] was for the baby. I kept it in my bedside drawer."],
  ["R","Jimmy is Hugo’s son. In every way."],
  ["A","A boy called Jimmy locked me in the basement. Then he started stealing things from me.","P","[The girl] was the daughter of a hotel guest. Jimmy wasn't nice to her.","H","[The girl] was staying in the hotel with her family.","R","[The girl] was a guest in the hotel."],
  ["A","[Jimmy] thought [stealing my toy] was funny. He gave it back, but then he ruined it anyway.","P","It's just the kind of thing [Jimmy] did.","H","[Jimmy] probably thought it was funny.","R","The girl was lying. Jimmy didn't steal things."],
  ["A","My hand got burned, it was really hurting, but I couldn't tell anyone.","P","[The girl's] hand was badly burned quite badly, but Jimmy thought it was all a joke.","H","[The girl] was burned, pretty badly.","R","[The girl] was burned, but she kept doing dangerous things like that. She was odd."],
  ["A","I was trying to find a doctor, but Jimmy threatened me and made me stay.","H","[The girl] was probably scared of Jimmy.","R","[The reason Amy was scared] could have been anything. She was a strange girl."],
  ["A","The boy said it was medicine. It tasted horrible.","P","I wasn't there then, but I think she drank alcohol."],
  ["A","I felt really light, I really thought I could jump down to the bottom.","P","Jimmy made the girl drink too much.","H","[The girl had] drunk a bottle of whiskey, she didn't know what she was doing.","R","I didn't know much about [the girl]."],
  ["A","I jumped, but then it all went dark and I couldn't wake up. I can't wake up anymore.","P","[The girl] fell down the stairs from the top floor. She was too drunk to know what she was doing. It was the reason Rose got in touch with me.","H","[The girl] fell from the top floor down the stairs. I knew Jimmy had to be behind it.","R","[The girl] fell. Harvey blamed Jimmy for it. It was the girl's own fault, not Jimmy's."],
  ["P","I got a call from Rose. She wanted me to find out what was bothering Jimmy. But Harvey was worried about the things Jimmy was imagining.","H","Doctor Bose was supposed to help Jimmy, but Jimmy was beyond help.","R","Doctor Bose came to help Jimmy."],
  ["P","Jimmy was killing things. I realised he needed to work on his empathy skills. So I asked him to think of something nice he could do for me. He came up with an idea right away.","H","Jimmy said he'd found [the dead rabbit] somewhere. What he was doing with it is another story.","R","Harvey said Jimmy had probably killed [the rabbit] himself, but I didn't believe him."],
  ["P","Jimmy was making me a sandwich. He brought it up to my room, as I asked. I didn't suspect anything was wrong at first.","H","The doctor was trying to educate Jimmy, get him to help out. Big mistake.","R","Doctor Bose kept trying to make Jimmy do things he didn't want to."],
  ["P","Jimmy had put broken glass in my sandwich. I nearly choked on it. I realised I'd underestimated Jimmy's illness. I had to step up his treatment, urgently.","H","[Doctor Bose] learned about Jimmy the hard way. Jimmy's pranks always went too far.","R","[Doctor Bose] cut himself, but then he tried to blame Jimmy. He did it to himself, it wasn't Jimmy."],
  ["P","Jimmy refused to let me administer the drug. Then he told Rose I'd tried to force him to take it, that I'd used violence. It was ridiculous!","H","I don't know, I wasn't there.","R","[Doctor Bose] was trying to medicate Jimmy, without my permission."],
  ["P","I was worried Rose would believe Jimmy. It was a bare faced lie. But I managed to convince Rose that Jimmy was making it up.","H","[Doctor Bose] was worried about what else Jimmy would make up about him. And he was right to be.","R","Because [Doctor Bose] was worried about his reputation. But I decided to give him another chance."],
  ["P","I thought when [Jimmy] realised he'd been caught lying he'd start to engage with me. Instead he just made up another lie. Only this one was much worse. The worst.","R","[Doctor Bose] was talking to Jimmy, trying to control him. Get him to do bad things. I should never have trusted him."],
  ["P","Rose reported me. I knew they'd strike me off. I had no career, no future. I decided to take control, once and for all.","H","They were going to arrest [Doctor Bose]. Jimmy had ruined him. But I didn't believe any of it.","R","They came to arrest [Doctor Bose]. He deserved everything he got."],
  ["P","I'd had enough. There was no going back. My life was over anyway.","H","[Doctor Bose had] been driven to it. Everyone thought he'd 'touched' Jimmy. Jimmy was too clever. The doctor had no chance.","R","[Doctor Bose] knew he was guilty. He did the right thing."],
  ["P","Harvey knew Jimmy was lying about me. Harvey understood.","H","Jimmy had made accusations about the doctor. Rose believed him, but I'd heard that story somewhere before.","R","Harvey didn't believe what Jimmy was saying [about the doctor], but I knew he wasn't lying."],
  ["P","Jimmy never admitted his lies.","H","Jimmy just laughed. Then he started setting little traps for me. Some of them not so little.","R","How could Jimmy admit to something that wasn't true? Harvey was wrong to bully Jimmy like that."],
  ["H","[Jimmy] knew that was my heater, he'd wired the casing straight to the mains. I knew he needed to be taught a lesson. He'd damaged my property so I decided to damage his.","R","Harvey blamed Jimmy, but that heater was faulty. Harvey should have thrown it away."],
  ["P","I don't know [what Harvey was doing with the bat], but violence only makes things worse.","H","I smashed up [Jimmy's] television and games consoles. I was angry. But it didn't work. It just made him worse. He soon retaliated.","R","[Harvey] ruined Jimmy's things. He couldn't control his anger."],
  ["H","Jimmy had set [the crossbow] up to fire when I opened the door. I had to go to into A&E. When I got back I couldn't find him. Rose said he was hiding in the basement. That gave me an idea.","R","Harvey said Jimmy had shot him with an arrow, but I knew Jimmy wouldn’t use a weapon like that."],
  ["H","I wanted to give Jimmy a dose of his own medicine. I thought he couldn’t do any damage [in the basement]. I was wrong.","R","I don’t know what [Harvey] was doing [in the basement]."],
  ["P","I don’t remember [the hotel fire].","H","We managed to contain [the hotel fire] before it got out of hand. But all our old photos and letters were down there, it all went up in flames. Jimmy was out of control, I’d had enough of him. I wanted him gone.","R","Harvey blamed Jimmy [for the hotel fire], but it was a loose wire that started that fire. It was an accident."],
  ["P","I don’t know [where the gun came from]. But Harvey couldn’t control his anger.","H","I don’t know what I was going to do [with the gun]. Problem was, I didn’t realise he was going to be armed too.","R","I don’t know [where the gun came from]. Harvey shouldn’t have had a gun in the hotel."],
  ["H","I was looking for Jimmy."],
  ["H","Jimmy crept up behind me, I didn’t see him. Jimmy always won in the end.","R","Harvey had gone mad. Jimmy was just defending himself."],
  ["H","Rose believed Jimmy. She defended him, right to the end.","R","I had to explain to the police that the dagger was just a letter opener and that Harvey had a loaded gun. Jimmy acted in self-defence. They understood."],
  ["H","[The police] let Jimmy go. They said it was self-defence, that I’d tried to shoot Jimmy. But it was all lies.","R","Jimmy was coming home. The police understood [it was self-defence]. But it changed him, he started helping run the hotel. And he found a way of bringing in more guests."],
  ["H","I don’t know who [Hugo Punch] was.","R","I was enjoying it, we were making money again. Then Jimmy started behaving oddly. I heard him shouting, staring at himself. He seemed angry."],
  ["R","I didn't understand at first, I was confused. But then I realised Jimmy wasn’t the one doing these things. Like the mirrors, he was starting to fracture. Jimmy wasn’t in control anymore."],
  ["H","I don't know, but I know Jimmy always ruined everything eventually.","R","It wasn't Jimmy on stage anymore, it was Hugo Punch. He started insulting his audience every night. Then one night after the show a guest told Jimmy what she thought of him. He lost his temper and did something stupid."],
  ["R","Journalists [were banging on the door], they wanted Jimmy. But it was Hugo Punch who tied the woman up. Jimmy couldn't control it anymore. He was depressed. He just wanted to leave everything behind and go."],
  ["R","It was Jimmy [in the bath]. He tried to kill himself. That's why I had to tell him the truth."],
  ["H","I don't know [who Rose was attacking]. There were things Rose never told me.","R","I buried Hugo [in the basement] in concrete, in a secret room. I let him abuse Jimmy for too long. It was my fault Jimmy turned out the way he did. I thought the guilt would go away if I told Jimmy. I was wrong, it made it worse. I couldn’t accept what I'd done. I couldn't live with myself."],
  ["R","If I hadn't [killed] myself Jimmy would have, or rather, Hugo would have. Hugo’s still in charge, even now. He's controlling Jimmy. Ask Jimmy to show you where Hugo lives."],
  ["H","I never knew [The Great Hugo].","R","Hugo was a magician and an entertainer. He bought the hotel to promote his stage show. He became famous. I worked as his assistant, then things developed."],
  ["R","I never knew what he wanted. There was only one thing I could give him."],
  ["R","Hugo was a violent, evil, sick man."],
  ["A","Yes! [Jimmy] took it when I wasn’t looking and stole my money. I told him off but he wouldn’t listen."],
  ["A","[Jimmy] soaked my toy with that stuff in the bottle. I hated him!"],
  ["A","[Jimmy] got the sword down from the wall, it looked really sharp. He made me promise not to tell anyone and he said he could make my hand stop hurting."],
  ["A","[Jimmy] told me to keep drinking [the medicine]. It was horrible. Then I started to feel strange."],
  ["P","[The violent drawings] suggested a turbulent personality, but I wasn't particularly concerned until I started to realise how far [Jimmy's] imagination went."],
  ["P","Jimmy said he'd make something for me, so I followed him to see what he was going to do."],
  ["P","[Jimmy putting glass in a sandwich] was my first encounter with Jimmy’s sense of humour."],
  ["P","[Diazepam] wasn’t the ideal medication, but it was all I had. Jimmy needed treating immediately. He was dangerous."],
  ["P","Jimmy said I’d used the paddle to beat him. I would never use violence against a patient, it was ridiculous! But Rose believed him."],
  ["P","Jimmy accused me of the worst crime possible. He took it from a newspaper story he'd read. He was making it all up."],
  ["P","I experimented with the washing line, but it was too thin. I found some rope instead. I still had my keys to the hotel so I crept in one night while I was on bail."],
  ["H","As soon as I found that scrapbook I knew where Jimmy had got [the story] from. It was the same, down to every detail."],
  ["H","Jimmy was always playing with electricity. Funny how he was never the one who got shocked."],
  ["H","I kept those bats for self-defence, but I was angry. I took one and went to Jimmy’s room."],
  ["H","Jimmy was fond of weapons like [the crossbow]. I hadn’t seen Jimmy all night after I'd smashed his stuff. I should have guessed he’d been working on his next little trick."],
  ["H","Well if Jimmy wanted to hide [in the basement] I thought he must like it."],
  ["H","Nobody realised how far Jimmy would go to get attention."],
  ["H","I'd lost it. I was seeing red, I hated him. I'd lost control."],
  ["H","[The letter opener] wasn't even a dagger! But I never learned my lesson, Jimmy was always one step ahead of me."],
  ["R","Jimmy started doing a comedy act on stage: Hugo Punch. He was good. People started to come just to watch him."],
  ["R","Breaking the mirrors was just the start. He didn’t remember doing it. Then other strange things started happening."],
  ["R","Jimmy locked [the woman who made a complaint] in a room and tied her up. I found her and let her go. She didn’t press charges, but she told the newspapers."],
  ["R","Jimmy had been fighting Hugo Punch all his life. Jimmy didn’t want to live anymore."],
  ["R","[Hugo and I] were married. We were happy at first, before things started to change."],
  ["R","I thought having a child would solve everything. I was wrong."],
  ["R","I admitted it all to Jimmy. Hugo beat Jimmy from when he was born, for 2 years. I should have stopped it earlier."],
  ["R","Jimmy had gone to find Hugo's grave. I was alone. I knew what I should do."],
],

finwords:[

  "In each of us is another<br>whom we do not know.",7,
  "",0.5,
  "He speaks to us in dreams,",6,
  "and tells us how differently he sees us<br>from the way we see ourselves.<br><span class='h8'>Carl Jung</span>",8,
  "V",5,
  "You can see them,",4,
  "",0.5,
  "At Dead Of Night",5,
  "",16,
  "<span class='hf'>Maya</span><br>Chloe Booyens",5,
  "<span class='hf'>Jimmy Hall</span><br>Huld Martha",5,
  "<span class='hf'>Rose Hall</span><br>Joanna Bond",5,
  "<span class='hf'>Harvey</span><br>Karl Haynes",5,
  "<span class='hf'>Dr Bose</span><br>Rohit Gokani",5,
  "<span class='hf'>Amy Bell</span><br>Daisy Follin",5,
  "<span class='hf'>With supporting actors</span><br>Rachel Alfieri<br>Paige Ryan<br>Sally Alfieri<br>Daniel Alfieri<br>Luke Chase",8,
  "<span class='hf'>With supporting actors</span><br>Sam Follin<br>Jamie Follin<br>Tom Follin<br>Clare Follin",7,
  "<span class='hf'>Special thanks to</span><br>Mark Wilson<br>Fay Wilkins",7,
  "",1,
  "Thank you for playing<br>At Dead Of Night",8,
  "",

],

words:[

  "TURN ON DEVICE",
  "TURN OFF DEVICE",
  "SHOUT",
  "USE SCRYING MIRROR",
  "ASK QUESTION",
  "CLOSE",
  "Ask<br>who's<br>there",
  "Ask<br>their<br>name",
  "Is It<br>",
  "RUN AHEAD",
  "PRESS<br>LOWER<br>GROUND",
  "PRESS<br>GROUND<br>FLOOR",
  "PRESS<br>FLOOR<br>ONE",
  "PRESS<br>FLOOR<br>TWO",
  "PRESS<br>FLOOR<br>THREE",
  "RETURN",
  "OPEN<br>MENU",
  "Call Out To Jimmy",
  "TRY<br>DOOR<br>",
  "TRY<br>ROOM<br>",
  "RETURN<br>TO ROOM",
  "SEND<br>FRIEND<br>OUT",
  "YOU HAVE<br>PAIRED THESE",
  "TRY<br>STORE<br>FIVE",
  "CALL<br>THE LIFT",
  "ASK ABOUT THIS",
  "HIDE<br>IN THE<br>WARDROBE",
  "HIDE<br>IN THE<br>BATHROOM",
  "LOOK<br>THRU THE<br>SPY GLASS",
  "MOVE<br>INTO THE<br>ROOM",
  "SEARCH<br>HERE",
  "LEAVE<br>THE<br>ROOM",
  "TRY<br>THIS<br>DOOR",
  "CLOSE",
  "OPEN<br>NOTES",
  "ADD TO<br>PAIR",
  "RETURN<br>TO THE<br>DOOR",
  "PAIR SIGHTINGS<br><span style='font-family:arial'>&</span> OBJECTS",
  "ASK IF THESE ARE LINKED",
  "ASK",
  "NEXT PAGE",
  "PREVIOUS PAGE",
  "TRY THE STAIRWELL DOOR",
  "TOO DARK<br>AHEAD",
  "ENTER<br>ROOM",
  "EXIT<br>TUTORIAL",
  "Look in the first floor store near the stairs for the device",
  "You need to<br>find a scrying<br>mirror",
  "You need<br>to find a<br>compass",
  "You need to<br>find a compass<br>and scrying mirror",
  "Game<br>Saved",
  "LOOK THRU<br>THE WINDOW",
  "Wait Until You're Safe First",
  "EXIT",
  "That's the wrong key",
  "Door unlocked",
  "Face a locked door<br>to try a key",
  "Door locked",
  "Try the door first",
  "Use the room key<br>to lock the door",
  "Unlock the door first",
  "GO UP",
  "GO DOWN",
  "It's too dark in here to use the device",
  "Wait a while before trying to make contact again.",
  "Jimmy is about to enter the room!",
  "Jimmy can be heard somewhere",
  "Jimmy chuckles quietly",
  "Start game first",
  "You can't save at the moment",
  "Current Game Saved",
  "It's Too Soon To Use The Mirror Again",
  "Don't try!<br>Jimmy is in this room!",
  "LOOK<br>THRU<br>KEYHOLE",
  "It's best to leave store rooms unlocked",
  "COLLECT<br>DEVICE",
  "It's too dark in here to use the mirror",
  "Store",
  "Unknown",
  "It's too bright in here to use the mirror",
  "RETURN<br>TO MENU",
  "Save<br>Game?",
  "SAVE",
  "Jimmy can be heard walking nearby",
  "Jimmy can be heard moving quickly",
  "The room door is closed",
  "SKIP<br>WAKE",
  "Look in store rooms for the device",
  "SKIP",
  "CLOSE MESSAGE",

],

ghostex:[

  "A",
  "In Contact With<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;AMY&#160;&#160;</span>&#10023;<br><br>10 Year-Old Girl",
  "P",
  "In Contact With<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;Dr BOSE&#160;&#160;</span>&#10023;<br><br>Clinical Psychiatrist",
  "H",
  "In Contact With<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;HARVEY&#160;&#160;</span>&#10023;<br><br>Hotel Proprietor",
  "R",
  "In Contact With<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;ROSE&#160;&#160;</span>&#10023;<br><br>Hotel Proprietor",

],

headtex:[

  "<span class='h3'>Find The Spirit Receiver.</span>",
  "<span class='h3'>Turn On The Spirit Receiver<br>To Communicate With Spirits.</span>",
  "<span class='h3'>Turn Up The Spirit Receiver Volume To Hear Spirit Replies.</span>",
  "<span class='h3'>Try to Make Contact With A Spirit</span><br><span class='h2'>(Use Speak Icon Above)</span>",
  "<span class='h3'>A Spirit Is Making Contact.<br>Try To Confirm Their Identity.</span>",
  "<span class='h3'>Now In Contact With ",
  "<span class='h3'>Spirit Is Too Distant. Try To Move Closer.</span>",
  "<span class='h2'>When You Meet Spirits You Can Ask Them Questions. Pair Their Replies To Make Connections. When You're Alone You Can Review Spirits' Replies Here.</span>",

],

gametex:[

  "The Standard Game<br><br><span class='h2'>Find spirits, ask them questions and make connections to make them appear, while Jimmy tries to stop you finding out his secrets.</span>",
  "Search & Rescue<br><br><span class='h2'>Rescue your friends, while Jimmy tries to stop you. If he hits you once it's game over.</span>",
  "Search & Rescue<br><br><span class='h2'>Return to the end of your last game.</span>",
  "<span class='h9'>Select Your Game</span><br><br><span class='h2'>Choose Standard Game or Extreme Game. When playing the Extreme Game, if Jimmy attacks you he will take almost everything, every time.<br><br>Your current game will be lost when you begin a new one and your achievements will be reset.</span>",
  "<span class='h9'>Are you sure?</span><br><br><span class='h2'>This will end your current game and return you to your last saved game.</span>",
  "<span class='h9'>One Whack And You're Dead!</span><br><br><span class='h2'>This game doesn't save so you only get one chance to rescue everyone!</span>",

],

getex:[

  "<br>You Found<br><br>A Scrying Mirror<br><br><span style='font-size:50%'>Reveals Hints & Clues<br>When Used In<br>Dark Places</span>",
  "<br>You Found<br><br>A Compass<br><br><span style='font-size:50%'>Points Towards<br>Nearby Spirits</span>",
  "<span style='font-size:40%>'>You Found A<br>Key Labelled<br>",
  "You Found The<br>Deadlock Key<br>To Room",
  "You Found The<br>Deadlock Key<br>To Room",

],

roomtex:"Room",

foundtex:"You Found",

alreadytex:[

  "You Already Have A Scrying Mirror",
  "You Already Have A Compass"

],

adtext:[

  "Sound of a<br>girl crying",
  "Sounds from an amusement arcade",
  "Sound of a girl<br>crying quietly",
  "A girl singing<br>softly to herself",
  "Someone knocking<br>quietly on a door",
  "Sound of crockery being moved around",
  "Sound of a<br>running tap",
  "Sound of a<br>telephone dialling",
  "Loud knocking<br>on a door",
  "Sound of someone<br>banging on a door",
  "Sound of electrical<br>sparking and fizzing",
  "Sound of things<br>being smashed",
  "Intermittent hitting<br>or snapping sound",
  "Someone banging<br>on a metal door",
  "A loud alarm sound",
  "Harvey's voice shouting for Jimmy",
  "The soft murmur<br>of a crowd",
  "Music playing<br>from a radio",
  "A crowd booing and shouting loudly",
  "A door bell being rung sporadically",
  "Sound of water running into a bath",
  "A sporadic<br>whipping sound",
  "Music being played",

],

itdetext:[

  "Suitcases",
  "Trophies",
  "Child's Purse",
  "Turpentine & Lighter",
  "Sword",
  "Whiskey Bottles",
  "Violent Drawings",
  "Chef's Hat",
  "Blood Stained Cloth",
  "Diazepam Medicine",
  "Wooden Paddle",
  "Scrapbook",
  "Washing Line",
  "Dangerous Heater",
  "Sports Bats",
  "Crossbow",
  "Rusty Keys",
  "Photos Of A Fire",
  "Hand Gun",
  "Ornate Dagger",
  "Hugo Punch Poster",
  "Broken Mirrors",
  "Coil Of Wire",
  "'Goodbye' Note",
  "Wedding Ring",
  "Baby's Rattle",
  "Birth Certificate",
  "Girl In The Basement",
  "Jimmy Stealing From Amy",
  "Amy Holding A Toy On Fire",
  "Amy Scared Outside A Room",
  "Amy Drinking Something Horrible",
  "Amy At The Top Of The Stairs",
  "Amy At The Bottom Of The Stairs",
  "Man In Suit Knocking On Door",
  "Dr Bose Finding A Dead Animal",
  "Dr Bose Outside The Kitchen",
  "Dr Bose Spitting Out Blood",
  "Dr Bose With An Injection Needle",
  "Dr Bose Explaining What Happened",
  "Dr Bose Sat On A Bed In A Room",
  "Dr Bose In The Games Room",
  "Dr Bose Killing Himself",
  "The Man Saying Jimmy Lied",
  "Harvey Shouting Through A Door",
  "Harvey Receiving An Electric Shock",
  "Harvey With A Bat",
  "Harvey Being Shot In The Leg",
  "Harvey Locking Jimmy In Basement",
  "A Fire In The Basement",
  "Harvey With A Gun",
  "Harvey Heading Towards Ballroom",
  "Harvey Being Stabbed",
  "Lady Explaining The Dagger",
  "Rose At The Entrance Doors",
  "Rose Backstage Announcing Hugo Punch",
  "Rose Finding Lots Of Mannequins",
  "Rose Apologising To A Guest",
  "Rose Hiding And People Banging On A Door",
  "Rose Finding Jimmy In The Bathroom",
  "Rose Attacking Someone With A Bat",
  "Rose On Fire",
  "The Great Hugo On Stage",
  "Man Shouting & Child Crying",
  "Shouting & Falling Elevator",
  "Jimmy Wouldn't Listen",
  "Jimmy Soaked Amy's Toy",
  "Jimmy Could Stop Amy's Hand Hurting",
  "Amy Drank Something Horrible",
  "Dr Bose Saw Jimmy's Drawings",
  "Jimmy Came Up With An Idea",
  "Dr Bose Encountered Jimmy's Humour",
  "Dr Bose Decided To Medicate Jimmy",
  "Jimmy Accused Dr Bose Of Violence",
  "Jimmy Accused Dr Bose Of Abuse",
  "Dr Bose Knew What He Must Do",
  "Harvey Found Jimmy's Scrapbook",
  "Jimmy Played With Electricity",
  "Harvey Took A Bat To Jimmy's Room",
  "Harvey Suspected Another Trap",
  "Harvey Used The Boiler Room Key",
  "Harvey Realised Jimmy Was Crazy",
  "Harvey Lost Control",
  "Jimmy Was One Step Ahead",
  "Jimmy Started His Comedy Act",
  "Strange Things Started Happening",
  "The Newspapers Found Out",
  "Jimmy Had Had Enough",
  "Things Changed With Hugo",
  "A baby doesn't solve anything",
  "The Truth Was Revealed",
  "Rose Was Overcome With Guilt",
  "Key to&#160;'Store Room'",
  "",
  "",
  "Scrying Mirror",
  "Compass",
  "Key to 'Stairs Floor One'",
  "",
  "",
  "Scrying Mirror",
  "Compass",
  "Key to&#160;'Store Room'",
  "",
  "",
  "Scrying Mirror",
  "Compass",
  "Key to 'Stairs Floor Two'",
  "",
  "",
  "Scrying Mirror",
  "Compass",
  "Key to&#160;'Store Room'",
  "",
  "",
  "Scrying Mirror",
  "Compass",
  "Key to 'Stairs Floor Three'",
  "",
  "",
  "Scrying Mirror",
  "Compass",
  "Key to&#160;'Store Room'",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Hotel Exit Key",
  "Basement Store Room Key",

],

keyfinds:[

    "STORE ROOM",
    "STAIRS<br>FLOOR ONE",
    "STAIRS<br>FLOOR TWO",
    "STAIRS<br>FLOOR THREE",

  ],

gnames:[
  "Amy",
  "Dr Bose",
  "Harvey",
  "Rose",
  "Hugo"
],

extras:[
  "WELCOME TO<br>SEA VIEW HOTEL<br><span style='font-size:50%'>BOOK IN HERE</span>",
  "Maya:",
  "Game Saved",
  "Game Controller Connected",
  "Game Controller Disconnected",
],

};
