var FIN={

mentex:[

"Edison<br><span class='bt1'>Yliluonnollisten äänien vastaanotin<br></span>Käyttöohjeet<br><br><br>Yliluonnollinen vuorovaikutus (huomioi seuraavat seikat)<br><br>Ottaessasi yhteyttä henkiin niiden sähköinen potentiaali (eli energiatila) määrittyy suoraan senhetkisen tunnetason perusteella. Henget ilmestyvät sekä korkeassa että matalassa energiatilassa, mutta puheviestintä on mahdollista vain matalassa energiatilassa.<br><br>Energiatila saattaa vaihtua, mikäli kysymyksiä esitetään liian provokatiivisella tai aggressiivisella tavalla. Hengen siirryttyä korkeaan energiatilaan laite vastaanottaa vain voimakasta kohinaa, eikä viestinnän jatkaminen ole mahdollista.<br><br>Korkeassa energiatilassa olevat henget kykenevät näyttäytymään itsenäisesti, lähellä sellaista kohdetta, jossa tapahtuu sähkömagneettisia häiriöitä. Yliluonnolliset olennot ovat kuolleiden sieluja, osoitathan heille siis asianmukaista kunnioitusta.",

"energia on kasvanut<br>keskustelun myötä<br><br>MATALA TILA<br><br><br><br><br>HENGEN ÄÄNEN<br>VOI KUULLA",

"<br><br><br>KORKEA TILA<br><br><br><br><br>HENKI SAATTAA<br>NÄYTTÄYTYÄ<br><br>energia on heikentynyt<br>näyttäytymisen myötä",

"<div class='ht'><span style='font-size:170%'>Ohjeita pelaamiseen</span><br><br>Pelaa At Dead Of Nightia sydänyöllä - tai ainakin pimeässä huoneessa. Varmista, että taustamelua on mahdollisimman vähän, käytä kuulokkeita yksin pelatessasi.<br><br>Suosittelemme säätämään kirkkauden sopivaksi ennen pelin aloittamista, sillä hotellissa on pimeitä alueita ja Jimmyn varjoa hädin tuskin näkee. Voit säätää varjojen näkyvyyttä painamalla 'U/I'.<br><br>Jimmyn äänen voi kuulla silloin kun hän on samassa kerroksessa. Kuuntele huolellisesti ja kuulet hänen askeleensa, mikä auttaa hahmottamaan hänen etäisyyttään. Myös henget pitävät ääntä. Jos haluat kuulla tärkeät äänet paremmin, paina 'D' hiljentääksesi taustaääniä hetkellisesti.<br><br>Mikäli tarvitset avustusta kuulemiseen, valitse 'Kuvailutekstitykset' kohdassa 'Tekstitykset'. Jos et tarvitse tätä avustustoimintoa, on suositeltavaa pitää se poissa käytöstä.<br><br>Kompassit osoittavat henkiä kohti jopa seinien läpi: jatka kävelyä käytäviä pitkin, mikäli henki ei ole kompassin osoittamassa suunnassa. Kompassin neula pyörii hitaasti ympäri kun lähellä ei ole henkiä, ja nopeasti hengen ollessa lähettyvillä.<br><br>Muista, että voit kurkistaa huoneisiin avaimenrei'istä, ja kulkea nopeammin liikuttamalla nuolta ruudun yläosaan.</div>",

"<div class='ht'><span style='font-size:170%'>Jimmy ja DID</span><br><br>Jimmyn tarina on teatraalinen ja symbolinen kuvaus kahden keskenään ristiriitaisen moraalikäsityksen omaavan henkilön sisäisestä kamppailusta. Sen ei ole tarkoitus olla kirjaimellinen kuvaus todellisesta psykologisesta käytöshäiriöstä nimeltä DID (dissosiatiivinen identiteettihäiriö).<br><br>Todellinen DID on ahdistusta ja kärsimystä aiheuttava sairaus, joka on usein (muttei aina) liitoksissa lapsuudessa koettuun väkivaltaan. DID:llä ei ole mitään tekemistä moraalittoman tai rikollisen käyttäytymisen kanssa. DID:stä kärsivät tarvitsevat myötätuntoa, mutta saavat usein osakseen epäluottamusta ja tuomitsemista tullessaan väärin ymmärretyiksi.<br><br>Meidän tarkoituksenamme ei ole vihjata, että Jimmyllä olisi tämä käytöshäiriö, ja tunnustamme, että stereotyyppisten kuvausten levittäminen on haitallista paitsi häiriöstä kärsiville, myös kehityksen ja ymmärryksen edistämiselle. Pahoittelemme, mikäli olemme aiheuttaneet harmia tai ahdistusta DID:stä kärsiville.<br><br>Lisätietoja saat osoitteesta:<br><br>https://survivorsnetwork.org.uk/resource/dissociative-identity-disorder-d-i-d/</div>",

"Suurkiitos loistaville näyttelijöillemme:<br><br><table><tr><td><span class='h5'>Jimmy</span><br><span class='ht'>Huld Martha</span><br><br><span class='h5'>Rose</span><br><span class='ht'>Joanna Bond</span><br><br><span class='h5'>Dr Bose</span><br><span class='ht'>Rohit Gokani</span><br><br></td><td><span class='h5'>Maya</span><br><span class='ht'>Chloe Booyens</span><br><br><span class='h5'>Harvey</span><br><span class='ht'>Karl Haynes</span><br><br><span class='h5'>Amy<span><br><span class='ht'>Daisy Follin</span><br><br></td></tr></table><span class='h5'>Sekä sivuroolien esittäjille:</span><table><tr><td><span class='ht'>Rachel Alfieri<br>Paige Ryan<br>Sam Follin</span></td><td><span class='ht'>Jamie Follin<br>Clare Follin<br>Tom Follin</span></td></tr></table><br><span class='h5'>Erityiskiitokset:</span><br><table><tr><td><span class='ht'>Mark Wilson</span></td><td><span class='ht'>Fay Wilkins</span></td><td><span class='ht'>Daniel Alfieri<span></td><td><span class='ht'>Sally Alfieri</span></td><td><span class='ht'>Luke Chase</span></td></tr></table><br><span class='h7'>Pelin on luonut Tim 'so what do you do now' Follin<br>©2020 Baggy Cat Ltd</span></span>",

"&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;Kuvailutekstitykset<br><br><span class='h2'>Näyttää tehostetun tekstityksen lisäksi äänenvoimakkuusindikaattorin sekä kuvaukset pelin aikana kuulluista äänistä.<br><br>Jos et tarvitse tätä avustustoimintoa, on suositeltavaa pitää se poissa käytöstä.</span>",

"&#160;&#160;&#160;&#160;&#160;&#160;&#160;&#160;Tekstitykset<br><br><span class='h2'>Näyttää perustekstitykset pelin sekä alkukohtauksen aikana.</span>",

"Ei vielä<br>tapahtumia.",

"ALOITA UUSI PELI",

"<span class='h9'>Jimmy Hallin tarina</span><br><br><span class='h2'>Selvitä Jimmyn salaisuudet kysymällä hengiltä löytämistäsi asioista ja muodosta juoniyhteyksiä saadaksesi henkiä ilmestymään. Jimmy yrittää estää sinua saamasta selville totuutta.</span>",

"<span class='h9'>Loppuhuipentuma</span><br><br><span class='h2'>Aloita peli siitä kohdasta, kun Jimmy pyysi sinua tapaamaan Hugon.</span>",

"<span class='h9'>Viimeinen pelastus (uusi peli)</span><br><br><span class='h2'>Pelasta kaikki ystäväsi samalla kun välttelet Jimmyä. Peli on ohi ensimmäisestä iskusta! Peliä ei voi tallentaa, palaudut nykyiseen tallennukseesi päästyäsi pakoon tai jäätyäsi kiinni.</span>",

"Katso kaikki opastusvideot",

"Katso kohdasta 'Jahtaus'",

"Katso kohdasta 'Strategia'",

"Katso kohdasta 'Kuolleiden sielut'",

"Katso kohdasta 'Mayan kyky'",

"Katso alkukohtaus",

"Katso kohdasta 'Maya saapuu'",

"Katso kohdasta 'Hugo ottaa ohjat'",

"Katso kohdasta '2:30'",

"Katso kohdasta 'Henkilähetin'",

"Pelitilastot",

"Aloita uusi peli",

"Katso näyt",

"Lähettimen käyttöohjeet",

"Katso opastusvideot ja alkukohtaus",

"Tekstitykset ja kuvailu",

"Tekijät",

"Ohjeita pelaamiseen",

"Jimmy ja DID",

"Lähde Merihelmestä<br><span class='h2'>Tallenna ja poistu</span>",

"Haluatko varmasti<br>poistua hotellista nyt?",

"PÄÄSTÄ MINUT ULOS!",

"<br>ET OLE<br>VIELÄ LÖYTÄNYT<br>MITÄÄN",

"Jimmy sai sinut kiinni viimeisen kerran.<br><br>Pakosi päättyi tähän.<br><br>Yritä silti uudelleen...",

"Astu Merihelmeen<br><span style='font-size:50%'>Palaa viimeksi tallennettuun peliin</span>",

"Astu Merihelmeen<br><span style='font-size:70%'>Aloita uusi peli</span>",

"ALOITA STANDARD-PELI",

"ALOITA EXTREME-PELI",

"Tallenna peli",

],

achtex:[

  "Olet suorittanut",
  "pelistä",
  "Jimmy ei saanut sinua kiinni",
  "Jimmy sai sinut kiinni kerran",
  "Jimmy sai sinut kiinni kahdesti",
  "Jimmy sai sinut kiinni",
  "kertaa",
  "Sait selville hotellin salaisuuden",
  "Tarina",
  "Suoritettu",
  "",
  "",
  "",
  "Pelastit kaikki ystäväsi",
  "Etsi hotellin uloskäynti",
  "Olet läpäissyt pelin!",
  "Tilastoja ei ole vielä saatavilla",
  "Pelitilastot",
  "Saavutukset",
  "Amyn tarina suoritettu",
  "Dr Bosen tarina suoritettu",
  "Harveyn tarina suoritettu",
  "Rosen tarina suoritettu",
  "Suoritit tarinaosuuden",
  "Suoritit tarinaosuuden jäämättä kiinni",
  "Suoritit At Dead Of Nightin",
  "Pelastit kaikki pikapelissä",
  "Suoritit At Dead Of Nightin jäämättä kiinni!",
  "Palaa Merihelmeen",
  "Ei vielä saavutuksia",
  "Peli tallentuu automaattisesti näkyjen jälkeen, henkien vastausten jälkeen (kun henkilähetin on sammutettu) sekä Jimmyn lyötyä sinut tajuttomaksi.",
  "Suoritit tarinaosuuden EXTREME-pelissä",
  "Suoritit tarinaosuuden EXTREME-pelissä jäämättä kiinni",
  "Suoritit At Dead Of Nightin EXTREME-pelissä",
  "Suoritit At Dead Of Nightin EXTREME-pelissä jäämättä kiinni!",
  "Kaikki ystäväsi pääsivät turvallisesti ulos.",

],

selx:[

  "Ei vastausta",
  "Et ole vielä kysynyt tästä kohteesta",
  "Luo yhteys henkeen kysyäksesi tästä kohteesta",
  "Valitse kohde nähdäksesi jokaisen hengen vastauksen",
  "Seiso oven edessä koettaaksesi avainta",
  "Valitse kohde kysyäksesi siitä",
  "ei osannut vastata",
  "sanoi:",
  "TURVALLISTA MATKAA<br>Tulethan pian takaisin",
  "Peli tallennettu",
  "Aloita peli ensin",

],

numwo:[

  "Sinulla on enää yksi ystävä pelastettavana",
  "Sinulla on kaksi ystävää pelastettavana",
  "Sinulla on kolme ystävää pelastettavana",
  "Sinulla on neljä ystävää pelastettavana",
  "Sinulla on viisi ystävää pelastettavana",

],

numwa:[

  "Viisi ystävää pelastui",
  "Neljä ystävää pelastui",
  "Kolme ystävää pelastui",
  "Kaksi ystävää pelastui",
  "Yksi ystävä pelastui",

],

helx:"<span class='ht'>&#8679;S</span> Tallenna peli | <span class='ht'>Esc</span> Avaa/Sulje valikko | <span class='ht'>D</span> Hiljennä taustaääniä | <span class='ht'>Q/W</span> Taustan kuuluvuus<br><span class='ht'>&#8679;X</span> Pikapoistuminen | <span class='ht'>U/I</span> Säädä kirkkautta | <span class='ht'>O/P</span> Säädä värikylläisyyttä | <span class='ht'>R</span> Palauta oletukset",

resk:[

  "Löysit<br><br>viisi avainta<br><br><span style='font-size:50%'>Sinulla on viisi ystävää pelastettavana</span>",
  "Odota, että he<br><br>pääsevät pakoon<br><br>",
  "<span style='font-size:50%'>Olet pelastanut kaikki ystäväsi</span>",
  "<span style='font-size:50%'>Sinulla on vielä yksi ystävä pelastettavana</span>",
  "<span style='font-size:50%'>Sinulla on vielä kaksi ystävää pelastettavana</span>",
  "<span style='font-size:50%'>Sinulla on vielä kolme ystävää pelastettavana</span>",
  "<span style='font-size:50%'>Sinulla on vielä neljä ystävää pelastettavana</span>",

],

ityptex:[

  "Näytä kaikki",
  "Näytä löydetyt esineet",
  "Näytä näyt",
  "Näytä juoniyhteydet",
  "Näytä avaimet"

],

intros:[

  "Tämä on henkilähetin. Paina kuvaketta käynnistääksesi laitteen.",
  "Lähetin havaitsee henkien äänet, kun olet riittävän lähellä niitä.",
  "Jollet ole vielä nähnyt laitetta, mene päävalikkoon ja katso opastusvideo.",
  "Lähetin havaitsee henkien äänet, kun olet riittävän lähellä niitä.",

  "Jollet ole vielä nähnyt laitetta, mene päävalikkoon ja katso opastusvideo.",
  "Tässä näkyvät löytämäsi esineet ja avaimet.",

  "Maya voi esittää hengille kysymyksiä luettelossa näkyvistä esineistä.",
  "Tässä näkyvät löytämäsi esineet ja avaimet.",

  "Maya voi esittää hengille kysymyksiä luettelossa näkyvistä esineistä.",
  "Voit käyttää ennepeiliä vain silloin, kun sen kuvake on näkyvillä,",

  "joko hotellihuoneissa ovien vierellä tai pohjakerroksen keittiössä.",
  "Käytä peiliä saadaksesi vihjeitä paikoista ja esineistä,",
  "kadonneista avaimista, kompasseista ja henkilähettimestä.",
  "Voit käyttää ennepeiliä vain silloin, kun sen kuvake on näkyvillä,",

  "joko hotellihuoneissa ovien vierellä tai pohjakerroksen keittiössä.",
  "Käytä peiliä saadaksesi vihjeitä paikoista ja esineistä,",
  "kadonneista avaimista, kompasseista ja henkilähettimestä.",
  "Jos samassa kerroksessa on henkiä, kompassi osoittaa niiden suuntaan.",

  "Kysy hengiltä asioista, joita olet nähnyt.",

  "Näet vastaukset valitsemalla kohteen.",
  "Yhdistä kaksi vastausta, joiden uskot liittyvän hengen tarinaan.",

  "Yhdistä näkyvastaukset esinevastauksiin edistyäksesi nopeammin.",
  "Jos henki lakkaa vastaamasta, on se todennäköisesti lähtenyt pois.",

  "Käytä kompassia, seuraa välkkyviä valoja ja kuuntele ääniä.",
  "Aloita keskustelu hengen kanssa kysymällä aloituskysymykset.",

  "Jollet saa vastausta, lähellä ei ole henkiä.",
  "Voimakas kohina tarkoittaa, että lähellä on korkeassa energiatilassa oleva henki.",
  "Aloita keskustelu hengen kanssa kysymällä aloituskysymykset.",

  "Jollet saa vastausta, lähellä ei ole henkiä.",
  "Voimakas kohina tarkoittaa, että lähellä on korkeassa energiatilassa oleva henki.",
  "Jimmy Hall on saapunut etsimään sinua tähän kerrokseen. Pysy kaukana hänestä!",

  "Avaa muistiinpanot, seiso oven edessä ja valitse avain koettaaksesi sitä oveen.",

  "Ovia voidaan avata ja lukita oikealla avaimella.",
  "Avaa muistiinpanot, seiso oven edessä ja valitse avain koettaaksesi sitä oveen.",

  "Ovia voidaan avata ja lukita oikealla avaimella.",
  "Peli tallentuu nyt viimeistä kertaa.",

  "Sinun pitää nyt pelastaa ystäväsi,<br>mutta jos Jimmy saa sinut kiinni, on peli ohi!",
  "Olet nyt pelastanut<br>viimeisen ystävän.<br>Etsi uloskäynti<br>ja poistu hotellista!",

  "Klikkaa ovea lähettääksesi ystäväsi ulos huoneesta.",

],

substan:[

  "En tiedä.",
  "Ehkä.",
  "Ei",
  "ÄÄNI<br>KUULUU<br>EPÄSELVÄSTI/",
  "KOHINAA<br>/"

],

subrepa:[
[
  "Kuuluuko?",
  "Kuuluu",
  "Kuuluu.",
  "Kuuluu",
  "Kuuluu.",
  "Kuuluu"
],[
  "Kuuluuko?",
  "Kuuluuko?",
  "Kuuluuko?",
  "Kuuluuko?"
],[
  "Kuuletko minua?",
  "Kuulen sinut",
  "Kuulen sinut.",
  "Kuulen sinut."
],[
  "Kuuletko minua?",
  "Kuulen sinut.",
  "Kuuletko minua?",
  "Kuulen sinut.",
  "Kuulen sinut."
],
],

subrepb:[
[
  "Olen Amy Bell. Olen 10-vuotias.",
  "Olen Amy.",
  "Olen Amy.",
  "Se olen minä.",
  "Olen Amy.",
  "Kyllä. Olen Amy.",
  "Kyllä, olen Amy.",
  "Se olen minä."
],[
  "Doctor Bose. Työskentelen psykiatrina.",
  "Kyllä, olen Doctor Bose.",
  "Doctor Bose täällä.",
  "Kyllä. Olen Doctor Bose.",
  "Kyllä.",
  "Se olen minä.",
  "Olen Doctor Bose."
],[
  "Harvey. Omistan tämän hotellin.",
  "Kyllä.",
  "Joo, olen Harvey.",
  "Joo. Olen Harvey.",
  "Joo. Harvey täällä.",
  "Joo, Harvey täällä."
],[
  "Rose, Rose Hall. Tämä on hotellini.",
  "Kyllä.",
  "Kyllä. Olen Rose.",
  "Kyllä.",
  "Kyllä, olen Rose.",
  "Kyllä.",
  "Kyllä. Olen Rose."
],
],

subcall:[

  "JIMMY?",
  "HEI!",
  "OLEN TÄÄLLÄ!",
  "TULE TÄNNE!",
  "TÄNNEPÄIN!",

],

subin:[

  "Onko täällä ketään?",
  "Onko täällä ketään?",
  "Onko täällä ketään?",
  "Onko siellä joku?",
  "Onko siellä joku?",
  "Onko siellä joku?",
  "Kuka siellä?",
  "Haloo?",
  "Haloo?",
  "Onko siellä joku?",
  "Onko siellä joku?",

],

subnm:[

  "Oletko sinä Amy?",
  "Oletko sinä Dr&#160;Bose?",
  "Oletko sinä Harvey?",
  "Oletko sinä Rose?",
  "Mikä on nimesi?",

],

subrepc:[

  ["H","Roselle, mutta hän ei koskaan käyttänyt niitä.","R","Ne olivat minun. Halusin lähteä pois, mutten koskaan saanut tilaisuutta."],
  ["R","Jimmy osti ne luodakseen vaikutelman, että hänet olisi palkittu."],
  ["A","Se kuului minulle. Se oli syntymäpäivälahjani, mutta se varastettiin.","H","Se oli sen tyttörukan kukkaro.","R","Se kuului sille pikkutytölle."],
  ["A","En tiennyt, mitä ne olivat ennen kuin Jimmy näytti ne minulle.","P","Sinun olisi parasta kysyä Jimmyltä.","H","Ne kuuluivat minulle, mutten säilyttänyt niitä yhdessä.","R","En tiedä. Ne kuuluivat Harveylle."],
  ["A","Se oli Jimmyn kädessä. En pitänyt siitä.","P","Näin Jimmyn leikkivän sillä. Mielestäni se oli vaarallista.","H","Jimmy varasti sen keskiaikaisten aseiden näyttelystä.","R","Se kuului yhteen haarniskan kanssa, mutta se katosi."],
  ["A","En tiedä, mutta lasten ei kuuluisi juoda alkoholia.","P","Ne olivat todennäköisesti baarista.","H","En muista, mutta muutama lasillinen ei ole koskaan pahitteeksi.","R","Harvey varmaan laittoi ne sinne."],
  ["A","Se poika piirsi niitä.","P","Jimmy. Hän piirsi ne.","H","Kukakohan? Jimmy! Hänellä oli raju mielikuvitus.","R","Jimmy piirsi sota-aiheisia kuvia. Hän oli samanlainen kuin muutkin pojat."],
  ["P","Jimmy löysi sen ja laittoi päähänsä.","H","Kokille! Kuka muu käyttäisi kokin hattua?","R","Kokkimme käytti sitä."],
  ["A","Se saattoi olla minun.","P","Se oli minun. Säilytin sitä siltä varalta, että tarvitsisin todistusaineistoa.","H","En tiedä, mutta se saattaa liittyä lääkäriin."],
  ["P","Se kuului minulle. Se auttaa hillitsemään joidenkin ihmisten käytöshäiriöitä.","H","Lääkäri varmaan jätti sen tänne.","R","Se kuului lääkärille."],
  ["P","En tiedä, mutta Jimmy löysi sen.","H","Sitä säilytettiin vastaanottotiskin hyllyllä. En tiedä, mistä se on peräisin.","R","Se kuului miehelleni."],
  ["A","Jimmy teki sen. En tiedä miksi. Hän oli outo.","P","Jimmy teki sen. Minun olisi pitänyt tajuta sen olleen varoitus.","H","Jimmy - hän leikkeli uutisia ilkeistä opettajista ja lääkäreistä. Hän ei ollut tavallinen poika.","R","Harveyn mukaan Jimmy teki sen. En muista sitä."],
  ["P","Sidoin ne yhteen, se oli kokeilu."],
  ["H","Se antoi sähköiskuja. Säilytin sitä poliiseja varten.","R","Harvey siirsi sen syrjään. Se oli kuulemma vaarallinen."],
  ["A","En tiedä. Jimmy leikki niillä.","P","Harvey säilytti niitä, en tiedä miksi.","H","Säilytin niitä varmuuden vuoksi.","R","Ne kuuluivat miehelleni, kun hän työskenteli opettajana."],
  ["A","Näin sen vitriinissä.","P","Hotellissa oli vanhojen aseiden näyttely.","H","Se oli osa asenäyttelyämme. Jimmy kiintyi siihen.","R","Se oli esillä Harveyn näyttelyssä. En pitänyt siitä, että se oli hotellissa."],
  ["H","Ne olivat pannuhuoneen vanhaan oveen.","R","Ne olivat pannuhuoneen oveen, mutta ovi piti vaihtaa."],
  ["P","En ole kuullut siitä.","H","Kyllä. Palo saatiin hallintaan, mutta menetin paljon tavaraa.","R","Kyllä, mutta saimme sen hallintaan ennen kuin se alkoi levitä."],
  ["P","Harveylle. En pitänyt siitä, että se oli hotellissa.","H","Perin sen isältäni. Siinä oli muutama panos jäljellä.","R","Harveylle, mutta sitä säilytettiin minun huoneessani."],
  ["A","Jimmy näytti sen minulle, mutta se ei ollut hänen.","H","Se ei ole tikari, vaan kirjeveitsi. Sen ei kuuluisi olla terävä.","R","Se on kirjeveitsi. Joku antoi sen lahjaksi."],
  ["R","Se oli Jimmyn komediahahmo."],
  ["P","En ole nähnyt niitä.","H","En muista tapausta.","R","Jimmy rikkoi ne."],
  ["A","Jimmy kantoi sitä mukanaan.","P","Se oli Jimmyn. Hän piti sitä taskussaan, muttei kertonut mihin käytti sitä.","H","Jimmy kantoi sitä mukanaan, en tiedä miksi.","R","Jimmy kuljetti sitä mukanaan. Sähkö ja elektroniikka kiinnostivat häntä."],
  ["R","Jimmy kirjoitti sen."],

  ["H","Se kuului todennäköisesti Roselle.","R","Se oli minun. Minulle tehtiin tarjous, josta en voinut kieltäytyä."],
  ["A","En tiedä. En nähnyt vauvaa.","R","Se oli vauvaani varten. Säilytin sitä vetolaatikossa sänkyni vieressä."],
  ["R","Jimmy on Hugon poika, kaikin puolin."],
  ["A","Se olin minä - poika nimeltä Jimmy lukitsi minut kellariin. Hän alkoi varastaa omaisuuttani.","P","Se oli erään hotellivieraan tytär. Jimmy oli ilkeä häntä kohtaan.","H","Hän oleskeli hotellissa perheensä kanssa.","R","Hän oli vieraana hotellissa."],
  ["A","Jimmyn mielestä se oli hauskaa. Hän antoi sen takaisin, mutta se oli jo pilalla.","P","En tiedä, mutta se oli tyypillistä hänelle.","H","Se oli varmaan hauskaa hänen mielestään.","R","Ei hän ottanut sitä, tyttö valehtelee. Jimmy ei koskaan varastanut mitään."],
  ["A","Käteni paloi. Se teki todella kipeää, mutten voinut kertoa kenellekään.","P","Hänen kätensä paloi aika pahasti, mutta Jimmylle se oli vain leikkiä.","H","Hän sai pahoja palovammoja.","R","Tyttö sai palovammoja tehdessään vaarallisia asioita. Hän oli outo."],
  ["A","Aioin etsiä lääkärin, mutta Jimmy pakotti minut jäämään.","H","Hän varmaan pelkäsi Jimmyä.","R","Se saattoi olla mitä tahansa. Hän oli kummallinen tyttö."],
  ["A","Poika sanoi, että se oli lääkettä. Se maistui kamalalta.","P","En ollut silloin paikalla, mutta uskoisin hänen juoneen alkoholia."],
  ["A","Tunsin itseni niin kevyeksi, että saatoin hypätä pohjalle asti.","P","Jimmy pakotti tytön juomaan liikaa.","H","Hän oli juonut pullollisen viskiä, hän ei tiennyt mitä oli tekemässä.","R","En tiedä. Tiesin hänestä hyvin vähän."],
  ["A","Hyppäsin, mutta kaikki pimeni silmissäni, enkä enää herännyt. En pysty enää heräämään, en tiedä missä olen.","P","Hän oli juovuksissa ja putosi portaikon yläpäästä. Sen takia Rose otti minuun yhteyttä.","H","Hän putosi portaikon yläpäästä. Tiesin, että Jimmyn oli oltava sen takana.","R","Hän putosi. Harvey syytti Jimmyä, mutta vika oli tytössä itsessään, ei Jimmyssä."],
  ["P","Se olin minä - sain soiton Roselta, Jimmyn äidiltä. Hän halusi minun selvittävän, mikä Jimmyä vaivasi. Harveyta huoletti eniten Jimmyn mielenlaatu.","H","Se oli Doctor Bose. Hänen oli määrä auttaa Jimmyä, mutta mitään ei ollut tehtävissä.","R","Doctor Bose. Hän tuli auttamaan Jimmyä."],
  ["P","Jimmy tappoi pieniä lintuja ja eläimiä. Huomasin, että hänen oli harjoiteltava empatiakykyään. Niinpä pyysin häntä tekemään minulle jonkin mukavan asian. Olin yllättynyt, kun hän sai heti idean.","H","Jimmy sanoi löytäneensä sen. En tiedä, mitä hän teki sillä.","R","Harvey sanoi Jimmyn tappaneen sen, mutten uskonut häntä."],
  ["P","Jimmy valmisti minulle voileivän. Hän toi sen huoneeseeni, kuten olin pyytänyt. Aluksi en osannut epäillä mitään.","H","Lääkäri yritti kouluttaa Jimmyä. Se osoittautui suureksi virheeksi.","R","Doctor Bose yritti saada Jimmyn tekemään asioita, joista hän ei pitänyt."],
  ["P","Jimmy oli piilottanut lasinsirpaleita voileipääni. Minä melkein tukehduin. Säilytin liinan ja sirpaleet todisteina. Olin aliarvioinut Jimmyn sairauden. Minun täytyi tehostaa hoitoa välittömästi.","H","Hän oppi Jimmyn kujeista kantapään kautta.","R","Hän viilsi itseään, mutta syytti Jimmyä. Ei Jimmy sitä tehnyt."],
  ["P","Jimmy kieltäytyi lääkkeestä. Jouduin juoksemaan hänen perässään. Hän sanoi Roselle, että olin käyttänyt väkivaltaa. Naurettava ajatus!","H","En tiedä, en ollut paikalla.","R","Hän yritti lääkitä Jimmyä ilman lupaani."],
  ["P","Pelkäsin Rosen uskovan Jimmyn valheita. Mutta sain hänet vakuuttuneeksi siitä, että poika oli valehdellut.","H","Häntä huoletti syystäkin se, mitä Jimmy keksisi sanoa seuraavaksi.","R","Hän pelkäsi menettävänsä maineensa. En tiennyt, kehen uskoa, mutta annoin hänelle toisen mahdollisuuden."],
  ["P","Ajattelin, että jäätyään kiinni valehtelusta Jimmy alkaisi tottelemaan minua. Sen sijaan hän sepitti uuden valheen. Pahimman mahdollisen.","R","Hän yritti kontrolloida Jimmyä. Saada hänet tekemään pahoja asioita. Minun ei olisi pitänyt luottaa häneen."],
  ["P","Rose ilmiantoi minut ja olisin joutunut luopumaan virastani. Päätin ottaa ohjat viimein käsiini.","H","Hänet aiottiin pidättää. Jimmy oli tuhonnut hänet. Minä en uskonut valheisiin.","R","Häntä tultiin pidättämään. Hän oli ansainnut sen."],
  ["P","Olin saanut tarpeekseni. Paluuta entiseen ei ollut. Elämäni oli jo ohi.","H","Hänellä ei ollut vaihtoehtoja. Kaikki luulivat hänen.... koskeneen Jimmyyn. Se poika oli liian nokkela. Lääkäri parka.","R","Hän tiesi olevansa syyllinen. Hän toimi oikein."],
  ["P","Se oli Harvey. Hän tiesi Jimmyn valehdelleen. Harvey ymmärsi kaiken.","H","Se olin minä. Jimmy oli esittänyt tekaistuja syytöksiä lääkäriä kohtaan. Rose uskoi häntä, mutta minulle tarina oli jo tuttu.","R","Se oli Harvey. Hän ei uskonut Jimmyä. Tiesin, ettei Jimmy valehdellut."],
  ["P","Jimmy ei ikinä myöntänyt valheitaan.","H","Ei tietenkään! Hän vain nauroi. Sitten hän alkoi asettaa minulle ansoja.","R","Ei - miten Jimmy voisi myöntää jotakin, mikä ei ollut totta? Harveylla ei ollut mitään oikeutta kiusata Jimmyä."],
  ["H","Hän oli yhdistänyt lämmittimen kotelon suoraan verkkovirtaan. Minä melkein kuolin. Hän teki sen tahallaan, mutta Rose ei uskonut minua. Jimmy tarvitsi opetuksen. Hän vahingoitti omaisuuttani, joten minä tein vastapalveluksen.","R","Harvey syytti Jimmyä, mutta se lämmitin oli viallinen. Harveyn olisi pitänyt hävittää se."],
  ["P","En tiedä, mutta väkivalta pahentaa aina asioita.","H","Rikoin hänen televisionsa ja pelikonsolinsa. Olin vihainen; mutta se vain pahensi tilannetta. Jimmy kosti minulle pian.","R","Hän tuhosi Jimmyn omaisuutta. Hän ei kyennyt hillitsemään itseään."],
  ["H","Jimmy oli asettanut varsijousen laukeamaan oven avauduttua. Minun oli mentävä päivystykseen. Kun palasin, Rose sanoi Jimmyn piileskelevän kellarissa. Siitä sainkin idean.","R","Harvey sanoi Jimmyn ampuneen häntä varsijousella, mutta tiesin, ettei Jimmy käyttäisi sellaista asetta."],
  ["H","Jimmy sai maistaa omaa lääkettään. Luulin, ettei hän saisi tuhoa aikaiseksi kellarissa. Olin väärässä.","R","En tiedä, mitä hän teki."],
  ["P","En muista sitä.","H","Saimme palon hallintaan ennen sen leviämistä. Kaikki vanhat kuvat ja kirjeet paloivat poroiksi. Jimmyä ei pidätellyt mikään, olin saanut tarpeekseni hänestä. Halusin päästä hänestä eroon.","R","Harvey syytti Jimmyä, mutta tulipalo sai alkunsa löystyneestä liitoksesta. Se oli pelkkää sattumaa."],
  ["P","En tiedä. Harvey oli raivoissaan.","H","En tiennyt, mitä olin tekemässä. Ajattelin uhkailla Jimmyä, saada hänet pois hotellista.... En tajunnut, että hänkin olisi aseistautunut.","R","En tiedä. Harveyn ei olisi kuulunut pitää asetta hotellissa."],
  ["H","Etsin Jimmyä."],

  ["H","Jimmy hiipi taakseni, en nähnyt häntä. Jimmy voitti aina lopulta.","R","Harvey oli tullut hulluksi. Jimmy vain puolusti itseään."],
  ["H","Rose - Hän uskoi Jimmyä. Hän puolusti poikaansa viimeiseen asti.","R","Se olin minä. Selitin poliiseille, että tikari oli vain kirjeveitsi, ja että Harveylla oli ladattu ase. Jimmy puolusti itseään. He ymmärsivät sen."],
  ["H","Poliisit olivat päästäneet Jimmyn vapaaksi. Sanottiin, että olin uhannut ampua Jimmyn ja hän puolustautui. Ne olivat molemmat valheita.","R","Jimmyä - hän palasi kotiin. Poliisit olivat ymmärtäneet tilanteen. Jimmy oli muuttunut: hän alkoi auttaa minua ja löysi uuden keinon houkutella lisää asiakkaita hotelliin."],
  ["H","En tiedä, kuka hän oli.","R","Oli hienoa, kun hotellilla meni jälleen hyvin. Kaikki meni kohti parempaa, kunnes.... Jimmy alkoi käyttäytyä oudosti. Hän huusi ja tuijotti itseään. Hän vaikutti vihaiselta."],
  ["R","Jimmy - olin aluksi hämilläni, mutta sitten tajusin, mistä oli kyse. Jimmy ei tehnyt näitä asioita. Hän alkoi särkyä niiden peilien tavoin. Hän ei ollut enää oma itsensä."],
  ["H","En tiedä, mutta Jimmyllä oli tapana pilata kaikki aina lopulta.","R","Jimmy ei ollut enää lavalla, vaan Hugo Punch, hänen komediahahmonsa. Hugo loukkasi yleisöään joka ilta, ja nauttikin siitä. Eräänä iltana esityksen jälkeen eräs vieraista sanoi hänelle suorat sanat. Jimmy menetti malttinsa ja teki jotain tyhmää."],
  ["R","Toimittajia, he halusivat nähdä Jimmyn. He eivät ymmärtäneet, että Hugo Punch sitoi sen naisen. Jimmy oli masentunut. Hän halusi jättää kaiken taakseen ja lähteä."],
  ["R","Jimmy yritti tappaa itsensä. Siksi minun oli kerrottava hänelle totuus."],
  ["H","En tiedä. Rose ei kertonut minulle kaikkea.","R","Hugo - hautasin hänet salaiseen huoneeseen. Minun olisi pitänyt tehdä se jo aiemmin. On minun syytäni, että Jimmy kasvoi huonosti. Luulin, että totuuden kertominen korjaisi kaiken. Olin väärässä. En voinut hyväksyä tekoani, enkä elää itseni kanssa."],
  ["R","Ellen olisi tehnyt sitä itse, Jimmy olisi, tai pikemminkin Hugo. Hugo määrää tälläkin hetkellä. Hän kontrolloi Jimmyä. Pyydä Jimmyä näyttämään, missä Hugo asuu."],
  ["H","En tuntenut häntä.","R","Hän oli taikuri ja viihdyttäjä. Hän osti hotellin edistääkseen showtansa. Hänestä tuli kuuluisa, hän oli televisiossakin. Toimin hänen avustajanaan, kunnes tapahtui.... käänteitä."],
  ["R","En tiedä, mitä hän halusi. Pystyin antamaan hänelle vain yhden asian."],
  ["R","Hugo oli väkivaltainen, sairas ja viheliäinen mies."],
  ["A","Kyllä, hän nappasi sen, kun katsoin muualle, ja varasti rahani. Toruin häntä, mutta hän ei kuunnellut."],
  ["A","Hän kasteli leluni sillä kauhealla aineella, vihasin häntä!"],
  ["A","Kyllä - hän otti sen terävän miekan seinältä. Hän pakotti minut olemaan kertomatta kenellekään ja sanoi voivansa parantaa käteni."],
  ["A","Ehkä - hän kehotti minua jatkamaan juomista. Se oli kamalaa. Sitten minulle tuli outo olo...."],
  ["P","Kyllä - ne viittasivat rauhattomaan luonteeseen, mutten ollut huolissani ennen kuin.... huomasin kuinka laaja mielikuvitus hänellä oli."],
  ["P","Kyllä - Jimmy sanoi valmistavansa minulle jotakin, joten seurasin häntä mielenkiinnosta."],
  ["P","Sain ensimmäistä kertaa maistiaisen Jimmyn huumorintajusta."],
  ["P","Se ei ollut paras lääkitys, mutta minulla ei ollut muutakaan. Jimmy tarvitsi hoitoa välittömästi; hän oli vaarallinen."],
  ["P","Jimmy väitti, että olin hakannut häntä melalla. En ikinä käyttäisi voimakeinoja potilaaseen. Mutta Rose uskoi häntä."],
  ["P","Jimmy syytti minua pahimmasta mahdollisesta rikoksesta. Hän oli keksinyt väitteensä suoraan lukemastaan sanomalehtiartikkelista."],
  ["P","Kokeilin pyykkinarua, mutta se oli liian ohutta. Löysin köyttä. Minulla oli vielä hotellin avaimet ja onnistuin hiipimään sisään."],
  ["H","Se oli kopioitu suoraan siitä! Löydettyäni leikekirjan asia valkeni minulle heti. Tarina oli sama jokaista yksityiskohtaa myöten."],
  ["H","Jimmy leikki aina sähkölaitteilla. Hassua, ettei hän itse saanut sähköiskuja."],
  ["H","Säilytin mailoja itsepuolustusta varten, mutta olin vihainen. Otin yhden niistä ja menin Jimmyn huoneeseen."],
  ["H","Jimmy piti kovasti sellaisista aseista. En nähnyt häntä lainkaan sinä yönä. Minun olisi pitänyt arvata, että hän suunnitteli jo seuraavaa siirtoaan."],
  ["H","Jimmy piileskeli mielellään kellarissa, joten hän varmasti pitäisi siitä."],
  ["H","Kukaan ei osannut aavistaa, miten pitkälle Jimmy menisi saadakseen huomiota."],
  ["H","Olin mennyt järjiltäni. Näin pelkkää punaista. Vihasin häntä."],
  ["H","Se ei edes ollut tikari! En koskaan oppinut läksyjäni, Jimmy oli aina askeleen edellä minua."],
  ["R","Kyllä - se oli Jimmyn roolihahmo. Hän oli loistava koomikko. Hänen showtaan saapui katsomaan paljon väkeä."],
  ["R","Peilien rikkominen oli vasta alkua. Kysyin häneltä asiasta, mutta hän ei muistanut tehneensä sitä. Sitten alkoi tapahtua lisää outoja asioita."],
  ["R","Jimmy lukitsi naisen huoneeseen ja sitoi hänet. Löysin naisen ja päästin hänet vapaaksi. Jimmy sanoi sen olleen vitsi! Nainen ei nostanut syytteitä, mutta kertoi asiasta lehdistölle."],
  ["R","Jimmy vihasi itseään. Hän oli taistellut Hugo Punchia vastaan koko elämänsä. Hugo pakotti hänet tekemään pahoja asioita. Jimmy ei halunnut enää elää."],
  ["R","Kyllä - olimme naimisissa. Aluksi olimme onnellisia, sitten asiat alkoivat muuttua."],
  ["R","Luulin yhteisen lapsen pelastavan suhteemme. Olin väärässä."],
  ["R","Tunnustin kaiken Jimmylle. Jimmyllä ei ollut muistikuvaa Hugosta. Hugo pieksi Jimmyä kahden vuoden ajan heti tämän syntymästä alkaen. Minun olisi pitänyt puuttua siihen aiemmin."],
  ["R","Minulla ei ollut vaihtoehtoja. Jimmy oli mennyt etsimään Hugon hautaa. Olin yksin. Tiesin, mitä tehdä."],

],

subob:[

  ["Löysin matkalaukkuja puisesta arkusta. Kenelle ne kuuluivat?",
  "liittyykö se jotenkin matkalaukkuihin?"],

  ["Löysin palkintoja. Kuka voitti ne?",
  "liittyykö se jotenkin palkintoihin?"],

  ["Kenelle kukkaro kuului?",
  "liittyykö se siihen, mitä sanoit kukkarosta?"],

  ["Löysin sytyttimen ja tärpättipullon. Mihin niitä käytettiin?",
  "liittyykö se siihen, mitä sanoit sytyttimestä ja tärpättipullosta?"],

  ["Kenelle miekka kuului?",
  "onko sillä jotain tekemistä miekan kanssa?"],

  ["Miksi eräässä huoneessa oli kokoelma viskipulloja?",
  "onko sillä jotain tekemistä viskipullojen kanssa?"],

  ["Kuka piirsi ne rajut piirrokset?",
  "onko sillä jotain tekemistä niiden rajujen piirrosten kanssa?"],

  ["Kenelle kokin hattu kuului?",
  "liittyykö se jotenkin kokin hattuun?"],

  ["Miksi eräässä vetolaatikossa oli verinen liina?",
  "onko sillä jotain tekemistä verisen liinan kanssa?"],

  ["Kenelle diatsepaamipullo kuului?",
  "liittyykö se siihen, mitä sanoit diatsepaamipullosta?"],

  ["Mistä puinen mela on peräisin?",
  "liittyykö se siihen, mitä sanoit melasta?"],

  ["Löysin leikekirjan, jossa oli artikkeleita sanomalehdistä. Kuka teki sen?",
  "liittyykö se siihen, mitä sanoit leikekirjasta?"],

  ["Miksi kaulimen ympärille oli kiedottu pyykkinaru?",
  "onko sillä jotain tekemistä kaulimen ja pyykkinarun kanssa?"],

  ["Miksi vanha lämmitin on merkitty vaaralliseksi?",
  "liittyykö se jotenkin vaaralliseen lämmittimeen?"],

  ["Mihin tarkoitukseen mailoja käytettiin?",
  "onko sillä jotain tekemistä mailojen kanssa?"],

  ["Mistä varsijousi on peräisin?",
  "onko sillä jotain tekemistä varsijousen kanssa?"],

  ["Mihin tarkoitukseen ne ruosteiset avaimet ovat?",
  "liittyykö se jotenkin ruosteisiin avaimiin?"],

  ["Oliko hotellissa tulipalo?",
  "liittyykö se siihen, mitä sanoit tulipalosta hotellissa?"],

  ["Kenelle ase kuului?",
  "onko sillä jotain tekemistä aseen kanssa?"],

  ["Kenelle tikari kuului?",
  "onko sillä jotain tekemistä tikarin kanssa?"],

  ["Kuka on Hugo Punch?",
  "liittyykö se siihen, mitä sanoit Hugo Punch -julisteesta?"],

  ["Kuinka peilit särkyivät?",
  "liittyykö se siihen, mitä sanoit särkyneistä peileistä?"],

  ["Mihin lankakelaa käytettiin?",
  "liittyykö se jotenkin lankakelaan?"],

  ["Kuka kirjoitti jäähyväisviestin?",
  "liittyykö se jotenkin jäähyväisviestiin?"],

  ["Kenelle vihkisormus kuului?",
  "liittyykö se jotenkin vihkisormukseen?"],

  ["Kenelle vauvan helistin kuului?",
  "onko sillä jotain tekemistä vauvan helistimen kanssa?"],

  ["Löysin Jimmyn syntymätodistuksen. Siinä lukee, että Hugo Hall on Jimmyn isä.",
  "liittyykö se siihen, mitä sanoit Jimmyn syntymätodistuksesta?"],

  ["Näin itkevän tytön kellarissa. Kuka hän oli?",
  "",
  "Sanoit Jimmyn varastaneen omaisuuttasi,",
  "Sanoit Jimmyn olleen ilkeä pikkutyttöä kohtaan,",
  "Kerroit minulle pikkutytöstä, joka oleskeli hotellissa,",
  "Sanoit pikkutytön olleen vieraana hotellissa,"],

  ["Näin pikkutytön vaativan Jimmyä antamaan lelunsa takaisin. Miksi hän otti sen?",
  "Näin sinun vaativan Jimmyä antamaan lelusi takaisin. Miksi hän otti sen?",
  "Se, mitä sanoit varastetusta lelustasi,",
  "Sanoit, että varastaminen oli tyypillistä Jimmylle,",
  "",
  "Sanoit, ettei Jimmy varastanut koskaan mitään,"],

  ["Näin Amyn, sen pikkutytön, pitävän kädessään palavaa lelua. Mitä tapahtui?",
  "Näin sinun pitävän palavaa lelua kädessäsi. Mitä tapahtui?",
  "Sanoit, ettet voinut kertoa kenellekään palaneesta kädestäsi.",
  "Sanoit, että Amyn lelun sytyttäminen tuleen oli Jimmylle vain leikkiä,",
  "Sanoit tytön saaneen pahoja palovammoja.",
  "Sanoit tytön tehneen outoja asioita ja syyttäneen niistä Jimmyä,"],

  ["Näin Amyn käytävällä. Jokin pelotti häntä. Mikä se oli?",
  "Näin sinut käytävällä. Jokin pelotti sinua. Mikä se oli?",
  "Sanoit aikoneesi etsiä lääkärin, mutta Jimmy pakotti sinut jäämään,",
  "",
  "Sanoit, että tyttö pelkäsi luultavasti Jimmyä,",
  "Sanoit pikkutytön olleen kummallinen,"],

  ["Näin Amyn juovan jotakin, josta hän ei pitänyt. Mitä se oli?",
  "Näin sinun juovan jotakin, josta et pitänyt. Mitä se oli?",
  "Sanoit lääkkeen maistuneen kamalalta,",
  "Sanoit pienen tytön, Amyn, juoneen alkoholia,",
  "",
  ""],

  ["Näin pikkutytön nojaamassa kaiteeseen portaikon yläpäässä. Mitä oli tekeillä?",
  "Näin sinut nojaamassa kaiteeseen portaikon yläpäässä. Mitä oli tekeillä?",
  "Sanoit voivasi hypätä portaikon pohjalle asti,",
  "Sanoit Jimmyn pakottaneen tytön juomaan liikaa,",
  "Sanoit Amyn juoneen pullollisen viskiä.",
  ""],

  ["Näin Amyn makaamassa portaikon alapäässä. Mitä hänelle tapahtui?",
  "Näin sinut makaamassa portaikon alapäässä. Mitä sinulle tapahtui?",
  "Sanoit, ettet pysty enää heräämään.",
  "Sanoit Amyn kuoleman olleen syynä sille, että Rose otti yhteyttä.",
  "Sanoit Jimmyn olleen syypää Amyn kuolemaan,",
  "Sanoit Amyn kuoleman olleen hänen oma vikansa,"],

  ["Näin miehen koputtamassa oveen, hän halusi jutella Jimmyn kanssa. Kuka hän oli?",
  "",
  "",
  "Sanoit Harveyn olleen huolissaan Jimmyn mielenlaadusta,",
  "Sanoit, ettei Jimmyä voinut enää auttaa,",
  "Sanoit Dr Bosen tulleen auttamaan Jimmyä."],

  ["Näin Dr Bosen roikottavan kuollutta eläintä. Mitä oli tapahtunut?",
  "Näin sinun roikottavan kuollutta eläintä. Mitä oli tapahtunut?",
  "",
  "Sanoit Jimmyn keksineen tehdä sinulle jonkin mukavan asian,",
  "Sanoit Jimmyn kertoneen, että hän löysi kuolleen eläimen,",
  "Sanoit, ettet uskonut Jimmyn tappaneen sitä eläintä,"],

  ["Näin Dr Bosen puhumassa Jimmylle keittiön ovella. Mitä hän teki?",
  "Näin sinut puhumassa Jimmylle keittiön ovella. Mitä tapahtui?",
  "",
  "Sanoit, ettet osannut epäillä aluksi mitään,",
  "Dr Bose yritti auttaa Jimmyä, sanoit sen olleen suuri virhe.",
  "Sanoit Dr Bosen yrittäneen saada Jimmyä tekemään epämiellyttäviä asioita,"],

  ["Näin Dr Bosen sylkevän verta. Mitä oli tapahtunut?",
  "Näin sinun sylkevän verta. Mitä oli tapahtunut?",
  "",
  "Sanoit, että sinun täytyi tehostaa Jimmyn hoitoa välittömästi,",
  "Sanoit Jimmyn kujeiden menneen aina liian pitkälle,",
  "Sanoit Dr Bosen viiltäneen itseään ja syyttäneen siitä Jimmyä,"],

  ["Näin Dr Bosen puhumassa Jimmylle neula kädessään. Mitä tapahtui?",
  "Näin sinun puhuvan Jimmylle neula kädessäsi. Mitä tapahtui?",
  "",
  "Sanoit Jimmyn kieltäytyneen lääkkeestä,",
  "",
  "Sanoit Dr Bosen yrittäneen lääkitä Jimmyä ilman lupaasi."],

  ["Näin Dr Bosen selittämässä tapahtunutta. Hän vaikutti epätoivoiselta.",
  "Näin sinut selittämässä tapahtunutta. Vaikutit epätoivoiselta.",
  "",
  "Sanoit saaneesi Rosen vakuuttuneeksi siitä, että Jimmy oli valehdellut,",
  "Sanoit Dr Bosea huolettavan syystäkin se, mitä seuraavaksi tapahtuisi,",
  "Sanoit antaneesi Dr Boselle toisen mahdollisuuden,"],

  ["Näin Dr Bosen istuvan sängyllä ja puhuvan Jimmylle. Mitä tapahtui?",
  "Näin sinun istuvan sängyllä ja puhuvan Jimmylle. Mitä tapahtui?",
  "",
  "Sanoit Jimmyn sepittäneen pahimman mahdollisen valheen.",
  "",
  "Sanoit, ettei sinun olisi pitänyt luottaa Dr Boseen,"],

  ["Näin Dr Bosen liikehtivän levottomasti, poliisit olivat oven takana. Mitä tapahtui?",
  "Näin sinun liikehtivän levottomasti, poliisit olivat oven takana. Mitä tapahtui?",
  "",
  "Sanoit päättäneesi ottaa ohjat viimein käsiisi,",
  "Sanoit, ettet uskonut Jimmyn kertomuksiin Dr Bosesta.",
  "Sanoit, että Dr Bose ansaitsi tulla pidätetyksi,"],

  ["Näin Dr Bosen kietomassa köyttä kaulansa ympärille. Miksi hän tappoi itsensä?",
  "Kiedoit köyttä kaulasi ympärille. Miksi tapoit itsesi?",
  "",
  "Sanoit, että olit saanut tarpeeksesi.",
  "Sanoit, ettei Dr Bosella ollut vaihtoehtoja,",
  "Sanoit Dr Bosen toimineen oikein,"],

  ["Näin miehen, joka sanoi Jimmyn keksineen väitteet hyväksikäytöstä. Kuka hän oli?",
  "",
  "",
  "Sanoit Harveyn tienneen, että Jimmy valehteli,",
  "Sanoit tarinan olleen sinulle jo tuttu,",
  "Sanoit, ettei Harvey uskonut Jimmyä,"],

  ["Näin Harveyn vaatineen Jimmyä myöntämään valheensa. Myönsikö hän?",
  "Vaadit Jimmyä myöntämään valheensa. Myönsikö hän?",
  "",
  "Sanoit, ettei Jimmy ikinä myöntänyt valheitaan,",
  "Sanoit Jimmyn alkaneen asettaa ansoja sinulle,",
  "Sanoit, ettei Harveylla ollut oikeutta kiusata Jimmyä."],

  ["Näin Harveyn saavan sähköiskun. Mitä tapahtui?",
  "Sait sähköiskun. Mitä tapahtui?",
  "",
  "",
  "Sanoit aikovasi antaa Jimmylle opetuksen,",
  "Sanoit, että Harveyn olisi pitänyt hävittää se viallinen lämmitin."],

  ["Näin Harveyn tulevan ulos huoneesta maila kädessään. Mitä hän oli tehnyt?",
  "Näin sinun tulevan ulos huoneesta maila kädessäsi. Mitä olit tehnyt?",
  "",
  "Sanoit, että väkivalta pahentaa aina asioita.",
  "Sanoit, että Jimmy kosti sinulle pian,",
  "Sanoit, ettei Harvey kyennyt hillitsemään itseään,"],

  ["Näin nuolen osuvan Harveyn jalkaan. Mitä tapahtui?",
  "Näin nuolen osuvan jalkaasi. Mitä tapahtui?",
  "",
  "",
  "Sanoit saaneesi idean, kun kuulit, että Jimmy oli kellarissa,",
  "Sanoit, ettei Jimmy käyttäisi varsijousen kaltaista asetta,"],

  ["Näin Harveyn lukitsevan Jimmyn kellariin. Mitä tapahtui?",
  "Näin sinun lukitsevan Jimmyn kellariin. Mitä tapahtui?",
  "",
  "",
  "Sanoit olleesi väärässä, kun et uskonut Jimmyn voivan aiheuttaa vahinkoa kellarissa.",
  ""],

  ["Näin tulipalon kellarissa. Mitä hotellille tapahtui?",
  "Näin tulipalon kellarissa. Mitä hotellille tapahtui?",
  "",
  "",
  "Sanoit halunneesi päästä Jimmystä eroon,",
  "Sanoit tulipalon olleen pelkkää sattumaa."],

  ["Näin Harveyn harjoittelevan aseella. Mitä hän aikoi tehdä?",
  "Näin sinun harjoittelevan aseella. Mitä olit aikeissa tehdä?",
  "",
  "Sanoit Harveyn olleen raivoissaan.",
  "Sanoit, ettet tajunnut Jimmyn olleen myös aseistautunut,",
  "Sanoit, ettei Harveyn olisi kuulunut pitää asetta hotellissa,"],

  ["Näin Harveyn suuntaavan juhlasaliin aseen kanssa. Mitä hän oli tekemässä?",
  "Näin sinun suuntaavan juhlasaliin aseen kanssa. Mitä olit tekemässä?",
  "",
  "",
  "Sanoit etsineesi Jimmyä,",
  ""],

  ["Näin Harveyta puukotettavan lavan takana. Mitä tapahtui?",
  "Näin sinua puukotettavan lavan takana. Mitä tapahtui?",
  "",
  "",
  "Sanoit Jimmyn voittaneen aina lopulta,",
  "Sanoit Jimmyn vain puolustaneen itseään,"],

  ["Näin naisen selittävän, että tikari olikin kirjeveitsi. Kuka hän oli?",
  "",
  "",
  "",
  "Sanoit Rosen puolustaneen Jimmyä viimeiseen asti.",
  "Sanoit poliisien ymmärtäneen, että Jimmy puolusti itseään."],

  ["Ketä Rose tervehti hotellin pääovilla?",
  "Ketä tervehdit hotellin pääovilla?",
  "",
  "",
  "Sanoit poliisien luulleen, että olit aikeissa ampua Jimmyn,",
  "Sanoit Jimmyn löytäneen uuden keinon houkutella lisää asiakkaita hotelliin,"],

  ["Näin Rosen kuuluttavan Hugo Punchia lavalle.",
  "Näin sinun kuuluttavan Hugo Punchia lavalle.",
  "",
  "",
  "",
  "Sanoit Jimmyn vaikuttaneen vihaiselta,"],

  ["Näin Rosen käytävällä, joka oli täynnä mallinukkeja. Kuka asetti ne sinne?",
  "Näin sinut käytävällä, joka oli täynnä mallinukkeja. Kuka asetti ne sinne?",
  "",
  "",
  "",
  "Sanoit, ettei Jimmy ollut enää oma itsensä,"],

  ["Näin Rosen juhlasalin ovella. Yleisö buuasi ja hän pyyteli anteeksi. Mitä tapahtui?",
  "Näin sinut juhlasalin ovella. Yleisö buuasi ja pyytelit anteeksi. Mitä tapahtui?",
  "",
  "",
  "Sanoit, että Jimmyllä oli tapana pilata kaikki aina lopulta.",
  "Sanoit Jimmyn menettäneen malttinsa ja tehneen jotain tyhmää,"],

  ["Näin Rosen ahdistuneena, ovella oli ihmisiä esittämässä kysymyksiä. Keitä he olivat?",
  "Näin sinut ahdistuneena, ovella oli ihmisiä esittämässä kysymyksiä. Keitä he olivat?",
  "",
  "",
  "",
  "Sanoit Jimmyn halunneen jättää kaiken taakseen ja lähteä,"],

  ["Näin Rosen eräässä huoneessa. Hän löysi jonkun kylpyhuoneesta. Mitä tapahtui?",
  "Näin sinut eräässä huoneessa. Löysit jonkun kylpyhuoneesta. Mitä tapahtui?",
  "",
  "",
  "",
  "Sanoit, että sinun oli kerrottava Jimmylle totuus,"],

  ["Näin Rosen hyökkäävän jonkun kimppuun maila kädessä. Kuka se oli?",
  "Näin sinun hyökkäävän jonkun kimppuun maila kädessä. Kuka se oli?",
  "",
  "Sanoit Rosen menneisyyden olleen synkkä.",
  "Sanoit, ettei Rose kertonut sinulle kaikkea.",
  "Sanoit, ettet voinut enää elää itsesi kanssa,"],

  ["Näin Rosen, hän oli liekeissä. Mitä tapahtui?",
  "Näin sinut, olit liekeissä. Mitä tapahtui?",
  "",
  "",
  "",
  "Sanoit, että minun pitäisi pyytää Jimmyä näyttämään, missä Hugo asuu,"],

  ["Näin jonkun lavalla. Hän julisti olevansa Mahtava Hugo.",
  "",
  "",
  "",
  "Sanoit Hugon olleen Rosen ensimmäinen aviomies,",
  "Sanoit, että Hugon kanssa tapahtui käänteitä,"],

  ["Kuulin miehen määräävän jotakuta toimimaan niin kuin hän haluaa.",
  "",
  "",
  "",
  "",
  "Sanoit pystyväsi antamaan Hugolle vain yhden asian."],

  ["Kuulin miehen karjuvan ja lapsen itkevän.",
  "",
  "",
  "",
  "",
  "Sanoit, että Jimmy on Hugon poika."],

],

subs:[

  "ALKUKOHTAUS",[
   13.6,5,"Jimmy!",14.6,4,"",
   16.2,4,"Jimmy!",17.4,4,"",
   18.8,2,"Jimmy!",20,4,"",
   20.1,6,"ÄÄNIÄ LÄHETTIMESTÄ",21.6,6,"",
   24.3,3,"Jättäkää minut rauhaan...",25.9,4,"",
   26.5,6,"NYYHKYTYSTÄ",27.9,4,"",
   28.6,6,"ÄÄNET VOIMISTUVAT",30.3,4,"",
   30.7,3,"Lopettakaa!",31.8,4,"",
   32.4,3,"Jättäkää minut vain rauhaan!",34.8,4,"",
   35.8,6,"KOHINAA JA ÄÄNIÄ",37.3,4,"",
   44.5,6,"PUHELIN SOI",45.6,0,"",
   46.6,1,"Haloo?",47.6,0,"",
   47.7,3,"Maya? Hannah tässä.",48.8,0,"",
   49.4,1,"Hannah? Missä olet?",51.2,0,"",
   51.3,1,"Te jätitte minut jälkeenne!",53.6,0,"",
   53.7,1,"Missä olette nyt? Mistä numerosta soitat?",55.6,0,"",
   55.7,3,"Kirjauduimme kaikki yhteen hotelliin tien päässä.",57.4,0,"",
   57.5,3,"Kuinka kaukana olet?",58.8,0,"",
   58.9,1,"En osaa sanoa. Soitan sitten kun olen perillä.",61.1,0,"",
   61.2,3,"Et voi, olemme kantaman ulkopuolella.",62.9,0,"",
   63,1,"No... ",64.1,1,"",
   65,1,"Ei sillä ole väliä. Mene jo nukkumaan, Hannah.",67,0,"",
   67.1,3,"Kuuntele. Varmista, että...",68.3,0,"",
   68.6,6,"PUHELU KATKEAA",70.1,0,"",
   71,6,"PUHELU PÄÄTTYY",72.5,0,"",
   84,6,"1950-LUVUN JAZZMUSIIKKIA",85.5,4,"",
   92.1,3,"Ah, Maya, oletan?",94.1,0,"",
   94.5,3,"Älä hätäile.",96.4,0,"",
   96.6,3,"Ystäväsi kirjasivat sinutkin sisään...",99,0,"",
   99.1,3,"annahan kun vilkaisen.",100.8,0,"",
   101.8,3,"Aivan.",102.8,0,"",
   102.9,3,"Huone 101.",104,0,"",
   104.2,3,"Yöpyminen on jo maksettu, joten kaikki on kunnossa.",107.2,0,"",
   107.3,3,"Sinulla on mukavia ystäviä.",109.1,0,"",
   109.9,3,"Todella mukavia.",111.2,0,"",
   111.5,3,"Ja teitä onkin monta.",115.6,0,"",
   116.2,3,"On mukavaa nähdä niin monia...",118.2,0,"",
   118.3,3,"uusia kasvoja vaihteeksi.",122.7,0,"",
   123.5,3,"Osallistutte varmaan festareille?",126.8,0,"",
   127.3,1,"Joo, meidän piti majoittua siellä tänä yönä, mutta...",130.5,0,"",
   130.6,3,"Sää ei tainnut suosia teitä!",133.1,0,"",
   136,3,"Jäättekö aamiaiselle?",137.5,0,"",
   137.6,1,"En usko, lähdemme aikaisin liikkeelle.",140.2,0,"",
   140.3,3,"Selvä. Ja jos saan kysyä,",143.7,0,"",
   143.8,3,"haluaisitko tulla katsomaan showta tänä yönä?",147.5,0,"",
   147.9,1,"Tänä yönä?",148.9,0,"",
   149,3,"Se alkaa yleensä keskiyöllä.",152.1,0,"",
   152.6,3,"Minä olen esiintyjänä.",155.8,0,"",
   155.9,3,"Näyttelen Hugo Punchia,",161,0,"",
   161.1,3,"koomista sosiopaattia,",164.8,0,"",
   164.9,3,"joka sanoo asioita, joita ei kuuluisi sanoa.",169.6,0,"",
   169.7,3,"Opiskelijat tykkäävät siitä paljon.",171.7,0,"",
   172.3,1,"Taidamme vain mennä suoraan nukkumaan.",175.7,0,"",
   175.8,3,"Enkö mitenkään saisi houkuteltua sinua mukaan?",179.2,0,"",
   179.5,1,"Olen pahoillani, mutta menisin mieluiten jo nukkumaan.",182.8,0,"",
   182.9,3,"Ymmärrän, ymmärrän...",185.4,0,"",
   185.6,1,"Missä huoneet ovat?",186.7,0,"",
   187.2,3,"Ota vain hissi, olet ensimmäisessä kerroksessa.",190.2,0,"",
   190.3,1,"Kiitos.",191.6,0,"",
   193.1,3,"Ja Maya... pudotathan avaimen laatikkoon aamulla.",198.1,0,"",
   198.2,1,"Selvä!",199.2,0,"",
   199.3,6,"HISSIN OVI SULKEUTUU",200.8,0,"",
   204.4,3,"Kylän paras show, eikä kukaan tule katsomaan.",207.2,0,"",
   210.3,3,"Kuka tarvitsee enää laatuviihdettä, kun kaikilla on 'You Tune' ja 'My Face'.",216.6,0,"",
   216.7,3,"Typerät, sivistymättömät...",218.7,0,"",
   218.8,5,"Hugo ei pidä ilkeistä lapsista, ne ovat tuhmia.",223,0,"",
   225.5,3,"Älä aloita tätä taas.",227.3,0,"",
   231.1,3,"En halua kuulla tästä tänä yönä.",234.2,0,"",
   237,5,"Tuhmat lapset ovat mätämunia. Niille pitää antaa opetus!",240.9,0,"",
   254.2,3,"Hiljaa! Ole jo hiljaa!",256.5,0,"",
   257.3,3,"He ovat maksavia asiakkaita.",260.2,0,"",
   260.5,3,"He eivät ole tehneet sinulle mitään.",262.4,0,"",
   263.3,3,"Jätä heidät rauhaan.",265.4,0,"",
   266.2,5,"Mätämunat pitää rikkoa! Niiden kuoret murskataan,",269.3,0,"",
   269.5,5,"ja portaita alas potkaistaan!",272.3,0,"",
   272.8,5,"Tiedät mitä tehdä, Jimmy.",275,0,"",
   275.6,5,"Näytä heille, kuka määrää.",277.7,0,"",
   278.9,5,"Ei ole muuta keinoa!",281.1,0,"",
   293.3,6,"KAUKAISTA KIRKUMISTA",294.9,0,"",
   308,6,"MIES NAURAA",309.6,0,"",
   310,3,"Nukuhan nyt...",313,0,"",
   345.2,6,"PUHELIN RÄTISEE",346.9,0,"",
   358.5,6,"ÄÄNIÄ LÄHETTIMESTÄ",361.9,0,"",
   362,1,"Lähde hotellista!",363.6,0,"",
   363.7,1,"Lähde kun vielä voit!",365.7,0,"",
   367.6,1,"Selvitä hänen pahat tekonsa...",369.3,0,"",
   369.4,1,"...ja kerro ne kaikille.",371.3,0,"",
   371.4,1,"Hänen täytyy kantaa vastuu teoistaan!",373.3,0,"",
   373.5,6,"KOHINA VOIMISTUU",376,0,"",
   420,1,"",420.9,0,"X",
],
  "A2",[
   0.8,1,"Jimmy, anna se takaisin! Se on minun!",2.9,0,"",
   3,1,"Lakkaa varastamasta tavaroitani!",4.3,0,"X",
],
  "A3",[
   0.7,6,"AMY KIRKUU",2,0,"X",
],
  "A4",[
   1.1,1,"Et saa tehdä noin, Jimmy!",3.1,0,"",
   3.2,1,"Olet kauhea...",4.7,0,"X",
   3.8,6,"AMY VAIKENEE",4.4,0,"X",
],
  "A5",[
   3.8,6,"AMY YSKII",4.8,0,"X",
],
  "A6",[
   4.2,6,"AMY KIKATTAA",5.2,0,"X",
],
  "P1",[
   3.8,6,"MIES KOPUTTAA",4.8,0,"",
   5.8,2,"Jimmy?",6.8,0,"",
   7.2,2,"Olen Doctor Bose.",8.9,0,"",
   9,2,"Tulin juttelemaan kanssasi hetkeksi.",11.5,0,"",
   14.5,2,"Kiitos Jimmy, tämä ei kestä kauaa.",16.6,2,"X",
],
  "P3",[
   1,2,"Tämä on loistoidea, Jimmy!",3.4,0,"",
   3.5,2,"Sinusta tulee loistava kokki jonain päivänä.",5.7,0,"",
   5.8,2,"Tuotko sen minulle, kun olet valmis?",8,0,"",
   8.1,2,"Odotan sinua ylhäällä.",9.8,0,"X",
],
  "P4",[
   3,6,"DR BOSE PÄRSKII",4,0,"",
   7.6,2,"Jimmy!",8.6,0,"X",
],
  "P5",[
   1.2,2,"Tämä ei satu, Jimmy.",2.9,0,"",
   3,2,"Seiso aloillasi äläkä liiku!",6.6,0,"X",
],
  "P6",[
   0.6,2,"En ikinä käyttäisi voimakeinoja potilaaseen, rouva Hall.",4.8,0,"",
   4.8,2,"Se on vastoin kaikkia periaatteitani.",7.3,0,"",
   7.4,2,"Poikanne keksii kaiken omasta päästään, koettakaa ymmärtää!",10,0,"X",
],
  "P7",[
   1.1,2,"Et pääse minusta eroon näin helposti, Jimmy.",3.9,0,"",
   4,2,"Mielestäni meidän pitäisi aloittaa alusta.",6.5,0,"",
   6.6,2,"Etkö voisi kerrankin tehdä niin kuin sanon?",8.7,0,"",
   8.8,2,"Se olisi hyvä alku.",11,0,"X",
],
  "P8",[
   0.6,2,"Poliisi täällä, herra Bose.",2.1,0,"",
   2.2,2,"Teidän pitää tulla kanssamme asemalle.",4.1,0,"",
   4.4,2,"Voitteko avata oven?",5.8,0,"X",
],
  "P9",[
   14.1,6,"DR BOSE KURISTUU",15.5,0,"",
   15.9,6,"HISSIN HÄLYTYS SOI",16.9,0,"X",
],
  "H1",[
   0.8,3,"Hän keksi sen päästään. Hän valehtelee jatkuvasti kaikesta,",3.4,0,"",
   3.5,3,"Varmaan siitä toisestakin jutusta.",5,0,"",
   5.1,4,"Älä ole typerä! Ei hän valehtelisi sellaisesta asiasta!",7.3,0,"",
   7.4,3,"Oletko varma?",8.3,0,"",
   8.4,3,"Kaikki, mitä hän sanoo, on valhetta! Avaa silmäsi, Rose!",11.4,0,"",
   11.5,3,"Kävele vain poispäin, se ratkaiseekin kaiken!",12.8,0,"",
   12.9,4,"En aio kuunnella sinua, olet vain päättänyt vihata häntä.",14.7,0,"",
   14.9,3,"Kerron ainoastaan totuuden!",16.2,0,"X",
],
  "H2",[
   1.5,6,"HARVEY HAKKAA OVEA",2.4,0,"",
   2.5,3,"Jimmy?",3.5,0,"",
   4.3,3,"Tiedän, että olet siellä!",5.8,0,"",
   6.2,3,"Syytöksesi lääkäriä kohtaan ovat täyttä hölynpölyä.",10,0,"",
   10.1,3,"Tiedän, miten keksit tarinasi!",11.6,0,"",
   12,3,"Löysit sen siitä pahuksen leikekirjastasi!",15.3,0,"",
   16.1,3,"Tule ulos!",17.3,0,"",
   18.3,3,"Jimmy!",19.6,0,"X",
],
  "H3",[
   1.2,6,"KIPINÖINTIÄ",2.2,0,"",
   2.3,6,"HARVEY HUUTAA TUSKISSAAN",3.3,0,"",
   7.2,3,"Jimmy!",8.2,0,"X",
],
  "H4",[
   1,6,"HARVEY HAJOTTAA TAVAROITA",2,0,"X",
],
  "H5",[
   0.8,6,"HARVEY HUUTAA TUSKISSAAN",1.9,0,"",
   4.1,3,"Jimmy!",5.1,0,"X",
],
  "H6",[
   1.3,3,"Saat luvan pysyä siellä yön yli, Jimmy!",3.7,0,"",
   3.8,3,"Olen saanut tarpeekseni.",5,0,"",
   5.1,6,"OVEA HAKATAAN",6.6,0,"X",
],
  "H7",[
   0.3,6,"PALOHÄLYTYS",1.8,0,"",
   2.7,3,"Jimmy, älä ole hölmö, avaa ovi!",4.9,0,"",
   5.2,3,"Kuolet sinne kohta, senkin typerys! Avaa ovi!",8.4,0,"X",
],
  "H8",[
   2.7,3,"Häivy hotellista, Jimmy.",4.6,0,"",
   6.6,3,"Häivy hotellistani...",8,0,"",
   8.6,3,"Tämä on minun hotellini. Häivy hotellistani, Jimmy.",12,0,"X",
],
  "H9",[
   1.8,3,"Häivy hotellistani.",3.2,0,"",
   3.3,3,"Tämä on MINUN hotellini.",5,0,"X",
],
  "R1",[
   0.8,8,"Harvey aikoi ampua Jimmyn.",2.4,0,"",
   2.5,8,"Jimmy yritti vain puolustaa itseään. Se on kirjeveitsi, katsokaa vaikka!",5.9,0,"X",
],
  "R2",[
   3.5,4,"Jimmy",4.5,0,"X",
],
  "R3",[
   1.2,4,"Hyvät naiset ja herrat,",2.4,0,"",
   2.5,4,"antakaa kunnon aplodit",3.9,0,"",
   4,4,"tämäniltaiselle viihdyttäjällenne,",5.9,0,"",
   6,4,"Mr Hugo Punchille!",8,0,"",
   8.1,6,"MUSIIKKIA JA TAPUTUKSIA",9.6,0,"X",
],
  "R4",[
   0,4,"",0,0,"",
],
  "R5",[
   0.7,4,"Se on vain hänen tapansa tehdä komediaa.",2.6,0,"",
   2.7,4,"Hänellä on sellainen huumorintaju!",4.4,0,"",
   4.5,4,"Pyydän anteeksi, jos pahoititte mielenne...",6.3,0,"",
   6.4,4,"Anteeksi...",7.6,0,"X",
],
  "R6",[
   0.5,6,"ETUOVEA HAKATAAN",1.8,0,"",
   1.9,4,"Rouva Hall?",3.4,0,"",
   4.2,4,"Rouva Hall, voimmeko jutella hetken?",6.5,0,"X",
],
  "R7",[
   1.4,4,"Jimmy?",2.4,0,"",
   4.1,6,"ROSE KIRKUU",5.1,0,"",
   5.2,4,"Jimmy! Mitä olet mennyt tekemään! Jimmy!",8,0,"X",
],
  "R8",[
   0.5,6,"LAPSI ITKEE",1.5,0,"",
   1.6,5,"Teet niin kuin minä käsken! Ymmärrätkö?",4.2,0,"",
   4.3,5,"Typerä kakara!",5.4,0,"",
   5.5,6,"LASTA LYÖDÄÄN",6.7,0,"",
   6.9,6,"MAILA OSUU MIEHEEN",8.3,0,"X",
],
  "R9",[
   1.4,6,"ROSE KIRKUU",2.9,0,"X",
],
  "V1",[
   5.5,7,"Katsokaa!",6.3,0,"",
   6.4,6,"GONG",7.4,0,"",
   7.5,7,"Olen Mahtava Hugo!",10.2,0,"",
   11.9,7,"Seison kaikkien yläpuolella.",15.9,0,"",
   17.4,7,"Olen pimeyttä valaiseva kirkkaus.",21.4,0,"",
   22.7,7,"Olen velhoista suurin.",26.5,0,"X",
],
  "V2",[
   5,6,"NAINEN NYYHKYTTÄÄ",6.5,0,"",
   8,5,"Älä osta mitään ilman lupaani!",10.5,0,"",
   10.6,6,"LASI SÄRKYY",11.5,0,"",
   11.6,5,"En anna sinun pilata elämääni!",14,0,"",
   14.1,6,"SÄRKYMISEN ÄÄNIÄ",15.2,0,"",
   15.1,5,"Elämäsi ei merkitse mitään!",16.8,0,"",
   16.9,5,"Ymmärsitkö mitä sanoin?",18.6,0,"",
   18.7,6,"SÄRKYMISEN ÄÄNIÄ, NAINEN KILJAISEE",20.9,0,"X",
],
  "V3",[
   3.1,6,"LAPSI ITKEE",4.6,0,"",
   9,5,"Istu aloillasi!",10,0,"",
   10.1,6,"LASTA PIISKATAAN",11.4,0,"",
   11.5,5,"Typerä kakara!",12.8,0,"",
   12.9,5,"Tee niin kuin käsken!",14.9,0,"",
   15,6,"NAINEN HUUTAA<br>Ei!",17,0,"X",
],
  "EPI",[
   17.9,3,"Hyvät naiset ja herrat,",19,0,"",
   19.1,3,"antakaa kunnon aplodit",20.6,0,"",
   20.7,3,"tämäniltaiselle viihdyttäjällenne,",22.5,0,"",
   22.6,3,"Mr Hugo Punchille!",24.7,0,"",
   24.8,6,"TAPUTUKSIA",26.4,0,"",
   33.5,5,"Maya!",34.5,0,"",
   36.1,5,"Maya!",37.1,0,"",
   40.5,5,"Maya?",41.5,0,"",
   42,5,"Maya!",43.5,0,"",
   44,6,"NYYHKYTYSTÄ",46,0,"",
   47.5,3,"Lopeta, lopeta, lopeta, lopeta...",49.9,0,"",
   50,3,"Lopeta jo.",51.5,0,"",
   52.6,3,"Miksi pakotat minut tekemään tätä?",55.3,0,"",
   56,3,"Ole kiltti ja lopeta.",57.5,0,"",
   58.4,3,"Ole kiltti, lopeta jo...",60.4,0,"",
   63.2,5,"Sinä teet niin kuin käsken, Jimmy.",64.9,0,"",
   66.7,5,"Minä määrään täällä.",68.6,0,"",
   68.7,5,"Et sinä.",69.7,0,"",
   71,5,"Vaan minä.",73.5,0,"",
],
  "BRO",[
   1.5,5,"Tervetuloa Hugon haudalle!",5.5,5,"",
   5.6,5,"Äidin pieni salaisuus.",8.9,5,"",
   9,5,"Hän sekoitti betonin itse,",11.8,5,"",
   11.9,5,"kaatoi sen ruumiin päälle",15.1,5,"",
   15.2,5,"ja seurasi sen kovettumista.",17.8,5,"",
   18.1,5,"Hän luuli päässeensä eroon Hugosta.",21,5,"",
   21.3,5,"Mutta hän ei käsittänyt,",24.7,5,"",
   24.8,5,"että Hugo oli vain yksi meistä, Maya.",29.1,5,"",
   29.2,5,"Vain yksi halko pesässä.",33,5,"",
   33.2,5,"Hän hiiltyi.",35.8,5,"",
   36,5,"Mutta liekki on palanut Hallien suvussa jo vuosisatoja.",41.2,5,"",
   41.3,5,"Tehden tietä...",43.5,5,"",
   43.6,5,"valaisten pimeyttä...",45.9,5,"",
   46,5,"tuhoamalla vanhojen, heikkojen ja onnettomien jäsentensä sieluja.",52.3,5,"",
   52.4,5,"Se palaa myös sinussa, Maya.",56.7,5,"",
   56.8,5,"Näen sen!",58.8,5,"",
   59,5,"Meidän kahden oli tarkoituskin päätyä yhteen.",62.9,5,"",
   63,5,"Olen odottanut sinua jo kauan.",66.6,5,"",
   66.8,5,"Enkä voi antaa sinun lähteä.",71,5,"",
   71.1,5,"Sinä pysyt luonani, Maya.",75.2,5,"",
   75.3,5,"Ikuisesti.",77.5,5,"X",
],
  "COR",[
   0.2,5,"Puhutko kuolleille, Maya?",4.3,1,"",
   4.5,1,"Tiedän, että Hugo on isäsi, Jimmy.",6.6,1,"",
   6.7,1,"Löysin syntymätodistuksesi ja tiedän, että Rose yritti tappaa hänet.",10.5,1,"",
   10.6,5,"Mutta äitini epäonnistui.",13.6,1,"",
   13.7,1,"Missä Hugo on nyt?",15.5,1,"",
   15.8,6,"JIMMY NAURAA",17,1,"",
   20.3,5,"Miksi et tulisi itse tapaamaan häntä?",22.8,1,"",
   22.9,5,"On tullut aika esitellä sinut perheelleni, Maya.",27.8,1,"",
   27.9,6,"JIMMY NAURAA",29,1,"X",
],
  "AP",[
   2.6,5,"Hei Maya!",5,1,"",
   6.5,5,"Maya!",7.5,5,"",
   9,5,"Maya!",10.3,5,"",
   10.4,6,"HAKKAA OVEA",11.4,5,"",
   11.9,5,"Et pääse pakoon, Maya!",14.9,5,"",
   15,5,"Avaa ovi!",16.2,5,"X",
],
  "TUT",[
   0.83,1,"LÄHTÖTILANNE",
   4.33,1,"",
   6.4,1,"Tämä on Jimmy Hall, hotellin omistaja",
   9.3,1,"Sekä vaarallinen psykopaatti",
   12.37,1,"",
   15.27,1,"Hänellä on mielessään katalia suunnitelmia",
   18.3,1,"",
   19.4,1,"Ystävyksistä vain Maya pääsi pakoon",
   22.4,1,"",
   24.23,1,"Ja Jimmyn on pysäytettävä hänet",
   27.33,1,"",
   27.83,1,"JAHTAUS",
   31.57,1,"",
   33.3,1,"Jimmy piileskelee monissa paikoissa",
   36.8,1,"",
   39.37,1,"Kulmien takana",
   41.63,1,"",
   42.33,1,"Varjoissa",
   44.33,1,"",
   45.27,1,"Odottaen, että saavut hänen luokseen",
   47.6,1,"",
   48.23,1,"Tai yllättäen sinut takaapäin",
   50.57,1,"",
   51.2,1,"Hän ei voi piileskellä portaikossa",
   53.53,1,"",
   54.33,1,"Eikä pohjakerroksessa",
   56.47,1,"",
   57.33,1,"Eikä kellarissa",
   60.27,1,"",
   60.7,1,"STRATEGIA",
   64.67,1,"",
   66.17,1,"Jos Jimmy näkee sinut",
   67.67,1,"liiku pois hänen näköpiiristään",
   71.83,1,"",
   75.13,1,"Piiloudu mihin tahansa huoneeseen",
   78.17,1,"",
   79.67,1,"Jos Jimmy alkaa avata ovea",
   81.73,1,"",
   84.13,1,"Piiloudu vaatekaappiin",
   86.4,1,"",
   90.2,1,"Tai kylpyhuoneeseen",
   92.33,1,"",
   94.73,1,"Katso ovisilmän läpi nähdäksesi",
   97.67,1,"",
   98.53,1,"onko Jimmy huoneen ulkopuolella",
   101.43,1,"",
   103.63,1,"Kutsu häntä huutamalla",
   105.2,1,"",
   106.67,1,"Niin voit kontrolloida hänen liikkeitään",
   109.67,1,"",
   110.23,1,"Etsi huoneiden avaimia vetolaatikoista",
   112.67,1,"",
   114.17,1,"Lukitse ovi ja Jimmy ei pääse sisään",
   116.4,1,"",
   117.83,1,"Tai lukitse Jimmy huoneeseen",
   120.13,1,"Kunhan pääset ensin hänen ohitseen",
   123.17,1,"",
   124.67,1,"Tarkista huoneet katsomalla avaimenrei'istä",
   127.7,1,"",
   129.67,1,"KUOLLEIDEN SIELUT",
   133.5,1,"",
   135.17,1,"Jimmyllä on synkkä menneisyys",
   138.2,1,"Hänen uhrinsa eivät koskaan lähteneet pois",
   141.17,1,"Vaan kummittelevat yhä hotellissa",
   144.47,1,"",
   145.67,1,"Käytä henkilähetintä puhuaksesi heille",
   150.2,1,"",
   153.23,1,"Kysy heiltä asioista ja esineistä, joita olet nähnyt",
   159.07,1,"",
   159.13,1,"Saat selvitettyä menneisyyttä pala palalta",
   166.63,1,"",
   168.17,1,"Seuraa välkkyviä valoja",
   171.1,1,"ja kuuntele ääniä",
   174.07,1,"",
   175.47,1,"Kompassi näyttää sinulle suunnan",
   178.4,1,"",
   180.07,1,"Kun olet lähellä, katsele ympärillesi",
   183.07,1,"Tai pysy paikoillasi ja odottele",
   186.17,1,"",
   186.7,1,"MAYAN KYKY",
   191.5,1,"",
   192.5,1,"Mayalla on kyky nähdä tuonpuoleiseen",
   196.5,1,"",
   197.97,1,"Liiku hämärään nurkkaukseen",
   200.43,1,"",
   201.43,1,"Ja katso peiliin",
   204.67,1,"",
   206.27,1,"Se näyttää sinulle tärkeiden esineiden",
   209.2,1,"ja henkien sijainteja",
   212.23,1,"Sekä juoniyhteyksiä esineiden ja henkien välillä",
   217.23,1,"",
   218.3,1,"Jimmy saattaa varastaa sinulta tavaroita hyökkäyksen jälkeen",
   222.77,1,"",
   224.27,1,"Löydät henkilähettimen ensimmäisen kerroksen varastohuoneesta, läheltä portaikkoa",
   229.3,1,"",
   230.27,1,"Etsi kompassia ja avaimia hotellihuoneiden vetolaatikoista",
   234.77,1,"",
   236.23,1,"Lue henkilähettimen käyttöohjeet saadaksesi lisätietoa kummitusjahdista",
   241.47,1,"",
],
],

itexts:[

  "vanhoja matkalaukkuja",
  "palkintopokaaleja",
  "lapsen kukkaron",
  "tärpättipullon ja sytyttimen",
  "koristeellisen miekan",
  "viskipulloja ja muita väkijuomia",
  "rajuja piirroksia",
  "kokin hatun",
  "vanhan verellä tahrautuneen liinan",
  "ruiskun ja diatsepaamilääkepullon",
  "vanhan puisen melan",
  "leikekirjan vanhoista sanomalehtiartikkeleista",
  "pyykkinarun ja kaulimen",
  "vanhan lämmittimen, joka on merkitty vaaralliseksi",
  "kriketti- ja pesäpallomailoja",
  "varsijousen",
  "vanhoja ruosteisia avaimia",
  "kuvia, joissa hotellista tulee savua",
  "vanhan käsiaseen",
  "koristeellisen tikarin",
  "Jimmy Hallin komedianäytelmän julisteen",
  "särkyneitä seinäpeilejä",
  "kuparilankakelan",
  "käsinkirjoitetun jäähyväisviestin",
  "sormuksen rasiassaan",
  "vauvan lelun",
  "Jimmy Hallin syntymätodistuksen",

],

ketex:[

  "Avain huoneeseen ",
  "Näit näyn ",
  "Näit näyn '",
  "Löysit ",
  "Löysit avaimen huoneeseen ",
  "kompassin",
  "ennepeilin",

],

patex:[

  ["H","Roselle, mutta hän ei koskaan käyttänyt [matkalaukkuja].","R","[Matkalaukut] olivat minun. Halusin lähteä pois, mutten koskaan saanut tilaisuutta."],
  ["R","Jimmy osti [palkintoja] luodakseen vaikutelman, että hänet olisi palkittu."],
  ["A","[Kukkaro] kuului minulle. Se oli syntymäpäivälahjani, mutta se varastettiin.","H","Se oli sen tyttörukan kukkaro.","R","[Kukkaro] kuului sille pikkutytölle."],
  ["A","En tiennyt, mitä [tärpätti ja sytytin] olivat ennen kuin Jimmy näytti ne minulle.","P","Sinun olisi parasta kysyä Jimmyltä.","H","[Tärpätti ja sytytin] kuuluivat minulle, mutten säilyttänyt niitä yhdessä.","R","En tiedä. [Tärpätti ja sytytin] kuuluivat Harveylle."],
  ["A","[Miekka] oli Jimmyn kädessä. En pitänyt siitä.","P","Näin Jimmyn leikkivän [miekalla]. Mielestäni se oli vaarallista.","H","Jimmy varasti [miekan] keskiaikaisten aseiden näyttelystä.","R","[Miekka] kuului yhteen haarniskan kanssa, mutta se katosi."],
  ["A","En tiedä [mistä pullot ovat peräisin], mutta lasten ei kuuluisi juoda alkoholia.","P","[Pullot] olivat todennäköisesti baarista.","H","En muista [mistä pullot ovat peräisin], mutta muutama lasillinen ei ole koskaan pahitteeksi.","R","Harvey varmaan laittoi [pullot] sinne."],
  ["A","Se poika piirsi [rajuja piirroksia].","P","Jimmy piirsi [rajuja piirroksia].","H","Kukakohan [piirsi rajuja piirroksia]? Jimmy! Hänellä oli raju mielikuvitus.","R","Jimmy piirsi sota-aiheisia kuvia. Hän oli samanlainen kuin muutkin pojat."],
  ["P","Jimmy löysi [kokin hatun] ja laittoi päähänsä.","H","Kuka muu [kuin kokki] käyttäisi kokin hattua?","R","Kokkimme käytti [kokin hattua]."],
  ["A","[Liina] saattoi olla minun.","P","[Liina] oli minun. Säilytin sitä siltä varalta, että tarvitsisin todistusaineistoa.","H","En tiedä, mutta [liina] saattaa liittyä lääkäriin."],
  ["P","[Lääke] auttaa hillitsemään joidenkin ihmisten käytöshäiriöitä.","H","Lääkäri varmaan jätti [lääkkeen] tänne.","R","[Lääke] kuului lääkärille."],
  ["P","En tiedä, mutta Jimmy löysi [melan].","H","[Melaa] säilytettiin vastaanottotiskin hyllyllä. En tiedä, mistä se on peräisin.","R","[Mela] kuului miehelleni."],
  ["A","Jimmy teki [leikekirjan]. En tiedä miksi. Hän oli outo.","P","Jimmy teki [leikekirjan]. Minun olisi pitänyt tajuta sen olleen varoitus.","H","[Jimmy] leikkeli uutisia ilkeistä opettajista ja lääkäreistä. Hän ei ollut tavallinen poika.","R","Harveyn mukaan Jimmy teki [leikekirjan]. En muista sitä."],
  ["P","Sidoin [pyykkinarun ja kaulimen] yhteen, se oli kokeilu."],
  ["H","[Vanha lämmitin] antoi sähköiskuja. Säilytin sitä poliiseja varten.","R","Harvey siirsi [vanhan lämmittimen] syrjään. Se oli kuulemma vaarallinen."],
  ["A","En tiedä [mailojen tarkoitusta]. Jimmy leikki niillä.","P","Harvey säilytti [mailoja], en tiedä miksi.","H","Säilytin [mailoja] varmuuden vuoksi.","R","[Mailat] kuuluivat miehelleni, kun hän työskenteli opettajana."],
  ["A","Näin [varsijousen] vitriinissä.","P","Hotellissa oli vanhojen aseiden näyttely.","H","[Varsijousi] oli osa asenäyttelyämme. Jimmy kiintyi siihen.","R","[Varsijousi] oli esillä Harveyn näyttelyssä. En pitänyt siitä, että se oli hotellissa."],
  ["H","[Ruosteiset avaimet] olivat pannuhuoneen vanhaan oveen.","R","[Ruosteiset avaimet] olivat pannuhuoneen oveen, mutta ovi piti vaihtaa."],
  ["P","En ole kuullut [tulipalosta].","H","Kyllä. Palo saatiin hallintaan, mutta menetin paljon tavaraa.","R","Kyllä, mutta saimme sen hallintaan ennen kuin se alkoi levitä."],
  ["P","Harveylle. En pitänyt siitä, että [ase] oli hotellissa.","H","Perin [aseen] isältäni. Siinä oli muutama panos jäljellä.","R","Harveylle, mutta [asetta] säilytettiin minun huoneessani."],
  ["A","Jimmy näytti [tikarin] minulle, mutta se ei ollut hänen.","H","Se ei ole tikari, vaan kirjeveitsi. Sen ei kuuluisi olla terävä.","R","[Tikari] on kirjeveitsi. Joku antoi sen lahjaksi."],
  ["R","[Julisteessa] oli Jimmyn komediahahmo."],
  ["P","En ole nähnyt [peilejä].","H","En muista tapausta.","R","Jimmy rikkoi [peilit]."],
  ["A","Jimmy kantoi [lankakelaa] mukanaan.","P","[Lankakela] oli Jimmyn. Hän piti sitä taskussaan, muttei kertonut mihin käytti sitä.","H","Jimmy kantoi [lankakelaa] mukanaan, en tiedä miksi.","R","Jimmy kuljetti [lankakelaa] mukanaan. Sähkö ja elektroniikka kiinnostivat häntä."],
  ["R","Jimmy kirjoitti [jäähyväisviestin]."],
  ["H","[Sormus] kuului todennäköisesti Roselle.","R","[Sormus] oli minun. Minulle tehtiin tarjous, josta en voinut kieltäytyä."],
  ["A","En tiedä. En nähnyt vauvaa.","R","[Helistin] oli vauvaa varten. Säilytin sitä vetolaatikossa sänkyni vieressä."],
  ["R","Jimmy on Hugon poika, kaikin puolin."],
  ["A","Poika nimeltä Jimmy lukitsi minut kellariin. Hän alkoi varastaa omaisuuttani.","P","[Tyttö] oli erään hotellivieraan tytär. Jimmy oli ilkeä häntä kohtaan.","H","[Tyttö] oleskeli hotellissa perheensä kanssa.","R","[Tyttö] oli vieraana hotellissa."],
  ["A","Jimmyn mielestä [lelun varastaminen] oli hauskaa. Hän antoi sen takaisin, mutta se oli jo pilalla.","P","En tiedä, mutta [lelun varastaminen] oli tyypillistä hänelle.","H","[Lelun varastaminen] oli varmaan hauskaa hänen mielestään.","R","Ei [Jimmy] ottanut sitä, tyttö valehtelee. Jimmy ei koskaan varastanut mitään."],
  ["A","Käteni paloi. Se teki todella kipeää, mutten voinut kertoa kenellekään.","P","Hänen kätensä paloi aika pahasti, mutta Jimmylle se oli vain leikkiä.","H","[Tyttö] sai pahoja palovammoja.","R","Tyttö sai palovammoja tehdessään vaarallisia asioita. Hän oli outo."],
  ["A","Aioin etsiä lääkärin, mutta Jimmy pakotti minut jäämään.","H","[Tyttö] varmaan pelkäsi Jimmyä.","R","[Syy, miksi Amya pelotti] saattoi olla mitä tahansa. Hän oli kummallinen tyttö."],
  ["A","Poika sanoi, että se oli lääkettä. Se maistui kamalalta.","P","En ollut silloin paikalla, mutta uskoisin hänen juoneen alkoholia."],
  ["A","Tunsin itseni niin kevyeksi, että saatoin hypätä pohjalle asti.","P","Jimmy pakotti tytön juomaan liikaa.","H","[Tyttö] oli juonut pullollisen viskiä, hän ei tiennyt mitä oli tekemässä.","R","En tiedä. Tiesin [tytöstä] hyvin vähän."],
  ["A","Hyppäsin, mutta kaikki pimeni silmissäni, enkä enää herännyt. En pysty enää heräämään, en tiedä missä olen.","P","[Tyttö] oli juovuksissa ja putosi portaikon yläpäästä. Sen takia Rose otti minuun yhteyttä.","H","[Tyttö] putosi portaikon yläpäästä. Tiesin, että Jimmyn oli oltava sen takana.","R","[Tyttö] putosi. Harvey syytti Jimmyä, mutta vika oli tytössä itsessään, ei Jimmyssä."],
  ["P","Sain soiton Roselta, Jimmyn äidiltä. Hän halusi minun selvittävän, mikä Jimmyä vaivasi. Harveyta huoletti eniten Jimmyn mielenlaatu.","H","[Doctor Bosen] oli määrä auttaa Jimmyä, mutta mitään ei ollut tehtävissä.","R","[Doctor Bose] tuli auttamaan Jimmyä."],
  ["P","Jimmy tappoi pieniä lintuja ja eläimiä. Huomasin, että hänen oli harjoiteltava empatiakykyään. Niinpä pyysin häntä tekemään minulle jonkin mukavan asian. Olin yllättynyt, kun hän sai heti idean.","H","Jimmy sanoi löytäneensä [kuolleen jäniksen]. En tiedä, mitä hän teki sillä.","R","Harvey sanoi Jimmyn tappaneen [jäniksen], mutten uskonut häntä."],
  ["P","Jimmy valmisti minulle voileivän. Hän toi sen huoneeseeni, kuten olin pyytänyt. Aluksi en osannut epäillä mitään.","H","Lääkäri yritti kouluttaa Jimmyä. Se osoittautui suureksi virheeksi.","R","Doctor Bose yritti saada Jimmyn tekemään asioita, joista hän ei pitänyt."],
  ["P","Jimmy oli piilottanut lasinsirpaleita voileipääni. Minä melkein tukehduin. Säilytin liinan ja sirpaleet todisteina. Olin aliarvioinut Jimmyn sairauden. Minun täytyi tehostaa hoitoa välittömästi.","H","[Doctor Bose] oppi Jimmyn kujeista kantapään kautta.","R","[Doctor Bose] viilsi itseään, mutta syytti Jimmyä. Ei Jimmy sitä tehnyt."],
  ["P","Jimmy kieltäytyi lääkkeestä. Jouduin juoksemaan hänen perässään. Hän sanoi Roselle, että olin käyttänyt väkivaltaa.","H","En tiedä, en ollut paikalla.","R","[Doctor Bose] yritti lääkitä Jimmyä ilman lupaani."],
  ["P","Pelkäsin Rosen uskovan Jimmyn valheita. Mutta sain hänet vakuuttuneeksi siitä, että poika oli valehdellut.","H","[Doctor Bosea] huoletti syystäkin se, mitä Jimmy keksisi sanoa seuraavaksi.","R","[Doctor Bose] pelkäsi menettävänsä maineensa. En tiennyt, kehen uskoa, mutta annoin hänelle toisen mahdollisuuden."],
  ["P","Ajattelin, että jäätyään kiinni valehtelusta Jimmy alkaisi tottelemaan minua. Sen sijaan hän sepitti uuden valheen. Pahimman mahdollisen.","R","[Doctor Bose] yritti kontrolloida Jimmyä. Saada hänet tekemään pahoja asioita. Minun ei olisi pitänyt luottaa häneen."],
  ["P","Rose ilmiantoi minut ja olisin joutunut luopumaan virastani. Päätin ottaa ohjat viimein käsiini.","H","[Doctor Bose] aiottiin pidättää. Jimmy oli tuhonnut hänet. Minä en uskonut valheisiin.","R","[Doctor Bosea] tultiin pidättämään. Hän oli ansainnut sen."],
  ["P","Olin saanut tarpeekseni. Paluuta entiseen ei ollut. Elämäni oli jo ohi.","H","[Doctor Bosella] ei ollut vaihtoehtoja. Kaikki luulivat hänen koskeneen Jimmyyn. Se poika oli liian nokkela. Lääkäri parka.","R","[Doctor Bose] tiesi olevansa syyllinen. Hän toimi oikein."],
  ["P","[Harvey] tiesi Jimmyn valehdelleen. Harvey ymmärsi kaiken.","H","Jimmy oli esittänyt tekaistuja syytöksiä lääkäriä kohtaan. Rose uskoi häntä, mutta minulle tarina oli jo tuttu.","R","[Harvey] ei uskonut Jimmyä. Tiesin, ettei Jimmy valehdellut."],
  ["P","Jimmy ei ikinä myöntänyt valheitaan.","H","[Jimmy] vain nauroi. Sitten hän alkoi asettaa minulle ansoja.","R","Miten Jimmy voisi myöntää jotakin, mikä ei ollut totta? Harveylla ei ollut mitään oikeutta kiusata Jimmyä."],
  ["H","[Jimmy] oli yhdistänyt lämmittimen kotelon suoraan verkkovirtaan. Minä melkein kuolin. Hän teki sen tahallaan, mutta Rose ei uskonut minua. Jimmy tarvitsi opetuksen. Hän vahingoitti omaisuuttani, joten minä tein vastapalveluksen.","R","Harvey syytti Jimmyä, mutta se lämmitin oli viallinen. Harveyn olisi pitänyt hävittää se."],
  ["P","En tiedä [mitä Harvey teki mailalla], mutta väkivalta pahentaa aina asioita.","H","Rikoin hänen televisionsa ja pelikonsolinsa. Olin vihainen; mutta se vain pahensi tilannetta. Jimmy kosti minulle pian.","R","[Harvey] tuhosi Jimmyn omaisuutta. Hän ei kyennyt hillitsemään itseään."],
  ["H","Jimmy oli asettanut varsijousen laukeamaan oven avauduttua. Minun oli mentävä päivystykseen. Kun palasin, Rose sanoi Jimmyn piileskelevän kellarissa. Siitä sainkin idean.","R","Harvey sanoi Jimmyn ampuneen häntä varsijousella, mutta tiesin, ettei Jimmy käyttäisi sellaista asetta."],
  ["H","Jimmy sai maistaa omaa lääkettään. Luulin, ettei hän saisi tuhoa aikaiseksi kellarissa. Olin väärässä.","R","En tiedä, mitä [Harvey] teki [kellarissa]."],
  ["P","En muista [tulipaloa].","H","Saimme palon hallintaan ennen sen leviämistä. Kaikki vanhat kuvat ja kirjeet paloivat poroiksi. Jimmyä ei pidätellyt mikään, olin saanut tarpeekseni hänestä. Halusin päästä hänestä eroon.","R","Harvey syytti Jimmyä, mutta tulipalo sai alkunsa löystyneestä liitoksesta. Se oli pelkkää sattumaa."],
  ["P","En tiedä [mistä ase on peräisin]. Harvey oli raivoissaan.","H","En tiennyt, mitä olin tekemässä. Ajattelin uhkailla Jimmyä [aseella], saada hänet pois hotellista. En tajunnut, että hänkin olisi aseistautunut.","R","En tiedä [mistä ase on peräisin]. Harveyn ei olisi kuulunut pitää asetta hotellissa."],
  ["H","Etsin Jimmyä."],
  ["H","Jimmy hiipi taakseni, en nähnyt häntä. Jimmy voitti aina lopulta.","R","Harvey oli tullut hulluksi. Jimmy vain puolusti itseään."],
  ["H","Rose uskoi Jimmyä. Hän puolusti poikaansa viimeiseen asti.","R","Se olin minä. Selitin poliiseille, että tikari oli vain kirjeveitsi, ja että Harveylla oli ladattu ase. Jimmy puolusti itseään. He ymmärsivät sen."],
  ["H","Poliisit olivat päästäneet Jimmyn vapaaksi. Sanottiin, että olin uhannut ampua Jimmyn ja hän puolustautui. Ne olivat molemmat valheita.","R","[Jimmy] palasi kotiin. Poliisit olivat ymmärtäneet [hänen puolustaneen itseään]. Jimmy oli muuttunut: hän alkoi auttaa minua ja löysi uuden keinon houkutella lisää asiakkaita hotelliin."],
  ["H","En tiedä, kuka [Hugo Punch] oli.","R","Oli hienoa, kun hotellilla meni jälleen hyvin. Kaikki meni kohti parempaa, kunnes.... Jimmy alkoi käyttäytyä oudosti. Hän huusi ja tuijotti itseään. Hän vaikutti vihaiselta."],
  ["R","Olin aluksi hämilläni, mutta sitten tajusin, mistä oli kyse. Jimmy ei tehnyt näitä asioita. Hän alkoi särkyä niiden peilien tavoin. Hän ei ollut enää oma itsensä."],
  ["H","En tiedä, mutta Jimmyllä oli tapana pilata kaikki aina lopulta.","R","Jimmy ei ollut enää lavalla, vaan Hugo Punch, hänen komediahahmonsa. Hugo loukkasi yleisöään joka ilta, ja nauttikin siitä. Eräänä iltana esityksen jälkeen eräs vieraista sanoi hänelle suorat sanat. Jimmy menetti malttinsa ja teki jotain tyhmää."],
  ["R","[Ovella oli] toimittajia, he halusivat nähdä Jimmyn. He eivät ymmärtäneet, että Hugo Punch sitoi sen naisen. Jimmy oli masentunut. Hän halusi jättää kaiken taakseen ja lähteä."],
  ["R","Jimmy yritti tappaa itsensä. Siksi minun oli kerrottava hänelle totuus."],
  ["H","En tiedä [kenen kimppuun Rose hyökkäsi]. Rose ei kertonut minulle kaikkea.","R","Hautasin [Hugon kellarin] salaiseen huoneeseen. Minun olisi pitänyt tehdä se jo aiemmin. On minun syytäni, että Jimmy kasvoi huonosti. Luulin, että totuuden kertominen korjaisi kaiken. Olin väärässä. En voinut hyväksyä tekoani, enkä elää itseni kanssa."],
  ["R","Ellen olisi [tappanut] itse [itseäni], Jimmy olisi, tai pikemminkin Hugo. Hugo määrää tälläkin hetkellä. Hän kontrolloi Jimmyä. Pyydä Jimmyä näyttämään, missä Hugo asuu."],
  ["H","En tuntenut [Mahtavaa Hugoa].","R","Hän oli taikuri ja viihdyttäjä. Hän osti hotellin edistääkseen showtansa. Hänestä tuli kuuluisa, hän oli televisiossakin. Toimin hänen avustajanaan, kunnes tapahtui käänteitä."],
  ["R","En tiedä, mitä hän halusi. Pystyin antamaan hänelle vain yhden asian."],
  ["R","Hugo oli väkivaltainen, sairas ja viheliäinen mies."],
  ["A","Kyllä, [Jimmy] nappasi sen, kun katsoin muualle, ja varasti rahani. Toruin häntä, mutta hän ei kuunnellut."],
  ["A","[Jimmy] kasteli leluni sillä kauhealla aineella, vihasin häntä!"],
  ["A","[Jimmy] otti sen terävän miekan seinältä. Hän pakotti minut olemaan kertomatta kenellekään ja sanoi voivansa parantaa käteni."],
  ["A","[Jimmy] kehotti minua jatkamaan [lääkkeen] juomista. Se oli kamalaa. Sitten minulle tuli outo olo."],
  ["P","[Rajut piirrokset] viittasivat rauhattomaan luonteeseen, mutten ollut huolissani ennen kuin huomasin kuinka laaja mielikuvitus hänellä oli."],
  ["P","Jimmy sanoi valmistavansa minulle jotakin, joten seurasin häntä mielenkiinnosta."],
  ["P","Sain ensimmäistä kertaa maistiaisen Jimmyn huumorintajusta [kun söin voileivän, jonka sisällä oli lasinsirpaleita]."],
  ["P","[Diatsepaami] ei ollut paras lääkitys, mutta minulla ei ollut muutakaan. Jimmy tarvitsi hoitoa välittömästi; hän oli vaarallinen."],
  ["P","Jimmy väitti, että olin hakannut häntä melalla. En ikinä käyttäisi voimakeinoja potilaaseen. Mutta Rose uskoi häntä."],
  ["P","Jimmy syytti minua pahimmasta mahdollisesta rikoksesta. Hän oli keksinyt väitteensä suoraan lukemastaan sanomalehtiartikkelista."],
  ["P","Kokeilin pyykkinarua, mutta se oli liian ohutta. Löysin köyttä. Minulla oli vielä hotellin avaimet ja onnistuin hiipimään sisään."],
  ["H","Löydettyäni leikekirjan asia valkeni minulle heti. Tarina oli sama jokaista yksityiskohtaa myöten."],
  ["H","Jimmy leikki aina sähkölaitteilla. Hassua, ettei hän itse saanut sähköiskuja."],
  ["H","Säilytin mailoja itsepuolustusta varten, mutta olin vihainen. Otin yhden niistä ja menin Jimmyn huoneeseen."],
  ["H","Jimmy piti kovasti [varsijousen kaltaisista] aseista. En nähnyt häntä lainkaan sinä yönä. Minun olisi pitänyt arvata, että hän suunnitteli jo seuraavaa siirtoaan."],
  ["H","Jimmy piileskeli mielellään kellarissa, joten hän varmasti pitäisi siitä."],
  ["H","Kukaan ei osannut aavistaa, miten pitkälle Jimmy menisi saadakseen huomiota."],
  ["H","Olin mennyt järjiltäni. Näin pelkkää punaista. Vihasin häntä."],
  ["H","[Kirjeveitsi] ei edes ollut tikari! En koskaan oppinut läksyjäni, Jimmy oli aina askeleen edellä minua."],
  ["R","[Hugo Punch] oli Jimmyn roolihahmo. Hänen showtaan saapui katsomaan paljon väkeä."],
  ["R","Peilien rikkominen oli vasta alkua. Kysyin häneltä asiasta, mutta hän ei muistanut tehneensä sitä. Sitten alkoi tapahtua lisää outoja asioita."],
  ["R","Jimmy lukitsi [valituksen tehneen] naisen huoneeseen ja sitoi hänet. Löysin naisen ja päästin hänet vapaaksi. Nainen ei nostanut syytteitä, mutta kertoi asiasta lehdistölle."],
  ["R","[Jimmy] oli taistellut Hugo Punchia vastaan koko elämänsä. Jimmy ei halunnut enää elää."],
  ["R","[Hugo ja minä] olimme naimisissa. Aluksi olimme onnellisia, sitten asiat alkoivat muuttua."],
  ["R","Luulin yhteisen lapsen pelastavan suhteemme. Olin väärässä."],
  ["R","Tunnustin kaiken Jimmylle. Hugo pieksi Jimmyä kahden vuoden ajan heti tämän syntymästä alkaen. Minun olisi pitänyt puuttua siihen aiemmin."],
  ["R","Jimmy oli mennyt etsimään Hugon hautaa. Olin yksin. Tiesin, mitä tehdä."],
],

finwords:[

  "Jokaisessa meistä asuu<br>toinen henkilö, jota emme tunne.",7,
  "",0.5,
  "Hän puhuu meille unissamme, ja kertoo meille",6,
  "kuinka hän näkee meidät tavalla,<br> jolla emme itse näe itseämme.<br><span class='h8'>Carl Jung</span>",8,
  "V",5,
  "Kohtaat hänet",4,
  "",0.5,
  "sydänyöllä",5,
  "",16,
  "<span class='hf'>Maya</span><br>Chloe Booyens",5,
  "<span class='hf'>Jimmy Hall</span><br>Huld Martha",5,
  "<span class='hf'>Rose Hall</span><br>Joanna Bond",5,
  "<span class='hf'>Harvey</span><br>Karl Haynes",5,
  "<span class='hf'>Dr Bose</span><br>Rohit Gokani",5,
  "<span class='hf'>Amy Bell</span><br>Daisy Follin",5,
  "<span class='hf'>Sivurooleissa</span><br>Rachel Alfieri<br>Paige Ryan<br>Sally Alfieri<br>Daniel Alfieri<br>Luke Chase",8,
  "<span class='hf'>Sivurooleissa</span><br>Sam Follin<br>Jamie Follin<br>Tom Follin<br>Clare Follin",7,
  "<span class='hf'>Erityiskiitokset</span><br>Mark Wilson<br>Fay Wilkins",7,
  "",1,
  "Kiitos, kun pelasit<br>At Dead Of Nightin",8,
  "",

],

words:[

  "KÄYNNISTÄ LAITE",
  "SAMMUTA LAITE",
  "HUUDA",
  "KÄYTÄ ENNEPEILIÄ",
  "ESITÄ KYSYMYS",
  "SULJE",
  "Kysy<br>kuka<br>siellä",
  "Kysy<br>hengen<br>nimeä",
  "Oletko sinä<br>",
  "JUOKSE",
  "PAINA<br>KELLARI",
  "PAINA<br>POHJAKERROS",
  "PAINA<br>ENSIMMÄINEN<br>KERROS",
  "PAINA<br>TOINEN<br>KERROS",
  "PAINA<br>KOLMAS<br>KERROS",
  "PALAA TAKAISIN",
  "AVAA<br>VALIKKO",
  "Huuda Jimmyä",
  "KOKEILE<br>OVEA<br>",
  "KOKEILE<br>HUONETTA<br>",
  "PALAA<br>HUONEESEEN",
  "LÄHETÄ<br>YSTÄVÄ<br>ULOS",
  "OLET<br>YHDISTÄNYT<br>NÄMÄ",
  "KOKEILE<br>VARASTOA<br>NRO VIISI",
  "KUTSU<br>HISSI",
  "KYSY TÄSTÄ",
  "PIILOUDU<br>VAATEKAAPPIIN",
  "PIILOUDU<br>KYLPYHUONEESEEN",
  "KATSO<br>OVISILMÄN<br>LÄPI",
  "ASTU<br>HUONEESEEN",
  "ETSI<br>TÄÄLTÄ",
  "POISTU<br>HUONEESTA",
  "KOKEILE<br>TÄTÄ OVEA",
  "SULJE",
  "AVAA<br>MUISTIINPANOT",
  "SIIRRÄ<br>YHDISTETTÄVÄKSI",
  "PALAA<br>OVELLE",
  "YHDISTÄ<br>ESINE <span style='font-family:arial'>&</span> NÄKY",
  "KYSY NÄIDEN YHTEYDESTÄ",
  "KYSY",
  "SEURAAVA SIVU",
  "EDELLINEN SIVU",
  "KOKEILE PORTAIKON OVEA",
  "LIIAN<br>PIMEÄÄ",
  "ASTU<br>HUONEESEEN",
  "POISTU<br>OPASTUSVIDEOSTA",
  "Etsi laite ensimmäisen kerroksen varastohuoneesta, portaikon läheltä",
  "Sinun on<br>etsittävä<br>ennepeili",
  "Sinun on<br>etsittävä<br>kompassi",
  "Sinun on etsittävä<br>kompassi ja ennepeili",
  "Peli<br>tallennettu",
  "KATSO<br>IKKUNASTA",
  "Odota, että olet turvassa",
  "POISTU",
  "Väärä avain",
  "Oven lukitus avattu",
  "Seiso lukitun oven edessä<br>koettaaksesi avainta",
  "Ovi lukittu",
  "Kokeile ovea ensin",
  "Käytä avainta<br>lukitaksesi huoneen oven",
  "Avaa oven lukitus ensin",
  "MENE YLÖS",
  "MENE ALAS",
  "Laitetta ei voi käyttää näin pimeässä tilassa",
  "Odota hetki ennen kuin muodostat yhteyden uudelleen.",
  "Jimmy on astumassa sisään huoneeseen!",
  "Jimmyn ääni kuuluu selvästi",
  "Jimmy hihittää vaimeasti",
  "Aloita peli ensin",
  "Peliä ei voi tallentaa tällä hetkellä",
  "Peli tallennettu",
  "Peiliä ei voi käyttää uudestaan näin pian",
  "Älä yritä!<br>Jimmy on sisällä huoneessa!",
  "KURKISTA<br>AVAIMENREIÄSTÄ",
  "Varastohuoneiden ovia ei kannata lukita",
  "OTA<br>LAITE",
  "Peiliä ei voi käyttää näin pimeässä tilassa",
  "Varasto",
  "Ei tietoa",
  "Peiliä ei voi käyttää näin kirkkaassa valaistuksessa",
  "PALAA<br>VALIKKOON",
  "Tallennetaanko<br>peli?",
  "TALLENNA",
  "Jimmy kulkee lähistöllä",
  "Jimmy kulkee ripeästi",
  "Huoneen ovi sulkeutui",
  "OHITA<br>HERÄÄMINEN",
  "Etsi laitetta varastohuoneista",
  "OHITA",
  "SULJE VIESTI",

],

ghostex:[

  "A",
  "Yhteys muodostettu<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;AMY&#160;&#160;</span>&#10023;<br><br>Kymmenvuotias tyttö",
  "P",
  "Yhteys muodostettu<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;Dr BOSE&#160;&#160;</span>&#10023;<br><br>Psykiatri",
  "H",
  "Yhteys muodostettu<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;HARVEY&#160;&#160;</span>&#10023;<br><br>Hotellinomistaja",
  "R",
  "Yhteys muodostettu<br><br>&#10023;<span style='font-size:150%;vertical-align:bottom'>&#160;&#160;ROSE&#160;&#160;</span>&#10023;<br><br>Hotellinomistaja",

],

headtex:[

  "<span class='h3'>Etsi henkilähetin.</span>",
  "<span class='h3'>Käynnistä henkilähetin<br>puhuaksesi henkien kanssa.</span>",
  "<span class='h3'>Säädä äänenvoimakkuutta, jotta kuulet henkien vastaukset.</span>",
  "<span class='h3'>Ota yhteys henkeen</span><br><span class='h2'>(Paina puhekuvaketta ruudun vasemmassa yläkulmassa)</span>",
  "<span class='h3'>Henki on läsnä.<br>Vahvista henkilöllisyys kysymällä nimeä.</span>",
  "<span class='h3'>Yhteys muodostettu henkeen nimeltä ",
  "<span class='h3'>Henki on liian kaukana, liiku lähemmäs.</span>",
  "<span class='h2'>Esitä kysymyksiä hengille. Yhdistä vastaukset juoniyhteyksiksi. Voit vertailla henkien vastauksia yksin ollessasi.</span>",

],

gametex:[

  "Standard-peli<br><br><span class='h2'>Etsi henkiä, esitä niille kysymyksiä ja muodosta juoniyhteyksiä. Jimmy yrittää estää sinua saamasta selville totuutta!</span>",
  "Etsi & Pelasta<br><br><span class='h2'>Pelasta ystäväsi Jimmyn jahdatessa sinua. Peli on ohi ensimmäisestä iskusta.</span>",
  "Etsi & Pelasta<br><br><span class='h2'>Palaa edellisen pelisi loppuun.</span>",
  "<span class='h9'>Valitse pelisi</span><br><br><span class='h2'>Valitse Standard tai Extreme. Extreme-pelissä Jimmy varastaa sinulta joka kerta lähes kaiken.<br><br>Kun aloitat uuden pelin, aiemmat saavutuksesi ja pelitallennuksesi poistuvat kokonaan.</span>",
  "<span class='h9'>Oletko varma?</span><br><br><span class='h2'>Nykyinen pelisi päättyy ja palaat aiempaan tallennukseen.</span>",
  "<span class='h9'>Kerrasta poikki!</span><br><br><span class='h2'>Peliä ei voi tallentaa, joten sinulla on vain yksi mahdollisuus pelastaa kaikki ystäväsi!</span>",

],

getex:[

  "<br>Löysit<br><br>ennepeilin<br><br><span style='font-size:50%'>Käytä sitä hämärissä<br>paikoissa<br>saadaksesi vihjeitä</span>",
  "<br>Löysit<br><br>kompassin<br><br><span style='font-size:50%'>Osoittaa<br>lähellä olevia henkiä kohti</span>",
  "<span style='font-size:40%>'>Löysit<br>avaimen, jossa on merkintä<br>",
  "Löysit<br>avaimen<br>huoneeseen",
  "Löysit<br>avaimen<br>huoneeseen",

],

roomtex:"Huone",

foundtex:"Löysit",

alreadytex:[

  "Sinulla on jo ennepeili",
  "Sinulla on jo kompassi"

],

adtext:[

  "Tytön itkua",
  "Pelihuoneen ääniä",
  "Tytön vaimeaa itkua",
  "Tytön lauleskelua",
  "Hiljaista koputusta",
  "Astioiden kilinää",
  "Juoksevan veden ääntä",
  "Puhelimen valintaääniä",
  "Äänekästä koputusta",
  "Ovea hakataan",
  "Sähkön kipinöintiä",
  "Tavaroita rikotaan",
  "Napsahduksia",
  "Koputuksia metallioveen",
  "Kovaääninen palohälytys",
  "Harvey huutaa Jimmyä",
  "Ihmisjoukon hälinää",
  "Musiikki soi radiossa",
  "Yleisö buuaa ja huutaa",
  "Ovikello soi",
  "Veden lorinaa",
  "Piiskauksen ääniä",
  "Musiikki soi",

],

itdetext:[

  "Matkalaukkuja",
  "Palkintoja",
  "Kukkaro",
  "Tärpätti ja sytytin",
  "Miekka",
  "Viskipulloja",
  "Rajuja piirroksia",
  "Kokin hattu",
  "Verinen liina",
  "Diatsepaamipullo",
  "Puinen mela",
  "Leikekirja",
  "Pyykkinaru",
  "Vaarallinen lämmitin",
  "Mailoja",
  "Varsijousi",
  "Ruosteisia avaimia",
  "Kuvia tulipalosta",
  "Käsiase",
  "Koristeellinen tikari",
  "Hugo Punch -juliste",
  "Särkyneitä peilejä",
  "Lankakela",
  "Jäähyväisviesti",
  "Vihkisormus",
  "Helistin",
  "Syntymätodistus",
  "Tyttö kellarissa",
  "Jimmy varastaa Amyltä",
  "Amy palava lelu kädessään",
  "Amy seisoo peloissaan käytävällä",
  "Amy juo jotain pahanmakuista",
  "Amy portaikon yläpäässä",
  "Amy portaikon alapäässä",
  "Mies koputtaa oveen",
  "Dr Bose löytää kuolleen jäniksen",
  "Dr Bose keittiön ovella",
  "Dr Bose sylkee verta",
  "Dr Bose injektioneula kädessään",
  "Dr Bose selittää tapahtumia",
  "Dr Bose istuu sängyllä",
  "Dr Bose pelihuoneessa",
  "Dr Bose tappaa itsensä",
  "Mies, joka syyttää Jimmyä valehtelusta",
  "Harvey huutaa oven takana",
  "Harvey saa sähköiskun",
  "Harvey maila kädessään",
  "Harvey saa osuman jalkaan",
  "Harvey lukitsee Jimmyn kellariin",
  "Tulipalo kellarissa",
  "Harvey ase kädessään",
  "Harvey suuntaa juhlasaliin",
  "Harveyta puukotetaan",
  "Nainen kertoo tikarista",
  "Rose pääsisäänkäynnillä",
  "Rose kuuluttamassa kulisseissa",
  "Rose löytää mallinukkeja",
  "Rose pahoittelee Jimmyn käytöstä",
  "Rose piileskelee ihmisjoukolta",
  "Rose löytää Jimmyn kylpyhuoneesta",
  "Rose juoksee maila kädessään",
  "Rose liekeissä",
  "Mahtava Hugo lavalla",
  "Karjuva mies ja itkevä lapsi",
  "Hissi putoaa",
  "Jimmy ei kuunnellut",
  "Jimmy valeli Amyn lelun tärpätillä",
  "Jimmy sanoi parantavansa Amyn käden",
  "Amy joi jotain pahanmakuista",
  "Dr Bose näki Jimmyn piirrokset",
  "Jimmy sai idean",
  "Dr Bose sai maistiaisen Jimmyn huumorintajusta",
  "Dr Bose päätti antaa Jimmylle lääkettä",
  "Jimmy syytti Dr Bosea väkivallasta",
  "Jimmy syytti Dr Bosea hyväksikäytöstä",
  "Dr Bose tiesi mitä tehdä",
  "Harvey löysi Jimmyn leikekirjan",
  "Jimmy leikki sähkölaitteella",
  "Harvey astui maila kädessä Jimmyn huoneeseen",
  "Harvey epäili joutuvansa taas ansaan",
  "Harvey käytti pannuhuoneen avainta",
  "Harvey piti Jimmyä hulluna",
  "Harvey menetti malttinsa",
  "Jimmy oli askeleen edellä",
  "Jimmy aloitti koomikon uran",
  "Outoja asioita alkoi tapahtua",
  "Lehdistö kuuli tapahtuneesta",
  "Jimmy oli saanut tarpeekseen",
  "Elämä Hugon kanssa muuttui",
  "Vauvasta ei ollut apua",
  "Totuus valkeni",
  "Syyllisyys nujersi Rosen",
  "Avain&#160;'Varasto'",
  "",
  "",
  "Ennepeili",
  "Kompassi",
  "Avain 'Ensimmäinen kerros'",
  "",
  "",
  "Ennepeili",
  "Kompassi",
  "Avain&#160;'Varasto'",
  "",
  "",
  "Ennepeili",
  "Kompassi",
  "Avain 'Toinen kerros'",
  "",
  "",
  "Ennepeili",
  "Kompassi",
  "Avain&#160;'Varasto'",
  "",
  "",
  "Ennepeili",
  "Kompassi",
  "Avain 'Kolmas kerros'",
  "",
  "",
  "Ennepeili",
  "Kompassi",
  "Avain&#160;'Varasto'",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Hotellin ulkoavain",
  "Kellarin varastohuoneen avain",

],

keyfinds:[

    "VARASTO",
    "PORTAIKKO<br>ENSIMMÄINEN KERROS",
    "PORTAIKKO<br>TOINEN KERROS",
    "PORTAIKKO<br>KOLMAS KERROS",

  ],

gnames:[
  "Amy",
  "Dr Bose",
  "Harvey",
  "Rose",
  "Hugo"
],

extras:[
  "TERVETULOA<br>HOTELLI MERIHELMEEN<br><span style='font-size:50%'>KIRJAA ITSESI SISÄÄN</span>",
  "Maya:",
  "Peli tallennettu",
  "Peliohjain yhdistetty",
  "Peliohjaimen yhteys katkaistu",
],

};
